### ISSUE TITLE
HLS and TSWriter issue, when ReplayKit in backgroud  to open other app

### ISSUE THREAD

**Issue by burning-git** [shogo4405/HaishinKit.swift#1015]
**Describe the bug**
HLS and TSWriter issue, when ReplayKit in backgroud  to open other app. 
chrome is loading . can auto play. 
safai is pause, but not auto play, need refresh

log:  write(_:) > *** -[NSConcreteFileHandle writeData:]: No such file or directory

I can you help me?

`class SampleHandler: RPBroadcastSampleHandler {

    var httpStream : HTTPStream!
    var httpService: HLSService!
    
    override func broadcastStarted(withSetupInfo setupInfo: [String : NSObject]?) {
        // User has requested to start the broadcast. Setup info from the UI extension can be supplied but optional.
      
        let session = AVAudioSession.sharedInstance()
        do {
            if #available(iOS 10.0, *) {
                try session.setCategory(.playAndRecord, mode: .default, options: [.defaultToSpeaker, .allowBluetooth])
            } else {
                session.perform(NSSelectorFromString("setCategory:withOptions:error:"), with: AVAudioSession.Category.playAndRecord, with: [
                                    AVAudioSession.CategoryOptions.allowBluetooth,
                                    AVAudioSession.CategoryOptions.defaultToSpeaker]
                )
                try session.setMode(.default)
            }
            try session.setActive(true)
        } catch {
            print(error)
        }
                
        httpStream = HTTPStream()
        httpStream.expectedMedias.insert(.video)
        httpStream.mixer.session.sessionPreset = .medium
        httpService = HLSService(domain: "", type: "_http._tcp", name: "Cast", port: 8081)
        httpService.addHTTPStream(httpStream)
        httpService.startRunning()
        httpStream.publish("hello")   
    }
    
    func isIpad() -> Bool {
        
        if UI_USER_INTERFACE_IDIOM() == .pad {
            return true
        }
        return false
    }
    
    override func broadcastPaused() {
        // User has requested to pause the broadcast. Samples will stop being delivered.
    }
    
    override func broadcastResumed() {
        // User has requested to resume the broadcast. Samples delivery will resume.
    }
    
    override func broadcastFinished() {
        // User has requested to finish the broadcast.
    }
    
    override func processSampleBuffer(_ sampleBuffer: CMSampleBuffer, with sampleBufferType: RPSampleBufferType) {

        switch sampleBufferType {
        case RPSampleBufferType.video:
            var num: Int32 = 1
            if isIpad() {
                num = 2
            }

            if let description = CMSampleBufferGetFormatDescription(sampleBuffer) {
                let dimensions = CMVideoFormatDescriptionGetDimensions(description)
                httpStream.videoSettings = [
                    .width: dimensions.width / num,
                    .height: dimensions.height / num,
                    .profileLevel: kVTProfileLevel_H264_Baseline_AutoLevel,
                    .maxKeyFrameIntervalDuration: 2
                ]
            }
            self.httpStream.appendSampleBuffer(sampleBuffer, withType: .video)
            break
        case RPSampleBufferType.audioApp:
            // Handle audio sample buffer for app audio
            httpStream.appendSampleBuffer(sampleBuffer, withType: .audio)
            break
        case RPSampleBufferType.audioMic:
            // Handle audio sample buffer for mic audio
           // httpStream.appendSampleBuffer(sampleBuffer, withType: .audio)
            break
        @unknown default:
            // Handle other sample buffer types
            fatalError("Unknown type of sample buffer")
        }
    }
}
`

**To Reproduce**

**Expected behavior**
See the stream at http://192.168.0.181:8080/hello/playlist.m3u8 (192.168.0.181 is the IP displayed in my iPhone wifi settings on the same wifi my Mac).

**Desktop (please complete the following information):**
 - Version [e.g. 1.2.3]

**Comment by shogo4405** [comment]
First, Chrome don't support HLS. Please use Safari.

>  HLSService(domain: "", type: "_http._tcp", name: "Cast", port: 8081)

Please use a port of 8081. http://192.168.0.181:8080/hello/playlist.m3u
![スクリーンショット 2022-06-22 23 12 19](https://user-images.githubusercontent.com/810189/175051141-a8951499-e2f7-40bc-a8f2-ab294e66d839.png)
8

**Comment by burning-git** [comment]
Chrome use plugin play m3u8,  Reproductor M3U8 - HLS + DASH Player
port use 8081, I write error in git issue.

when HLS start, I in backgroud.  and open other app Chrome pause and loading,  then xcode  show log: 
`2022-23-06 10:21:52.446 [Warn] [com.haishinkit.HaishinKit] [TSWriter.swift:391] write(_:) > *** -[NSConcreteFileHandle writeData:]: No such file or directory`

**Comment by shogo4405** [comment]
Where did you launch the ReplayKit? Is the control center or your application?
- The control center:
  - I'm not sure. I can't reproduce it. Please more details.
- Your applicaiton:
  - This is specifications. I can't resolve it.
