### ISSUE TITLE
No message available on STREAM 

### ISSUE THREAD

**Issue by idajimenez** [shogo4405/HaishinKit.swift#1062]
### Describe the bug

Hi! I'm currently working on a react native project, I created a bridge to use the swift version. 
I am having issue with Facebook livestreaming. I'm getting `Receive failed with error "No message available on STREAM"` from the connection

<img width="1379" alt="Screen Shot 2022-09-13 at 5 59 50 PM" src="https://user-images.githubusercontent.com/17695101/190445841-676b190c-75d7-4e15-9e97-5ff3f89725a9.png">

I don't get this when streaming in Youtube and Twitch.
Hope you can help me on this. Thanks
Great library by the way.

### To Reproduce

1. Followed the sample codes from Prerequisites until Screen Capture
2. Called this code below on click of a button
> LiveStreamView.connection.requireNetworkFramework = true
>     LiveStreamView.connection.connect(_streamUrl)
>     stream.publish(_streamName)
3. Error shows up

### Expected behavior

The expected behavior is you can stream without having this error.

### Version

v1.2.7

**Comment by shogo4405** [comment]
Please show me trace log.
- Logboard.with(HaishinKitIdentifier).level = .trace

How about `LiveStreamView.connection.requireNetworkFramework = false` ?

**Comment by idajimenez** [comment]
Hi @shogo4405 setting `LiveStreamView.connection.requireNetworkFramework = false` worked. Thanks
I just need to adjust url and stream key.
