### ISSUE TITLE
Authentication does't seem to work

### ISSUE THREAD

**Issue by hameedst** [shogo4405/HaishinKit.swift#1064]
### Describe the bug

I am trying to publish rtmp stream aith authentication.

i get this error :

[PublishLiveStreamVC.swift:163] rtmpStatusHandler(_:) > NetConnection.Connect.Rejected

my url is  : 
 public static let streamName  = "WlAydmJL"

"rtmp://client79681:9921ee43@b945a8.entrypoint.cloud.wowza.com/app-r4162s7M/WlAydmJL"

client79681 is username
9921ee43 is password
b945a8.entrypoint.cloud.wowza.com/app-r4162s7M is stream publish url
and. WlAydmJL is stream name

rtmpConnection.connect("rtmp://username:password@localhost/appName/instanceName")

i am trying to follow this templete.

please guide me, thanks.

### To Reproduce

tap on publish stream 
 [PublishLiveStreamVC.swift:163] rtmpStatusHandler(_:) > NetConnection.Connect.Rejected will get this error

### Expected behavior

stream should be published with authentication

### Version

1.2.7

### Smartphone info.

iPhone 11
ios 15.6

**Comment by shogo4405** [comment]
Please try and set `Logboard.with(HaishinKitIdentifier).level = .trace`
- `rtmpConnection.connect("rtmp://client79681:9921ee43@b945a8.entrypoint.cloud.wowza.com/app-r4162s7M")`
- `rtmpStream.publish("WlAydmJL")`

**Comment by shogo4405** [comment]
It seems RTMP Auth works ok. But disconnect by the server other reason.
Can I see `.trace` log and video settings?
