### ISSUE TITLE
PlayOption struct is not used and where i add "streamName", "Application Name" ?

### ISSUE THREAD

**Issue by KaranVakharia789** [shogo4405/HaishinKit.swift#1082]
### Describe the bug

I need to upload live video stream on server so i want to application name and stream name for upload through SDP URL so please guide me how to add stream name and application name in PlayOption struct.

### To Reproduce

There is no any reproduce and the device is in only portrait mode.

### Expected behavior

No response

### Version

1.3.0

**Comment by shogo4405** [comment]
No way. PlayOption struct is not supported.
I have no plan to support `PlayOption`.
