### ISSUE TITLE
Missing audiosamplerate

### ISSUE THREAD

**Issue by daveisfera** [shogo4405/HaishinKit.swift#1103]
### Describe the bug

`audiosamplerate` is typically included in the metadata but is missing here ( see https://github.com/apivideo/api.video-reactnative-live-stream/issues/51#issuecomment-1343995514 )

### To Reproduce

1. Send audio to RTMP server
2. Observe that audiosamplerate isn't sent

### Expected behavior

`audiosamplerate` is included in the metadata

### Version

1.3.0

### Smartphone info.

iPhone 14 Pro Max
16.1

**Comment by shogo4405** [comment]
Thank you. I'm waiting your PR.

**Comment by daveisfera** [comment]
Is the information available somewhere other than the codec? To encode the AAC audio, the sample rate must be available somewhere... 🤔

**Comment by daveisfera** [comment]
Is there an ETA for when this will be released? Would love to start using it.
