### ISSUE TITLE
AudioConverterFillComplexBuffer EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by jinwoojung97** [shogo4405/HaishinKit.swift#1118]
### Describe the bug

When the player plays rtmpStream.play or rtmpStreamPlay() after rtmpStream.close(), the app crashes, often causing 'EXC_BAD_ACCESS' error in the AudioConverterFillComplexBuffer section.

![스크린샷 2023-01-06 오후 3 43 45](https://user-images.githubusercontent.com/83794512/210945456-51e1d932-4ad5-44b0-abf2-f858e8148546.png)

### To Reproduce

1. publisher and player rtmpStream.Close()
2. publisher and player rtmpConnection.Close()
3. publisher reconnect and Publish Start
4. player reconnect and try rtmpStream.Play()

### Expected behavior

Successful connection and reconnection

### Version

1.4.0

### Smartphone info.

iphone 11 (15.6.1)
iphone 14 pro(16.1.2)
iphone 8(14.8.1)

**Comment by leo150** [comment]
What are `_converter`, `inSourceFormat`, `inDestinationFormat` values before the call?

**Comment by shogo4405** [comment]
I can't reproduce it. I would like more detailed steps to reproduce.
Please provide reproduce code.
