### ISSUE TITLE
Unable to link after 1.2.7 version on React Native

### ISSUE THREAD

**Issue by ezranbayantemur** [shogo4405/HaishinKit.swift#1119]
### Describe the bug

Hi there

I'm using HaishinKit.swift package in my React Native third-party library [here](https://github.com/ezranbayantemur/react-native-rtmp-publisher)

My HaishinKit pod version was 1.2.7 and I wanted to update it to 1.4.1 but when I compile example project it gives these errors
<img width="511" alt="Screenshot 2023-01-07 at 01 36 34" src="https://user-images.githubusercontent.com/42299721/211111801-4b7291bb-d0ae-493f-809f-5e4206149e65.png">

I'm thinking it happens because Logger dependency. 
Do you have any thoughts about it? @shogo4405 

### To Reproduce

`s.dependency "HaishinKit", "~> 1.2.7"` to `  s.dependency "HaishinKit", "~> 1.4.1"`

### Expected behavior

Compiling without any error

### Version

Example project version:
    "react-native": "0.63.5"

**Comment by shogo4405** [comment]
I added the os.Logger.
- https://developer.apple.com/documentation/os/logger
- https://github.com/shogo4405/Logboard/blob/main/Sources/Logboard/OSLoggerAppender.swift

I think it's a compiler problem of react-native. I have no idea.
