### ISSUE TITLE
audiosamplerate is 0

### ISSUE THREAD

**Issue by daveisfera** [shogo4405/HaishinKit.swift#1120]
### Describe the bug

`audiosamplerate` was added to fix #1103 but it's [coming through as 0](https://github.com/apivideo/api.video-reactnative-live-stream/issues/51#issuecomment-1376155056)

### To Reproduce

1. Run RTMP connection from iPhone with audio
2. Receive connection metadata
3. Observe that `audiosamplerate` is incorrectly 0

### Expected behavior

`audiosamplerate` would match the sample rate used in the audio

### Version

1.4.1

### Smartphone info.

- Device: iPhone 14 Pro Max
- OS: 16.2

**Comment by shogo4405** [comment]
The value is indeed 0. https://github.com/shogo4405/HaishinKit.swift/blob/main/Sources/Codec/AudioCodec.swift#L82
It is not good to send incorrect values. I will revert it.
