### ISSUE TITLE
isVideoMirrored doesn't work.

### ISSUE THREAD

**Issue by patthehuman** [shogo4405/HaishinKit.swift#1130]
### Describe the bug

I am attempting to "mirror" the camera as well as the video data being sent to my RTMP server, and when I set the property `self.rtmpStream.videoCapture(for: 0)?.isVideoMirrored = true` to true, nothing happens.

Perhaps I'm using this incorrectly, or I am going about this the wrong way.

I'm able to set isMirrored on the MTHKView, however, the live stream has no mirroring effect.

I have attempted to create a `VisualEffect` for this and modifying CIImage data, however that seems like it may be the incorrect route.

### To Reproduce

Set up project

Add `self.rtmpStream.videoCapture(for: 0)?.isVideoMirrored = true`

Video is not mirrored, nor is stream data.

### Expected behavior

I expect the stream to be mirrored horizontally.

### Version

1.4.2

### Smartphone info.

iPhone 14 pro

**Comment by patthehuman** [comment]
I found that `self.rtmpStream.videoCapture(for: 0)?.isVideoMirrored = true` is nil if you call it before you set up the cameras (makes sense)

I'd like to have the camera start as front facing camera, with the isVideoMirrored set to true by default. Is there a way to do this without waiting for self.rtmpStream.videoCapture(for: 0)` to have a value?

**Comment by shogo4405** [comment]
It is certainly difficult to use. 

**Workaround code:**
```
stream.attachCamera(back) { error in
  logger.warn(error)
}
stream.lockQueue.async {
  print("hello")
  print(self.rtmpStream.videoCapture(for: 0))
}
```
