### ISSUE TITLE
Cannot find 'LBLogger' in scope

### ISSUE THREAD

**Issue by mcelhennyi** [shogo4405/HaishinKit.swift#1134]
### Describe the bug

When trying to build the test project for iOS I get this when I compile: "Cannot find 'LBLogger" in scope.

This comes from [this](https://github.com/shogo4405/HaishinKit.swift/blob/42d1381a0897c6a3ee48e305c5e6c31fe890b47e/Sources/Util/Constants.swift#L7) line. 

I have already tried [this change](https://github.com/shogo4405/HaishinKit.swift/pull/1014) because logboard itself wasnt being found. That fixed that issue, but now I have a LBLogger issue.

### To Reproduce

Clone 1.4.2 branch. Build in XCode.

### Expected behavior

LogBoard isnt found. Fix with ```carthage bootstrap --use-xcframeworks``` then see LBLogger not found in scope.

### Version

1.4.2

### Screenshots

![Screenshot 2023-02-06 at 4 22 16 PM](https://user-images.githubusercontent.com/14264857/217100873-5bc69c4b-bdd2-43cd-8996-2485454d8235.png)

**Comment by shogo4405** [comment]
I can't reproduce it. Perhaps, it seems that faild to build carthage.
