### ISSUE TITLE
Stuck in an infinite loop in the MP4Box.setData method

### ISSUE THREAD

**Issue by AbcTM** [shogo4405/HaishinKit.swift#1138]
### Describe the bug

Stuck in an infinite loop in the MP4Box.setData method

### To Reproduce

sample code

``` swift 
    func readMp4box() {
        guard reader == nil else {
            return
        }
        guard let url = Bundle.main.url(forResource: "hs_bg4.mp4", withExtension: nil) else {
            return
        }
        do {
            let reader = try MP4FileReader(forReadingFrom: url)
            print(reader.execute().xmlString)
        } catch {
            print("error:\(error.localizedDescription)")
        }

    }
```

### Expected behavior

can print xmlstirng

### Version

1.4.2

### Additional context

mp4 resource url:https://github.com/AbcTM/HaishinKit.swift/blob/main/Tests/Asset/hs_bg4.mp4

**Comment by shogo4405** [comment]
Thank you feedback. This is the internal code. I have no plan fix this issue.
