### ISSUE TITLE
Audio Codec

### ISSUE THREAD

**Issue by DineshkumarKandasamy** [shogo4405/HaishinKit.swift#1149]
### Describe the bug

Hi @shogo4405 Could you please guide how to setup Audio codec as AAC? I tried to set like below. But sound not coming in stream url.

### To Reproduce

 
                        self.rtmpStream.audioSettings = [
                            .bitrate: 128000
                        ] 

                        self.rtmpStream.startRecording([
                          AVMediaType.audio: [
                            AVFormatIDKey: Int(kAudioFormatMPEG4AAC),
                            AVEncoderBitRateKey: 128000,
                          ],
                          AVMediaType.video: [
                            AVVideoCodecKey: AVVideoCodecType.h264,

                            AVVideoCompressionPropertiesKey: [
                              AVVideoMaxKeyFrameIntervalDurationKey: 2,
                              AVVideoProfileLevelKey: AVVideoProfileLevelH264Baseline30,
                              AVVideoAverageBitRateKey: 1250000
                            ]

                          ]
                        ])

### Expected behavior

Sound in Live Output

### Version

1.4.3

**Comment by shogo4405** [comment]
I feel like don't use the `rtmpStream#attachAudio` method.

**Comment by DineshkumarKandasamy** [comment]
yes @shogo4405 we did not use that method. Setting up aac code as similar like below is the right way? Please confirm

AVFormatIDKey: Int(kAudioFormatMPEG4AAC),

**Comment by shogo4405** [comment]
no way. always set to aac internal.

**Comment by shogo4405** [comment]
Sorry. I honestly don't know what to you expect.
This issue is not good. I will close. Thank you.
