### ISSUE TITLE
FPS 60 doesn't work in the sample project.

### ISSUE THREAD

**Issue by JamesJunsungKim** [shogo4405/HaishinKit.swift#1157]
### Describe the bug

I was trying to see if 60 framerate works but it doesn't seem to work. FPS came out around 30. 

### To Reproduce

1. click on fps 60
2. start streaming
3. check FPS on the left top corner

### Expected behavior

FPS comes out 60

### Version

1.4.4

### Smartphone info.

Device: iphone 12 max
ios: 16.3.1

**Comment by shogo4405** [comment]
fixed 42f060a
