### ISSUE TITLE
When restarting to broadcast, the audio doesn't seem to get sent to the streaming server.

### ISSUE THREAD

**Issue by JamesJunsungKim** [shogo4405/HaishinKit.swift#1171]
### Describe the bug

When restarting to broadcast, only video data gets sent to the streaming server. Audio not found

### To Reproduce

With the example code from Hainshinkit repository,

1. start braodcasting
2. stop
3. start broadcasting again

### Expected behavior

Video and audio get transferred.

### Version

main branch

### Smartphone info.

Device: iphone 12 pro max
iOS: 16.4

**Comment by shogo4405** [comment]
Thank you. I fixed it.
