### ISSUE TITLE
crash when receiving a call in the middle of broadcasting with top snack var. 

### ISSUE THREAD

**Issue by JamesJunsungKim** [shogo4405/HaishinKit.swift#1172]
### Describe the bug

With the sample app from the Hainshinkit, the app crashes when getting a call in the middle of the streaming. 

### To Reproduce

1. Start streaming
2. get a call
3. just accept the call instead of going to the full screen
4. end the call and come back to the streaming
5. crash.

### Expected behavior

restart streaming

### Version

main branch

### Smartphone info.

Device: iphone 12 pro max
os: 16.4

**Comment by shogo4405** [comment]
> Version
> 1.4.5

Is it 1.4.5 or main branch?

**Comment by JamesJunsungKim** [comment]
It's the main branch. tested with the latest commit

**Comment by shogo4405** [comment]
I can't reproduce it. might be fix it https://github.com/shogo4405/HaishinKit.swift/issues/1168 Thank yoy.
