### ISSUE TITLE
Value of type 'UnsafeMutablePointer<Int16>' has no member 'update'

### ISSUE THREAD

**Issue by zazzaze** [shogo4405/HaishinKit.swift#1176]
### Describe the bug

While compiling Example iOS app on m1 mac using XCode 14.2 an error `Value of type 'UnsafeMutablePointer<Int16>' has no member 'update'` occurs 

### To Reproduce

1. carthage bootstrap --use-xcframeworks --platform iOS
2. open proj
3. run build using `Example iOS` scheme

### Expected behavior

the app is being launched

### Version

1.4.5

### Screenshots

<img width="444" alt="image" src="https://user-images.githubusercontent.com/37036145/230714265-8e805bf5-f444-4f5d-9db8-4366a9cf0917.png">

**Comment by shogo4405** [comment]
Yes. main branch require Xcode 14.3. Please consider to use Xcode 14.3 or `git checkout -b main refs/tags/1.4.5`.
HaishinKit 1.4.5 will works fine with Xcode 14.2. Thank you.
