### ISSUE TITLE
HKView no camera preview

### ISSUE THREAD

**Issue by Dgut** [shogo4405/HaishinKit.swift#1177]
### Describe the bug

When using the code from the RTMP Usage section HKView gives black color but server receives the stream.

### To Reproduce

1. Create new empty project
2. Go to Prerequisites and RTMP Usage section
3. Copy code to viewDidLoad

### Expected behavior

Camera preview

### Version

1.4.5

**Comment by shogo4405** [comment]
Indeed, HKView does not support multi-camera and other features. Please consider using MTHKView or PiPHKView. I I think it should work fine with version 1.3.0.

**Comment by leo150** [comment]
Switching to MTHKView helped

**Comment by shogo4405** [comment]
I fixed it as a workaround.  c84dce1
