### ISSUE TITLE
Rtmp stream crash RTMPURL with rtmpConnection.connect("rtmp://${hostName}") without /

### ISSUE THREAD

**Issue by jiajialaixi** [shogo4405/HaishinKit.swift#1178]
### Describe the bug

2023-15-04 11:52:13.530 [Debug] [com.haishinkit.HaishinKit] [RTMPConnection.swift:490] didSetReadyState(_:) > uninitialized
2023-15-04 11:52:13.928 [Debug] [com.haishinkit.HaishinKit] [RTMPConnection.swift:490] didSetReadyState(_:) > versionSent
2023-15-04 11:52:13.962 [Debug] [com.haishinkit.HaishinKit] [RTMPConnection.swift:490] didSetReadyState(_:) > ackSent
2023-15-04 11:52:13.963 [Debug] [com.haishinkit.HaishinKit] [RTMPConnection.swift:490] didSetReadyState(_:) > handshakeDone
Swift/StringCharacterView.swift:60: Fatal error: String index is out of bounds
Swift/StringCharacterView.swift:60: Fatal error: String index is out of bounds
* thread #52, queue = 'com.haishinkit.HaishinKit.NetSocket.input', stop reason = Fatal error: String index is out of bounds
    frame #0: 0x0000000190dd5458 libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`:
->  0x190dd5458 <+0>: ret    
libswiftCore.dylib`:
    0x190dd545c <+0>: b      0x190dd5458               ; _swift_runtime_on_report
libswiftCore.dylib`:
    0x190dd5460 <+0>: adrp   x8, 334924
    0x190dd5464 <+4>: ldrb   w0, [x8, #0xcec]
Target 0: (Runner) stopped.

### To Reproduce

1、rtmpUrl:= rtmp://live.ncbase.comtom.cn/ncbase10001
authKey=1681617133-add49b4e9820449ebb36daf0861f609f-0-c13b520dc6b55d1c10ae67b7509fca52&extra=0/e48f82cc6d744a279f4bde8efc0836eb

2、rtmpConnection.connect(rtmpUrl)

3、String index is out of bounds

### Expected behavior

无

### Version

HaishinKit 1.4.5

### Smartphone info.

iphone 12 mini
ios 15.4.1

**Comment by shogo4405** [comment]
Did you try a code like this?
```
var rtmpUrl = "rtmp://live.ncbase.comtom.cn/ncbase10001
authKey=1681617133-add49b4e9820449ebb36daf0861f609f-0-c13b520dc6b55d1c10ae67b7509fca52&extra=0/e48f82cc6d744a279f4bde8efc0836eb"

rtmpConnection.connect(rtmpUrl)
```

1. This rtmpUrl is malformed. Do not accept line breaks.
2. This is not a valid string, so there is a possibility that it could cause a crash during continuation processing.

This is not a valid string, so there is a possibility that it could cause a crash during continuation processing.
I suspect that there might be a problem with how the RTMP URL is being specified.

**Comment by jiajialaixi** [comment]
original url =rtmp://live.ncbase.comtom.cn/ncbase10001?authKey=1681617133-add49b4e9820449ebb36daf0861f609f-0-c13b520dc6b55d1c10ae67b7509fca52&extra=0/e48f82cc6d744a279f4bde8efc0836eb


**Connect as follows**

rtmpConnection.connect("rtmp://live.ncbase.comtom.cn")

rtmpSteam.publish("ncbase10001?authKey=1681617133-add49b4e9820449ebb36daf0861f609f-0-c13b520dc6b55d1c10ae67b7509fca52&extra=0/e48f82cc6d744a279f4bde8efc0836eb",type:.live)

**Comment by shogo4405** [comment]
https://github.com/shogo4405/HaishinKit.swift#rtmp-url-format
- Please try rtmpConnection.connect("rtmp://live.ncbase.comtom.cn/“) // with /

**Comment by jiajialaixi** [comment]
1、rtmpConnection.connect("rtmp://live.ncbase.comtom.cn/“) //  add a last "/".

2、rtmpSteam.publish("ncbase10001?authKey=1681617133-add49b4e9820449ebb36daf0861f609f-0-c13b520dc6b55d1c10ae67b7509fca52&extra=0/e48f82cc6d744a279f4bde8live",type:ebc083)


The address received in the server will be changed to rtmp://live.ncbase.comtom.cn//ncbase10001?authKey=1681617133-add49b4e9820449ebb36daf0861f609f-0-c13b520dc6b55d1c10ae67b7509fca52&extra=0/e48f82cc6d744a279f4bde8live

An additional one will be added after the domain name "/"

**Comment by shogo4405** [comment]
> The address received in the server will be changed to

what do you mean? I'm not sure what it has to do with the RTMP connection.
A typical RMPURL looks like this: 

> rtmp://server-ip-address[:port]/application/[appInstance]/[prefix:[path1[/path2/]]]streamName

It is correct to specify like this. Don't you have a separate stream key?

> rtmpConneciton.connect("rtmp://live.ncbase.comtom.cn/ncbase10001?authKey=1681617133-add49b4e9820449ebb36daf0861f609f-0-c13b520dc6b55d1c10ae67b7509fca52&extra=0/e48f82cc6d744a279f4bde8live")

**Comment by jiajialaixi** [comment]
yes，There is no separate stream key

**Comment by shogo4405** [comment]
I had a fix this issue. https://github.com/shogo4405/HaishinKit.swift/commit/7ca0185652bf6fa918a70cb947e801590e950bdc
Please try this commit. Thank you.
