### ISSUE TITLE
Can't save local recording with MultiCamCapture.

### ISSUE THREAD

**Issue by nthnhung23** [shogo4405/HaishinKit.swift#1198]
### Describe the bug

i can't save video
It's return error `recorder(_:errorOccured:) error: failedToFinishWriting(error: nil)`

### To Reproduce

// MARK: - IORecorderDelegate
extension HomeViewController: AVRecorderDelegate {
     func recorder(_ recorder: AVRecorder, errorOccured error: AVRecorder.Error) {
        print("***  \(type(of: self)) \(#function) error: \(error)")
     }

    func recorder(_ recorder: AVRecorder, finishWriting writer: AVAssetWriter) {
        
        guard PHPhotoLibrary.authorizationStatus() == .authorized else {
            return
        }
        if viewModel.setting.value?.saveVideo ?? false {
            PHPhotoLibrary.shared().performChanges {
                PHAssetChangeRequest.creationRequestForAssetFromVideo(atFileURL: writer.outputURL)
            } completionHandler: { [weak self] status, error -> Void in
                guard let self = self else { return }
                print("***  \(type(of: self)) \(#function) status: \(status)")
                do {
                    try FileManager.default.removeItem(at: writer.outputURL)
                } catch {
                    print("***  \(type(of: self)) \(#function) error: \(error)")
                }
            }
        }
    }
}

### Expected behavior

Can save video

### Version

1.5.0

**Comment by shogo4405** [comment]
It seems that local saving is not possible with multi-camera capture. I have fixed it.
