### ISSUE TITLE
RTMPS audio randomly not start

### ISSUE THREAD

**Issue by arnauddorgans** [shogo4405/HaishinKit.swift#1200]
### Describe the bug

When I play a RTMPS stream most of the time I have no audio played, with this message in the logs.
Note: It seems that the issue is related to audio with stereo

> [avae]            AVAEInternal.h:130   [AUInterface.mm:539:SetFormat: ([[busArray objectAtIndexedSubscript:(NSUInteger)element] setFormat:format error:&nsErr])] returned false, error Error Domain=NSOSStatusErrorDomain Code=-10868 "(null)"
> [Warn] [com.haishinkit.HaishinKit] [IOMixer.swift:74] audioFormat > [[busArray objectAtIndexedSubscript:(NSUInteger)element] setFormat:format error:&nsErr]: returned false, error Error Domain=NSOSStatusErrorDomain Code=-10868 "(null)"

### To Reproduce

Each time I play a RTMPS stream

```swift
// Audio session
let session = AVAudioSession.sharedInstance()
do {
    try session.setCategory(.playback, mode: .default, options: [])
    try session.setActive(true)
} catch {
    print(error)
}

// Connection
let rtmpConnection = RTMPConnection()
rtmpConnection.requireNetworkFramework = true
let params = NWParameters.tls
rtmpConnection.parameters = params

let rtmpStream = RTMPStream(connection: rtmpConnection)

// View
let hkView = PiPHKView()
hkView.attachStream(rtmpStream)

// Handler
rtmpConnection.addEventListener(.ioError, selector: #selector(Coordinator.rtmpErrorHandler), observer: self)
rtmpConnection.addEventListener(.rtmpStatus, selector: #selector(Coordinator.rtmpStatusHandler), observer: self)
rtmpConnection.connect("url")

@objc func rtmpStatusHandler(_ notification: Notification) {
    let e = Event.from(notification)
    print(e)
    guard let data = e.data as? ASObject, let code = data["code"] as? String else {
        return
    }
    switch code {
    case RTMPConnection.Code.connectSuccess.rawValue:
        rtmpStream.play("live")
    case RTMPConnection.Code.connectFailed.rawValue, RTMPConnection.Code.connectClosed.rawValue:
        Thread.sleep(forTimeInterval: pow(2.0, Double(1)))
        rtmpConnection.connect("url")
    default:
        break
    }
}

@objc func rtmpErrorHandler(_ notification: Notification) {
    print(notification)
    rtmpConnection.connect(url.absoluteString)
}
```

### Expected behavior

Audio is played

### Version

1.5.0

**Comment by shogo4405** [comment]
Could you please provide more details about the settings on the streaming side? Specifically, I would like to know the server name and client name. If you are using OBS, please provide the detailed configuration settings for OBS.
