### ISSUE TITLE
Camera Does Not Dispose

### ISSUE THREAD

**Issue by kodypeterson** [shogo4405/HaishinKit.swift#1205]
### Describe the bug

After calling `attachCamera(nil)` the camera is still shown as being in use in the privacy center.

We believe that this is due to https://github.com/shogo4405/HaishinKit.swift/blob/52ad7d6ad488734b61eb438894dd591baaf522df/Sources/Media/IOVideoUnit.swift#LL142C1-L142C1 setting the flag to passthrough and not handling detaching from the device.

### To Reproduce

1. Attach a camera
2. Call `attachCamera` with nil

### Expected behavior

The camera should no longer show as in use

### Version

1.4.3

### Smartphone info.

iPhone 11 (iOS 16.3.1)

**Comment by kodypeterson** [comment]
@shogo4405 Thanks for the quick fix! Do you know when 1.5.2 is planned to release as we are blocking our release until we can get this in. Thanks again!

**Comment by shogo4405** [comment]
I will release it when I feel like it.
If I receive $500, I will release it as early as tomorrow. Thank you.

**Comment by tmak** [comment]
Hello @shogo4405, I'm with [PinSeeker](https://pinseekergame.com/), as @kodypeterson is as well.

First of all, thanks for this library! It's a high-quality library, and we plan to build many great product features with its capabilities.
I just started a monthly sponsorship for you via our PinSeeker account; confident that this will lead to a great synergy where we can support your open-source efforts that directly impact our product development.

As @kodypeterson mentioned, this fix is blocking our initial product release for live-streaming support in our mobile app. Can you share a timeline of when you plan to release another version of this library so we can plan our product release schedule accordingly?

As a side note, we started migrating our iOS & Android apps, written in Swift and Kotlin, to Flutter via Flutter's add-to-app functionality and hoping to be able to migrate to your [HaishinKit for Flutter](https://github.com/shogo4405/HaishinKit.dart) library at some point.

Thanks again for this library, and I'm looking forward to building more product features with it!

Best,
Thomas

**Comment by shogo4405** [comment]
HaishinKit is an open-source project that I am developing as a personal hobby, and there is no fixed release plan. I appreciate your choice to become a sponsor.  I have released version 1.5.2. Thank you very much.
