### ISSUE TITLE
Logboard is down.

### ISSUE THREAD

**Issue by mdino** [shogo4405/HaishinKit.swift#1228]
Example can't be started since logboard framework is missing. 

Edit:
Before few days logboard github was down too, but example still doesn't work.

Solution: open logboard github page, download source, build iOS framework and from derived data paste framework to HaishinKit, delete old missing references from Frameworks folder and inside General/Frameworks,Libraries and Embedded content for logboard.framework - embed & sign

**Comment by shogo4405** [comment]
It doesn't seem like Logboard is down. Following the instructions in the README.md worked well for me. If the intention is to run the sample, there is no problem with copying and pasting it that way.
