### ISSUE TITLE
AudioCodec is crashed while appendSampleBuffer ReplayKit

### ISSUE THREAD

**Issue by xinhua01206** [shogo4405/HaishinKit.swift#1234]
### Describe the bug

HI @shogo4405.

Thanks for your this library.
This is good library but I am getting crash to send the audio from server.
I am using RPScreenRecorder to capture video/audio from device screen.

I am sending buffer like this.
rtmpStream.appendSampleBuffer(sampleBuffer)

![Screenshot 2023-07-13 at 4 09 49 AM](https://github.com/shogo4405/HaishinKit.swift/assets/131747089/b37b4952-667f-4706-8285-8e7419ceed05)

![Screenshot 2023-07-13 at 4 02 35 AM](https://github.com/shogo4405/HaishinKit.swift/assets/131747089/941a9e5c-a5a6-43e8-a8a3-99bf67b110c3)

Video works well but audio is crashed.

Could you please help me?
Thanks.

### To Reproduce

```
recorder.startCapture { sampleBuffer, bufferType, error in
            if let error = error {
                print(error.localizedDescription)
                return
            }
            
            switch bufferType {
            case .video:
                rtmpStream.appendSampleBuffer(sampleBuffer)
                break
            case .audioApp:
                rtmpStream.appendSampleBuffer(sampleBuffer)
                break
            case .audioMic:
                break
            default:
                print("ScreenRecorder - error")
                break
            }
        } completionHandler: { error in
            if let error = error {
                print(error.localizedDescription)
                completion(false, error)
            } else {
                completion(true, nil)
            }
        }
```

### Expected behavior

No crash and send audio to server.

### Version

1.5.2

### Smartphone info.

- Device: iPhone 12
- OS: 16.3.1
- Xcode 14.3.1

### Additional context

Capturing video/audio from camera/microphone works well.
But audio from RPScreenRecorder is crashed. Video from RPScreenRecorder works well.

**Comment by xinhua01206** [comment]
This is CMSampleBuffers

- Device

[Device.txt](https://github.com/shogo4405/HaishinKit.swift/files/12037702/Device.txt)

- ReplayKit

[ReplayKit.txt](https://github.com/shogo4405/HaishinKit.swift/files/12037704/ReplayKit.txt)

Thanks.

**Comment by shogo4405** [comment]
This issue occurs when there is a long interval between PTS values in the previous CMSampleBuffer. How much of a gap is there?

**Comment by xinhua01206** [comment]
Hi @shogo4405.

Thanks for your reply.
Followings are outputPTS values.

outputPTS = {81629692615291/1000000000 = 81629.693
outputPTS = {81629715830041/1000000000 = 81629.716
outputPTS = {81629739044750/1000000000 = 81629.739
outputPTS = {81629758608750/1000000000 = 81629.759
outputPTS = {81629781823500/1000000000 = 81629.782
outputPTS = {81629805060833/1000000000 = 81629.805
...

The interval is long?

* The version 1.3.0 is working well.

Thanks.

**Comment by shogo4405** [comment]
It looks in the normal range. Can you give me a reproducible sample code?

**Comment by xinhua01206** [comment]
Hi @shogo4405. Above code is helpful for you?

**Comment by shogo4405** [comment]
Of course, I'm glad I could help. I'm currently debugging, but I believe I have made the necessary fixes. https://github.com/shogo4405/HaishinKit.swift/pull/1236
