### ISSUE TITLE
Random Bitrate Change

### ISSUE THREAD

**Issue by heestand-xyz** [shogo4405/HaishinKit.swift#1244]
### Describe the bug

Sometimes (around 10% of the time), when starting ingest, I experience the ingested video bitrate to be at exactly `899942`, even tho I've set it to `2000000`. This seemingly random bitrate is actually consistently appearing on every ~10th stream.

### To Reproduce

Setup ingestion, set the bitrate to 2M, monitor the bitrate though AMS.

### Expected behavior

Bitrate should always be at 2M.

### Version

HaishinKit `1.5.2` or `1.5.3`

### Smartphone info.

iPhone 11
iOS 16.6

### Screenshots

![Screenshot 2023-07-13 at 11 55 15 AM](https://github.com/shogo4405/HaishinKit.swift/assets/7947442/ee1890bc-7570-40c4-8f70-c7691ec05100)

**Comment by shogo4405** [comment]
Is the value always 899942?

VideoToolbox is an ABR (Adaptive Bitrate) and typically reaches around 2Mbps during continuous streaming of several tens of seconds. Therefore, when capturing a specific time segment, it may go below 2Mbps. Starting from iOS 16, CBR (Constant Bitrate) is available. Trying that setting may work as expected.

```
stream.videoSettings.bitRateMode = .constant
stream.videoSettings.profileLevel = kVTProfileLevel_H264_Baseline_AutoLevel as String
stream.videoSettings.bitRate: 2000 * 1000
```

**Comment by heestand-xyz** [comment]
Yes the value is constantly changed from 2M to `899942` in the cases where the bitrate changes (~10% of the time).

**Comment by heestand-xyz** [comment]
I will test out the constant bit rate mode withe the profile level. Thanks.

**Comment by shogo4405** [comment]
I'm curious about the value always being 899942. The initial value of bitRate should be 640 * 1000 bps, so I wonder where the value 899942 comes from.

**Comment by heestand-xyz** [comment]
I'm not sure where the bitrate `899942` comes from, but it seems to consistently be that magic number. For your info, our resolution is set to `480x854`.

**Comment by heestand-xyz** [comment]
I tested ingesting with a bitrate of `4M` and now I get new number: `1999872`

![Screenshot 2023-07-27 at 9 38 36](https://github.com/shogo4405/HaishinKit.swift/assets/7947442/4c3d95e6-9bfc-4302-87ec-6019193b7b61)

**Comment by heestand-xyz** [comment]
In the latest test I also used the following settings:
```swift
stream.videoSettings.bitRateMode = .constant
stream.videoSettings.profileLevel = kVTProfileLevel_H264_Baseline_AutoLevel as String
```

**Comment by heestand-xyz** [comment]
I'm not sure what is causing the bitrate change, but the HaishinKit video settings are not changed.
Once the bitrate has changed, our ingestion fails. (I'm not sure if the resolution was also changed, I will look into this)
Here are the constant changes in bitrate:
```
video:
  2000000 -> 899942
  4000000 -> 1999872
audio:
  128000 -> 98784
```

**Comment by shogo4405** [comment]
> Once the bitrate has changed, our ingestion fails.

Rather than the bitrate changing, it seems more likely that there is a disconnection on the AWS side, and as a result, it ends up with that value.
I would like to see the logs for both cases, when it works normally and when the issue occurs.

Please set.
LBLogger.with(HaishinKitIdentifier).level = .trace

**Comment by shogo4405** [comment]
Translation: Also, you can check the actual bitrate on the client-side by using connection.totalBytesOut inside updateStats.

https://github.com/shogo4405/HaishinKit.swift/blob/main/Sources/RTMP/RTMPConnection.swift#L35
rtmpConneciton.delegate = self

func connection(_ connection: RTMPConnection, updateStats stream: RTMPStream) {
    print(“totalBytesOut =>”, connection.totalBytesOut)
}

**Comment by shogo4405** [comment]
Camera usage is not available in the background, so video transmission stops. This is an iOS limitation and specification. As a result, if AWS stops, I believe it is within the expected behavior according to the specification.

It seems that this issue is not related to the bitrate changing midway, but there might be other problems.

**Comment by shogo4405** [comment]
This is the extent to which I can provide support. If needed, please make the necessary fixes on your own. Thank you.
