### ISSUE TITLE
HLS with broadcast extension working unstable

### ISSUE THREAD

**Issue by minhvblc** [shogo4405/HaishinKit.swift#1245]
### Describe the bug

HLS with broadcast extension laggy, sometimes it stop hls after 10-15 secs after start. This is my code
`class SampleHandler: RPBroadcastSampleHandler {
    
    var httpStream = HTTPStream()
    var httpService = HLSService(domain: "", type: "_http._tcp", name: "HaishinKit", port: 8081)
  
    
    override func broadcastStarted(withSetupInfo setupInfo: [String : NSObject]?) {
        let session = AVAudioSession.sharedInstance()
        do {
            if #available(iOS 10.0, *) {
                try session.setCategory(.playAndRecord, mode: .default, options: [.defaultToSpeaker, .allowBluetooth])
            } else {
                session.perform(NSSelectorFromString("setCategory:withOptions:error:"), with: AVAudioSession.Category.playAndRecord, with: [
                    AVAudioSession.CategoryOptions.allowBluetooth,
                    AVAudioSession.CategoryOptions.defaultToSpeaker]
                )
                try session.setMode(.default)
            }
            try session.setActive(true)
        } catch {
            print(error)
        }
        httpStream.frameRate = 24
        httpStream.expectedMedias.insert(.video)
        httpService.addHTTPStream(httpStream)
        httpService.startRunning()
        httpStream.publish("hello")
}
    
    override func broadcastPaused() {
        // User has requested to pause the broadcast. Samples will stop being delivered.
    }
    
    override func broadcastResumed() {
        // User has requested to resume the broadcast. Samples delivery will resume.
    }
    
    override func broadcastFinished() {
    }
    
    override func processSampleBuffer(_ sampleBuffer: CMSampleBuffer, with sampleBufferType: RPSampleBufferType) {
        switch sampleBufferType {
        case RPSampleBufferType.video:
            if let description = CMSampleBufferGetFormatDescription(sampleBuffer) {
                let dimensions = CMVideoFormatDescriptionGetDimensions(description)
                httpStream.videoSettings.videoSize = VideoSize(width: dimensions.width, height:  dimensions.height)
            }
            httpStream.appendSampleBuffer(sampleBuffer)
            break
        case RPSampleBufferType.audioApp:
            break
        case RPSampleBufferType.audioMic:
            break
        @unknown default:
            // Handle other sample buffer types
            fatalError("Unknown type of sample buffer")
        }
    }
`

### To Reproduce

1. Start Broadcastting with HLS
2. Open link HLS and see laggy and HLS stop

### Expected behavior

HLS running smoothly without being stoped

### Version

Latest

**Comment by shogo4405** [comment]
If it's not available, please give up.

**Comment by minhvblc** [comment]
Sorry for bothering. If you have freetime, i hope you will show me how to deal with this. Thank you
