### ISSUE TITLE
Missing Import of UIKit in NetStream (v1.5.4)

### ISSUE THREAD

**Issue by heestand-xyz** [shogo4405/HaishinKit.swift#1250]
### Describe the bug

```
Cannot find 'UIApplication' in scope on line 175 in NetStream.swift
```

### To Reproduce

Build HaishinKit `1.5.4` for `iOS`

### Expected behavior

Build successful

### Version

1.5.4

### Smartphone info.

iPhone 11
iOS 16.6

**Comment by shogo4405** [comment]
You are using SPM, right? I would like you to mention that.
Duplicate as close https://github.com/shogo4405/HaishinKit.swift/issues/1246

**Comment by heestand-xyz** [comment]
Yes I'm using SPM. I'll mention that next time. Just trying to help!
