### ISSUE TITLE
Garbage collection crash in IOAudioMonitor

### ISSUE THREAD

**Issue by mkrn** [shogo4405/HaishinKit.swift#1263]
### Describe the bug

EXC_BAD_ACCESS: Exception 1, Code 2047862832, Subcode 8 >
Attempted to dereference garbage pointer 0xa32f64f17a0fe830.
  ?, in swift::RefCounts<T>::incrementSlow
  ?, in swift_retain
  ?, in swift_retain
  File "IOAudioMonitor.swift", line 32, in IOAudioMonitor.callback
  File "<compiler-generated>", in IOAudioMonitor.callback
<img width="925" alt="image" src="https://github.com/shogo4405/HaishinKit.swift/assets/1870075/6a0e9679-86c0-4911-b8b4-1e36a28d4a1a">
<img width="918" alt="image" src="https://github.com/shogo4405/HaishinKit.swift/assets/1870075/7904ed8b-b16c-4a6c-b88c-e0895a08ec40">

### To Reproduce

Not sure.. caught in the wild.

### Expected behavior

Expected not to crash

### Version

Latest, main

### Smartphone info.

Iphone 12
iOS 16.1.1

**Comment by shogo4405** [comment]
Are you using the recently added IOAudioMonitor feature? Does this crash occur when the stream.loopback=false?

**Comment by mkrn** [comment]
yes it's using loopback, however not sure if it's true or false when the crash occurs. Feature implemented as in example app. 
Can it be fixed or is it better to remove the feature?

**Comment by shogo4405** [comment]
Thank you for using the feature I recently implemented so promptly.
I suspect that the crash is occurring when the RTMPStream instance is being disposed of with loopback = true. I believe the crash could be avoided by setting loopback = false before rtmpStream setting null.

I will try to implement the fix.
