### ISSUE TITLE
RTMP audio streaming

### ISSUE THREAD

**Issue by Kirubhasankar** [shogo4405/HaishinKit.swift#1274]
### Describe the bug

Hi, I am using haishin_kit flutter plugin for rtmp audio streaming. Currently we are developing an live streaming app. we are playing video stream from camera device in the app and we need to push only audio from the app to rtmp server. Pushing audio to server works fine when video was not playing but when i try to publish audio from ios app to server while playing videos which has sound then audio publishing not working. In android its working great.
In simple words two way audio not working in ios.
(Note: Plugin returns successfully publishing but there is no audio data (0 bytes received in server).)
I also set avaudiosession category to playandRecord but it's not working. We are stuck in this for last two weeks. Can you please help us to fix this, Thanks

### To Reproduce

1. Play any video with sound in iphone
2. Try to publish audio to server, Plugin returns successfully publishing but there is no audio data

### Expected behavior

play the video with sound in ios app and publish audio to server.
(note: There should be audio data)

### Version

haishin_kit: ^0.11.2

### Smartphone info.

IOS - IPhone

**Comment by shogo4405** [comment]
I was able to confirm audio-only streaming and playback using the Example app of HaishinKit.swift. It's likely that the issue is on the Flutter side or within your app rather than on the HaishinKit side.
