### ISSUE TITLE
does not conform to protocol 'NetStreamDelegate' since 1.5.6

### ISSUE THREAD

**Issue by ariadnalls** [shogo4405/HaishinKit.swift#1279]
### Describe the bug

Hi, 

since 1.5.6 update I get the following error if I run a `pod lib lint`

`- ERROR | [iOS] xcodebuild:  /Users/....swift:102:1: error: type '...' does not conform to protocol 'NetStreamDelegate'`

In my class I have an extension which implements the 'NetStreamDelegate' 
the problem is in the following function
`public func stream(_ stream: HaishinKit.NetStream, audioCodecErrorOccurred error: HaishinKit.AudioCodec.Error)`

In 1.5.5 it's working fine but on later versions I get the does not conform to protocol if I keep the HaishinKit namespace, and I can't put
`public func stream(_ stream: NetStream, audioCodecErrorOccurred error: AudioCodec.Error)`

because I get
`'AudioCodec' is ambiguous for type lookup in this context`

has there been any change that could be causing this?

Thank you

### To Reproduce

create an extension conforming to NetStreamDelegate
run pod lib lint

NOTE: my iports on the class are
import AVFoundation
import HaishinKit
import UIKit

### Expected behavior

be able to run pod lib lint without errors

### Version

1.5.7

1.5.5 working fine

### Smartphone info.

iOS

**Comment by shogo4405** [comment]
Please see this document.
https://github.com/shogo4405/HaishinKit.swift/wiki/Moving-from-1.5.5-APIs-to-1.5.6
