### ISSUE TITLE
No SRTHaishinKit in 1.5.7

### ISSUE THREAD

**Issue by LambdaXe** [shogo4405/HaishinKit.swift#1287]
### Describe the bug

I migrated from SRTHaishinKit to HaiskinKit 1.5.7 to use SRTHaishinKit and stay updated, but the SRTHaishinKit folder in HaishinKit's PackageDependencies packet doesn't appear, in fact any references to (e.g.) SRTConnection , XCode doesn't recognize them

### To Reproduce

1) Removed SRTHaishinKit
2) Clean build folder, restart XCode
3) File->Add Package->Past HaishinKit Github link
4) Dependency rule "Up to next major version" 1.5.7
5) Add package
6) Build
7) All this error "Cannot find type 'SRTStream' in scope" etc

### Expected behavior

After added the package HaiskinKit 1.5.7, I can use SRTStream, SRTConnection etc, like before when I used SRTHaishinKit

### Version

1.5.7

**Comment by shogo4405** [comment]
The support for that is planned from 1.5.8 onwards, so it's not possible in 1.5.7.
