### ISSUE TITLE
Codec Hevc with SRT

### ISSUE THREAD

**Issue by LambdaXe** [shogo4405/HaishinKit.swift#1292]
### Describe the bug

Using the SRT protocol to stream on vMix, if I set the HEVC codec I receive a black screen, I checked that vMix was not the problem because with other programs I can, if I use H.264 I don't encounter any problems. How can I enable HEVC?

### To Reproduce

In the VideoCodecSettings, set profileLevel: "kVTProfileLevel_HEVC_Main_AutoLevel"

### Expected behavior

video streaming working with SRT protocol and HEVC codec

### Version

1.5.8

### Smartphone info.

iPhone 12 mini

**Comment by andreagiga** [comment]
> SRT compatibility for HEVC is not supported. It's by design.
Hi,
Do you plan to implement HEVC support also on SRT transport?

**Comment by shogo4405** [comment]
I don't have plans for that, so I don't know. I can implement it for $20,000. Thank you.
