### ISSUE TITLE
calling SRTConnection.performanceData results in a crash

### ISSUE THREAD

**Issue by ruirodrigues-eyenov** [shogo4405/HaishinKit.swift#1323]
### Describe the bug

I am using the latest version, 1.6.1, and setup a SRT stream. When calling `SRTConnection.performanceData` the app crashes and Xcode stops on `SRTSocket.doOutput(data:)`.

### To Reproduce

1. start streaming
2. call `SRTConnection.performanceData`

### Expected behavior

Receive performance data without a crash.

### Version

1.6.1

### Smartphone info.

- Device: iPhone 14 Pro
- OS: iOS 16.6.1

**Comment by shogo4405** [comment]
I think it's fixed on the main branch. There are no plans to backport it to the 1.6.x series.

**Comment by ruirodrigues-eyenov** [comment]
ok, I'll try the main branch.
I'm guessing the next release won't be a 1.6.x? 
Piggybacking on this one, any plans on having a currentFPS for SRTStream?

**Comment by shogo4405** [comment]
I'm currently debugging for the upcoming 1.7.0 release. It's expected to take at least another month. As for adding 'currentFPS,' it's not scheduled at the moment. I don't think it's too complicated, so we're looking forward to your pull request

**Comment by ruirodrigues-eyenov** [comment]
yes, it is fixed on main, thanks
