### ISSUE TITLE
VideoCodec still running after stream is close()

### ISSUE THREAD

**Issue by floriangbh** [shogo4405/HaishinKit.swift#1333]
### Describe the bug

The VideoCodec still running after stream is stopped

### To Reproduce

1. Take the sample project 
2. Start stream 
3. Stop the stream
4. See the VideoCodec continue to encode for the stream

<img width="1339" alt="Screenshot 2023-11-07 at 16 42 50" src="https://github.com/shogo4405/HaishinKit.swift/assets/14054997/36f3a6d1-39e5-4599-814d-96fcab37bb69">

### Expected behavior

VideoCodec should stop to encode ?

### Version

- Main branch

### Smartphone info.

- iOS 17.1

### Additional context

Maybe I'm wrong with the use case, but in my case it causes memory issues.

**Comment by shogo4405** [comment]
The specification is that during a pause, the last frame continues to be sent. This is done to prevent audio and video desynchronization on the viewer's end when video is continuously dropped.

**Comment by floriangbh** [comment]
Thanks for the clarification. 

In this case (with the sample), even after 1/2 min, the encoder still running. Not sure this is only the last frame :)

**Comment by shogo4405** [comment]
Yes, it will keep running even for 1 hour or 2 hours.

**Comment by floriangbh** [comment]
I'm not sure to undestrand "This is done to prevent audio and video desynchronization on the viewer's end when video is continuously dropped." 
If the stream/connexion is closed, there is no desynchronization possible issue. 

But it can lead to `Fatal error: Attempted to read an unowned reference but object 0x280971800 was already deallocated` when the encoder still running when not necessary. 🤔

**Comment by shogo4405** [comment]
I see. I'm not a native English speaker, so I'm not quite sure about the main point. It would be helpful if you could explain it more concisely. I think you're talking about that `stream.paused = false` was set. Is that correct, or am I mistaken?

**Comment by floriangbh** [comment]
I'm not a native English speaker so I'm probably not very clear also sorry.

I'm talking about when after `stream.close()`, the encoder is still running. To reproduce it:

- Take the example project
- Start the stream with an RTMP destination 
- Stop (close) the stream
- Place a breakpoint in VideoCodec `append()`

<img width="1339" alt="Screenshot 2023-11-07 at 16 42 50" src="https://github.com/shogo4405/HaishinKit.swift/assets/14054997/d43f31fb-9698-45e6 -aa6c- d2819cc9f963">

The `append()` in the VideoCodec is still running even after a `stream.close()`

**Comment by shogo4405** [comment]
It was an unintended behavior, so I have fixed it. Thank you.

**Comment by floriangbh** [comment]
Thank you !
