### ISSUE TITLE
RTSP support

### ISSUE THREAD

**Issue by clear-m** [shogo4405/HaishinKit.swift#134]
Please add rtsp support

**Comment by clear-m** [comment]
With rtsp your lib will be just brilliant !

**Comment by shogo4405** [comment]
I have a plan "RTMP support". https://github.com/shogo4405/lf.swift/tree/master/Sources/RTSP
But, The progress of that work is unfavorable. X(

**Comment by clear-m** [comment]
Yes - I already see those sources - and did some progress with them -  it is really not so easy to implement rtsp fully functional ) - but rtsp have one significant benefit compared to rtmp - latency - in most players/servers latency is about 0.5 s - rtmp gives 3-5 seconds latency by default

**Comment by floriangbh** [comment]
It look like RTSP support is not anymore in the roadmap 😞

**Comment by shogo4405** [comment]
Yes.  I have no plan RTSP Support.
