### ISSUE TITLE
[Crash] App crashes due to thread-safe issue of RTMPConnection.uri

### ISSUE THREAD

**Issue by RainyTunes** [shogo4405/HaishinKit.swift#1346]
### Describe the bug

My app accidentally executed this code for more than once:
``` swift
connection.addEventListener(.ioError, selector: #selector(rtmpErrorHandler), observer: self)
connection.addEventListener(.rtmpStatus, selector: #selector(rtmpStatusHandler), observer: self)
```

Then consequently, my code called connection.link() two times indirectly by mistake.
It caused my app cannot connect to Twitch, and the reconnect workflow started to work.

After about 4 times reconnect tries, the app crashed and the crash message showed EXC_BAD_ACCESS of RTMPConnection.uri

I think you could possibly consider adding more protection on RTMPConnection.uri for potential thread-safe issues.

### To Reproduce

Call RMTPConnection.addEventListener() for .rtmpStatus and .ioError for several times in purpose.
The crash might happen with tiny probability.

### Expected behavior

Don't crash in any network circumstances

### Version

1.7.1 
or
the newest main branch

### Smartphone info.

iPhone 14 pro

### Screenshots

![CleanShot 2023-11-30 at 4  23 53@2x](https://github.com/shogo4405/HaishinKit.swift/assets/11310665/4d6059d6-ea50-4756-a600-517b9cca8990)

**Comment by shogo4405** [comment]
I had opened it because it might occur even though it's a rare use case. Was it improved?

**Comment by RainyTunes** [comment]
@shogo4405 

Thank you for your attention and persistent contribution.

As I said in this page, the crash happened when I took a mistake to register the listener twice.

I had no idea whether it was improved in that rare case, but it never occured after I solve that mistake.

**Comment by shogo4405** [comment]
I see. I overlooked the fact that it was being registered twice. In that case, I thought it would be fine to close this ticket. Thank you for letting me know.
