### ISSUE TITLE
It is very slow to rotate camera in PiP mode

### ISSUE THREAD

**Issue by RainyTunes** [shogo4405/HaishinKit.swift#1348]
### Describe the bug

I find it is very smooth to rotate the camera in single-camera mode,
but it is very slow to rotate cameras in PiP mode.

It usually takes about 7 seconds to wait for the cameras to work again.

### To Reproduce

1. RTMPStream.attachMulticamera()
2. RTMPStream.attachCamera()
3. MTHKView.attachStream()
4. watch the MTHKView and it is working normally.
5. use a button to trigger rotateCamera() // I used the implementation in the Example project 
6. watch the MTHKView again, and it will get stuck for about 7 seconds.

### Expected behavior

Dont get stuck when rotating cameras.

### Version

1.7.1

### Smartphone info.

iPhone14 pro

**Comment by RainyTunes** [comment]
https://github.com/shogo4405/HaishinKit.swift/assets/11310665/b77a6482-b55e-4d8a-b418-0f3651532301

**Comment by RainyTunes** [comment]
It got stuck for about 10 seconds in the above video.

By the way, I would greatly appreciate it if you could explain a little bit further about _the following comment,_

because I really care about whether I can switch smoothly between _the multi-camera mode_ and _the single-camera mode._ 

// If you're using multi-camera functionality, please make sure to call the attachMultiCamera method first. This is required for iOS 14 and 15, among others.

**Comment by shogo4405** [comment]
Thank you for the report.
1. It has been fixed.
2. Regarding the issue, I believe fixing it would benefit the overall system. However, as for whether it meets your specific requirements or not, I do not provide free guidance for individual issues. Please consider sponsorship or paid consulting for personalized support.
