### ISSUE TITLE
When I closed the stream and then turned it back on, the log showed that it was connected, but frequent switching results in low transmission speed

### ISSUE THREAD

**Issue by Balopy** [shogo4405/HaishinKit.swift#1359]
### Describe the bug

I run the example:

--> start living    (    netStreamSwitcher.open(.ingest)    )
-->  pause     (     (stream as? RTMPStream)?.paused.toggle()  
                               netStreamSwitcher.close()   )
--> reopen    (    netStreamSwitcher.open(.ingest)    )

<img width="1136" alt="image" src="https://github.com/shogo4405/HaishinKit.swift/assets/35068028/bf03f9a9-89fe-481e-ae0f-68d4c26785a2">
<img width="1035" alt="image" src="https://github.com/shogo4405/HaishinKit.swift/assets/35068028/1abeacb1-a3f1-4a60-abf6-1df289ea666a">
<img width="1129" alt="image" src="https://github.com/shogo4405/HaishinKit.swift/assets/35068028/cf5936be-9fa9-4d01-9c49-0013a0584f87">

When I closed the live stream and then turned it on again, the log showed that it had been connected, but there was no push stream. It seemed that the live stream had not been pushed successfully, and the pull stream had not been pulled successfully.

Frequent switching results in low transmission speed, but the connection is successful.

### To Reproduce

no

### Expected behavior

Reopen fail

### Version

1.6.2

**Comment by shogo4405** [comment]
During streaming, "pause" means sending silent audio and the last frame continuously. If the pause is set to true even after reconnecting, it will continue. This behavior is by design.

**Comment by Balopy** [comment]
OK, thanks, let me continue to try
