### ISSUE TITLE
videoCodecErrorOccurred reason=failedToFlame(status: 0), description=The operation couldn’t be completed. (HaishinKit.IOVideoUnitError error 3.)

### ISSUE THREAD

**Issue by kenle** [shogo4405/HaishinKit.swift#1397]
### Describe the bug

Hi, when I stream RTMP I'm occasionally getting the following error: 

"videoCodecErrorOccurred reason=failedToFlame(status: 0), description=The operation couldn’t be completed. (HaishinKit.IOVideoUnitError error 3."

Is this normal?  This did not seem to occur in HaishinKit version 1.4.5, I recently did an upgrade.

### To Reproduce

```
                let connection = RTMPConnection();
                let stream =  RTMPStream(connection: connection);

                stream.videoSettings = VideoCodecSettings(
                    videoSize: .init(width: 1920, height: 1080),
                    bitRate: 8000 * 1000.0,
                    profileLevel: kVTProfileLevel_HEVC_Main_AutoLevel as String,
                    scalingMode: .trim,
                    bitRateMode: .average,
                    maxKeyFrameIntervalDuration: 2,
                    allowFrameReordering: nil,
                    isHardwareEncoderEnabled: true
                );
                
                stream.frameRate = 30;
                
                stream.audioSettings = AudioCodecSettings(
                    bitRate: 128 * 1000,
                    sampleRate: 0,
                    channels: 0,
                    downmix: false,
                    channelMap: nil
                );

               stream.connect("rtmp://a.rtmp.youtube.com/live2/my_stream_key");
```

I traced the code, the error is being called here during encodeFrame

### VideoCodec.swift
```
    func append(_ imageBuffer: CVImageBuffer, presentationTimeStamp: CMTime, duration: CMTime) {
        guard isRunning.value, !willDropFrame(presentationTimeStamp) else {
            return
        }
        if invalidateSession {
            session = VTSessionMode.compression.makeSession(self)
        }
        _ = session?.encodeFrame(
            imageBuffer,
            presentationTimeStamp: presentationTimeStamp,
            duration: duration
        ) { [unowned self] status, _, sampleBuffer in
            guard let sampleBuffer, status == noErr else {
                delegate?.videoCodec(self, errorOccurred: .failedToFlame(status: status))
                return
            }
            self.presentationTimeStamp = sampleBuffer.presentationTimeStamp
            outputFormat = sampleBuffer.formatDescription
            delegate?.videoCodec(self, didOutput: sampleBuffer)
        }
    }
```

### Expected behavior

I would expect it not to have a video codec errors, 
my similar code using HaishinKit version 1.4.5 did not have these errors.

### Version

1.7.4 and 1.7.5

### Smartphone info.

iPad Pro (12.9) (4th generation), Software Version 14.8.1
iPhone 12 Pro Max, Software Version 17.2.1

### Relevant log output

```shell
videoCodecErrorOccurred reason=failedToFlame(status: 0), description=The operation couldn’t be completed. (HaishinKit.IOVideoUnitError error 3.)
```

**Comment by shogo4405** [comment]
I tested it on my iPhone 14 Pro Max (iOS 17.3), and even when I set the values specified in "To Reproduce," it worked as expected. Would it behave similarly if I changed the parameters of videoSettings?
I also confirmed that I could stream on an iPhone 7 Plus (iOS 14.8) in the same manner. Is there anything else missing from the reproduction conditions?

**Comment by kenle** [comment]
Hi @shogo4405 ,

It was my mistake.  I double checked my code and bitrate was mistakenly set to 500*1000, not 8000*1000. I was doing adaptive bitrate pushing it up to 8000*1000, but perhaps the initial setting in the constructor limits the bitrate.

You may close this issue once you read it and thank you for looking into it.

-Ken
