### ISSUE TITLE
Recording not working since 1.8.0

### ISSUE THREAD

**Issue by gmsnap** [shogo4405/HaishinKit.swift#1470]
### Describe the bug

Stream recording with IOStreamRecorder and IOStreamRecorderDelegate does not work.

In the Delegate's error handler we get following error:
`failedToAppend(error: Optional(Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSLocalizedFailureReason=An unknown error occurred (-12780), NSLocalizedDescription=The operation could not be completed, NSUnderlyingError=0x28148b630 {Error Domain=NSOSStatusErrorDomain Code=-12780 "(null)"}}))`

The Delegate handler is declared as follow:
```
class RecorderDelegate: IOStreamRecorderDelegate {
    func recorder(_ recorder: HaishinKit.IOStreamRecorder,
                  errorOccured error: HaishinKit.IOStreamRecorder.Error) {
        print("recorder error: \(error)")
    }
    
    func recorder(_ recorder: HaishinKit.IOStreamRecorder,
                  finishWriting writer: AVAssetWriter) {
        PHPhotoLibrary.shared().performChanges({() -> Void in
            PHAssetChangeRequest.creationRequestForAssetFromVideo(atFileURL: writer.outputURL)
        }, completionHandler: { (_, error) -> Void in
            do {
                try FileManager.default.removeItem(at: writer.outputURL)
            } catch let error {
                print(error)
            }
        })
    }
}
```

### To Reproduce

1. Setup stream
2. Setup recorder: let recorder = IOStreamRecorder()
3. Declare and init Delegate: let recorderDelegate = RecorderDelegate()
4. Assign Delegate and add recorder to stream: 
    recorder.delegate = recorderDelegate
    rtmpStream.addObserver(recorder)
5. Start stream and recording

### Expected behavior

The stream should be recorded to video file as it worked in previous versions (< 1.8.0).

### Version

1.8.2

### Smartphone info.

- iPad Air 5th Generation, iPhone 14 Pro
- iOS 16 and 17

**Comment by shogo4405** [comment]
I tested version 1.8.2 upon release and confirmed that the recording worked as expected in the Example app.
I believe the issue might be on the user's end, so I would appreciate it if you could provide code that can reproduce the problem.

**Comment by gmsnap** [comment]
Thanks for testing. We've narrowed down the recording issue a bit.
It only occurs when appending a `CMSampleBuffer` via `rtmpStream.append()`.
However, when we use `rtmpStream.attachCamera()`, everything works well.

To reproduce the issue, you can refer to your iOSSwiftUI example, and append a dummy frame every 1/30 second instead of the camera image.

In versions 1.7.x and older, this works perfectly.
However, starting from version 1.8.x, we encounter the recorder error.
We've tested it with the default audio device (`RTMPStream.attachAudio`), a dummy audio sample buffer (`RTMPStream.append`), and no audio – none of these works without the error.

This is how we create the dummy frame:
```
func createDummyVideoSampleBuffer(width: Int, height: Int, presentationTimeStamp: CMTime) -> CMSampleBuffer? {
        var pixelBuffer: CVPixelBuffer?
        var sampleBuffer: CMSampleBuffer?
        
        let pixelBufferAttributes: [CFString: Any] = [
            kCVPixelBufferPixelFormatTypeKey: kCVPixelFormatType_32BGRA,
            kCVPixelBufferWidthKey: width,
            kCVPixelBufferHeightKey: height,
            kCVPixelBufferCGImageCompatibilityKey: true,
            kCVPixelBufferCGBitmapContextCompatibilityKey: true
        ]
        
        let status = CVPixelBufferCreate(kCFAllocatorDefault, width, height, kCVPixelFormatType_32BGRA, pixelBufferAttributes as CFDictionary, &pixelBuffer)
        
        if status != kCVReturnSuccess {
            print("Error: Could not create pixel buffer")
            return nil
        }
        
        CVPixelBufferLockBaseAddress(pixelBuffer!, CVPixelBufferLockFlags(rawValue: 0))
        let pixelData = CVPixelBufferGetBaseAddress(pixelBuffer!)
        
        let rgbColorSpace = CGColorSpaceCreateDeviceRGB()
        let context = CGContext(data: pixelData, width: width, height: height, bitsPerComponent: 8, bytesPerRow: CVPixelBufferGetBytesPerRow(pixelBuffer!), space: rgbColorSpace, bitmapInfo: CGImageAlphaInfo.noneSkipFirst.rawValue)
        
        context?.setFillColor(UIColor.black.cgColor)
        context?.fill(CGRect(x: 0, y: 0, width: width, height: height))
        
        CVPixelBufferUnlockBaseAddress(pixelBuffer!, CVPixelBufferLockFlags(rawValue: 0))
        
        var timingInfo = CMSampleTimingInfo(duration: CMTime.invalid, presentationTimeStamp: presentationTimeStamp, decodeTimeStamp: CMTime.invalid)
        
        var formatDescription: CMVideoFormatDescription?
        CMVideoFormatDescriptionCreateForImageBuffer(allocator: kCFAllocatorDefault, imageBuffer: pixelBuffer!, formatDescriptionOut: &formatDescription)
        
        CMSampleBufferCreateReadyWithImageBuffer(allocator: kCFAllocatorDefault,
                                                 imageBuffer: pixelBuffer!,
                                                 formatDescription: formatDescription!,
                                                 sampleTiming: &timingInfo,
                                                 sampleBufferOut: &sampleBuffer)
        
        return sampleBuffer
    }
```

The dummy frame is appended every 1/30 sec like this:
```
let mt = CACurrentMediaTime()
let ts = CMTimeMakeWithSeconds(mt, preferredTimescale: Int32(mt.magnitude) * 30)
if let s = createDummyVideoSampleBuffer(width: 1920, height: 1080, presentationTimeStamp: ts) {
    rtmpStream.append(s)
}
```

Addressing this issue would be greatly appreciated, as our project relies on using `RTMPStream.append` to stream and record composed video.
