### ISSUE TITLE
Black screen at the trailing

### ISSUE THREAD

**Issue by vishakh-ncompass** [shogo4405/HaishinKit.swift#1485]
### Describe the bug

I'm using the IORecorder to record video using 10 second interval. At the end of each video there is a black screen .Is there any ways to avoid the black screen at the end of the video.

### To Reproduce

record video and manually move your playhead to the end you will see a black screen.

### Expected behavior

I should have no black frames.

### Version

1.4.0

**Comment by shogo4405** [comment]
I have confirmed that the issue does not occur and everything works fine with version 1.9.0. I don't have a development environment for version 1.4.0, so I can't provide information on that. Please update to the latest version and try again.
