### ISSUE TITLE
Missing required module 'SwiftPMSupport'

### ISSUE THREAD

**Issue by jay0118** [shogo4405/HaishinKit.swift#1502]
### Describe the bug

xcode didn't report any other bugs, just this one。 Does this package really exist? Why hasn't a more detailed statement followed up?
I hope you can answer that. Thank you
<img width="691" alt="截屏2024-07-01 下午2 40 06" src="https://github.com/shogo4405/HaishinKit.swift/assets/59227505/b2b661ac-433d-4255-a82d-258e9ad2b719">
<img width="691" alt="截屏2024-07-01 下午3 33 31" src="https://github.com/shogo4405/HaishinKit.swift/assets/59227505/4d5f15b1-0477-44a8-a5d9-861d9caf032a">
<img width="785" alt="截屏2024-07-01 下午3 34 30" src="https://github.com/shogo4405/HaishinKit.swift/assets/59227505/07f7d26b-5401-4dae-800f-1fcad5e2b2c4">

### To Reproduce

```// swift-tools-version:5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.
import PackageDescription

let package = Package(
    name: "HaishinKit",
    platforms: [
        .iOS(.v13),
        .tvOS(.v13),
        .visionOS(.v1),
        .macOS(.v10_15),
        .macCatalyst(.v14)
    ],
    products: [
        .library(name: "HaishinKit", targets: ["HaishinKit"]),
        .library(name: "SRTHaishinKit", targets: ["SRTHaishinKit"])
    ],
    dependencies: [
        .package(url: "https://github.com/shogo4405/Logboard.git", "2.5.0"..<"2.6.0")
    ],
    targets: [
        .binaryTarget(
            name: "libsrt",
            path: "Vendor/SRT/libsrt.xcframework"
        ),
        .target(name: "SwiftPMSupport"),
        .target(name: "HaishinKit",
                dependencies: ["Logboard", "SwiftPMSupport"],
                path: "Sources",
                sources: [
                    "Codec",
                    "Extension",
                    "IO",
                    "ISO",
                    "Net",
                    "RTMP",
                    "Screen",
                    "Util"
                ]),
        .target(name: "SRTHaishinKit",
                dependencies: [
                    "libsrt",
                    "HaishinKit"
                ],
                path: "SRTHaishinKit"
        )
    ]
)
```

### Expected behavior

Start the app normally

### Version

1.9

**Comment by shogo4405** [comment]
I couldn't find instructions on how to try it, so I don't know. At least in the case of git clone, this error didn't occur when calling Xcode features from other projects.

**Comment by ZacharyHandshoe** [comment]
Same issue here on a simple import.

**Comment by shinsuk** [comment]
To avoid this error, I created a framework target named "SwiftPMSupport" and included the following source files:

- HaishinKit.swift/Sources/SwiftPMSupport/include/HaishinKit.h
- HaishinKit.swift/Sources/SwiftPMSupport/dummy.m

By adding this framework to my project, I was able to avoid the error.

**Comment by Gamec** [comment]
For me it happens when I added HaishinKit as a dependency of other Swift Package. If I add it as dependency to main project it works fine.

**Comment by shogo4405** [comment]
As a maintainer, I can't address the issue without knowing how to reproduce it. Please provide detailed steps to reproduce the problem.

The way the issue is currently written is not helpful, and leaving it open is unlikely to lead to any progress.
If others are experiencing the same problem, please write the reproduction steps and open a separate PR.
