### ISSUE TITLE
Offscreen Rendering issue with some PNG formats

### ISSUE THREAD

**Issue by floriangbh** [shogo4405/HaishinKit.swift#1505]
### Describe the bug

Hello, 

I just tried to migrate to the new offscreen rendering API with ImageScreenObject. 
In some cases, the image is set correctly, but in others, the application crashes on draw. 

AssetScreenObject seems to be also concerned with native video taken with the phone.

### To Reproduce

Use ImageScreenObjet with PNG from assets :

```swift
if let image = UIImage(named: "test")?.cgImage {
            imageScreenObject.verticalAlignment = .middle
            imageScreenObject.layoutMargin = .init(top: 0, left: 0, bottom: 16, right: 0)
            imageScreenObject.cgImage = image
        } else {
            Logs.info("no image")
        }
```

With this image (just a screenshot) : 

<img width="887" alt="Screenshot 2024-07-09 at 11 28 25" src="https://github.com/shogo4405/HaishinKit.swift/assets/14054997/302af02b-67f1-4baf-b864-7376d5291101">

Result to : 

<img width="1349" alt="Screenshot 2024-07-09 at 11 29 56" src="https://github.com/shogo4405/HaishinKit.swift/assets/14054997/766ed2a4-85db-4671-9317-4d36542fe2b5">

### Expected behavior

Integrate all kinds of PNG

### Version

v1.9.1
xCode 15.4

**Comment by shogo4405** [comment]
I have a hypothesis that crashes occur when the composite range of the PNG exceeds the screen size. To fix the issue, I need the following information:

1. Please provide a reproducible PNG file that causes the issue.
   - It's okay to send it via Gmail.
1. Please let me know the screen size.
   - screen.size = ???

Thank you.

**Comment by floriangbh** [comment]
The image size is the reason for the crash. 

With rtmpStream.screen.size : (1280.0, 720.0) You can reproduce the crash with this image (1280x800) :
![fail](https://github.com/shogo4405/HaishinKit.swift/assets/14054997/67749c4c-41a3-4c2f-8bff-c47a396f06bd)

If I switch to a 1280x720 everything is ok, thanks !

**Comment by shogo4405** [comment]
It's not good to crush, so I think it's better to either issue a warning or have the framework handle the clipping. For now, please avoid the issue using the above method. I will try to fix. Reopen.
