### ISSUE TITLE
Issue with Live Streaming URL 

### ISSUE THREAD

**Issue by Asfand-Hafeez** [shogo4405/HaishinKit.swift#1509]
### Describe the bug

I am new to live streaming if i am doing anything wrong please share good  direction 
I am trying to implement live streaming in my app where if i click on start streaming then i need to share  rtmp://192.168.1.6/live to chromecast for reviewing in smart 
first issue this url not getting live streaming 
second issue 

Optional([AnyHashable("event"): Event{type: Name(rawValue: "ioError"),bubbles: false,data: nil,target: Optional(HaishinKit.RTMPConnection)}])
2024-11-07 14:21:43.370 [Warn] [com.haishinkit.HaishinKit] [RTMPSocketCompatible.swift:43] didTimeout() > connection timedout

### To Reproduce

open example app click on start streaming and url is not getting live streaming 

### Expected behavior

using same code from example app to get live streaming url 

### Version

1.1.1

**Comment by shogo4405** [comment]
Specify the address of the RTMP server where you want to stream.
HaishinKit is an RTMP client library, so you need to prepare an RTMP server separately.
