### ISSUE TITLE
Every FLV frame has key type

### ISSUE THREAD

**Issue by levs42** [shogo4405/HaishinKit.swift#1515]
### Describe the bug

Every frame sets `keyframe` value to true [here](https://github.com/shogo4405/HaishinKit.swift/blob/59b4b8ad5eff430dded90a9fd651538fd6f74c77/Sources/RTMP/RTMPMuxer.swift#L170). It worked in 1.8.0, keyframe appears approximately every 2 seconds. It stopped working in 1.8.1, keyframe is always true.

### To Reproduce

1. Add `print("keyframe: \(keyframe)")` to sample project [here](https://github.com/shogo4405/HaishinKit.swift/blob/59b4b8ad5eff430dded90a9fd651538fd6f74c77/Sources/RTMP/RTMPMuxer.swift#L170)
2. Start stream
3. Observe that keyframe is always true

### Expected behavior

To set keyframe every 2 seconds

### Version

1.9.1

### Smartphone info.

iPhone 15 Pro Max

**Comment by shogo4405** [comment]
Thank you feedback.
