### ISSUE TITLE
Unable to access AVCaptureVideoPreviewLayer while using stream.

### ISSUE THREAD

**Issue by DarshanJGigLabz** [shogo4405/HaishinKit.swift#1518]
### Describe the bug

PLease help me get the access to **AVCaptureVideoPreviewLayer** for the following usage of **MLKit camera position.**

```
func normalizedPoint(
    fromVisionPoint point: VisionPoint,
    width: CGFloat,
    height: CGFloat
    ) -> CGPoint {
        let cgPoint = CGPoint(x: point.x, y: point.y)
        var normalizedPoint = CGPoint(x: cgPoint.x / width, y: cgPoint.y / height)
        normalizedPoint = self.previewLayer.layerPointConverted(fromCaptureDevicePoint: normalizedPoint)
        return normalizedPoint
    }
```

### To Reproduce

please check the IOCaptureVideoPreview for more details

### Expected behavior

We should get the access to use AVCaptureVideoPreviewLayer

### Version

1.9.2

### Smartphone info.

iPhone 15

**Comment by shogo4405** [comment]
I haven't set it up to allow special access. I would appreciate it if you could fork it and handle it that way.
