### ISSUE TITLE
Any ideas about optimizing with the Howling Problem?

### ISSUE THREAD

**Issue by RainyTunes** [shogo4405/HaishinKit.swift#1528]
### Describe the bug

It seems that nobody has mentioned this issue in the git issues.

Usually, when I open both the streaming client and the playback client together for testing, and the howling problem is very obvious.

The issue can also occur among streamers, so I wanna try to figure it out.

From my experience, I suppose the problem is not such obvious when streaming via OBS or the platforms' private streaming tools.

And could we use any approaches related to audio hardware or driver to optimize this?

### To Reproduce

While streaming, open a viewer playback player and play the sound out loud.

### Expected behavior

Any approches to make the problem not so obvious?

### Version

1.9.1

**Comment by shogo4405** [comment]
At the framework level, it is not provided.
If you need calls or video chat, we recommend using WebRTC.

There are limitations, but by setting it as follows, it seems that the OS-level echo cancellation feature works.

```
let session = AVAudioSession.sharedInstance()
try session.setCategory(.playAndRecord, mode: .voiceChat, options: [.allowBluetooth])
try session.setActive(true)
```

**Comment by RainyTunes** [comment]
Thank you very much for the answer. I would have a try.
