### ISSUE TITLE
Phone -> OBS -> Stream quality problem

### ISSUE THREAD

**Issue by iostestuser985** [shogo4405/HaishinKit.swift#1539]
### Describe the bug

I connect to "OBS" using "srt" on my phone, after a short while after starting the broadcast the image looks like the one below (It looks like it's burnt, the quality is bad) OBS and phone resolution - bitrate - fps settings are the same, my config settings on the phone side are like this:

VideoCodecSettings(videoSize: (1280.0, 720.0), bitRate: 2560000, profileLevel: "H264_Main_AutoLevel", scalingMode: HaishinKit.VideoCodecSettings.ScalingMode.trim, bitRateMode: HaishinKit.VideoCodecSettings.BitRateMode.constant, maxKeyFrameIntervalDuration: 2, allowFrameReordering: Optional(false), dataRateLimits: Optional([0.0, 0.0]), isHardwareEncoderEnabled: true, frameInterval: 0.0, format: HaishinKit.VideoCodecSettings.Format.h264)

What can I do about this?

### To Reproduce

- install obs
- add media device
- enter url: srt://0.0.0.0:7654?mode=listener
- input format: mpegts

### Expected behavior

Continuing the stream without deteriorating image quality

### Version

main branch(e3288d1)

### Smartphone info.

- iphone xr
- iphone 11
- iphone 15 pro

### Screenshots

![image](https://github.com/user-attachments/assets/d047bf22-226a-479d-8795-f2f88be9edb9)

**Comment by shogo4405** [comment]
Did you use OBS as the sending side? Also, where was the screenshot you provided captured from?

**Comment by iostestuser985** [comment]
> Did you use OBS as the sending side? Also, where was the screenshot you provided captured from?

yes, the sender is obs. This screenshot was also taken on the obs screen, it looks the same on the broadcast

**Comment by iostestuser985** [comment]
### Update: 
I can't give "colorFormat" when broadcasting in dual camera mode. If I give "colorFormat" to one camera, both cameras don't open together, but if I make it a single camera and give "colorFormat", the image quality doesn't deteriorate much. Does "colorFormat" not support dual cameras?

**Comment by shogo4405** [comment]
I'm not sure. I can't help with that use case.
