### ISSUE TITLE
Multiple compile time error in  AMFFoundation and RTMPSharedObject Swift and SwiftUI

### ISSUE THREAD

**Issue by anand-OSM** [shogo4405/HaishinKit.swift#1541]
### Describe the bug

I am using SwiftUI and Swift.
My use case is send realtime video recording to server
I installed HaishinKit through Cocoapod also tried through SPM
But getting multiple compile time error.
<img width="1440" alt="Screenshot 2024-08-21 at 6 15 25 PM" src="https://github.com/user-attachments/assets/6a0de395-499a-4e8d-8261-f6b023aa9bd3">

### To Reproduce

1. Created a demo project in Swift and Swiftui
2. Install package through cocoapod
```
 def import_pods
    pod 'HaishinKit', '~> 1.9.2'
  end
  def import_pods
    pod 'SRTHaishinKit', '~> 1.9.2'
  end
```
 3. Compile the project 
4. Check issue navigator in Xcode
5. IT shows Issues in AMFFoundation and RTMPSharedObject

### Expected behavior

It should compile seamlessly 

### Version

Swift : 5
Xcode : 15.2
Macos : 14.2.1 (23C71

### Screenshots

<img width="1440" alt="Screenshot 2024-08-21 at 6 26 34 PM" src="https://github.com/user-attachments/assets/3aab2c7e-c491-46fe-8df4-d7d5c7323c30">
<img width="1438" alt="Screenshot 2024-08-21 at 6 26 12 PM" src="https://github.com/user-attachments/assets/2f6c6fc0-873a-4805-93a3-1c130714c5a6">

**Comment by shogo4405** [comment]
- First, it cannot be built with Xcode 15.2. Please update to 15.4.
  - [Requirements](https://github.com/shogo4405/HaishinKit.swift?tab=readme-ov-file#-requirements)
- If you are using CocoaPods, you can use it by importing only SRTHaishinKit.

**Comment by anand-OSM** [comment]
Thanks for the quick reply, I'll try with 15.4

**Comment by anand-OSM** [comment]
It works but camera screen is not showing instead showing a white screen

**Comment by shogo4405** [comment]
I will close this since the build was successful. Thank you for the report.
