### ISSUE TITLE
Bug in RTMPStream method dispatch

### ISSUE THREAD

**Issue by sergeymild** [shogo4405/HaishinKit.swift#1559]
### Describe the bug

Hello, i found a bug in `dispatch` method of `RTMPStream` class
on line 551 right after `continuation?.resume(throwing: Error.requestFailed(response: response))`
you are trying to set nil wrong field `connection` instead of `continuation` because of this, methods like `open` and `close` fails with an error

`Thread 6: Fatal error: SWIFT TASK CONTINUATION MISUSE: close() tried to resume its continuation more than once, throwing requestTimedOut!`
<img width="649" alt="Screenshot 2024-09-03 at 9 09 06 PM" src="https://github.com/user-attachments/assets/53e62848-cf75-4f1d-997f-68be0b872d0d">

### To Reproduce

1. start stream
2. close stream

### Expected behavior

stream should close without any errors

### Version

2.0.0-beta.2

**Comment by shogo4405** [comment]
Thank you fixed it.
