### ISSUE TITLE
Background noise cancellation

### ISSUE THREAD

**Issue by Nandhu-89** [shogo4405/HaishinKit.swift#1562]
### Describe the bug

Hi @shogo4405 I am using haishin_kit: ^0.13.0 in my flutter app to publish audio to RTMP server. How to remove background noise from microphone audio. When I use headphones the audio is clear. But without headphones the audio has background noise.

### To Reproduce

```
await session.configure(AudioSessionConfiguration(
      avAudioSessionMode: AVAudioSessionMode.voiceChat,
      avAudioSessionCategory: AVAudioSessionCategory.playAndRecord,
      avAudioSessionCategoryOptions:
      AVAudioSessionCategoryOptions.allowBluetooth|AVAudioSessionCategoryOptions.defaultToSpeaker,
    ));
```
audio bitrate => 120 kbps

### Expected behavior

publish live  audio to rtmp server without background noise.

### Version

haishin_kit: ^0.13.0

### Smartphone info.

iPhone

**Comment by shogo4405** [comment]
What kind of noise are you hearing? Could you record it and upload it? If it's just general noise, the library doesn't have a feature to handle that. I'm assuming you'll need to enable this OS feature: [https://support.apple.com/en-ca/101993](https://support.apple.com/en-ca/101993%E3%80%8D)
