### ISSUE TITLE
Screen objects rendering performance

### ISSUE THREAD

**Issue by levs42** [shogo4405/HaishinKit.swift#1564]
### Describe the bug

1.9.1 has significant CPU usage increase comparing to 1.8.1. Here's some comparison:
```
1.8.1:
- Multicam disabled
	- Idle: 15%
	- Streaming: 21%
- Multicam enabled
	- Idle: 53% (main: 5%)
	- Streaming: 56%
1.9.1:
- Multicam disabled
	- Idle: 65% (main: 31%)
	- Streaming: 68%
- Multicam enabled
	- Idle: 80% (main: 31%)
	- Streaming: 83%
```
There is a gain on the main thread:
<details>
  <summary>Spoiler</summary>
  
  1.8.1:
<img width="559" alt="1 8 1" src="https://github.com/user-attachments/assets/8f363314-7458-4dfb-aec7-7dbe8d717261">

  1.9.1:
<img width="546" alt="1 9 1" src="https://github.com/user-attachments/assets/0f195b4f-d220-44ed-90ac-73d2ada71e76">

</details>

Most of the gain comes from `vImageAlphaBlend_ARGB8888` and `createCGImage`. I'm thinking about some optimizations that could be done and looking for your opinion:
* To move `vImageAlphaBlend_ARGB8888` from the main thread
* To try using `CIFilter` for screens' rendering instead of `vImage` to avoid using CPU’s vector processor
* Use existing image buffer from the camera like 1.8.1 to void calling `createCGImage`
* Something that is related specifically to multicam - didn't identify yet

Any feedback is appreciated. 

### To Reproduce

Profile CPU usage of 1.8.1 and 1.9.1

### Expected behavior

* To have less usage of main thread
* To distribute work across the cores

### Version

1.8.1, 1.9.1

### Smartphone info.

iPhone 15 Pro Max

**Comment by shogo4405** [comment]
We've discussed this in another thread, but if you're using Xcode 15.4, I'd like you to measure with the Thread Performance Checker turned OFF. If you're using a different version of Xcode, please provide the environment information. For example, with iOS + iPhone 15 Pro Max + Multicam enabled, the CPU usage is around 45-55%.

> Expected behavior
> * To have less usage of main thread
> * To distribute work across the cores

As for the expected behavior, in version 2.0.0, the transition from @MainActor to a custom @ScreenActor has been made. It is expected to be resolved in version 2.0.0.

**Comment by levs42** [comment]
Thank you for the advice! I tried the example app with the Thread Performance Checker disabled, and the CPU usage for 1.9.1 + multicam + idle dropped from 80% to 50%. I will start migrating to version 2.0.0 to obtain the actor fix. Regarding multicam and screen rendering performance, it still seems like `vImage` is taking a considerable CPU toll. I haven't checked the performance with 2.0.0 yet, but version 1.8.1 uses `vImage` to render multicam on a non-main thread, and this still increases CPU usage from 15% to 50%. As more users will have devices that support multicam, a 50% CPU usage on the fastest iPhone appears quite high. Reducing the usage back to 15-20% by moving the rendering to the GPU would be a significant win. I can try to implement something like `ScreenRendererByGPU` using Core Image. What do you think?

**Comment by shogo4405** [comment]
Currently, the iPhone 15 Pro Max (2023) has a 6-core CPU, allowing for a maximum CPU usage of 600%.
I believe it's not an issue since it's using about 50% (with around 10-15% of that being for rendering to the view).

Additionally, on the iPhone XR (2018), which is the minimum requirement for iOS 17, it was around 65-70%. As long as the main thread isn't locked, I think it’s practical to use.

In the future, I’d like to try rendering using Metal. However, my understanding is that the CPU usage isn't so much due to vImage but rather the bottleneck is the YUV to RGB conversion of the camera feed.

Simply switching to Metal-based or other alternative methods won’t necessarily reduce CPU usage or stabilize FPS and other performance aspects; I don't know until it’s implemented.

**Comment by levs42** [comment]
I'll try to use 2.0.0 + CISourceOverCompositing to compare the performance. However, looks like Metal is the best choice because Core Image might be unpredictable in utilizing GPU over CPU. 

It looks like the YUV to RGB conversion is possible using a [shader](https://github.com/BradLarson/GPUImage3/blob/main/Sources/GPUImage/YUVToRGBConversion.swift). 

Going to close this for now as I don't know when I'll be able to try to add Metal implementation.

**Comment by mkrn** [comment]
Sorry for adding to a closed thread, but also dealing with this now, 
Is there any way to improve performance for this? Profiling:
![Screenshot 2024-09-20 at 14 53 13](https://github.com/user-attachments/assets/796da344-9b53-4ace-b01c-43012f349479)
![Screenshot 2024-09-20 at 14 32 36](https://github.com/user-attachments/assets/84b76402-f173-40f9-b5e0-1adaaa85e1aa)
Total CPU is not huge, but it seems to all happen on the main thread 
It seems to slow down the preview significantly, especially when using Image stabilization:
```
rtmpStream.videoMixerSettings.mode = .offscreen
```

**Comment by shogo4405** [comment]
Regarding the lag in the preview with stabilization, are you referring to the following preferredVideoStabilizationMode?
```swift
preferredVideoStabilizationMode = .cinematic
```

**Comment by mkrn** [comment]
![image](https://github.com/user-attachments/assets/b2be1776-38b8-4b64-b540-e70a4c6f16ac)
It looks like a staggering amount of time is spent on Alpha blending, I removed the alpha channel from colors in my image but it didn't help...
Perhaps the algorithm can be improved to reuse buffer or image in makeImage ? @shogo4405

**Comment by mkrn** [comment]
I use 
```
videoCapture.preferredVideoStabilizationMode = .standard  
```

However, when switching to .off it seems to help with perceived performance

**Comment by shogo4405** [comment]
As for the issue, is the problem the lag that occurs when` preferredVideoStabilizationMode = .standard `is set? Or is the high CPU usage itself the main issue?

Thanks to mkrn's advice, I was able to reduce the CPU usage to some extent. Thank you.
- I optimized the process and managed to reduce CPU usage. #1576
- I reviewed the rendering of MTHKView. It seems the CPU usage on the main thread has decreased. #1578

**Comment by mkrn** [comment]
This is good. I already tested first, and it improved a lot. Waiting for 1.9.5 for testing the second

**Comment by floriangbh** [comment]
We launched production a week ago and we noticed some lag issues in rendering (whether for the preview, local recording or streaming). This appears when ScreenObject is rendered. That's was not the case before with the old way with the old registerVideoEffect and older version. 

@mkrn did you test the with the new version ?

**Comment by floriangbh** [comment]
After some tests the problem seems to come from the stabilization. 
By the default it's off, put `preferredVideoStabilizationMode = .standard` seems to be almost OK. Let's try !
