### ISSUE TITLE
Cannot connect to rtmps server in 2.0.0 beta-3

### ISSUE THREAD

**Issue by kosmokoks** [shogo4405/HaishinKit.swift#1569]
### Describe the bug

Hi, I'm using an example for iOS Swift UI, trying to connect to the server. I didn't change anything in the example.

I just added streamName as streamKey to startPublish since the API requires it. Error when connecting: [RTMPSocket.swift:147] stateDidChange(to:) > Connection failed: POSIXErrorCode(rawValue: 54): Connection reset by peer.

the only method I changed in the example:
the uri and streamName exist
```
 func startPublish() {
        Task { @MainActor in
            UIApplication.shared.isIdleTimerDisabled = true
            logger.info(Preference.default.uri!)
            try? await rtmpConnection.connect(Preference.default.uri!)
            try await rtmpStream.publish(Preference.default.streamName!)
        }
    }
```

I tested my server on 1.7.0 version and it works
example server data:
uri: rtmps://live.cloudflare.com:443/live/
streamKey: [REMOVED]

### To Reproduce

1. Clone example repo
2. Open project
3. Build IOSSwiftUI 
4. Enter the rtmps server url and streamName
5. Start stream

### Expected behavior

Working live stream

### Version

2.0.0-beta.3

### Smartphone info.

Iphone 12 Pro

### Relevant log output

```shell
[RTMPSocket.swift:147] stateDidChange(to:) > Connection failed:POSIXErrorCode(rawValue: 54): Connection reset by peer
```

**Comment by shogo4405** [comment]
Thank you for your report. The issue has been fixed. The stream key you reported contains sensitive information, so I have deleted it on our end.

**Comment by shogo4405** [comment]
You can test it on the `main` branch. The next release is scheduled for around the end of September.
