### ISSUE TITLE
Crash after commit [Add movieFragmentInterval options.] when enter in background

### ISSUE THREAD

**Issue by al3x88** [shogo4405/HaishinKit.swift#1629]
### Describe the bug

If I install version 2.0.0 everything works perfectly unless you can't record locally as for the change in this commit: f433315e4fb946f2779cdf22d7c526bdeac96633

If setup my SPM with this commit:

<img width="865" alt="Screenshot 2024-11-21 at 12 07 54" src="https://github.com/user-attachments/assets/7b35a28c-7b35-42df-8a1f-ea0486915025">

what happen is that, the first time I call (in viewDidLoad):

`Task{ await mixer... }`

and I put the app in background, it throw the error:

`Incorrect actor executor assumption`

and, if you are from the simulator it crashes,  otherwise it restart from splash view (so basically the streaming is lost).

Note: if I comment all mixer occurrences and I test it works perfectly (unless does nothing since mixer is commented)

I tested extensively and I figured out that the behaviour happens **after** commit [Oct 31]:

4d190725e3dfdc2f8ca9d7c15fe09d403772efe1

**So most probably is related to some change happened on MediaMixer() on [Nov 1]** here:

1e95f8948750dbf7b0b1bcd952749e2f01d6ab2b

So currently I don't see any commit on ver 2.0.0 that allow my to record and going in background without issues.
Hope you can help me!! Many thanks for you amazing work.

### To Reproduce

1. SPM: setup commit: f433315e4fb946f2779cdf22d7c526bdeac96633
2. When you are on IngestViewController.swift (or similar) put app in background
3.  if you are testing from Xcode it will crash with error: `Incorrect actor executor assumption`
4. if you are testing without out Xcode it will restart from splash view.

### Expected behavior

When app is set in background, it should be resumed without issues and keeping RTMP connection and view alive.

### Version

2.0.0 commit f433315e4fb946f2779cdf22d7c526bdeac96633

### Smartphone info.

- IPHONE 12 iOS 18.1

**Comment by shogo4405** [comment]
I'm able to fix the issue on our end. Thank you for reporting it. https://github.com/shogo4405/HaishinKit.swift/pull/1630
