### ISSUE TITLE
PTS out of order, potentially causing audio/video sync issues

### ISSUE THREAD

**Issue by zachsimone** [shogo4405/HaishinKit.swift#1632]
### Describe the bug

We have issues where some users experience their audio and video getting out of sync during a stream. 

It was touched on in a [separate discussion](https://github.com/shogo4405/HaishinKit.swift/discussions/1475#discussioncomment-10621360), but we've started logging when we receive a video frame where the PTS is behind that of the earlier frame. We notice that the users experiencing the sync issue also seem to have this PTS sync issue during a stream. 

### To Reproduce

We don't really have a reliable way to reproduce. It seems to be isolated to certain devices, but we haven't been able to establish a pattern, nor reproduce the issue ourselves. 

### Expected behavior

The frames should be in sync and/or not cause the audio and video to be out of sync.

### Version

1.8.3

### Additional context

Happy to move this to a discussion if it's more appropriate there. We're seeking guidance as to if this is a HaishinKit bug or likely a bug with something we are doing within our code, and what to look out for if it's the latter.

Also when PTS is out of sync what is normally a suitable solution - drop the video frame or is there more to it? 

Thanks.

**Comment by shogo4405** [comment]
This issue is addressed in this release. Please consider updating or applying the patch. 
https://github.com/shogo4405/HaishinKit.swift/releases/tag/1.9.6

**Comment by zachsimone** [comment]
Thanks @shogo4405, I will give that a try. 😀

**Comment by shogo4405** [comment]
Closing this issue as it may have been fixed in the latest version.
