### ISSUE TITLE
OS 버전과 Video profileLevel: kVTProfileLevel_H264_Main_5_0 의 상관 관계가 있나요?

### ISSUE THREAD

**Issue by keatonMD** [shogo4405/HaishinKit.swift#1647]
### Describe the bug

hello! 
This may be a question rather than an issue. When setting profileLevel: kVTProfileLevel_H264_Main_5_0 on rtmpStream iPhone 14 Pro in OS version 18.x, the video was stuttered when transmitted.
When I used OS 17.x version, it was broadcast normally. Do you know anything about this issue?
I need help ㅠ

For reference, in OS 18.x
If profileLevel: kVTProfileLevel_H264_Baseline_AutoLevel is set, it will be transmitted normally.

### To Reproduce

OS 18.x  device 14 pro >  
Video Setting : 
profileLevel: kVTProfileLevel_H264_Baseline_AutoLevel 
profileLevel: kVTProfileLevel_H264_Main_5_0  

OS 17.x  device 14 pro >  
Video Setting : 
profileLevel: kVTProfileLevel_H264_Baseline_AutoLevel 
profileLevel: kVTProfileLevel_H264_Main_5_0  

### Expected behavior

OS 18.x  device 14 pro >  
Video Setting : 
profileLevel: kVTProfileLevel_H264_Baseline_AutoLevel  > normal operation
profileLevel: kVTProfileLevel_H264_Main_5_0  > Problem occurred

OS 17.x  device 14 pro >  
Video Setting : 
profileLevel: kVTProfileLevel_H264_Baseline_AutoLevel  > normal operation
profileLevel: kVTProfileLevel_H264_Main_5_0  > normal operation

### Version

1.7.6

### Smartphone info.

iPhone 14 Pro in OS version 18.x

**Comment by shogo4405** [comment]
I tested it on the main branch locally, but I couldn’t reproduce the issue.
This does not mean that the latest version will resolve the problem.

First, please provide a method for me to reproduce the issue using the sample app below.
https://github.com/shogo4405/HaishinKit.swift/tree/main/Examples/iOS
