### ISSUE TITLE
Support Swift4.0 + XCode9.0

### ISSUE THREAD

**Issue by shogo4405** [shogo4405/HaishinKit.swift#239]
Of course! :)

* fileprivate to private
  * https://github.com/apple/swift-evolution/blob/master/proposals/0169-improve-interaction-between-private-declarations-and-extensions.md

**Comment by aerotran** [comment]
Is this being worked on another branch?

**Comment by shogo4405** [comment]
@aerotran 
No.

**Comment by shogo4405** [comment]
Released 0.8.0.
