### ISSUE TITLE
Crash encoding in landscape iOS 9.3.4 [736x414].

### ISSUE THREAD

**Issue by dmitryond** [shogo4405/HaishinKit.swift#241]
While at H264Encoder.swift application will crash at 5% cases when starting a stream, at 90% cases when closing a RTMP connection, and restarting the stream while at landscape and set to resolution of 736 : 414. 

Crash occurs during VTCompressionSessionEncodeFrame call.

Crash occurs on iPhone 6 Plus device with iOS 9.3.4 . 

Crash does not occur on iPhone 6s Plus device with iOS 10.3.2 .

Crash does not occur when using simulators.

**Comment by dmitryond** [comment]
This issue is no longer relevant. After update 0.7.2 or so I've yet to encounter same issue. Probably should be closed as solved.

**Comment by shogo4405** [comment]
OK.
