### ISSUE TITLE
Support VisualEffects without GLLFView

### ISSUE THREAD

**Issue by shogo4405** [shogo4405/HaishinKit.swift#264]
## Motivation
* #169

## Exsample
```swift
rtmpStream.contextFactory = {
     return CIContext()
}
rtmpStream.registerEffect(video: MonochromeEffect())
```

**Comment by animaonline** [comment]
Are you planning to add support for this? I would like to use effects, but cannot because of this bug https://github.com/shogo4405/HaishinKit.swift/issues/598
