### ISSUE TITLE
Rename lf.xcodeproj to HaishinKit.xcodeproj

### ISSUE THREAD

**Issue by shogo4405** [shogo4405/HaishinKit.swift#266]

**Comment by pvinis** [comment]
this is done, right?

**Comment by shogo4405** [comment]
xcodeproj file is done.
Remaining work... Readme, github's link... and so on.

**Comment by shogo4405** [comment]
'''kisaragi:HaishinKit.swift shogo$ pod trunk deprecate lf --in-favor-of=HaishinKit
[!] An unexpected error occurred: <!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>
'''
