### ISSUE TITLE
RTMP playback

### ISSUE THREAD

**Issue by MingLoan** [shogo4405/HaishinKit.swift#273]
I tried to run on some iOS simulator.

1. iPhone 5 and 5s simulator crashed but not iPhone 6s. (all ios10)
Any idea?

2. And CPU usage run high as 1xx% when playing stream, is it normal?

3. any way to detach RTMP stream after glLFView.attachStream(stream)?

Thanks.

**Comment by MingLoan** [comment]
can share some codes?

**Comment by shogo4405** [comment]
> 1. iPhone 5 and 5s simulator crashed but not iPhone 6s. (all ios10)
Any idea?

How about iOS real device? If iOS real device cause crash. I will fix it.

> 2. And CPU usage run high as 1xx% when playing stream, is it normal?

Are you talking about iOS simulator?  If iOS simulator, It's normal. Because, iOS simulator can't use hardware decoding.

> 3. any way to detach RTMP stream after glLFView.attachStream(stream)?

glfView.attachStream(nil)

**Comment by MingLoan** [comment]
thanks
