### ISSUE TITLE
Hello. I have some problem with image on first second live.

### ISSUE THREAD

**Issue by RomanIvaniv** [shogo4405/HaishinKit.swift#275]
When i start stream I have bad output image on youtube web page(only first 1-2 seconds, and then its back to normal). Can you give me some advice?
![rtmp](https://user-images.githubusercontent.com/15250116/28973088-dc42a094-793a-11e7-92e2-e4da3686854d.png)

**Comment by shogo4405** [comment]
It seems that application does not send a Keyframe.
How about Example applicaiton? It's the same?

**Comment by RomanIvaniv** [comment]
yes, the same problem on Example application. But its appeared only on  Youtube and only at the beginning. On Facebook everything ok.

**Comment by shogo4405** [comment]
I can't reproduce :(

Please write down your enviroment.
framework version, iPhone device model, iOS version. 
And YouTube viewer name. Chrome? Safari?

And RTMPStream.videoSettings

**Comment by shogo4405** [comment]
My video is here.
https://www.youtube.com/watch?v=SsRZHg9jfiM

**Comment by RomanIvaniv** [comment]
Thanks for your answer. 
Framework - 0.7.3, devices - iPod touch 6 and iPhone 5, iOS - 10.3.3, Safari.
RTMPStream.videoSettings from example.
https://www.youtube.com/watch?v=S_n0WDdrI74

**Comment by RomanIvaniv** [comment]
Hmm strange thing there. Yesterday this problem appeared on https://www.youtube.com/watch?v=S_n0WDdrI74 this video, but today I launch it and its ok. Maybe its something with youtube. I will investigate this problem. Thanks.
