### ISSUE TITLE
Having problem when running app

### ISSUE THREAD

**Issue by lethanhnguyen** [shogo4405/HaishinKit.swift#276]
I can build the app into my iphone but when I run it, it crashes and throws this message:

dyld: Library not loaded: @rpath/lf.framework/lf
  Referenced from: /private/var/containers/Bundle/Application/86A433CD-163C-4A91-9418-2F0280E13F2D/Example iOS.app/Frameworks/HaishinKit.framework/HaishinKit
  Reason: image not found

**Comment by shogo4405** [comment]
It works for me. My step is here. How about you?
```
git clone https://github.com/shogo4405/HaishinKit.swift.git
cd HaishinKit.swift/
carthage update --platform iOS
open XCGLogger.xcodeproj
```

**Comment by lethanhnguyen** [comment]
![screen shot 2017-08-05 at 3 16 20 pm](https://user-images.githubusercontent.com/6578323/28994137-17c27a84-79f1-11e7-801a-6e6c4d32b215.png)

Here is what I have after run carthage update --platform iOS. I cannot find any XCGLogger.xcodeproj to run

**Comment by shogo4405** [comment]
oh... I'm wrong.
```
open HaishinKit.xcodeproj
```

**Comment by lethanhnguyen** [comment]
yeah many thanks. I can run it now. But cannot find any button to start capture from my iphone to display on my website. I changed the rtmp link.

**Comment by shogo4405** [comment]
> But cannot find any button to start capture from my iphone

Exsample application does not cover all features.
Please customize yourself!
