### ISSUE TITLE
Stream from iPhone 7 to wowza at double speed

### ISSUE THREAD

**Issue by about-prog** [shogo4405/HaishinKit.swift#277]
Hi!

Have problems with streaming from iPhone 7 to Wowza server. Now using this settings:
rtmpStream.videoSettings = [
        "width": 1280,
        "height": 720,
        "bitrate": 900 * 1024,
        "profileLevel": kVTProfileLevel_H264_Baseline_AutoLevel,
      ]
Stream from iPhone 7 is like double speed on computer. Though video on iPhone 5, 6 seems ok but there is strange sound.

With kVTProfileLevel_H264_Baseline_5_2 stream from iPhone 6 doesn't work too (double speed on computer and no stream on iPhones). With kVTProfileLevel_H264_Baseline_3_1 stream from iPhones to iPhones seems works fine but on computer and android it's double speed. Other profile levels tested too - they have similar problems.

So kVTProfileLevel_H264_Baseline_AutoLevel is best I could get. Only stream from iphone 7 doesn't work properly. 

Any clues?

**Comment by shogo4405** [comment]
> Stream from iPhone 7 is like double speed on computer. Though video on iPhone 5, 6 seems ok but there is strange sound.

Do you have these lines?

```swift
import AVFoundation

do {
   try AVAudioSession.sharedInstance().setPreferredSampleRate(44_100)
   try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord)
   try AVAudioSession.sharedInstance().setMode(AVAudioSessionModeDefault)
   try AVAudioSession.sharedInstance().setActive(true)
   } catch {
}
```

**Comment by about-prog** [comment]
Yes, I have these lines.
Here I've uploaded two video samples. They were recorded by Wowza. And that's the same I see on live streaming:
https://files.fm/u/e7q6acdm#/
One is the stream from iphone 6 (all good) and another is the stream from iphone7 (it's not smooth).
Both streams had same settings.

**Comment by shogo4405** [comment]
>  but on computer and android it's double speed.

How can I test?

**Comment by shogo4405** [comment]
Addition, Need this line.
```swift
rtmpStream.audioSettings = [
    "sampleRate": 44_100, 
]
```

**Comment by about-prog** [comment]
Yes, have this line.
I can't explain it right. The audio is... hmmm... edgy.
I've posted links to videos in my previous comment - that's exactly how it looks on any device or player.

If I set kVTProfileLevel_H264_Baseline_5_2 and stream from iphone 6/7 - video is ok on any device except iphones 6 and 7 (HLS, I just  paste link to safari on ios) - it's just doesn't work. If I change to kVTProfileLevel_H264_Baseline_AutoLevel it's ok for all devices if the stream is from iphone 6. But if stream is going from iphone 7, the video is 'broken' (you can see how it is in example above). I can upload video to other file sharing service if needed.

**Comment by shogo4405** [comment]
Profile level 5.2 is highest. Old devices are not supported.
https://developer.apple.com/library/content/technotes/tn2224/_index.html

I'm always to set range 3.1~4.0. I have no trouble.
https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC#.E3.83.97.E3.83.AD.E3.83.95.E3.82.A1.E3.82.A4.E3.83.AB.E3.81.A8.E3.83.AC.E3.83.99.E3.83.AB

**Comment by about-prog** [comment]
Solved.
The problem was with this code:
rtmpStream.audioSettings = [
    "sampleRate": 44_100, 
]

Stream from iPhone 7 were fixed after I removed  these lines.

**Comment by shogo4405** [comment]
oh. really. Sounds good!
