### ISSUE TITLE
Sometime I received error like this.. Please help

### ISSUE THREAD

**Issue by MingLoan** [shogo4405/HaishinKit.swift#282]
cannot form weak reference to instance (0x1702834d0) of class HaishinKit.AVMixer. It is possible that this object was over-released, or is in the process of deallocation.

**Comment by MingLoan** [comment]
I am working on Broadcast Extension, using the same codes as your example.

**Comment by shogo4405** [comment]
OK. I will test. Please tell me.
iOS version and model name.

**Comment by MingLoan** [comment]
iOS 10.3, iPhone 7

**Comment by shogo4405** [comment]
well, I can't reprodece :(
I'm tested Vaingory or TowerDash.
How, about you?

**Comment by shogo4405** [comment]
Please more information, How to reprodece it.
Then I will reopen this issue. Best regards.
