### ISSUE TITLE
Question: Any way to get single frames while broadcasting?

### ISSUE THREAD

**Issue by CR34L** [shogo4405/HaishinKit.swift#284]
Is there any way to get single Frames as UIImage, CGImage or something else?
I dont want do use "GLLFView.snapshot" cause I need the image in original broadcast resolution. 
Thx in advise.

**Comment by shogo4405** [comment]
Please see this issue. https://github.com/shogo4405/HaishinKit.swift/issues/186
I hope this will help

**Comment by CR34L** [comment]
Nice solution. Thanks for pointing me into the right direction working with filters.

/// close
