### ISSUE TITLE
Adaptive upload RTMP

### ISSUE THREAD

**Issue by MingLoan** [shogo4405/HaishinKit.swift#285]
How can I do adaptive upload via RTMP?

I need to reduce bitrate when networking is poor and scale up again if it resumes normal.

**Comment by jbeoris** [comment]
[This has been solved here.](https://github.com/shogo4405/HaishinKit.swift/issues/126)

**Comment by shogo4405** [comment]
Please use Timer. And increse bitrate little by little.

```
    func tick(timer:Timer) {
        if let bitrate = stream.videoSettings["bitrate"] as? Int {
            stream.videoSettings["bitrate"] = min(bitrate + 64 * 1024, RTMPClient.maximumBitrate)
        }
    }
```

**Comment by jbeoris** [comment]
I implemented a similar solution to this, but it appeared to cause weird frame drop issues and low FPS issues. Is there a recommended timer interval that you have used to achieve a smooth upscaling of the bitrate? Thank you for your help.

**Comment by MingLoan** [comment]
same as @jbeoris

**Comment by chrisscholly** [comment]
same here :p
