### ISSUE TITLE
screen attach

### ISSUE THREAD

**Issue by streamingPer** [shogo4405/HaishinKit.swift#287]
hello,
why the camera view stop when i try to stream the screen
thx

**Comment by shogo4405** [comment]
I'm not sure :( Please your code.

**Comment by streamingPer** [comment]
This is my code
 override func viewDidLoad() {
        super.viewDidLoad()
        
        
        
        rtmpStream = RTMPStream(connection: rtmpConnection)
        
        
        
        rtmpStream.captureSettings = [
            "fps": 30, // FPS
            "sessionPreset": AVCaptureSessionPresetMedium, // input video width/height
            "continuousAutofocus": true, // use camera autofocus mode
            "continuousExposure": true, //  use camera exposure mode
        ]
        rtmpStream.audioSettings = [
            "muted": false, // mute audio
            "bitrate": 32 * 1024,
            "sampleRate": sampleRate,
        ]
        rtmpStream.videoSettings = [
            "width": 640, // video output width
            "height": 360, // video output height
            "bitrate": 160 * 1024, // video output bitrate
            // "dataRateLimits": [160 * 1024 / 8, 1], optional kVTCompressionPropertyKey_DataRateLimits property
            "profileLevel": kVTProfileLevel_H264_Baseline_3_1, // H264 Profile require "import VideoToolbox"
            "maxKeyFrameIntervalDuration": 2, // key frame / sec
        ]
        // "0" means the same of input
        rtmpStream.recorderSettings = [
            AVMediaTypeAudio: [
                AVFormatIDKey: Int(kAudioFormatMPEG4AAC),
                AVSampleRateKey: 0,
                AVNumberOfChannelsKey: 0,
                // AVEncoderBitRateKey: 128000,
            ],
            AVMediaTypeVideo: [
                AVVideoCodecKey: AVVideoCodecH264,
                AVVideoHeightKey: 0,
                AVVideoWidthKey: 0,
                
                AVVideoCompressionPropertiesKey: [
                    AVVideoMaxKeyFrameIntervalDurationKey: 2,
                    AVVideoProfileLevelKey: AVVideoProfileLevelH264Baseline30,
                    AVVideoAverageBitRateKey: 512000
                ],
                
            ],
        ]
}

 override func viewWillAppear(_ animated: Bool) {
        
        super.viewWillAppear(true)
        rtmpStream.attachAudio(AVCaptureDevice.defaultDevice(withMediaType: AVMediaTypeAudio), automaticallyConfiguresApplicationAudioSession: false)
        rtmpStream.attachCamera(DeviceUtil.device(withPosition: currentPosition)) { error in
                    }
               rtmpStream.addObserver(self, forKeyPath: "currentFPS", options: NSKeyValueObservingOptions.new, context: nil)
        streamGlobalView?.attachStream(rtmpStream)
        
        
        
        
    }

    
    override func viewWillDisappear(_ animated: Bool) {
       // logger.info("viewWillDisappear")
        super.viewWillDisappear(animated)
        rtmpStream.removeObserver(self, forKeyPath: "currentFPS")
        rtmpStream.close()
        rtmpStream.dispose()
    }
    
        override func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?) {
        if (Thread.isMainThread) {
            loadText?.text = "\(rtmpStream.currentFPS)"
        }
    }
    

    @IBAction func switchCam(_ sender: UIButton) {
        let position:AVCaptureDevicePosition = currentPosition == .back ? .front : .back
        rtmpStream.attachCamera(DeviceUtil.device(withPosition: position)) { error in
            //logger.warn(error.description)
        }
        currentPosition = position

        
        
    }

    @IBAction func screenattach(_ sender: Any) {
        rtmpStream.attachScreen(ScreenCaptureSession(shared: UIApplication.shared))
    }
    
        // Do any additional setup after loading the view.

func selectRTMP (_ notification: NSNotification){
    let ex = notification.object as! RTMPSourceM
    print(ex.name)
    print(ex.serverUrl)
    print(ex.streamKey)
    load.startAnimating()
    self.streamurl = ex.serverUrl
    self.streamKey = ex.streamKey
    isLive = true
    goLive.setImage(UIImage(named: "pauseStream"), for: .normal)
   /* rtmpConnection.addEventListener(Event.RTMP_STATUS, selector:#selector(StreamLiveViewController.rtmpStatusHandler(_:)), observer: self)
   */
    UIApplication.shared.isIdleTimerDisabled = true
    rtmpConnection.addEventListener(Event.RTMP_STATUS, selector:#selector(StreamLiveViewController.rtmpStatusHandler(_:)), observer: self)
    rtmpConnection.connect(Preference.defaultInstance.uri!)
    
 
   
    
    
}
    
   func rtmpStatusHandler(_ notification:Notification) {
        let e:Event = Event.from(notification)
        if let data:ASObject = e.data as? ASObject , let code:String = data["code"] as? String {
            switch code {
            case RTMPConnection.Code.connectSuccess.rawValue:
                rtmpStream!.publish(Preference.defaultInstance.streamName!)
            // sharedObject!.connect(rtmpConnection)
            default:
                break
            }
        }
    }

**Comment by streamingPer** [comment]
befor your last update it works fine. but now it crashes and also the display of the cam didn't move

**Comment by streamingPer** [comment]
also the preview befor the streaming and switshing between cams works fine. but when i tried to load an RTSP link with a timer as bellow
videoRTSP2 = RTSPPlayer(video: "rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov", usesTcp: false)
 timertest1 = Timer.scheduledTimer(timeInterval: 1.0/30, target: self, selector: #selector(StreamLiveViewController.updateglobalwithvid1), userInfo: nil, repeats: true)
            timertest1.fire()
the timer for update an imageview with the video 
the screen cam didnt' respond ans didnt move but i can see the diffusion on the server

please i need help
thx

**Comment by shogo4405** [comment]
> but now it crashes and also the display of the cam didn't move

Please attach crash log.

**Comment by streamingPer** [comment]
how can attach it?

**Comment by streamingPer** [comment]
i think my probleme it about threading? i have tu put the RTSP loading video and the attch on the same threadh howerver your'e using Thread.isMainThread and Thread.isMultiThread how can i use them?

**Comment by shogo4405** [comment]
> how can attach it?

Please screen shot on your xcode.

> i think my probleme it about threading?

I'm not sure. Please try yourself.

**Comment by shogo4405** [comment]
> why the camera view stop when i try to stream the screen

OK. I understand. It's a specification.
