### ISSUE TITLE
Freeze cam

### ISSUE THREAD

**Issue by RamzyChatti90** [shogo4405/HaishinKit.swift#290]
Please could you tell me how to disable freezing cam while streaming using attach screen
Thx

**Comment by shogo4405** [comment]
Can't use attachCamera and attachScreen at the same time.

**Comment by RamzyChatti90** [comment]
How about using attach screen without freezing the camera view behind

**Comment by RamzyChatti90** [comment]
And sometimes when i try to switch between this 2 function the app crashes ?

**Comment by shogo4405** [comment]
No way. I'm not design to switch between attachCamea and attachScreen.

**Comment by RamzyChatti90** [comment]
could you try to make it possible?

**Comment by shogo4405** [comment]
> could you try to make it possible?

No. I can't. I'm busy.

**Comment by Easyschools** [comment]
Did you have time solve this issue?
