### ISSUE TITLE
VisualEffect with UIGraphicsBeginImageContext creates empty RTMP stream

### ISSUE THREAD

**Issue by CR34L** [shogo4405/HaishinKit.swift#292]
Wiring up a filter like this:

    class DummyFilter: VisualEffect {

    func convert(fromCIImage: CIImage) -> UIImage {
        let context: CIContext = CIContext.init(options: nil)
        let cgImage: CGImage = context.createCGImage(fromCIImage, from: fromCIImage.extent)!
        let image: UIImage = UIImage.init(cgImage: cgImage)
        return image
    }
         
    override func execute(_ image: CIImage) -> CIImage {
            let temp = convert(fromCIImage: image);
            let sz = temp.size;

            UIGraphicsBeginImageContextWithOptions(sz, true, 0.5);
            temp.draw(in: CGRect(origin: CGPoint.zero, size: sz));
            let noAlphaImage = UIGraphicsGetImageFromCurrentImageContext();
            UIGraphicsEndImageContext();
            return image;
        }
    }

As you see this filter does nothing with the input image. If I start the stream the RTMP stream is always 0 bytes in size. Preview is working correctly. 

If I comment out the line: ` temp.draw(in: CGRect(origin: CGPoint.zero, size: sz));` everything is working correctly.

**Comment by shogo4405** [comment]
What do you want?

**Comment by CR34L** [comment]
Uff...

If I enable this DummyFilter the RTMP stream gets corrupted. I created some kind of "bluebox" filter to remove a background color and replace the color by an image. But using UIGraphicsBeginImageContextWithOptions and some UIImage conversions produces strange stuff.

**Comment by shogo4405** [comment]
Well... I'm recommending CIFilter approch. https://developer.apple.com/library/content/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html
UIGraphicsBeginImageContext is heavy :(
