### ISSUE TITLE
UInt16 conversion issue (macOS)

### ISSUE THREAD

**Issue by DimaZava** [shogo4405/HaishinKit.swift#293]
I have a problem while changing quality settings of screen streaming (I've tried many options of quality settings, including ones I found here like [this](https://github.com/shogo4405/HaishinKit.swift/issues/210) and so on). If I set at least medium quality of picture, 
```
        self.httpStream.videoSettings = ["width" : 1280, "height" : 720, "bitrate" : 160 * 1024]
        //self.httpStream.captureSettings = ["fps" : 30]
        self.httpStream.captureSettings = ["sessionPreset": AVCaptureSessionPreset1280x720] 
        //AVCaptureSessionPreset960x540
        self.httpStream.videoSettings = ["profileLevel": kVTProfileLevel_H264_Baseline_AutoLevel] 
        //kVTProfileLevel_H264_Baseline_5_0
```
framework starts crushing like this
![2017-09-04 18 09 36](https://user-images.githubusercontent.com/1781631/30032193-18a4f8aa-919d-11e7-964a-ad1bf64b7e31.png)

And that's reason - data.count + optionalPESHeader!.data.count = 283487

Also sometimes this function triggers exception
```
    func effect(_ buffer:CVImageBuffer) -> CIImage {
        var image:CIImage = CIImage(cvPixelBuffer: buffer)
        for effect in effects {
            image = effect.execute(image)
        }
        return image
    }
```

> Mirror(11223,0x700008b17000) malloc: *** error for object 0x6000000a7f1c: Invalid pointer dequeued from free list
> *** set a breakpoint in malloc_error_break to debug

These errors appear regulary.

And i've tried to set Optimization to Fastest - still no luck

How can I avoid it or fix?

**UPD:** I've spotted that changing of videoSettings size cause error, neither bitrate, nor fps, nor sessionPreset, nor profileLevel:

```
self.httpStream.captureSettings = [
            "fps": 30, // FPS
            "sessionPreset": AVCaptureSessionPresetHigh, // input video width/height
        ]
        self.httpStream.videoSettings = [
            "width": 1280, // video output width - CAUSE ERROR
            "height": 720, // video output height - CAUSE ERROR
            "bitrate": 14000 * 1024, // video output bitrate
            "profileLevel": kVTProfileLevel_H264_High_AutoLevel, // H264 Profile require "import VideoToolbox"
            "maxKeyFrameIntervalDuration": 1, // key frame / sec
        ]
```

XCode - 8.3.3
macOS - Sierra 10.12.6
HaishinKit - latest version

**Comment by shogo4405** [comment]
Thank u. I thought framework side bug.

**Comment by DimaZava** [comment]
@shogo4405 I've spotted that due to PES format there is packetLength field, which in framework have size of 2bytes, but, due to [wiki](https://en.wikipedia.org/wiki/Packetized_elementary_stream) size
> Can be zero. If the PES packet length is set to zero, the PES packet can be of any length. 
Which is actually my case.

So I've implemented such changes in Sources/ISO/PacketizedElementaryStream.swift

```
var packetLength: UInt32 = 0
---------------------------------
var payload:Data {
        get {
            let dataToReturn = ByteArray()
            dataToReturn.writeBytes(startCode).writeUInt8(streamID)
            if (packetLength < UInt32(UInt16.max)) {
                dataToReturn.writeUInt16(UInt16(packetLength))
            } else {
                dataToReturn.writeUInt16(0)
            }
            dataToReturn.writeBytes(optionalPESHeader?.data ?? Data())
            dataToReturn.writeBytes(data)
            
            return dataToReturn.data
        }
---------------------------------
    init?(sampleBuffer:CMSampleBuffer, timestamp:CMTime, config:AudioSpecificConfig?) {
        guard let payload:Data = sampleBuffer.dataBuffer?.data else {
            return nil
        }
        if (payload.count < Int(UInt16.max)) {
            data.append(contentsOf: config!.adts(payload.count))
        } else {
            print("more than UInt16")
        }
        data.append(payload)
        optionalPESHeader = PESOptionalHeader()
        optionalPESHeader?.dataAlignmentIndicator = true
        optionalPESHeader?.setTimestamp(
            timestamp,
            presentationTimeStamp: sampleBuffer.presentationTimeStamp,
            decodeTimeStamp: sampleBuffer.decodeTimeStamp
        )
        packetLength = UInt32(data.count + optionalPESHeader!.data.count)
    }
```
And implement some other changes like replacing UInt16 to UInt32

Also I've inserted checking of optional variable in Sources/Codec/AACEncoder function encodeSampleBuffer 

```
if let realBuffer = blockBuffer {
    let dataLength:Int = realBuffer.dataLength
    ....
    free(outOutputData.unsafeMutablePointer)
}
```

Thanks if you can correct me and give some advices
