### ISSUE TITLE
Chunk Type 3 is handled incorrectly

### ISSUE THREAD

**Issue by dtrofymenko** [shogo4405/HaishinKit.swift#294]
According to documentation "Adobe’s Real Time Messaging Protocol" 5.3.1.2.4.  Type 3 
"chunks of this type (Type 3) take values from the preceding chunk for the same Chunk Stream ID."

RTMPConnection doesn't track preceding chunks and doesn't propagate info to chunks with Type 3 in 
`func listen(_ data:Data)`

It can break the chunks stream entirely, because payload data from chunk with Type 3 goes to the beginning of the next chunk and corrupts it. 
`if (0 < position && position < data.count) {
   listen(data.advanced(by: position))
}`

After then corrupted chunk is saved to currentChunk and persists there till the end of the stream.
`guard let chunk:RTMPChunk = currentChunk ?? RTMPChunk(data, size: socket.chunkSizeC) else {
   socket.inputBuffer.append(data)
   return
}`
blocking all further chunks.

**Comment by shogo4405** [comment]
Oh. Thanks. I will fix. How can I reproduce?

**Comment by dtrofymenko** [comment]
I can't provide server URL I'm working with. In my particular case (live video upload) server sent first Acknowledgement with chunk type 2 (66 0 0 0 0 0 4 3 0 3 208 197) and consecutive with chunk type 3 (c2 00 07 a1 71) expecting me to take payload size from previous chunk with type 2.
