### ISSUE TITLE
HOWTO - Mac OS X - Flip Video Preview

### ISSUE THREAD

**Issue by nic0lae** [shogo4405/HaishinKit.swift#297]
Using the "Facetime HD Camera", how can I flip the video for preview ? What about the video that is being streamed ?

**Comment by shogo4405** [comment]
Please see this document. https://developer.apple.com/documentation/avfoundation/avcaptureconnection/1389172-videomirrored

Unfortunately, AVCaptureConnection property is private. Please customize yourself!
