### ISSUE TITLE
HOWTO - Apply Settings

### ISSUE THREAD

**Issue by nic0lae** [shogo4405/HaishinKit.swift#298]
I have a bit more detailed video preview than in the sample, see image below,
From each combo I can choose different settings.
How to correctly apply them to the video both preview and streamed ?

<img width="890" alt="screen shot 2017-09-11 at 8 40 26 pm" src="https://user-images.githubusercontent.com/3322853/30307231-8383ec78-9731-11e7-890f-4e2574c39283.png">

**Comment by shogo4405** [comment]
see this document. https://developer.apple.com/documentation/avfoundation/avcapturedevice/1389221-activeformat
