### ISSUE TITLE
cannot install from POD, carthage build failed

### ISSUE THREAD

**Issue by pconk** [shogo4405/HaishinKit.swift#299]
Hi 
I try to install from POD with 
_pod 'HaishinKit', '~> 0.7.4'_
result:
_Analyzing dependencies
[!] Unable to find a specification for `HaishinKit (~> 0.7.4)`_

Then i try Carthage:
_*** Fetching HaishinKit.swift
*** Fetching Logboard
*** Checking out HaishinKit.swift at "0.7.4"
*** Checking out Logboard at "1.0.1"
*** xcodebuild output can be found in /var/folders/3k/c96260ds5hgfld0sz_4xsy2r0000gr/T/carthage-xcodebuild.csIeR2.log
*** Building scheme "Logboard iOS" in Logboard.xcodeproj
*** Building scheme "iOS" in HaishinKit.xcodeproj
Build Failed
	Task failed with exit code 65:_

**Comment by shogo4405** [comment]
> [!] Unable to find a specification for HaishinKit (~> 0.7.4)
Please try this command `pod setup`
