### ISSUE TITLE
sample not work

### ISSUE THREAD

**Issue by duckscorpion13** [shogo4405/HaishinKit.swift#300]
Constant.swift
No such module 'Logboard'

**Comment by shogo4405** [comment]
Please use `carthage update --platform iOS`
Carthage is here. https://github.com/Carthage/Carthage

**Comment by jacobbullock** [comment]
@shogo4405 you might consider putting this in the readme file

**Comment by androidkeshav** [comment]
No such module 'Logboard'
how to solve by cocopods?

**Comment by Rauf54** [comment]
@androidkeshav you find any answer?
