### ISSUE TITLE
Audio loops when streaming

### ISSUE THREAD

**Issue by solodkyi** [shogo4405/HaishinKit.swift#303]
Hi! How I need to setup AVAudioSession to prevent audio looping? As of now I use:

> 

       do {
            try AVAudioSession.sharedInstance().setPreferredSampleRate(self.sampleRate)
            try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord)
            try AVAudioSession.sharedInstance().overrideOutputAudioPort(AVAudioSessionPortOverride.speaker)
            try AVAudioSession.sharedInstance().setMode(AVAudioSessionModeVideoChat)
            try AVAudioSession.sharedInstance().setActive(false)
        } catch {
            print("FAIL")
        }

> 

and
>
        rtmpStream = RTMPStream(connection: rtmpConnection)
        rtmpStream.captureSettings = [
            "fps": 30, // FPS
            "sessionPreset": AVCaptureSessionPresetLow,
            "continuousAutofocus": true,
            "continuousExposure": true,
        ]
        rtmpStream.videoSettings = [
            "width": 500, // video output width
            "height": 700, // video output height
            "bitrate": 160 * 1024, // video output bitrate
             "dataRateLimits": [160 * 1024 / 8, 1],
            "maxKeyFrameIntervalDuration": 5,
        ]
        rtmpStream.audioSettings = [
            "sampleRate": self.sampleRate,
            "muted" : false,
        ]
    }
>

>
    self.rtmpStream.attachAudio(AVCaptureDevice.defaultDevice(withMediaType: AVMediaTypeAudio), automaticallyConfiguresApplicationAudioSession: true) { error in
     print(error)
        }
>

**Comment by matthijsotterloo** [comment]
Same issue here.

**Comment by shogo4405** [comment]
I thought it's not suitable for AVAudioSession.sharedInstance().
Please trial and error :(

**Comment by HauDo** [comment]
I have the same issue, please tell me how to fix it?
