### ISSUE TITLE
Cannot override `didFinishWriting(_ recorder: AVMixerRecorder)` of the `DefaultAVMixerRecorderDelegate`

### ISSUE THREAD

**Issue by akolov** [shogo4405/HaishinKit.swift#305]
I have a class which inherits from the `DefaultAVMixerRecorderDelegate` and overrides `didFinishWriting(_ recorder: AVMixerRecorder)`. With Swift 4 it's now impossible to override any methods declared in the `extension DefaultAVMixerRecorderDelegate : AVMixerRecorderDelegate { ... }` due to `Declarations from extensions cannot be overridden yet`.

**Comment by shogo4405** [comment]
Thank u.
