### ISSUE TITLE
nginx-rtmp-moduleを用いて立てたrtmpサーバへの接続に失敗

### ISSUE THREAD

**Issue by murata99** [shogo4405/HaishinKit.swift#312]
nginx-rtmp-moduleを用いて立てたrtmpサーバに対して、以下のようなURLで接続しようとすると失敗しました。
`rtmp://hoge.com:5002/live/4?token=fooo`

次のような修正を行い、接続に成功しました。
https://github.com/murata99/HaishinKit.swift/commit/e346b3bb5c4c06ec138a1aeab80880c50ff395c0

私はRTMPに詳しくなく、修正内容が間違っていると感じます。
もう少しきちんとした状態にして Pull requests を出したいと思っていますが、どのようにするのが最適でしょうか。

**Comment by shogo4405** [comment]
こんにちわ。

rtmp://hoge.com:5002/live/4?token=foooというURIがあった場合、
以下の解釈がありサーバー実装上どちらも間違っておりません。

1)
    var uri:String? = "rtmp://hoge.com:5002/live?token=fooo"
    var streamName:String? = "4"

2)
    var uri:String? = "rtmp://hoge.com:5002/live"
    var streamName:String? = "4?token=fooo"

したがってどちらも対応するためにこのような実装になっております。

**Comment by murata99** [comment]
コメントありがとうございます。

私の理解が追いついておらず、少し小分けにして整理させてください。
まず１点目に、RTMPConnection.connect()の直後に以下のようなログが出力され、コネクションが切断されます（URIは一例です）。
```
[Trace] [com.haishinkit.HaishinKit] [84] doOutput(chunk:locked:) > RTMPChunk{size:0,type:zero,streamId:3,message:Optional(RTMPCommandMessage{type:amf0Command,length:337,streamId:0,timestamp:0,payload:325 bytes,objectEncoding:0,commandName:connect,transactionId:1,commandObject:Optional(["videoCodecs": Optional(128), "tcUrl": Optional("rtmp://hoge:5002/live/4?token=foo"), "flashVer": Optional("FMLE/3.0 (compatible; FMSc/1.0)"), "app": Optional("live/4?token=foo"), "videoFunction": Optional(1), "swfUrl": nil, "fpad": Optional(false), "capabilities": Optional(239), "audioCodecs": Optional(1024), "pageUrl": nil, "objectEncoding": Optional(0)]),arguments:[],serializer:AMF0Serializer{data:0 bytes,position:0,reference:HaishinKit.AMFReference}}),fragmented:false,_data:12 bytes}
[Trace] [com.haishinkit.HaishinKit] [90] close(isDisconnected:) > isDisconnected:true
[Warn] [com.haishinkit.HaishinKit] [362] on(status:) > 
```

原因はおそらく以下の箇所です。
以下のコードを実行すると、appには `live/4` が入ります。
ここは `live` となるべきではないでしょうか。
```
let uri = URL(string: "rtmp://hoge.com:5002/live/4?token=fooo")!
var app:String = uri.path.substring(from: uri.path.characters.index(uri.path.startIndex, offsetBy: 1))
print(app)
```

環境は以下のとおりです。
- Xcode Version 9.0
- Apple Swift version 4.0

**Comment by shogo4405** [comment]
前提条件としてなのですが、

murata99さんの設定いただいているPreference.swiftの中身が次の通りという解釈でよろしいでしょうか？
```
 Preference.defaultInstance.uri = "rtmp://hoge.com:5002/live/4?token=fooo"
 Preference.defaultInstance.streamName = nil
```

上記前提での話であればmurata99さんの仰る通りで間違いありません。

**Comment by shogo4405** [comment]
しかしながら、RTMPの場合は 以下の2つの情報が必要です。

1. 接続に必要なRTMP URL
2. 接続後に必要な RTMP StreamKey

今回のケースでは以下のようにセットしていただくことで解決するかと存じます。
```
 Preference.defaultInstance.uri = "rtmp://hoge.com:5002/live"
 Preference.defaultInstance.streamName = "4?token=fooo"
```

**Comment by murata99** [comment]
丁寧なご説明、ありがとうございます。
Exampleの画面にあった２つの入力欄の使い方が分かりました。

ご指摘の通り、以下の形で接続することが出来ました。
```
rtmp://hoge.com:5002/live
4?token=fooo
```

RTMPConneciton.connect()への入力のURIは `rtmp://hoge.com:5002/live/4?token=fooo` で、その後ライブラリ側の処理で分割されるものと思いこんでいました。
最初にテスト用に実行したffmpegでのftmpサーバのURI指定がそうだったためかもしれません。

**Comment by murata99** [comment]
誤記があったので訂正します。
誤：ftmpサーバの
正：rtmpサーバの
