### ISSUE TITLE
RTMPStream.qosDelegate should be declared as weak

### ISSUE THREAD

**Issue by macness-pavelh** [shogo4405/HaishinKit.swift#315]
Cocoa patterns typically declare delegates as weak. 

`RTMPStream` owner frequently set the delegate to `self` (or to an another owned object) what creates a circular reference which has to be treated manually. 

Changing it to weak MIGHT (but more likely will not) have some impact on existing code, but I believe pros are stronger then cons.

HTH

**Comment by shogo4405** [comment]
Absolutely! I will change next release :)

**Comment by shogo4405** [comment]
Released 0.8.2
