### ISSUE TITLE
Compiling Issues

### ISSUE THREAD

**Issue by jrahaim** [shogo4405/HaishinKit.swift#318]
I am updating a project that used to use LF. I have switched the Podfile to `HaishinKit` cleaned everything, and am recompiling.. 
```
Installing HaishinKit (0.8.1)
Installing Logboard (1.1.1)
```
On Xcode 9 I get an error on references to `AVMediaType`
for example in `AudioIOComponent.swift`

``` swift
 func appendSampleBuffer(_ sampleBuffer:CMSampleBuffer) {
        mixer?.recorder.appendSampleBuffer(sampleBuffer, mediaType: .audio)
        encoder.encodeSampleBuffer(sampleBuffer)
    }
```

I get `Type 'AVMediaType' (aka 'NSString') has no member 'audio'`

I also get other errors (33 total).
`Type 'AVCaptureSession.Preset' (aka 'NSString') has no member 'medium'`

I feel like I have something set wrong, but I can't figure out what. 

In Xcode 8 I get a different set of errors.. 
`Pods/HaishinKit/Sources/Media/VideoIOComponent.swift:48:34: 'Position' is not a member type of 'AVCaptureDevice'`
`Pods/HaishinKit/Sources/Media/VideoIOComponent.swift:48:9: Could not infer type for 'position'`
etc..

**Comment by jrahaim** [comment]
I am going to close this. I don't know what was happening.. but I removed All my pods.. deleted the Pods/ dir.. Added them one at a time.. And managed to get compiled. 

Sorry for the noise.

**Comment by shogo4405** [comment]
No problem. Thank u for issue.
