### ISSUE TITLE
AV out of sync after camera toggle

### ISSUE THREAD

**Issue by macness-pavelh** [shogo4405/HaishinKit.swift#320]
If I flip back/front camera with the code below, the video is a fragment of second behind audio. This seems to be cumulative (lag increases each toggle)

```
 func flipCamera() {
        let position:AVCaptureDevice.Position = currentPosition == .back ? .front : .back
        rtmpStream.attachCamera(DeviceUtil.device(withPosition: position)) { error in
            //logger.warning(error)
            log_error("attach camera error: \(error)")
        }
        currentPosition = position
    }
```

**Comment by ParvinderjitSF** [comment]
Facing the same issue on 1.4.1 and 1.4.3.

To reproduce:- 
- Download the Sample app 
- Start streaming on server 
- Toggle the camera back to front and so on
- Check the result
