### ISSUE TITLE
Support audio & mic mixing for ReplayKit2 extension ?

### ISSUE THREAD

**Issue by PatrickSCLin** [shogo4405/HaishinKit.swift#322]
I found in iOS 11,  AVAudioEngine supports manual rendering in offline mode which allows to mix audios to a rendering block instead of device output

Is possible using AVAudioEngine to support audio & mic mix before appendBuffer to RTMPStream ?

**Comment by shogo4405** [comment]
Well... I'm not sure :( Please try to do your self.
