### ISSUE TITLE
Screen Capturing not working

### ISSUE THREAD

**Issue by lukvol** [shogo4405/HaishinKit.swift#323]
Hello
I'm currently trying to make an app which can broadcast the screen to an external server (rtmp/hls does not matter at the moment). I tried to use this frameworks `rtmpStream.attachScreen(ScreenCaptureSession(viewToCapture: ))
` method to achieve this. However, it does not work as expected.
I have tried to implement a very basic application which captures the content of one view and displays it in a LFView. This is my code:

`let rtmpConnection:RTMPConnection = RTMPConnection()

        let rtmpStream: RTMPStream = RTMPStream(connection: rtmpConnection)
        rtmpStream.attachScreen(ScreenCaptureSession(viewToCapture: screen))
        test.attachStream(rtmpStream)

        rtmpConnection.connect("rtmp://localhost:9000/live")
        rtmpStream.publish("test")`
However, instead of displaying the view 'screen' in test (which is an LFView), test remains black. Am I missing something or is there a bug?

**Comment by shogo4405** [comment]
How about GLLFView? LFView supports an AVCaptureSession only.
