### ISSUE TITLE
stream from pre-record video ?

### ISSUE THREAD

**Issue by pensokha** [shogo4405/HaishinKit.swift#326]
is it possible to stream from existing mp4 video file instead of camera?

**Comment by shogo4405** [comment]
Yes. Framework has feature.
https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/RTMP/RTMPStream.swift#L556

Please try RTMPStream.appendFile.

**Comment by sevenb** [comment]
How? I'm getting a black screen when use that:

rtmpStream.appendFile(Bundle.main.url(forResource: "Wanderlei", withExtension: ".mp4")!,completionHandler: {
			print("erro?")
		})
		lfView?.attachStream(rtmpStream)

**Comment by shogo4405** [comment]
> How? I'm getting a black screen when use that:

You are correct. But framework can't playback.

**Comment by sevenb** [comment]
Sorry, I mean that I'm getting a black screen on the streaming video, not on the device.
That happens when I switch the camera for the append file. I'm using the GLHKView.

**Comment by shogo4405** [comment]
In the first place, framework can't support switch camera to appendFile.

**Comment by sevenb** [comment]
Hi,
Can you show a sample of that? Because there is no documentation for this framework, that's why you have a lot of people asking for something.

**Comment by sevenb** [comment]
Just show me how can I load a mp4 file and stream it.
Thanks

**Comment by sevenb** [comment]
Really thanks! it works. Is there a way to get an event when the video is finished? using the completionHandler? is there some example of that?

stream.appendFile(url,completionHandler:{
				print("how can I know the end?")
			})

**Comment by mocman** [comment]
Is there a way to change the videoSettings when using appendFile? Video is choppy on Twitch and some other RTMPs. Would like to be able to change "profileLevel" to kVTProfileLevel_H264_Baseline_3_1 to fix it.

Using stream.videoSettings didn't seem to affect the output at all.

**Comment by abubaqr70** [comment]
how can we append existing mov file i try to stream an mov file picked from the gallery

**Comment by abubaqr70** [comment]
> Really thanks! it works. Is there a way to get an event when the video is finished? using the completionHandler? is there some example of that?
> 
> stream.appendFile(url,completionHandler:{
> print("how can I know the end?")
> })

it works for mp4 only but how to append mov file picked from the gallery

**Comment by abubaqr70** [comment]
> Yes. Framework has feature.
> https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/RTMP/RTMPStream.swift#L556
> 
> Please try RTMPStream.appendFile.

i need to append the mov file what is the workaround and there is no such documentation available

**Comment by abubaqr70** [comment]
> is it possible to stream from existing mp4 video file instead of camera?

how to stream from existing mov file

**Comment by abubaqr70** [comment]
@sevenb  @shogo4405  how can i append the file from the gallery in swift is there a working sample please provide me...!

**Comment by dovelive** [comment]
@shogo4405 
It seems that appendFile function in RTMPStream has removed.
In this case, which function should I use for this feature.
