### ISSUE TITLE
Recording the ReplayKit stream locally.

### ISSUE THREAD

**Issue by dmitryond** [shogo4405/HaishinKit.swift#329]
I'm streaming application using ReplayKit solution (much faster).

When I'm trying to use the CMSampleBuffer of the RPBroadcastSampleHandler to feed it to AVAssetWriter I created or  when I'm trying to run two RTMPStream instances at the same time (one is regular, another one is .localRecord) it results in a same unplayable file.

Could you please direct me to a proper solution?

**Comment by shogo4405** [comment]
I'm not sure. I heard can't work AVAssetWriter.
https://forums.developer.apple.com/thread/84479

**Comment by dmitryond** [comment]
The problem he's describing is slightly different, but I guess it is better to wait for a new Xcode version. He is unable to start AVAssetWriter, while in my case whether it's a RTMPStream recorder.writer or my own writer, they start and they write the buffers to an output file, but when it's time to .stopWriting then never stop and the writer is still in state .writing. This is very strange, it's like something is preventing it from finalizing.

Maybe it is a Xcode bug after all. 

I will update after ... after there's an update. :)
