### ISSUE TITLE
XCode9.1 Swift Compiler Warning

### ISSUE THREAD

**Issue by shogo4405** [shogo4405/HaishinKit.swift#333]
<img width="1440" alt="2017-11-04 3 39 50" src="https://user-images.githubusercontent.com/810189/32390453-d9415718-c111-11e7-9a29-1d340e1d1425.png">

**Comment by dmitryond** [comment]
I had this error as soon as I upgraded to XCode 9.1.

I did pod install, cleaned and recompiled, and this error went away.
