### ISSUE TITLE
how to use the extension about ScreencastUI and Screencast

### ISSUE THREAD

**Issue by CodeZheng** [shogo4405/HaishinKit.swift#335]
I don't know the type of ScreencastUI and Screencast , how to show BroadcastViewController when I use the haishinkit?

**Comment by CodeZheng** [comment]
![img_0007](https://user-images.githubusercontent.com/15793692/32484431-c11818d6-c3da-11e7-9253-3f52b3f7e59c.png)
Could you tell me how to deal with this error ? Thinks!

**Comment by shogo4405** [comment]
> I don't know the type of ScreencastUI and Screencast , how to show BroadcastViewController when I use the haishinkit?
Please try to my example project.

> Could you tell me how to deal with this error ? 
I'm not sure. Please google it!
