### ISSUE TITLE
Streaming over RTMP to twitch

### ISSUE THREAD

**Issue by szczebel1995** [shogo4405/HaishinKit.swift#336]
Hi

I tried to run the example app and make it stream to twitch to one of their [rtmp servers](https://stream.twitch.tv/ingests/) and I managed to make the app run properly. I replaced the url in the preferences with the proper twitch one that I tested so I know there is nothing wrong with it. When I press publish button I see in the debug console that the packets are sent but I can't see anything on my twitch channel. Does anyone have some tips how to make rtmp broadcast to twitch work? Maybe some really minimal code example?

**Comment by shogo4405** [comment]
> I replaced the url in the preferences

You have to replace url and streamKey.
rtmp://live-eze.twitch.tv/app/{stream_key}

> struct Preference {
>    static var defaultInstance:Preference = Preference()
>    
>    var uri:String? = "rtmp://test:test@192.168.11.19/live"
>    var streamName:String? = "live"
>}

url = rtmp://live-eze.twitch.tv/app/
streamName = "{stream_key}"

Best regards.
