### ISSUE TITLE
mixer.videoIO.lockQueue.async may caused crash

### ISSUE THREAD

**Issue by PatrickSCLin** [shogo4405/HaishinKit.swift#340]
I am using HaishinKit in broadcast upload extension on iOS 11 (Screen Broadcasting)

It always give us a portrait up orientation, and an orientation key in CMSampleBuffer, so we have to create a new CMSampleBuffer with rotated CIImage. 

then append our own CMSampleBuffer to RTMPBroadcaster, here is a problem , this method has invoked  an async method, so it will caused crash after I release my own CMSampleBuffer.

**Comment by shogo4405** [comment]
I think framework needs lockQueue.async.
If has no lockQueue. Video frame order went wrong.

BTW, Framework has a video effect feature.

**Comment by PatrickSCLin** [comment]
how about add a consume callback ? 

I have take a look VisualEffect, it's perfect to do something cool, however it's just only provide CIImage, the orientation info is included in CMSampleBuffer

https://developer.apple.com/documentation/replaykit/rpvideosampleorientationkey
```
/*!
 @key RPVideoSampleOrientationKey
 @abstract Use this key in conjunction with CMGetAttachment on CMSampleBufferRef to get the orientation for the sample. The orientation will follow the enum CGImagePropertyOrientation
 */
@available(iOS 11.0, *)
public let RPVideoSampleOrientationKey: String
```

**Comment by shogo4405** [comment]
```
class YourEffect: VisualEffect {
    var orientation: ????
    override func execute(_ image: CIImage) -> CIImage {
        // Please custom your logic
        return image
    }
}
```

```
rtmpStream.context = CIContext(mtlDevice: MTLCreateSystemDefaultDevice()!)
rtmpStream.registerEffect(video: yourEffect!)
```

**Comment by PatrickSCLin** [comment]
Have you try ReplayKit2 broadcast upload  extension in iOS 11?

It's different with ReplayKit in iOS10.

you will always get a CMSampleBuffer which orientation of image is UP, detail of orientation is attached in CMSampleBuffer. 

https://developer.apple.com/documentation/replaykit/rpvideosampleorientationkey

**Comment by shogo4405** [comment]
> It's different with ReplayKit in iOS10.

Yes. I know. What's problem?

**Comment by PatrickSCLin** [comment]
effect only execute video effect but  RPVideoSampleOrientationKey is attached in CMSampleBuffer,
you have no idea user is in left landscape or right landscape exactly in this frame since there is no params or userInfo in this method

```
func effect(_ buffer:CVImageBuffer) -> CIImage {
        var image:CIImage = CIImage(cvPixelBuffer: buffer)
        for effect in effects {
            image = effect.execute(image)
        }
        return image
    }

```

**Comment by PatrickSCLin** [comment]
oh, ok, I saw this RTMPStream appendSampleBuffer is still in same thread, maybe I can handle this by myself

**Comment by PatrickSCLin** [comment]
@shogo4405 I've setup a VisualEffect for rotation, I can see CIImage does change the size.
but it looks nothing change in player, I'm using v0.7.8

**Comment by PatrickSCLin** [comment]
Does VisualEffect just for PreviewView ?

**Comment by shogo4405** [comment]
> Does VisualEffect just for PreviewView ?

No. But framework has other issue https://github.com/shogo4405/HaishinKit.swift/issues/344.
If you want output change size. You have to set this properties. 
* rtmpStream.videoSettings["width"] 
* rtmpStream.videoSettings["height"]
