### ISSUE TITLE
Is there a way to stream from two audio inputs?

### ISSUE THREAD

**Issue by szczebel1995** [shogo4405/HaishinKit.swift#341]
Hi,

I'm currently using this amazing library to stream the screen from my app. My app plays audio - background music, and I want to let users stream their voice with the music at the same time. When I use default mic it also captures the audio from the speakers but of course, it's not the best quality and when there are headphones plugged in, then the background music can't be streamed. My question is, is there a way to have two audio inputs, one from the mic and one from the app, and stream them together? I just want to know if its possible even if it will take a lot of work. The audio is played from embedded unity view so I can be very flexible with manipulating and streaming audio to an encoder.

**Comment by shogo4405** [comment]
Framework has no feature!
Thank u.
