### ISSUE TITLE
Stream capture always streams in 320p

### ISSUE THREAD

**Issue by szczebel1995** [shogo4405/HaishinKit.swift#342]
Hi

I got 2 problems with screen capture, first is that no matter what settings I choose output stream is always in 320p, I tried 720p and 1080p settings and it still streams in 320p. Here's my settings:

```
store.rtmpStream = RTMPStream(connection: rtmpConnection)
        store.rtmpStream.syncOrientation = true
        store.rtmpStream.captureSettings = [
             "fps": 30.0,
            "sessionPreset": AVCaptureSession.Preset.hd1920x1080,
        ]
        store.rtmpStream.videoSettings = [
            "width": 1920,
            "height": 1080,
            "bitrate": 300 * 1024,
            "profileLevel": kVTProfileLevel_H264_Baseline_3_1,
            "maxKeyFrameIntervalDuration": 2,
        ]
        store.rtmpStream.audioSettings = [
            "muted": true,
            "sampleRate": sampleRate,
            "bitrate": 32 * 1024,
        ]
```
I tried streaming with both

```
rtmpStream.attachScreen(ScreenCaptureSession(viewToCapture: lfview!))
```
and
```
rtmpStream.attachScreen(ScreenCaptureSession(shared: UIApplication.shared))
```
but no success, it's always the same quality. Also, the second issue I have is with fps. When I stream screen with lfview(which is GLLFView) Its always 30fps, even when I set lower or higher fps in the settings. On the other hand, when I use UIApplication.shared it almost always streams in 15fps. In first 2 seconds, it jumps above 15fps but then drops and stays at 15fps, out of 30 runs I managed to get 30fps only one time so it seems like there is some cap that I'm not aware of. 

Just to be sure I tested it on repo demo app and I also got exactly the same behavior, please help me out because I'm running out of ideas how to solve it. Thank you.

**Comment by shogo4405** [comment]
>  it's always the same quality.

It's seems that output video resolution is 1920x1080.
"Quality" What do you mean?

> the second issue I have is with fps.

It's in the specifications. ScreenCaptureSession can't change fps.

**Comment by shogo4405** [comment]
>  it's always the same quality.

Try here.
```
rtmpStream.attachScreen(ScreenCaptureSession(shared: UIApplication.shared), useScreenSize: false)
```

**Comment by szczebel1995** [comment]
Update:
I tried useScreenSize: false and seems like its working nice 👍 . I'm gonna give another update when I'm gonna fix fps issue, also there is one thing that is still a problem witch are small black bars on top and bottom of the stream, I'm testing on iPhone SE.
