### ISSUE TITLE
HEVC RTMP ID 12

### ISSUE THREAD

**Issue by garybruckheimer** [shogo4405/HaishinKit.swift#343]
since iOS 11 and iPhone 8 / X there is an HEVC encoder included. There are some RTMP server that support that new HEVC codec and they set ID 12 in the FLV specification for RTMP HEVC. Is it possible that you can implement this codec in HaishinKit?

**Comment by shogo4405** [comment]
https://github.com/ksvc/FFmpeg/wiki

**Comment by shogo4405** [comment]
Yes I can. But low-priority.
If Wowza Server supports this, I will implement soon.

**Comment by animaonline** [comment]
Any plans on implementing this?

**Comment by albidev** [comment]
Any news on this implementation? Thanks for work! 👍

**Comment by khoadotan12** [comment]
Any update for this?
