### ISSUE TITLE
Implementing RTMPStreamQoSDelagate for dynamic bitrate

### ISSUE THREAD

**Issue by szczebel1995** [shogo4405/HaishinKit.swift#346]
Hi,

Based on this [issue](https://github.com/shogo4405/HaishinKit.swift/issues/126) I tried to implement RTMPStreamQoSDelagate in my project but I can't make it work. I can't get rid of this error:

![screen shot 2017-12-06 at 16 54 54](https://user-images.githubusercontent.com/26637546/33672544-c0bded8e-daaa-11e7-9f4c-9e0845ec7636.jpg)

I tried to put it in the separate file and also copypaste HaishinKit.swift/Sources/RTMP/RTMPStreamQoSDelagate.swift code to my code but the error is still there

I installed HaishinKit using Carthage and everything else is working, when I use Xcode's "go to definition" on RTMPStreamQoSDelagate, it sees the delegate in the library so idk what is wrong. I can't crack how to implement this dynamic bitrate due to my lack of experience. Can anyone tell me how to make it work and what is the cause of the error?

**Comment by shogo4405** [comment]
Because it is RTMPStreamQoSDel"a"gate. It's typo :(
Please try RTMPStreamQoSDel"e"gate.
