### ISSUE TITLE
How to use screencast

### ISSUE THREAD

**Issue by mirzaaghazadeh** [shogo4405/HaishinKit.swift#350]
Hi , I build the project and I can stream the camera and the application screen.
But how can I use screencast ?  when I 3d touch on screen record and choose the application and click on start broadcast nothing do

**Comment by shogo4405** [comment]
1. Please change this line. https://github.com/shogo4405/HaishinKit.swift/blob/master/Examples/iOS/Screencast/SampleHandler.swift#L19-L36
```
    override open func broadcastStarted(withSetupInfo setupInfo: [String: NSObject]?) {
        broadcaster.streamName = "YourStreamName"
        broadcaster.connect("rtmp://path.to/yourserver", arguments: nil)
    }
```
2. Then, start screencast.

**Comment by mirzaaghazadeh** [comment]
thanks😍😍 worked!
how can attach microphone on broadcast?

**Comment by shogo4405** [comment]
https://github.com/shogo4405/HaishinKit.swift/blob/master/Examples/iOS/Screencast/SampleHandler.swift#L50-L51
```
case .audioApp:
            broadcaster.appendSampleBuffer(sampleBuffer, withType: .audio)
```
To
```
case .audioMic:
            broadcaster.appendSampleBuffer(sampleBuffer, withType: .audio)
```

RTMP can send  one audio source.  If you need audioApp with audioMic. Please be synthesized.

**Comment by mirzaaghazadeh** [comment]
very thanks! <3
And the last questions!
How can I move this project file to other project? (which files?)

**Comment by shogo4405** [comment]
> How can I move this project file to other project? (which files?)

Sources/*
Platforms/iOS/*

I'm recommend to use CocoaPods or Carthage.

**Comment by mazharhameed25** [comment]
hi all,
can we add image and stream it?
