### ISSUE TITLE
M3U8 format

### ISSUE THREAD

**Issue by KelvnLing** [shogo4405/HaishinKit.swift#353]
The M3U8 file output from HaishinKit seems can't be processed by some player, is the format correct exactly ? Or just some player not process it well ?

Thanks.

**Comment by shogo4405** [comment]
I tested Safari(iOS), Chrome(macOS/Android). VLC.
It's not perfect. Please tell me your tested players.

**Comment by KelvnLing** [comment]
Hi, that is an internal Developed App player, it seems that App can't process the space in m3u8 file. I have fixed this in my code.
