### ISSUE TITLE
Error message "Dropping audio sample buffe"

### ISSUE THREAD

**Issue by KelvnLing** [shogo4405/HaishinKit.swift#354]
I am using on Mac OS X, sometimes there are error message output :"Dropping audio sample buffer 0x1028dddfor output <AVCaptureAudioDataOutput: 0x60> connection <AVCaptureConnection: 0x6080 [type:soun][enabled:1][active:1]>"

How to fix this?

Thanks.

**Comment by shogo4405** [comment]
I'm not sure. how to resolve it. But I known workaround tips.
1.  Stop any macOS's process.
2. Performance tuning an application.
