### ISSUE TITLE
Cannot live to youtube when microphone is off

### ISSUE THREAD

**Issue by vipnetvnn** [shogo4405/HaishinKit.swift#356]
Hi,
Everything is ok, but when i turnoff microphone audio in screencast mode library not work. 

Please help me :(

**Comment by shogo4405** [comment]
Please more information.

**Comment by piyuesh-dev** [comment]
I'm facing similar issue, basically **without microphone** screen sharing via broadcast upload extension don't work for youtube.
I've narrow down it to youtube stream status (https://developers.google.com/youtube/v3/live/docs/liveStreams#status.streamStatus) got **inactive** after few seconds without microphone, after that youtube broadcast status can't be upgraded to **"testing" or "live"** as mentioned at https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/transition.

Upload Handler code is similar to https://github.com/shogo4405/HaishinKit.swift/blob/master/Examples/iOS/Screencast/SampleHandler.swift.

Any hint ?
