### ISSUE TITLE
Send HLS stream to Server 

### ISSUE THREAD

**Issue by Micror** [shogo4405/HaishinKit.swift#357]
Hi,
I am trying use your HTTP sample to send the live video to my http server:

var httpStream:HTTPStream = HTTPStream()
httpStream.attachCamera(DeviceUtil.device(withPosition: .back))
httpStream.attachAudio(AVCaptureDevice.defaultDevice(withMediaType: AVMediaTypeAudio))
httpStream.publish("hello")

var lfView:LFView = LFView(frame: view.bounds)
lfView.attachStream(httpStream)

var httpService:HLSService = HLSService(domain: "", type: "_http._tcp", name: "lf", port: 8080)
httpService.startRunning()
httpService.addHTTPStream(httpStream)

// add ViewController#view
view.addSubview(lfView)

Could you please tell how to configure the HLSService? I always get error message such like this:

), NSUnderlyingError=0x1c044beb0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2018-14-01 21:30:25.036 [Warn] [com.haishinkit.HaishinKit] [TSWriter.swift:156] rotateFileHandle > Error Domain=NSCocoaErrorDomain Code=4 "“775997.ts” couldn’t be removed." UserInfo={NSFilePath=/private/var/mobile/Containers/Data/Application/E203532A-A3C8-48C0-9995-52B703EC1AEE/tmp/775997.ts, NSUserStringVariant=(
    Remove
), NSUnderlyingError=0x1c4452e40 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

Thanks,

Miror

**Comment by shogo4405** [comment]
> I am trying use your HTTP sample to send the live video to my http server:

Framework has no feature.

**Comment by Micror** [comment]
How to use HLS to do the broadcasting then? Is there a sample in your project? Thanks.

**Comment by shogo4405** [comment]
1. Run HLSService (Your iOS / macOS)
1. Open your another device Safari with URL

Sample is here. for macOS
- https://github.com/shogo4405/HaishinKit.swift/tree/master/Examples/macOS

**Comment by Micror** [comment]
Thanks

**Comment by ezanalemma** [comment]
@Micror I'm still trying to broadcast HLS through iOS. Were you able to achieve this? I'm getting very similar errors. Thank you!

**Comment by Goule** [comment]
Hello @ezanalemma, did you find a solution ? 

I have the same error I think : https://github.com/shogo4405/HaishinKit.swift/issues/782
