### ISSUE TITLE
Is there an example for playing on iOS

### ISSUE THREAD

**Issue by ezcamlive** [shogo4405/HaishinKit.swift#358]
Is there an example for playing on iOS?

**Comment by shogo4405** [comment]
No. Playback feature is experimental.
This is playback snipet.

lfView = GLLFView()
rtmpConnection = RTMPConnection()
rtmpStream = RTMPStream(conneciton: rtmpConnection)
rtmpStream.play("yourStreamName")
lfView.attachStream(rtmpStreamp)

**Comment by ezcamlive** [comment]
Thanks
