### ISSUE TITLE
Frequently getting 'Stream Inactive' via YouTube Live streaming api from broadcast extension

### ISSUE THREAD

**Issue by cprovatas** [shogo4405/HaishinKit.swift#359]
I copy example for broadcast extension but am getting 'Inactive Stream' frequently.  It does not happen always.  I have decent connection (30mb/down) If samples are sent before the stream is connected/published would that cause issues? Thank you

**Comment by shogo4405** [comment]
Youtube Live needs fps parameter in metadata.
So. This example has no fps parameter.
Please customize it. https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/RTMP/RTMPStream.swift#L572

**Comment by cprovatas** [comment]
I will update RTMPStream.swift in the framework.  Thank you @shogo4405 for building a great framework!

**Comment by cprovatas** [comment]
I compare RTMPStream.swift from your link and the one I'm using with the framework and they appear to be the same.  I have attach what my sample handler looks like.  Thanks again for your help


`//
//  SampleHandler.swift
//  Mirror-For-Roku-Broadcast-Extension
//
//  Created by Charlton Provatas on 8/1/18.
//  Copyright © 2018 CharltonProvatas. All rights reserved.
//

import ReplayKit
import HaishinKit
import VideoToolbox
import YTLiveStreaming

final class SampleHandler: RPBroadcastSampleHandler {
    
    private let broadcaster: RTMPBroadcaster = RTMPBroadcaster()
    let input: YTLiveStreaming = .init()
    override func broadcastStarted(withSetupInfo setupInfo: [String : NSObject]?) {
        super.broadcastStarted(withSetupInfo: setupInfo)
        
        input.createBroadcast("ok", description: nil, startTime: Date(), completion: startBroadcast(broadcast:))
    }
    
    func startBroadcast(broadcast: LiveBroadcastStreamModel?) {
        guard let broadcast = broadcast else {
            return NSLog("%@", "[Mirror-For-Roku] \(self.self): \(#function) line: \(#line).  Broadcast not found!")
        }
        input.startBroadcast(broadcast, delegate: self) { (streamName, streamURL, scheduledStartTime) in
            self.broadcaster.streamName = streamName
            self.broadcaster.connect(streamURL!)
            NSLog("%@", "[Mirror-For-Roku] \(self.self): \(#function) line: \(#line).  Trying to switch to testing.  Stream name: '\(streamName!)'")
            self.transitionToTesting(broadcast: broadcast)
        }
    }
    
    private func transitionToTesting(broadcast: LiveBroadcastStreamModel) {
        
        self.input.transitionBroadcast(broadcast, toStatus: "testing", completion: { success in
            if success {
                self.transitionToLive(broadcast: broadcast)
            } else {
                DispatchQueue.main.asyncAfter(deadline: .now() + 1, execute: {
                    self.transitionToTesting(broadcast: broadcast)
                })
            }
            NSLog("%@", "[Mirror-For-Roku] \(self.self): \(#function) line: \(#line).  Completion transition: \(success)")
        })
    }
    
    private func transitionToLive(broadcast: LiveBroadcastStreamModel) {
        NSLog("%@", "[Mirror-For-Roku] \(self.self): \(#function) line: \(#line).  Trying to switch to live")
        self.input.transitionBroadcast(broadcast, toStatus: "live", completion: { (success) in
            if success {
                //NSLog("%@", "[Mirror-For-Roku] \(self.self): \(#function) line: \(#line).  live result: \(success)")
            } else {
                DispatchQueue.main.asyncAfter(deadline: .now() + 1, execute: {
                    self.transitionToLive(broadcast: broadcast)
                })
            }
            NSLog("%@", "[Mirror-For-Roku] \(self.self): \(#function) line: \(#line).  live result: \(success)")
        })
    }
    
    override func broadcastPaused() {
        super.broadcastPaused()
        // User has requested to pause the broadcast. Samples will stop being delivered.
    }
    
    override func broadcastResumed() {
        super.broadcastResumed()
        // User has requested to resume the broadcast. Samples delivery will resume.
    }
    
    override func broadcastFinished() {
        super.broadcastFinished()
        // User has requested to finish the broadcast.
        broadcaster.close()
    }
    
    override open func processSampleBuffer(_ sampleBuffer: CMSampleBuffer, with sampleBufferType: RPSampleBufferType) {
        super.processSampleBuffer(sampleBuffer, with: sampleBufferType)
        switch sampleBufferType {
        case .video:
            if let description: CMVideoFormatDescription = CMSampleBufferGetFormatDescription(sampleBuffer) {
                let dimensions: CMVideoDimensions = CMVideoFormatDescriptionGetDimensions(description)
                broadcaster.stream.videoSettings = [
                    "width": dimensions.width,
                    "height": dimensions.height ,
                    "profileLevel": kVTProfileLevel_H264_Baseline_AutoLevel
                ]
            }
            broadcaster.appendSampleBuffer(sampleBuffer, withType: .video)
        case .audioApp:
            broadcaster.appendSampleBuffer(sampleBuffer, withType: .audio)
        case .audioMic:
            break
        }
    }
}

extension SampleHandler: YTLiveStreamingDelegate {
    func didTransitionToStatus(broadcast: LiveBroadcastStreamModel, broadcastStatus: String?, streamStatus: String?, healthStatus: String?) {
        
    }
    
    func didTransitionToLiveStatus() {
        debugPrint(#function)
    }
}
`

**Comment by cprovatas** [comment]
Hello @shogo4405 .  I try many framework and no work but yours work beautifully.  I had to alter RTMPStream bitrate was far too low.  Had to set to 500 * 1024.  Thanks for looking into issue

**Comment by piyuesh-dev** [comment]
Hello @cprovatas, I'm facing the same issue with Youtube stream via upload extension, Can you please tell me how did you solved it. Where we need to set bitrate. Thanks

**Comment by piyuesh-dev** [comment]
@cprovatas , I narrowed down the problem to that youtube streaming **don't** work **when microphone is off**, it works **fine when microphone is on** . Have you face same issue ? I opened a new one at https://github.com/shogo4405/HaishinKit.swift/issues/441 .
Thanks
