### ISSUE TITLE
How to set high quality video ?

### ISSUE THREAD

**Issue by KelvnLing** [shogo4405/HaishinKit.swift#360]
I found two place to set the quality:
   `static let defaultSessionPreset: String = AVCaptureSession.Preset.medium.rawValue`

```
    static let defaultWidth: Int32 = 480
    static let defaultHeight: Int32 = 272
    static let defaultBitrate: UInt32 = 160 * 1024
    static let defaultScalingMode: String = "Trim"
```

How can I set to high quality video (720p, 1080p)?

**Comment by KelvnLing** [comment]
If I change the width and hight to 1024 * 768, then it crash here:
`packetLength = UInt16(data.count + optionalPESHeader!.data.count)`
Fatal error: Not enough bits to represent a signed value

**Comment by shogo4405** [comment]
It's a framework side bug. Can't change high quality video.
see also. https://github.com/shogo4405/HaishinKit.swift/issues/293
