### ISSUE TITLE
Updating to HaishinKit 0.8.5 from 0.7.9 with Carthage. Compile error

### ISSUE THREAD

**Issue by about-prog** [shogo4405/HaishinKit.swift#362]
When I try to update HaishinKit from 0.7 to 0.8, I get compilation error. Here is the log:

> CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
> cd /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift
> export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
> export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
> export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name HaishinKit -O -whole-module-optimization -Xfrontend -disable-swift3-objc-inference -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk -target arm64-apple-ios8.0 -g -module-cache-path /Users/roman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/HaishinKit.swift/0.8.5/ModuleCache -Xfrontend -serialize-debugging-options -application-extension -embed-bitcode -swift-version 4 -I /Users/roman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/HaishinKit.swift/0.8.5/Build/Intermediates.noindex/ArchiveIntermediates/HaishinKit\ iOS/BuildProductsPath/Release-iphoneos -F /Users/roman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/HaishinKit.swift/0.8.5/Build/Intermediates.noindex/ArchiveIntermediates/HaishinKit\ iOS/BuildProductsPath/Release-iphoneos -F /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Carthage/Build/iOS -c -num-threads 8 /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/FLV/FLVTagType.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/RTMP/RTMPMessage.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Media/ScalingMode.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Platforms/iOS/ScreenCaptureSession.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/RTMP/RTMPTSocket.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/FLV/FLVReader.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Media/VideoIOComponent.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Media/SoundSpliter.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/RTMP/RTMPSharedObject.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Util/ClockedQueue.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/FLV/FLVSoundRate.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Media/SoundTransform.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/ISO/PacketizedElementaryStream.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/HTTP/HTTPRequest.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/RTMP/ASClass.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/ISO/TSReader.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Codec/H264Encoder.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Net/NetStream.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/FLV/FLVVideoCodec.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Platforms/iOS/LFView.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Util/MachUtil.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/RTMP/RTMPChunk.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Platforms/iOS/VideoIOComponent+Extension.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/ISO/H264+AVC.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/ISO/TSWriter.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Net/MIME.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Net/NetClient.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/ISO/ProgramSpecific.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Util/AnyUtil.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/RTMP/RTMPConnection.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/FLV/FLVAVCPacketType.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/RTMP/RTMPStream.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Extension/CMBlockBuffer+Extension.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Util/TimerDriver.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Media/IOComponent.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Media/AVMixerRecorder.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/RTMP/RTMPMuxer.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/FLV/FLVSoundType.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Platforms/iOS/DeviceUtil+Extenstion.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/ISO/NALUnit.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Extension/CVPixelBuffer+Extension.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/FLV/FLVSoundSize.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Extension/Data+Extension.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Util/CRC32.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Extension/CMAudioFormatDescription+Extension.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/RTMP/RTMPSocket.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/RTMP/AMF0Serializer.swift /Users/shogo/Dropbox/xcode/HaishinKit.swift/Sources/Codec/AACEncoder.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Extension/Mirror+Extension.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/RTMP/RTMPHandshake.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Extension/CMSampleBuffer+Extension.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Extension/CMVideoFormatDescription+Extension.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Platforms/iOS/NetStream+Extension.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Extension/URL+Extension.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Util/ByteArray.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/ISO/AudioSpecificConfig.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/FLV/FLVFrameType.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Media/VisualEffect.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Extension/CMSampleTimingInfo+Extension.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Core/Constant.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Core/Protocol.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Platforms/iOS/AudioUtil.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/HTTP/HTTPService.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Util/DeviceUtil.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Platforms/iOS/GLLFView.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/ISO/TransportStream.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Util/EventDispatcher.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Net/NetService.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Net/NetSocket.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/FLV/FLVAudioCodec.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/FLV/FLVAACPacket.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/HTTP/HTTPStream.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/ISO/MP4Sampler.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/ISO/MP4Reader.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/RTMP/RTMPStreamQoSDelagate.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/RTMP/AMF3Serializer.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Extension/CMFormatDescription+Extension.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Media/AVMixer.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Media/AudioStreamPlayback.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Util/Mutex.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Util/MD5.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Extension/ExpressibleByIntegerLiteral+Extension.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/HTTP/M3U.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Util/VideoGravityUtil.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Media/AudioIOComponent.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/HTTP/HTTPResponse.swift /Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift/Sources/Codec/H264Decoder.swift -output-file-map /Users/roman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/HaishinKit.swift/0.8.5/Build/Intermediates.noindex/ArchiveIntermediates/HaishinKit\ iOS/IntermediateBuildFilesPath/HaishinKit.build/Release-iphoneos/HaishinKit\ iOS.build/Objects-normal/arm64/HaishinKit\ iOS-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/roman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/HaishinKit.swift/0.8.5/Build/Intermediates.noindex/ArchiveIntermediates/HaishinKit\ iOS/IntermediateBuildFilesPath/HaishinKit.build/Release-iphoneos/HaishinKit\ iOS.build/Objects-normal/arm64/HaishinKit.swiftmodule -Xcc -I/Users/roman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/HaishinKit.swift/0.8.5/Build/Intermediates.noindex/ArchiveIntermediates/HaishinKit\ iOS/IntermediateBuildFilesPath/HaishinKit.build/Release-iphoneos/HaishinKit\ iOS.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/roman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/HaishinKit.swift/0.8.5/Build/Intermediates.noindex/ArchiveIntermediates/HaishinKit\ iOS/IntermediateBuildFilesPath/HaishinKit.build/Release-iphoneos/HaishinKit\ iOS.build/HaishinKit-generated-files.hmap -Xcc -I/Users/roman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/HaishinKit.swift/0.8.5/Build/Intermediates.noindex/ArchiveIntermediates/HaishinKit\ iOS/IntermediateBuildFilesPath/HaishinKit.build/Release-iphoneos/HaishinKit\ iOS.build/HaishinKit-own-target-headers.hmap -Xcc -I/Users/roman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/HaishinKit.swift/0.8.5/Build/Intermediates.noindex/ArchiveIntermediates/HaishinKit\ iOS/IntermediateBuildFilesPath/HaishinKit.build/Release-iphoneos/HaishinKit\ iOS.build/HaishinKit-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/roman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/HaishinKit.swift/0.8.5/Build/Intermediates.noindex/ArchiveIntermediates/HaishinKit\ iOS/IntermediateBuildFilesPath/HaishinKit.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/roman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/HaishinKit.swift/0.8.5/Build/Intermediates.noindex/ArchiveIntermediates/HaishinKit\ iOS/IntermediateBuildFilesPath/HaishinKit.build/Release-iphoneos/HaishinKit\ iOS.build/HaishinKit-project-headers.hmap -Xcc -I/Users/roman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/HaishinKit.swift/0.8.5/Build/Intermediates.noindex/ArchiveIntermediates/HaishinKit\ iOS/BuildProductsPath/Release-iphoneos/include -Xcc -I/Users/roman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/HaishinKit.swift/0.8.5/Build/Intermediates.noindex/ArchiveIntermediates/HaishinKit\ iOS/IntermediateBuildFilesPath/HaishinKit.build/Release-iphoneos/HaishinKit\ iOS.build/DerivedSources/arm64 -Xcc -I/Users/roman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/HaishinKit.swift/0.8.5/Build/Intermediates.noindex/ArchiveIntermediates/HaishinKit\ iOS/IntermediateBuildFilesPath/HaishinKit.build/Release-iphoneos/HaishinKit\ iOS.build/DerivedSources -emit-objc-header -emit-objc-header-path /Users/roman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/HaishinKit.swift/0.8.5/Build/Intermediates.noindex/ArchiveIntermediates/HaishinKit\ iOS/IntermediateBuildFilesPath/HaishinKit.build/Release-iphoneos/HaishinKit\ iOS.build/Objects-normal/arm64/HaishinKit-Swift.h -import-underlying-module -Xcc -ivfsoverlay -Xcc /Users/roman/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/HaishinKit.swift/0.8.5/Build/Intermediates.noindex/ArchiveIntermediates/HaishinKit\ iOS/IntermediateBuildFilesPath/HaishinKit.build/Release-iphoneos/HaishinKit\ iOS.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/roman/Desktop/test/Carthage/Checkouts/HaishinKit.swift
> <unknown>:0: error: no such file or directory: '/Users/shogo/Dropbox/xcode/HaishinKit.swift/Sources/Codec/AACEncoder.swift'
> Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
> 
> ** ARCHIVE FAILED **
> 
> The following build commands failed:
> CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
> CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
> (2 failures)

The problem is with this path:
/Users/shogo/Dropbox/xcode/HaishinKit.swift/Sources/Codec/AACEncoder.swift

**Comment by shogo4405** [comment]
Thank u.

**Comment by shogo4405** [comment]
I updated. Please try 0.8.6
