### ISSUE TITLE
Issue On Setting func broadcastStarted() for ScreenCast 

### ISSUE THREAD

**Issue by gelb2** [shogo4405/HaishinKit.swift#363]
hi i'm Stucked On ScreenCast Issue.
(https://github.com/shogo4405/HaishinKit.swift/issues/361)
i Tried To Set func broadcastStarted() as You Mentioned, But i Can't Find Out Any Improvement or Difference. Even the Error Alert is Same..."Live Broadcast to MyDemoApp has stopped due to : (null)"
Also, I Read This Post too, and I Don't Understand Why My Demo App Doesn't work. Because i already Modified broadcastStarted() same as this Post. 
(https://github.com/shogo4405/HaishinKit.swift/issues/350)

so i Think This Issue is related to Another Thing. Such as Build Option, App Group, App Extension...
(Without Setting App Group, My Demo App Doesn't Show Up On Control Center's BrocastMenu. That's why i Set App Group)
Could You Tell me about More Thing? Maybe I Missed Some Option That Must Be Implemented

**Comment by shogo4405** [comment]
I think it's not HaishinKit's problem.
Please consider to use stackoverflow.
