### ISSUE TITLE
MPEG DASH Support

### ISSUE THREAD

**Issue by subdiox** [shogo4405/HaishinKit.swift#365]
Could you support MPEG DASH? HLS is Apple standard, but MPEG DASH is world standard.

**Comment by shogo4405** [comment]
No. Nothing special so far.

**Comment by devxoul** [comment]
I recently realized that major live streaming services like Facebook and YouTube use MPEG-DASH for their live streaming. It would be great if HaishinKit supports the new standard :tada:
