### ISSUE TITLE
didFinishWriting not called anymore?

### ISSUE THREAD

**Issue by chrisscholly** [shogo4405/HaishinKit.swift#366]
In `v0.8.5+`, it seems like `didFinishWriting(_ recorder: AVMixerRecorder)` of `DefaultAVMixerRecorderDelegate` is no longer called when `RTMPConnection` is closed. While it is in `v0.8.4`.

Anything about that?

**Comment by shogo4405** [comment]
Definitely. AVMixerRecorder#delegate always nil.
https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/Media/AVMixerRecorder.swift#L49

**Comment by samueleastdev** [comment]
Hi @shogo4405 

Could you provide some more information on this I am trying to set up local recording?

I am working with your example code here: https://github.com/shogo4405/HaishinKit.swift/blob/master/Examples/iOS/LiveViewController.swift

I have the ExampleRecorderDelegate class set at the top.
~~~
class ExampleRecorderDelegate: DefaultAVMixerRecorderDelegate {
    override func didFinishWriting(_ recorder: AVMixerRecorder) {
        guard let writer: AVAssetWriter = recorder.writer else { return }
        PHPhotoLibrary.shared().performChanges({() -> Void in
            PHAssetChangeRequest.creationRequestForAssetFromVideo(atFileURL: writer.outputURL)
        }, completionHandler: { (_, error) -> Void in
            do {
                try FileManager.default.removeItem(at: writer.outputURL)
            } catch let error {
                print(error)
            }
        })
    }
}
~~~

I am setting localRecord on the publish call.
~~~
rtmpStream.publish("streamName", type: .localRecord)
~~~

When I stop the stream nothing happens I would expect a popup for access to the photo library and save there.

After searching everywhere I have ended up at this post which seems to be the same issue as nothing get called.

Could you give some more details on a fix for this, please.

Thanks

**Comment by wolfcon** [comment]
Because property `delegate` is declared with weak attribute.
```swift
open weak var delegate: AVMixerRecorderDelegate?
```

PR is one the road

**Comment by yuya-h-29** [comment]
Just wondering but, when the app goes to the background, the `didFinishWriting` method should still be triggered?
I checked this thread and configured the `didFinishWriting` method; it works fine when the app remains in foreground, but the `didFinishWriting` never gets called when the app goes to the background and came back to the foreground. 
So, I wanted to make sure if the method is not triggered once it goes into the background and came back to the foreground.
