### ISSUE TITLE
AACEncoder.swift:80] inSourceFormat > nil

### ISSUE THREAD

**Issue by santoshpro95** [shogo4405/HaishinKit.swift#367]
Its not broadcasting It shows This log error:
[com.haishinkit.HaishinKit] [NetSocket.swift:91] close(isDisconnected:) > isDisconnected: true
2018-04-02 19:50:31.639 [Warn] [com.haishinkit.HaishinKit] [RTMPConnection.swift:359] on(status:) >

**Comment by shogo4405** [comment]
It seems that wrong RTMP URL.

**Comment by shogo4405** [comment]
> isDisconnected: true
