### ISSUE TITLE
Unable to find a specification for `HaishinKit (~> 0.8.0)`

### ISSUE THREAD

**Issue by swarna-a-26** [shogo4405/HaishinKit.swift#370]
Is there any problem with the CocoaPods? When I run Pod install, I get the following error.
 Unable to find a specification for `HaishinKit (~> 0.8.0)`
Please let me know how to overcome this issue.

**Comment by swarna-a-26** [comment]
I am not sure whether the cocopod Haishinkit 0.8.0 is not available.
I used the below configuration and it works. 

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def import_pods
    pod 'HaishinKit', :git => 'https://github.com/shogo4405/HaishinKit.swift', :tag => '0.8.6'
    pod 'Logboard', :git => 'https://github.com/shogo4405/Logboard', :tag => '1.1.2'    
end

target 'My target'  do
    platform :ios, '8.0'
    import_pods
end

Also, one more question, How to get error status after publishing the stream. Any stream errors or encoding errors?Please let me know.That would be very helpful.

**Comment by shogo4405** [comment]
@swarna-a-26 
I'm not sure. Please solve a problem your self. In my case works ok.

Podfile
```
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def import_pods
    pod 'HaishinKit', '~> 0.8.0'
end

target 'Test'  do
    platform :ios, '8.0'
    import_pods
end
```

```
kisaragi:Test shogo$ pod update
Update all pods
Updating local specs repositories
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 3253 and retry the command.

CocoaPods 1.4.0 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.4.0

Analyzing dependencies
Downloading dependencies
Installing HaishinKit (0.8.5)
Installing Logboard (1.1.5)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `Test.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.
```

**Comment by shogo4405** [comment]
>  Any stream errors or encoding errors?
### Stream errors
```
rtmpStream.addEventListener(Event.RTMP_STATUS, selector: #selector(self.rtmpStatusHandler(_:)), observer: self)

    @objc func rtmpStatusHandler(_ notification: Notification) {
        let e: Event = Event.from(notification)
        if let data: ASObject = e.data as? ASObject, let code: String = data["code"] as? String {
             // you can handle errors.
        }
    }
```

### encoding errors
no way.
