### ISSUE TITLE
Support SRT

### ISSUE THREAD

**Issue by shogo4405** [shogo4405/HaishinKit.swift#374]
- https://www.wowza.com/products/capabilities/SRT-secure-reliable-transport

**Comment by garybruckheimer** [comment]
SRT Support would be Amazing!

**Comment by ukudala** [comment]
Receiving SRT as well 💯

**Comment by shogo4405** [comment]
Open public beta SRTHaishinKit. https://github.com/shogo4405/SRTHaishinKit.swift
