### ISSUE TITLE
Default broadcast IOS(Screencast) crash. 

### ISSUE THREAD

**Issue by jimijings11** [shogo4405/HaishinKit.swift#375]
Screencast project crash with rtmp default settings (I provided _rtmp://a.rtmp.youtube.com/live2_ ) and my streamName.
Extension crash  in `AACEncoder` when get into `AudioConverterFillComplexBuffer`.
When  comment this line `broadcaster.appendSampleBuffer(sampleBuffer, withType: .audio)` in 
file: `SampleHandler` broadcasting works. It works also with broadcasting mic:
```
  case .audioMic:
      broadcaster.appendSampleBuffer(sampleBuffer, withType: .audio)

```
I tested it on iPhone 5s and iPad  mini 2.
Tip: When I try to debug `AACEncoder` I realized that in `encodeSampleBuffer` after  this line
`inSourceFormat = format.streamBasicDescription?.pointee`:

- when audio is enabled `inSourceFormat .mFormatFlags = 14` 

- when mic `inSourceFormat.mFormatFlags = 12`

  diffrence is (`kAudioFormatFlagIsBigEndian`) .
<img width="2320" alt="zrzut ekranu 2018-02-19 o 16 52 13" src="https://user-images.githubusercontent.com/36637017/36386871-8b369cd8-1597-11e8-943f-7d9d81cf3fed.png">

**Comment by shogo4405** [comment]
Are you talking about My Example project? https://github.com/shogo4405/HaishinKit.swift/blob/master/Examples/iOS/Screencast/SampleHandler.swift#L38?

Or your project?

**Comment by shogo4405** [comment]
If your code:

    override open func processSampleBuffer(_ sampleBuffer: CMSampleBuffer, with sampleBufferType: RPSampleBufferType) {
        switch sampleBufferType {
        case .video:
            // ...
        case .audioApp:
            broadcaster.appendSampleBuffer(sampleBuffer, withType: .audio)
        case .audioMic:
            broadcaster.appendSampleBuffer(sampleBuffer, withType: .audio)
        }
    }

It's not work fine! You can get crash :D

**Comment by jimijings11** [comment]
About Your Example iOS project(name HaishinKit).

W dniu poniedziałek, 19 lutego 2018 shogo4405 <notifications@github.com>
napisał(a):

**Comment by jimijings11** [comment]
I tested your iOS project in two ways:
- ```override open func processSampleBuffer(_ sampleBuffer: CMSampleBuffer, with sampleBufferType: RPSampleBufferType) {
    switch sampleBufferType {
    case .video:
        broadcaster.appendSampleBuffer(sampleBuffer, withType: .video)
    case .audioApp:
        broadcaster.appendSampleBuffer(sampleBuffer, withType: .audio)
    case .audioMic:
        break
    }
}``` -> it not works 
- second:
```override open func processSampleBuffer(_ sampleBuffer: CMSampleBuffer, with sampleBufferType: RPSampleBufferType) {
    switch sampleBufferType {
    case .video:
        broadcaster.appendSampleBuffer(sampleBuffer, withType: .video)
    case .audioApp:
        break
    case .audioMic:
       boadcaster.appendSampleBuffer(sampleBuffer, withType: .audio)
    } 
}```-> it works.

**Comment by shogo4405** [comment]
Thank u. I understand.

.audioApp: CMSampleBuffer can get CMSampleBufferGetSampleNum() = 22000〜.
.audioMic: CMSampleBuffer can get CMSampleBufferGetSampleNum() = 1024.

I designed. AACEncoder requires 1024/sampleNum.

**Comment by shogo4405** [comment]
My example project is wrong. I fixed it.

**Comment by jimijings11** [comment]
Some error to correct in your commit(`SampleHandler` file).

**Comment by shogo4405** [comment]
@jimijings11 
Thank u. Feedback. I will try to fix weekend.

**Comment by hominhtuong** [comment]
@shogo4405 
With your example, we cannot livestream with both audioApp and audioMic sound, but only use 1. How can I use both?
