### ISSUE TITLE
Adaptive bitrate only decreases bitrate

### ISSUE THREAD

**Issue by itsProf** [shogo4405/HaishinKit.swift#378]
When conforming to the `RTMPStreamQoSDelegate` protocol I noticed that the bitrate does get decreased when the delegate reports insufficient bandwidth, but it never gets increased back when the connection is good again. I've ran some test using the network conditioner to replicate the issue and the bitrate is only going down, never going up.

**Comment by shogo4405** [comment]
I'm not sure. How can I detect "when the connection is good again".
Do you have any idea?

My increased back approch is here:
https://github.com/shogo4405/HaishinKit.swift/issues/285

**Comment by itsProf** [comment]
@shogo4405 what would make the timer to activate?
