### ISSUE TITLE
UIWebViewの合成について

### ISSUE THREAD

**Issue by ohtasoji** [shogo4405/HaishinKit.swift#379]
`UIWebView` (またはWKWebView)を` rtmpStream `に合成したいのですが、どのように追加できますでしょうか？ 試す際に` VisualEffect ` を使ってみたのですがうまく行きませんでした。
またViewだけでなく` UIWebView `  (またはWKWebView)上の音声も`rtmpStream`内に合成したいのですが、どうしたら追加できますでしょうか？
実装方法を教えていただければと思います🙏

**Comment by shogo4405** [comment]
1. UIWebViewの映像について
   - ScreenCaptureSessionというViewをキャプチャーしてRTMP送信するクラスを追加しています https://github.com/shogo4405/HaishinKit.swift/blob/master/Platforms/iOS/ScreenCaptureSession.swift
1. UIWebViewの音声について
   - iPhoneのスピーカーから出る音をマイクで拾って流すという方法があります。

**Comment by ohtasoji** [comment]
カメラ映像とWebViewを合成したかったので、ViewにカメラとUIWebViewを配置してScreenCaptureSessionでViewをキャプチャーしてRTMP送信すればできそうです。
参考になりました！ありがとうございます！
