### ISSUE TITLE
Audiobus Support

### ISSUE THREAD

**Issue by productionvalues** [shogo4405/HaishinKit.swift#39]
Audiobus interfaces [your new] apps with one another and system audio via iOS APIs and their very cool framework, allowing for multiple routes from the same source (eg, the same system mic input stream can be piped/redirected to any number of Audiobus effects, apps, and System Audio 
(Audiobus is akin to iOS Inter-app Audio Input/Output!

**Comment by shogo4405** [comment]
Good idea! I will try.

**Comment by shogo4405** [comment]
Nice to have. I think no need framework level.
