### ISSUE TITLE
It looks strange on GPUHaishinKit 

### ISSUE THREAD

**Issue by nestor82** [shogo4405/HaishinKit.swift#394]
-Sending View Screen
![img_7df9611a07a8-1](https://user-images.githubusercontent.com/13027065/37899169-b7c8201a-3125-11e8-8848-1d76b65f30f2.jpeg)

-Receive View Screen
![img_0010](https://user-images.githubusercontent.com/13027065/37899178-c1091314-3125-11e8-9751-aa668b44a56f.jpg)

I set the videoSetting as follows..  
```
rtmpStream.videoSettings = ["width" : 960, "height" : 540, "bitrate" : 3000000]
rtmpStream.captureSettings = ["sessionPreset": AVCaptureSessionPresetiFrame960x540] 
camera?.addTarget(rtmpStream!.rawDataOutput)
camera?.outputImageOrientation = .portrait
camera?.startCapture()
```
the result is like that photo.

but I changed the setting  ["width" : 1280, "height": 720 ]
then it comes out normally.
even if I use other AVcaptureSessionPreset type, Should i use ["width" : 1280, "height": 720 ] this setting?

**Comment by shogo4405** [comment]
I give up supporting GPUHaishinKit. Thank u.
