### ISSUE TITLE
Xcode 9.3 won't compile

### ISSUE THREAD

**Issue by psegalen** [shogo4405/HaishinKit.swift#397]
Hi!
Thanks for this SDK, it's great!
Xcode 9.3 complains about not being able to import modules compiled with Swift 4.0.3 in Swift 4.1 classes, do you think you could send a version compiled with Swift 4.1?

**Comment by johnharutyunyan** [comment]
<img width="998" alt="screen shot 2018-03-31 at 8 38 02 pm" src="https://user-images.githubusercontent.com/26871856/38165394-9eadd88e-3523-11e8-9bbe-a7e50b344755.png">

**Comment by ukudala** [comment]
Agreed, same issue after Xcode update

**Comment by shogo4405** [comment]
https://github.com/shogo4405/HaishinKit.swift/pull/396

**Comment by shogo4405** [comment]
Released 0.8.8.
