### ISSUE TITLE
UI hangs videoSettings

### ISSUE THREAD

**Issue by shogo4405** [shogo4405/HaishinKit.swift#404]
From https://github.com/shogo4405/HaishinKit.swift/pull/400

I have modified the example iOS app to reproduce this issue. The changes are at ronhuang/HaishinKit.swift@fdc563b30e21ffa4790e0fbc5ad6f7ad476b510b.

Steps to reproduce:
1. Build example iOS app with the above modifications
2. Launch app (in simulator will be sufficient)
3. Switch to Second tab
4. Update any text field to change ``Preference.defaultInstance.bitrate``
5. Switch back and forth between First and Second tabs until UI hangs
6. Once UI hangs, click "Pause program execution" in Xcode
7. Exam the call stack and see thread is stuck at ``__ulock_wait`` (as illustrated in the following screenshot)

![netstream-videosettings-deadlock](https://user-images.githubusercontent.com/85052/38175643-60a037cc-3612-11e8-8457-ebf13f33cc4c.jpeg)

**Comment by milesegan** [comment]
I'm not sure if it's related or even sure if it's a HaishinKit issue but we're seeing a similar sporadic UI lockup in our app. The video preview will continue to play but the rest of the UI is unresponsive. This only started happening after we replaced the commercial RTMP library we were using with HaishinKit.

**Comment by venczel** [comment]
Experiencing **same issue** (HaishinKit 0.8.8);  log:

```log
2018-07-04 10:15:14.245 [Info] [com.haishinkit.HaishinKit] [VideoIOComponent.swift:35] fps > (fps: 30.0, duration: __C.CMTime(value: 100, timescale: 3000, flags: __C.CMTimeFlags(rawValue: 1), epoch: 0))
```
... **UI unresponsive** for 4-8 seconds ...
```log
2018-04-07 10:15:23:258 Live[2835:835798] RTMPManager: video settings: Video settings: width = 134, height = 240, bitrate = 716800
```

**Comment by Yatko** [comment]
Any ideas on how to fix this one?

**Comment by milesegan** [comment]
@Yatko It turned out our issue was unrelated to HaishinKit. So far we haven't had any issues like the one people describe in this thread.

**Comment by psegalen** [comment]
It may be related to #429 since changing videoSettings can cause deadlocks, my app just crashes when it happens but maybe sometimes the system can recover from the deadlock after a little while, it would explain this issue.
It's likely that #432 would solve this problem too.
