### ISSUE TITLE
Auto rotate or auto sync orientation is not working

### ISSUE THREAD

**Issue by rkoshti** [shogo4405/HaishinKit.swift#406]
Hi

In my case if i have started streaming in the landscape mode it will always display landscape streams and if i have started streaming in portrait mode it will always be in the portrait mode even though i will change the device orientation it doesn't effect on video it will always be in same orientation. 

**Its not syncing the device orientation**

![1](https://user-images.githubusercontent.com/19707208/38351681-3a81cee8-38ce-11e8-9f26-c53e8b994b72.png)

I have tried rtmpStream.syncOrientation = true and

```
NotificationCenter.default.addObserver(self, selector: #selector(rotated), name: NSNotification.Name.UIDeviceOrientationDidChange, object: nil)

func rotated() {
    switch UIDevice.current.orientation {
    case .landscapeLeft, .landscapeRight:
       rtmpStream.videoSettings = [
           "width": 640, // video output width
           "height": 360, // video output height
       ]
    default:
       rtmpStream.videoSettings = [
           "width": 360, // video output width
           "height": 640, // video output height
       ]
    }
}

```
But none of this works for me .

I want to know that in this framework i am missing any setting or anything ???

@shogo4405

**Comment by rkoshti** [comment]
@shogo4405

**Comment by adamasantares** [comment]
> Hi
> 
> In my case if i have started streaming in the landscape mode it will always display landscape streams and if i have started streaming in portrait mode it will always be in the portrait mode even though i will change the device orientation it doesn't effect on video it will always be in same orientation.
> 
> **Its not syncing the device orientation**
> 
> ![1](https://user-images.githubusercontent.com/19707208/38351681-3a81cee8-38ce-11e8-9f26-c53e8b994b72.png)
> 
> I have tried rtmpStream.syncOrientation = true and
> 
> ```
> NotificationCenter.default.addObserver(self, selector: #selector(rotated), name: NSNotification.Name.UIDeviceOrientationDidChange, object: nil)
> 
> func rotated() {
>     switch UIDevice.current.orientation {
>     case .landscapeLeft, .landscapeRight:
>        rtmpStream.videoSettings = [
>            "width": 640, // video output width
>            "height": 360, // video output height
>        ]
>     default:
>        rtmpStream.videoSettings = [
>            "width": 360, // video output width
>            "height": 640, // video output height
>        ]
>     }
> }
> ```
> 
> But none of this works for me .
> 
> I want to know that in this framework i am missing any setting or anything ???
> 
> @shogo4405

2019 Doesn't work for me too, we are looking for solution 4th day, but no success :(
