### ISSUE TITLE
How to use m4a as BGM

### ISSUE THREAD

**Issue by pompopo** [shogo4405/HaishinKit.swift#408]
I modified macOS sample code as below to use m4a file to use as BGM.
But connection closed immediately even if the file has 90 seconds music.

```
    @objc func rtmpStatusHandler(_ notification: Notification) {
        let e: Event = Event.from(notification)
        guard
            let data: ASObject = e.data as? ASObject,
            let code: String = data["code"] as? String else {
            return
        }
        switch code {
        case RTMPConnection.Code.connectSuccess.rawValue:
            let bundle: Bundle = Bundle(for: type(of: self))
            let url: URL = URL(fileURLWithPath: bundle.path(forResource: "myfile", ofType: "m4a")!)
            rtmpStream!.appendFile(url)
            rtmpStream!.publish(Preference.defaultInstance.streamName)
        case RTMPConnection.Code.connectClosed.rawValue:
            print("closed")
        default:
            break
        }
    }
```
[original implementation](https://github.com/shogo4405/HaishinKit.swift/blob/master/Examples/macOS/MainViewController.swift#L152)

Do I need more settings?

I also tried mp4 video file instead of m4a, then the connection didn't close but sound of mp4 seemed to be just ignored. Only my face and voice were published.

**Comment by shogo4405** [comment]
こんにちわ。日本語でも大丈夫でしょうか？

前提条件としてappendFileとattachCamera/attachAudioは同時に利用できるように設計してません。
もし同時に利用している場合であれば、サーバーサイドからコネクションが切られます。

BGMとして... とあるので。
マイクの音声とカメラのキャプチャーと合成希望であれば
1. BGMのスピーカーから出力してマイク経由で集音する
1. m4aの音声の圧縮を展開して、マイクの音声データと合成する
という方法が考えられます

**Comment by pompopo** [comment]
@shogo4405 ありがとうございます。2の方向で頑張ってみようと思います。
調べてみた感じだと、AVAudioEngineでマイク音声とm4a音声を合成してAVAudioPCMBufferを得る→CASampleBufferに変換して、appendSampleBuffer すればいけそうな気配がしました。
https://github.com/shogo4405/HaishinKit.swift/blob/dfeae6e05f3dbdd4cc51ff7786044f0d6f8871ee/Tests/Codec/SinWaveUtil.swift#L55

**Comment by pompopo** [comment]
`AVAudioEngineでマイク音声とm4a音声を合成してAVAudioPCMBufferを得る→CASampleBufferに変換して、appendSampleBuffer ` でいけました。ありがとうございます

**Comment by cuonghx2709** [comment]
I've been trying to set the mp3 background music with the recording mic to live streaming. If anyone wants to support please contact me cuonghx2709@gmail.com

**Comment by maheshmax** [comment]
@cuonghx2709
Can you share any sample code ?
