### ISSUE TITLE
chnage screencast link and stream key from app

### ISSUE THREAD

**Issue by Amirhasanioox** [shogo4405/HaishinKit.swift#410]
Hi ,

How Can I set link and stream Key to screencast from app ?
for example enter stream name in textfield in app and then when start screen cast that streamkey start .. ?

**Comment by shogo4405** [comment]
You can use the AppExtension Group feature.
Please see Apple's document. https://developer.apple.com/documentation/foundation/nsuserdefaults/1409957-initwithsuitename

**Comment by shogo4405** [comment]
> when start screen cast that streamkey start .. ?

Talking about ReplayKit at Control Center?
Unfortunately, no way.

**Comment by Amirhasanioox** [comment]
my stream link and key will change in app and I want to change them in sample handler but the samplehandler just uses for first time that application opens then the stream key won't change.

**Comment by Amirhasanioox** [comment]
please answer I just want to change the stream key and link when I clicked e btn and I give the key and link to a variable that i can use in samplehandler please help me.

**Comment by shogo4405** [comment]
1. Your host application and ReplayKit process are separate processes.
   - Therefore You can't use a variable.
1. You can use UserDefaults(suiteName: "NameOfAppGroup") insted of a variable.

**Comment by Amirhasanioox** [comment]
I use UserDefault but it does not works and always it is empty.

**Comment by shogo4405** [comment]
Please see Sharing Data with Your Containing App section
https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html
