### ISSUE TITLE
print in screencast

### ISSUE THREAD

**Issue by mirzaaghazadeh** [shogo4405/HaishinKit.swift#411]
hi , 
why print dont work in screen cast
when I print something it dont print in console

**Comment by shogo4405** [comment]
I'm having some trouble 😵
Please ask the Apple Developer Forum.

**Comment by shogo4405** [comment]
I'm using these libraries instead of "print in console"

https://github.com/shogo4405/Logboard#socketappender
https://github.com/shogo4405/LogboardConsole
