### ISSUE TITLE
Swift version error

### ISSUE THREAD

**Issue by Amirhasanioox** [shogo4405/HaishinKit.swift#415]
I have updated my xcode to 9.3. Now when I want to run the application I'm getting "Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1" error.

**Comment by pzs7602** [comment]
A module referenced in your project(probably a framework) was compiled by a Xcode earlier version, so recompile this module with Xcode 9.3 and override the older module in your project. If the module's source code is owned by other person, ask him do that or just wait.
