### ISSUE TITLE
Not working properly on XCode 9.3 when installed via cocoapods

### ISSUE THREAD

**Issue by rahulgolwalkar** [shogo4405/HaishinKit.swift#416]
Was working fine with XCode 9.2 when installed 0.8.8 via cocoapods 
Updated to 9.3
Loads of warnings and most of them weren't simple name changes. Many required change in parameters.

**Comment by shogo4405** [comment]
Was it resolved? Please more information.
Take a screenshoot in XCode and attach this issue.

**Comment by shogo4405** [comment]
> Loads of warnings and most of them weren't simple name changes.

I think that Swift-version detection problem.
