### ISSUE TITLE
How to save video in local storage

### ISSUE THREAD

**Issue by adavan2107** [shogo4405/HaishinKit.swift#421]
Thanks in advance for awesome library Hi i am streaming video to facebook live is working nice at the same time i need to save the video in local device storage how to do that.

Thanks,
A.Adavan

**Comment by samueleastdev** [comment]
Hi @adavan2107 

I asked the same question recently this should help.

https://github.com/shogo4405/HaishinKit.swift/issues/412

Sam

**Comment by adavan2107** [comment]
Hi @samueleastdev 

Thanks for your help you saved my day.
