### ISSUE TITLE
Swift 4.2 Support

### ISSUE THREAD

**Issue by williamsthing** [shogo4405/HaishinKit.swift#425]
Hi there,

I'm trying to use HaishinKit.swift with the new Swift 4.2 and iOS 12, but there are a lot of errors.

Do you know when Swift 4.2 will be supported? If anyone has a way to run Swift 4.1 in Xcode 10, please let me know.

Thanks!

**Comment by mmaschenko** [comment]
I am currently trying to launch it under another xCode version 9.3 with no success. Maybe you will be able to do this. You can download it on https://developer.apple.com/download/more/ with premium account
