### ISSUE TITLE
UI View Streaming (Requirment)

### ISSUE THREAD

**Issue by HimanshuChowdharyIndia** [shogo4405/HaishinKit.swift#430]
Hi, 

I am very happy to use library. This is not actually issue. Its my requirement. 

Use Case: I am getting preview on UI view using video previewer. then  streaming ui view using rtmp (HaishinKit library).

Issue: Frame resolution depends on ui view resolution 

Requirement:  Resolution should be maximum as irrespective of ui view size (height and width)

I need your support.

Thanks and Best Regards,
Himanshu Chowdhary

**Comment by HimanshuChowdharyIndia** [comment]
Hi shogo4405,

I request you to help me out of above mentioned issue. I am willing to pay for particular feature. 

My email id: hchowdhary@flyanra.com

Thanks and Best Regards,
 Himanshu Chowdhary

**Comment by shogo4405** [comment]
@HimanshuChowdharyIndia 
I'm busy now. I can't help you. Thank u.
