### ISSUE TITLE
What is LFView?

### ISSUE THREAD

**Issue by DomenicoCammarota** [shogo4405/HaishinKit.swift#431]
From this code example in the docs:

`let lfView: LFView = LFView(frame: view.bounds)
lfView.videoGravity = AVLayerVideoGravity.resizeAspectFill
lfView.attachStream(rtmpStream)`

What is LFView? Where is that class located in the SDK? I'm unable to locate it.

**Comment by shogo4405** [comment]
I renamed LFView -> HKView 0.9.0~. Please use HKView,

**Comment by shogo4405** [comment]
Update README.md. Thank u.
