### ISSUE TITLE
Is possible switch the camera for a local video?

### ISSUE THREAD

**Issue by sevenb** [shogo4405/HaishinKit.swift#433]
I'd like to switch the camera for a local video on the iOS. Is that possible?

**Comment by shogo4405** [comment]
@see https://github.com/shogo4405/HaishinKit.swift/issues/326

**Comment by abubaqr70** [comment]
@sevenb  i need to append the file from gallery but it's not working do you know how to achieve it...!

**Comment by sevenb** [comment]
Hi, I tried to make it a couple of years ago but didn't work. Since this, I have no tried to make it anymore. I don't know with the updates it is possible but I'd like to try to make it works.
