### ISSUE TITLE
Where should I put streaming Key

### ISSUE THREAD

**Issue by logictr** [shogo4405/HaishinKit.swift#438]
I am working on  a project in which I have to show live streaming of videos .I want to add streaming key with string url but I am not getting any idea where to put this. Thanks in advance

**Comment by psegalen** [comment]
URL goes there: https://github.com/shogo4405/HaishinKit.swift/blob/master/Examples/iOS/LiveViewController.swift#L132
Stream key goes there: https://github.com/shogo4405/HaishinKit.swift/blob/master/Examples/iOS/LiveViewController.swift#L143
