### ISSUE TITLE
Open question: how to detect non-wanted disconnections?

### ISSUE THREAD

**Issue by psegalen** [shogo4405/HaishinKit.swift#440]
My app broadcast sessions sometimes get disconnected server-side (when stream quality is too bad because of a poor network) and when it happens the app don't get any event (but the console shows `close(isDisconnected:) > isDisconnected: false`).

According to #376 it seems to be normal that no event is raised when such a thing happens but how could I detect this situation to inform the user his connection broke?

@shogo4405 what would be the best practice according to you?
- Should I submit a PR with a new event like `RTMPConnection.Code.connectLost` in a else here: https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/RTMP/RTMPTSocket.swift#L116 ?
- Or should I add an observer on `connected` property of the `RTMPConnection` in my app?
- Or should I submit a PR to open (read-only) `readyState` property of `RTMPStream` and add an observer on it to detect `closed` value in my app?
I think having the `RTMPStream.readyState` available read-only to the apps would be great!

**Comment by shogo4405** [comment]
> (but the console shows close(isDisconnected:) > isDisconnected: false).

Did you call "RTMPConnection.close" inside your app?
If you didn't call "close". I think should be close(isDisconnected:) > isDisconnected: true).

Currently, I don't think change to public read-only RTMPStream.readyState.

**Comment by psegalen** [comment]
I didn't call `close()` but isDisonnected was false when I got disconnected.

**Comment by shogo4405** [comment]
https://github.com/shogo4405/HaishinKit.swift/commit/2a8f80ea999c37bc95819c297a5d0612816b4362 I guess fixed it.

**Comment by psegalen** [comment]
Ok thanks, I close it for now and will reopen if 0.9.2 doesn't fix this issue.
