### ISSUE TITLE
screen cast don't work when microphone is off

### ISSUE THREAD

**Issue by piyuesh-dev** [shogo4405/HaishinKit.swift#441]
I'm facing issue similar to https://github.com/shogo4405/HaishinKit.swift/issues/356,  basically without microphone screen sharing via broadcast upload extension don't work for youtube.
I've narrow down it to youtube stream status (https://developers.google.com/youtube/v3/live/docs/liveStreams#status.streamStatus) got inactive after few seconds without microphone, after that youtube broadcast status can't be upgraded to "testing" or "live" as mentioned at https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/transition.

Upload Handler code is similar to https://github.com/shogo4405/HaishinKit.swift/blob/master/Examples/iOS/Screencast/SampleHandler.swift.

It is also not working for twitch.tv.

Any hint ?

**Comment by shogo4405** [comment]
How about using OBS microphone is off?

**Comment by piyuesh-dev** [comment]
OBS on youtube without microphone works fine.
ios screencast example at https://github.com/shogo4405/HaishinKit.swift example section didn't worked at my end w/o microphone. Does it work for you ?

It works in following case:
Start streaming with microphone **ON**, after youtube stream gets live, I can switch microphone to **OFF**. 

 @shogo4405 , **many thanks** for your library, it works fine for all other cases in my upload extension.

**Comment by piyuesh-dev** [comment]
I've tested again, https://github.com/shogo4405/HaishinKit.swift/tree/master/Examples/iOS don't work **without** microphone, and it works just fine with **microphone ON** with youtube default <**stream now**> stream.

I've captured traffic via wireshark, but not able to find any reason behind it. You may like to view it, shared at https://www.dropbox.com/sh/e1m7xj4g5crgmhr/AADodFb_O0yNwl6C39k_LXoTa?dl=0.

Thanks

**Comment by piyuesh-dev** [comment]
I found solution to this issue. After looking at traffic via wireshark, it seems that even muted streams (other encoders) have some audio frames (may be null, not sure). Following code works for me:

```
    func processSampleBuffer(sampleBuffer: CMSampleBuffer, sampleBufferType: RPSampleBufferType) {
        switch sampleBufferType {
            case RPSampleBufferType.video:
                
                if CMSampleBufferDataIsReady(sampleBuffer) {
                    if let description: CMVideoFormatDescription = CMSampleBufferGetFormatDescription(sampleBuffer) {
                        let dimensions: CMVideoDimensions = CMVideoFormatDescriptionGetDimensions(description)
                        
                        broadcaster.stream.videoSettings = [
                            "width": dimensions.width,
                            "height": dimensions.height ,
                            "profileLevel": kVTProfileLevel_H264_Baseline_AutoLevel
                        ]
                    }
                    broadcaster.appendSampleBuffer(sampleBuffer, withType: .video)
                }
                // Handle video sample buffer
            break
            case RPSampleBufferType.audioApp:
                // we need to send app audio, if microphone is not on,
                // since youtube, twitch requires atleast 1 audio stream.
                if !isMicrophoneOn && CMSampleBufferDataIsReady(sampleBuffer) {
                    spliter?.appendSampleBuffer(sampleBuffer)
                }
            break
            case RPSampleBufferType.audioMic:
                if CMSampleBufferDataIsReady(sampleBuffer) {
                    broadcaster.appendSampleBuffer(sampleBuffer, withType: .audio)
                }
                isMicrophoneOn = true;
            break
        }
    }

```

Now we send app audio frames as long as microphone frames are not available.

**It works fine with and w/o microphone.**
