### ISSUE TITLE
Crashes when HLS streaming

### ISSUE THREAD

**Issue by adamnemecek** [shogo4405/HaishinKit.swift#450]
**Describe the bug**
When streaming HLS, HaishinKit crashes very soon after the start of the streaming.

**To Reproduce**
1. Start macos demo.
2. Select HLS.
3. Start publishing.
4. Open quicktime, hit CMD + L, paste in the URL of the m3u manifest.
5. Wait some time (generally 20 seconds tops)
6. CRASH!

**Expected behavior**
No crash.

**Screenshots**
http://prntscr.com/kg98ox

**Additional context**
It appears that the issue is related to threading. I'll try to look into this some more however I'm not quite certain about the correct use of the threading in the framework.

**Comment by dvt282** [comment]
Same problem. When I start HLS. After 20s stream stop. New reload required to resume normal
