### ISSUE TITLE
Does this support 4K streaming?

### ISSUE THREAD

**Issue by sunil-targe** [shogo4405/HaishinKit.swift#452]
**I wanted to implement Live streaming which can support with 4K resolution.**
Before proceeding further, I just wanted to ask whether does it supporting this feature or not. Because all other third party libraries which we've observed that those doesn't support in actual situation even in high bandwidth network but they doesn't even mention about their limitation.

In this library also I couldn't found 4K supporting bullet point in their feature list.

**Comment by shogo4405** [comment]
Please try your self!
