### ISSUE TITLE
Disabling portrait orientation while using HaishinKit results in significant launch delay

### ISSUE THREAD

**Issue by BigSauce** [shogo4405/HaishinKit.swift#453]
When disabling portrait orientation in project settings -> `<build target>` -> General -> Deployment Info, apps (including the example project in this repo) experience a significant delay in launch time.  The hangup occurs at line 60 of `VideoIOComponent.swift`.

![image](https://user-images.githubusercontent.com/1718470/44218256-52e09500-a147-11e8-96b3-366637a0a4c1.png)

As a result, apps that are landscape-only cannot use HaishinKit without experiencing a significant delay (without writing a time-prohibitive amount of workaround code).

**To Reproduce**
This is replicable in the example project.

1. Pull this repo and run `carthage update` to install its dependencies.
2. Open the example project in this repo and notice that Portrait is enabled.  Run the app and see the launch time perform as expected.

![image](https://user-images.githubusercontent.com/1718470/44217917-8d95fd80-a146-11e8-878b-595f27d53119.png)

3. Disable Portrait orientation

![image](https://user-images.githubusercontent.com/1718470/44218146-0e54f980-a147-11e8-832f-6a294e52f8ca.png)

4. Run the app and observe a significant increase in launch time (around 5-7 seconds).

**Expected behavior**
Apps with Portrait orientation disabled at the project level to launch without a significant hangup/delay.

**Screenshots**
Screenshots have been added inline above.

**Comment by BigSauce** [comment]
Might I ask if there is a timeline in mind for this bug to be fixed?  I have a project that significantly relies upon this library and don't have the bandwidth to resolve it myself at the moment.  Thanks, again!

**Comment by triwav** [comment]
@shogo4405 any time line on this. I'm running into this same issue as well. Is there some quick work around to get this working if we don't want to allow portrait orientation for video recording? Thanks!

**Comment by shogo4405** [comment]
https://github.com/shogo4405/HaishinKit.swift/pull/447
