### ISSUE TITLE
Continue recording after stream ends.

### ISSUE THREAD

**Issue by ballmw** [shogo4405/HaishinKit.swift#454]
Sometimes our users have poor network connections and the stream is terminated and recording ends.

I believe that this behavior is as expected and works as such.

I would like to be able to continue recording offline, even though streaming has terminated.

I'm open to alternative suggestions, thanks for your help.

**Comment by tejaskdubal** [comment]
Don't know why this is closed but this could be the usual situation.

**Comment by elcssmouhsine** [comment]
did anyone find a solution for this
