### ISSUE TITLE
Autorotate issues (green screen when used with ReplayKit functionality)

### ISSUE THREAD

**Issue by mmaschenko** [shogo4405/HaishinKit.swift#455]
**When using Haishinkit in BroadcastExtension (the one that streams some app screen through you app to some web stream service etc. Youtube) there is an issue with autorotate**
I listen to orientation change and change stream params like this 
` broadcaster.stream.videoSettings = [
     "width": newOrient == "landscape" ? broadcastHeight : broadcastWidth,
     "height": newOrient == "landscape" ? broadcastWidth : broadcastHeight,
     "profileLevel": kVTProfileLevel_H264_Baseline_AutoLevel,
      "bitrate": 160 * 1024,
      "maxKeyFrameIntervalDuration": 2, // key frame / sec,
       "scalingMode": "Letterbox" 
 ]`
After that stream gets messed up and i see mostly green screen with crashed pixels everywhere, once i rotate to start position it's ok again.

There was an issue #147 but it was not active for two years and guys there discuss how handle rotation in general

**Comment by shogo4405** [comment]
It seems don't support client side player(YouTube, VLC).
I wasn't very helpful.
