### ISSUE TITLE
Switch from WiFi to 4G and visa versa

### ISSUE THREAD

**Issue by GerritPost** [shogo4405/HaishinKit.swift#456]
**Describe the bug**
What is the best practise for reestablish the connection when the wifi connection is lost and the iPhone switch to 4G, or reconnects to 4G?

The current solution that I've implemented is not sufficient/fast enough. 
 
My current solution contains a reachability observer that observes if the device changes the connection from WiFi to 4G or visa versa, Disconnects the stream and start it again. 

```
  /// Reconnect when connection is lost.
  /// RTMP Connection and stream will be recreated and added again to the view
  /// TODO: Check if there is a better way to reconnect when connection is lost.
  /// - Parameter note: Notification
  @objc private func reconnect(note: Notification) {
    
    let reach = note.object as! Reachability
    // Still connected to the internet
    if reach.isReachable {
      if rtmpConnection == nil {return}
      // when the rtmpConnection
      if self.rtmpConnection!.connected{
        self.rtmpStreamStop() // Stop the stream
        rtmpConnection = RTMPConnection() // Recreate the connection
        createRTMPStream() //create RTMP Stream
        attachRTMPStream() //attach to the view
        self.rtmpConnection!.addEventListener(Event.RTMP_STATUS, selector: #selector(self.rtmpStatusHandler(_:)), observer: self)
        self.rtmpConnection!.connect(Preference.defaultInstance.uri!)
      }
    }
  }

```

Default the HaishinKit stops uploading frames (according to the FPS) when the connection changes from WiFi to 4G or visa versa.

Haishinkit is replacing my old solution for livestreaming named VideoCore. This handles switching from wifi to 4g a lot faster. Yes, there are some frame drops but the connection will be restored very fast. Videocores performance is worse and contain less features. it uses a lot of battery so that's why I've moved on to Haishinkit!
https://github.com/tradecast/videocore

**Expected behavior**
Drop frames but keep connected as soon this is possible

**Device:**
 - Device: iPhone X
 - OS: iOS 11.4.1

I Want to contribute, but while debugging HaishinKit I could not find a reason why it cannot reconnect when  connection is lost due switching from WiFi to 4G

**Comment by shogo4405** [comment]
>  I could not find a reason why it cannot reconnect when connection is lost due switching from WiFi to 4G

I think it is not Framework layer. It is application layer. Reachability is best solution.

**Comment by mkrn** [comment]
@GerritPost  Did you find a solution to reconnect as soon as possible? I have opened a similar issue listing all the things I've tried:
https://github.com/shogo4405/HaishinKit.swift/issues/555 
Thanks
