### ISSUE TITLE
Switching camera functionality

### ISSUE THREAD

**Issue by jonbrew** [shogo4405/HaishinKit.swift#458]
**Describe the bug**
Switching camera according to the code in examples does not function correctly (my code for switching below). This is because the call to attachCamera() inside of NetStream.swift never runs due to the lockQueue. I was able to fix this by removing lockQueue.async and everything seems to function correctly. Am I not supposed to do this? What is the lockQueue for in the context of attaching cameras? Am I doing something wrong and it should function with the lockQueue? Thanks.
My switch camera functionality
```swift
@objc func switchCamera() {
		print("Called switch. Cur = "+String(self.currentCameraPos.rawValue))
		let newCameraPosition: AVCaptureDevice.Position = self.currentCameraPos == .back ? .front : .back
		print("NEW = "+String(newCameraPosition.rawValue))
		self.rtmpStream.attachCamera(DeviceUtil.device(withPosition: newCameraPosition)) { error in
			print(error.description)
		}
		currentCameraPos = newCameraPosition
	}
```
Problematic function in NetStream.swift ("REACHED" is never printed)
```swift
open func attachCamera(_ camera: AVCaptureDevice?, onError: ((_ error: NSError) -> Void)? = nil) {
        lockQueue.async {
            do {
                print("REACHED")
                try self.mixer.videoIO.attachCamera(camera)
            } catch let error as NSError {
                onError?(error)
            }
        }
    }
```

**Desktop (please complete the following information):**
 - OS: iOS 11.4.1

**Smartphone (please complete the following information):**
 - Device: iPhone 6s

**Additional context**

**Comment by jonbrew** [comment]
After adding a torch button as well, it seems that the same problem occurs with the torch variable. 
```swift
open var torch: Bool {
        get {
            var torch: Bool = false
            ensureLockQueue {
                torch = self.mixer.videoIO.torch
            }
            return torch
        }
        set {
            lockQueue.async {
                self.mixer.videoIO.torch = newValue
            }
        }
    }
```
Before I removed lockQueue from and ensureLockQueue, my app would freeze. After removing things function as expected.

**Comment by shogo4405** [comment]
Related issues is here. https://github.com/shogo4405/HaishinKit.swift/issues/429
I will try fix it.
