### ISSUE TITLE
Jerky sound with external mic on Lightning port

### ISSUE THREAD

**Issue by psegalen** [shogo4405/HaishinKit.swift#459]
**Describe the bug**
Using the SDK without any external mic is OK.
Using it with an external mic plugged into a jack port is OK.
but
Using it with an external mic plugged through a jack / lightning adapter (or with Apple lightning headset) is jerky.

**To Reproduce**
1. Run "Example iOS" on your device (change the settings to be able to watch and listen the streaming)
2. Launch the streaming
3. Speak, audio is good
4. Plug an external mic in through lightning
5. Speak, audio is jerky, like through a fan

**Expected behavior**
Audio should be good with external mics connected on lightning port (no more jack port on iPhones since the 7)

**Smartphone (please complete the following information):**
 - Device: iPhone 8 & iPod touch 6th generation
 - OS: iOS 11.4.1

**Additional context**
It may be a regression because I'm pretty sure I did the test at some point earlier this year and audio was good.

**Comment by psegalen** [comment]
I don't even know how to debug it since the device must be connected with the mic through the lightning port to experience the bug, so the port can't be used at the same time to access the logs...

**Comment by psegalen** [comment]
@shogo4405 could it be related to #457 ?

**Comment by shogo4405** [comment]
@psegalen No.
Maybe, Normal CMSampleBuffer has 1024 samples.
But External mic isn't 1024 samples.

HaishinKit needs 1024 samples.

**Comment by shogo4405** [comment]
I want to see. print(yourCMSampleBuffer) log.

https://github.com/shogo4405/HaishinKit.swift/issues/158#issuecomment-270649090
numSamples = 1024

**Comment by psegalen** [comment]
I'll need a better adapter since I can't connect the lightning cable to the Mac while the external mic is plugged so I can't access the logs. :(
I'll order one as soon as possible.

**Comment by shogo4405** [comment]
OK. I understand. Xcode 9 can do wireless debugging.
Please consider to use it.

**Comment by psegalen** [comment]
Wireless debugging, of course, it didn't occur to me! :(
How to print CMSampleBuffer?
Also, the "Example iOS" app sets the sample rate @ 44.1 KHz but the logs mention:
`[com.haishinkit.HaishinKit] [AACEncoder.swift:86] inSourceFormat > Optional(__C.AudioStreamBasicDescription(mSampleRate: 48000.0, mFormatID: 1819304813, mFormatFlags: 12, mBytesPerPacket: 2, mFramesPerPacket: 1, mBytesPerFrame: 2, mChannelsPerFrame: 1, mBitsPerChannel: 16, mReserved: 0))`
It appears to be @ 48 KHz, could it be the source of the problem?

**Comment by psegalen** [comment]
No, sample rate is @ 48 KHz also when unplugging the external mic but sound is OK.

**Comment by psegalen** [comment]
I figured how to print my CMSampleBuffer from your `Example iOS` app and (I set preferred sample rate @ 44.1KHz):

- a Samsung jack headset mic connected through the lightning adapter Apple provided with my iPhone has:
> numSamples of 1024
> mSampleRate of 48KHz
- the lightning headset provided by Apple has:
> numSamples of 940
> mSampleRate of 44.1KHz
- no external mic:
> numSamples of 1024
> mSampleRate of 44.1KHz

Here is one full log from first config:
```
2018-06-09 19:03:14.196 [Info] [com.haishinkit.HaishinKit] [AACEncoder.swift:162] encodeSampleBuffer > CMSampleBuffer 0x101dc0dd0 retainCount: 8 allocator: 0x1b2895538
	invalid = NO
	dataReady = YES
	makeDataReadyCallback = 0x0
	makeDataReadyRefcon = 0x0
	formatDescription = <CMAudioFormatDescription 0x1036afb40 [0x1b2895538]> {
	mediaType:'soun' 
	mediaSubType:'lpcm' 
	mediaSpecific: {
		ASBD: {
			mSampleRate: 48000.000000 
			mFormatID: 'lpcm' 
			mFormatFlags: 0xc 
			mBytesPerPacket: 2 
			mFramesPerPacket: 1 
			mBytesPerFrame: 2 
			mChannelsPerFrame: 1 
			mBitsPerChannel: 16 	} 
		cookie: {(null)} 
		ACL: {(null)}
		FormatList Array: {(null)} 
	} 
	extensions: {(null)}
}
	sbufToTrackReadiness = 0x0
	numSamples = 1024
	sampleTimingArray[1] = {
		{PTS = {3929705251208/1000000000 = 3929.705, rounded}, DTS = {INVALID}, duration = {1/48000 = 0.000}},
	}
	sampleSizeArray[1] = {
		sampleSize = 2,
	}
	dataBuffer = 0x101ded520
```

Here is one full log from second config:
```
2018-06-09 18:55:36.084 [Info] [com.haishinkit.HaishinKit] [AACEncoder.swift:162] encodeSampleBuffer > CMSampleBuffer 0x101dc8a20 retainCount: 9 allocator: 0x1b2895538
	invalid = NO
	dataReady = YES
	makeDataReadyCallback = 0x0
	makeDataReadyRefcon = 0x0
	formatDescription = <CMAudioFormatDescription 0x103679f40 [0x1b2895538]> {
	mediaType:'soun' 
	mediaSubType:'lpcm' 
	mediaSpecific: {
		ASBD: {
			mSampleRate: 44100.000000 
			mFormatID: 'lpcm' 
			mFormatFlags: 0xc 
			mBytesPerPacket: 2 
			mFramesPerPacket: 1 
			mBytesPerFrame: 2 
			mChannelsPerFrame: 1 
			mBitsPerChannel: 16 	} 
		cookie: {(null)} 
		ACL: {(null)}
		FormatList Array: {(null)} 
	} 
	extensions: {(null)}
}
	sbufToTrackReadiness = 0x0
	numSamples = 940
	sampleTimingArray[1] = {
		{PTS = {3471561138820/1000000000 = 3471.561, rounded}, DTS = {INVALID}, duration = {1/44100 = 0.000}},
	}
	sampleSizeArray[1] = {
		sampleSize = 2,
	}
	dataBuffer = 0x101dc8d90
```

And here is one without external mic (only good sound quality):
```
2018-06-09 18:56:58.411 [Info] [com.haishinkit.HaishinKit] [AACEncoder.swift:162] encodeSampleBuffer > CMSampleBuffer 0x10369f160 retainCount: 9 allocator: 0x1b2895538
	invalid = NO
	dataReady = YES
	makeDataReadyCallback = 0x0
	makeDataReadyRefcon = 0x0
	formatDescription = <CMAudioFormatDescription 0x103679f40 [0x1b2895538]> {
	mediaType:'soun' 
	mediaSubType:'lpcm' 
	mediaSpecific: {
		ASBD: {
			mSampleRate: 44100.000000 
			mFormatID: 'lpcm' 
			mFormatFlags: 0xc 
			mBytesPerPacket: 2 
			mFramesPerPacket: 1 
			mBytesPerFrame: 2 
			mChannelsPerFrame: 1 
			mBitsPerChannel: 16 	} 
		cookie: {(null)} 
		ACL: {(null)}
		FormatList Array: {(null)} 
	} 
	extensions: {(null)}
}
	sbufToTrackReadiness = 0x0
	numSamples = 1024
	sampleTimingArray[1] = {
		{PTS = {3553887643320/1000000000 = 3553.888, rounded}, DTS = {INVALID}, duration = {1/44100 = 0.000}},
	}
	sampleSizeArray[1] = {
		sampleSize = 2,
	}
	dataBuffer = 0x10369e650
```

Do you think we can fix it? If so, how can I help?

**Comment by psegalen** [comment]
Ran my app while setting 48KHz preferred sample rate today and it seems to fix the problem: switching between the 3 configs I mentioned in my previous comment doesn't alter the sound quality...
I'm closing this issue for now and will re-open it if I encounter the problem with 48KHz preferred sample rate.
