### ISSUE TITLE
Broadcast Extension is not streaming to the server?

### ISSUE THREAD

**Issue by dmyma** [shogo4405/HaishinKit.swift#460]
I have managed to run the example app and change the link and the key to my server, everything is working great when I am streaming in app, but when I use broadcast extension seems like there is no video. Am I doing something wrong? Thanks.

**Comment by dmyma** [comment]
I checked https://github.com/shogo4405/HaishinKit.swift/issues/350 and now it is working, streaming to facebook, but I have a question, why it did not work before with the preference.defaultInstance? Thank you for your work and HaishinKit.

**Comment by shogo4405** [comment]
I'm not sure. Please ask Apple.
