### ISSUE TITLE
iPhone x Camera not filling in entire screen

### ISSUE THREAD

**Issue by pjreact** [shogo4405/HaishinKit.swift#462]
It shows gaps on the top and bottom. The camera should fill the entire screen 

![screen shot 2018-09-06 at 2 26 01 pm](https://user-images.githubusercontent.com/2162230/45146642-e8b88e80-b1e0-11e8-881d-1a94ca0eebad.png)

**Comment by shogo4405** [comment]
Please use "Bug report" templates.
