### ISSUE TITLE
Command CompileSwift failed with a nonzero exit code

### ISSUE THREAD

**Issue by akiporoyopida** [shogo4405/HaishinKit.swift#463]
Environment: HaishinKit 0.8.8, Logboard 1.1.7 (Pods, iOS 12, Xcode 10.0)
Haishinkit has 1issue
Uncategorized Group
Command CompileSwift failed with a nonzero exit code
I use it via pods, but do I have to wait for the next version?

**Comment by akiporoyopida** [comment]
func enqueueSampleBuffer(_ stream: RTMPStream) {
.
.
 data.withUnsafeMutableBytes { (bytes: UnsafeMutablePointer<UInt8>) -> Void in
^^^^^
Pods/HaishinKit/Sources/RTMP/RTMPMessage.swift:672:9: Overlapping accesses to 'data', but modification requires exclusive access; consider copying to a local variable

<img width="1420" alt="2018-09-26 11 36 20" src="https://user-images.githubusercontent.com/1607194/46054061-7b18d600-c180-11e8-873f-6ee83c081bb0.png">

**Comment by shogo4405** [comment]
How about HaishinKit 0.9.4? I fixed it latest version.

https://github.com/shogo4405/HaishinKit.swift/blob/a801901af03d376caa8770629109fb371a838f81/Sources/RTMP/RTMPMessage.swift#L671

**Comment by akiporoyopida** [comment]
After updating the problem was resolved.
Thank you!!
