### ISSUE TITLE
Improving Performance/Reducing Latency of RTMP Screencast

### ISSUE THREAD

**Issue by joellubi** [shogo4405/HaishinKit.swift#464]
Great project! I'm currently using it to stream an iOS screen to a BeagleBone Black through WiFi.

I would ideally like to get total latency down to around ~1s if possible. Most of the slowdown currently occurs on the BeagleBone, so I would like to downscale the resolution of frames being sent from the SampleHandler. I tried changing the following lines to hardcode resolution but no luck:

```swift
override open func processSampleBuffer(_ sampleBuffer: CMSampleBuffer, with sampleBufferType: RPSampleBufferType) {
        switch sampleBufferType {
        case .video:
            broadcaster.stream.videoSettings = [
                "width": 854,
                "height": 480,
                "profileLevel": kVTProfileLevel_H264_Baseline_AutoLevel
            ]
            broadcaster.appendSampleBuffer(sampleBuffer, withType: .video)
        case .audioApp:
            // spliter?.appendSampleBuffer(sampleBuffer)
            break
        case .audioMic:
            broadcaster.appendSampleBuffer(sampleBuffer, withType: .audio)
        }
    }
```

Where would be the best point in the process to make a change to the resolution to save as much work as possible in the pipeline?

P.S. Am I correct in understanding that VTCompressionSession is currently only used for streaming the camera? My performance is much better there.

Thanks a lot!

**Comment by shogo4405** [comment]
> Where would be the best point in the process to make a change to the resolution to save as much work as possible in the pipeline?

I thought broadcastStarted(withSetupInfo:).
see https://developer.apple.com/documentation/replaykit/rpbroadcastsamplehandler/2143170-broadcaststarted
