### ISSUE TITLE
Stream is cropped from top and bottom

### ISSUE THREAD

**Issue by faiza-nawaz-confiz** [shogo4405/HaishinKit.swift#471]
**Issue:**
The video stream is cropped from the top and the bottom.

**To Reproduce:**
1. Follow the instructions/code given in the following link: https://github.com/shogo4405/HaishinKit.swift/blob/master/README.md
2. Stream starts
2. The video is cropped from the top and the bottom in the output stream.

**Expected behavior:**
The video should not be cropped and should be displayed completely as recorded from the source.

**Screenshots:**
This is the screenshot while recording the stream and the output stream:
![screen shot 2018-10-15 at 8 02 14 pm](https://user-images.githubusercontent.com/8266137/46959454-7f684d00-d0b5-11e8-8d08-f5c567fef334.png)

**Desktop:**
 - OS: MacOS 10.13.4
 - HaishinKit Version 0.9.3
 - XCode 9.3

**Smartphone:**
 - Device: iPhone6
 - OS: iOS 10.0.2

**Additional context:**
The stream is working fine via OBS (Desktop Client), i.e. it is not cropping when streamed from OBS.

We have also tried with custom capture settings and video settings for HD video, it is still cropping the video (setings given below):
![screen shot 2018-10-15 at 7 52 04 pm](https://user-images.githubusercontent.com/8266137/46958707-de2cc700-d0b3-11e8-936e-a6da247fa5a5.png)

**Comment by shogo4405** [comment]
1. You can select
   -  rtmpStream.videoSettings["scalingMode"} = {Trim|Letterbox|Normal|CropSourceToCleanAperture}
2. It seems your settings are portrait mode. Please try here.
   - videoSetting["width"] = 720 , videoSettings["height"] = 1280
