### ISSUE TITLE
No sound in HTTP Streaming

### ISSUE THREAD

**Issue by StanFedorov** [shogo4405/HaishinKit.swift#477]
**Describe the bug**
While recording stream with HTTP Streaming in Broadcast Upload Extension output (opened by URL on any devices) has no audio.

<img width="822" alt="2018-11-01 14 07 51" src="https://user-images.githubusercontent.com/12141524/47848575-d4a79c80-dddf-11e8-955b-33c713a1d538.png">

**To Reproduce**
1. Create Broadcast Upload Extension
2. Implement HTTP Streaming following the README
3. Start Recording

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max
 - OS: iOS 12.0.1

**Comment by shogo4405** [comment]
HaishinKit requires CMSampleBuffer / 1024 frames. But .audioApp is 22050 frames.
Please split CMSampleBuffer / 1024 frames.

https://github.com/shogo4405/HaishinKit.swift/commit/99b9c77936b372db1139e498f5f82d5318d8173b#diff-dca2c16b021c54ba96d5eeb462c7bdd9
