### ISSUE TITLE
How to turn off Adaptive bitrate for screencast?

### ISSUE THREAD

**Issue by Gorg5** [shogo4405/HaishinKit.swift#479]
Right now it seems adaptive bitrate feature only decreases the bitrate in case of a low quality network, but it never increase the bitrate back up after network quality improvement. I noticed sometimes bitrate is decreased immaturely even when the network quality is almost the same during the screencast. Is there a way to turn this feature off? In other word, keep the output bitrate the same at all time? What is the easiest way to do so?

Thanks.

**Comment by shogo4405** [comment]
@Gorg5 
> Is there a way to turn this feature off?

Default off. Framework does't support adaptive bitrate logic. But provide information for adaptive bitrate. https://github.com/shogo4405/HaishinKit.swift/issues/126#issuecomment-298697297 I think it's application layer.
