### ISSUE TITLE
local HLS record

### ISSUE THREAD

**Issue by vhmth** [shogo4405/HaishinKit.swift#483]
I would love to leverage the `TSFileWriter` (created in #482) and `AVMixer` classes to do local HLS recording.

My goal is:

1. Start a recording (screen + camera).
2. Get notified when each `.ts` file is created.
3. Upload that `.ts` file to a server.
4. End a recording.

I didn't see any way to do this with the current top-level APIs, but how would you suggest doing it with the current classes? Perhaps we can work on getting local HLS recording (with an infinitely growing M3U8 playlist) going as a top-level API?

**Comment by shogo4405** [comment]
Please fork and customize your project.
