### ISSUE TITLE
HLS not working

### ISSUE THREAD

**Issue by dvt282** [shogo4405/HaishinKit.swift#485]
**Describe the bug**
When I run example on macOS with HLS. Stream not display with version 0.10.4, Old version working.

**To Reproduce**
1. Start macos demo.
2. Select HLS.
3. Start publishing.
4 Open url on safari/vlc

**Expected behavior**
Display stream from camera

**Screenshots**
https://gyazo.com/46b142bbe9aef2ea0aa4b43c331a7de9

**Comment by shogo4405** [comment]
Thank u feedback. I stoped release 0.10.4.

**Comment by thatmarcel** [comment]
I'm still having the same issue with 0.10.6. Any way to fix? I'm using 0.10.1 now which works but is very choppy

**Comment by dvt282** [comment]
I also had a problem with it not working on safari with the latest version 0.10.7.
@shogo4405
