### ISSUE TITLE
I can't install this libraray with cocapods

### ISSUE THREAD

**Issue by MansoorJafari** [shogo4405/HaishinKit.swift#486]
Hello
I want to install this library on my project swift4  xcode 10
give me this error

`
[!] CocoaPods could not find compatible versions for pod "HaishinKit":
  In Podfile:
    HaishinKit (~> 0.10.3)

None of your spec sources contain a spec satisfying the dependency: `HaishinKit (~> 0.10.3)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

`

please help.

**Comment by shogo4405** [comment]
![2018-12-09 16 42 16](https://user-images.githubusercontent.com/810189/49694656-72f20380-fbd1-11e8-88ab-dcf664c5b9a6.png)

:(

**Comment by shogo4405** [comment]
I pushed into cocoapods trunk.
Well, might be use 0.10.3.

Thank u.
