### ISSUE TITLE
HaishinKit is not working when installing

### ISSUE THREAD

**Issue by Cristu39** [shogo4405/HaishinKit.swift#488]
Hi,
I'm getting this error:
Pods/HaishinKit/Sources/RTMP/RTMPMessage.swift:672:9: Overlapping accesses to 'data', but modification requires exclusive access; consider copying to a local variable

when trying to compile GPUHaishinKit that uses HaishinKit pod.
I'm using xcode 10.1 and swift 4.
This is my Podfile

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
def import_pods
    pod 'GPUHaishinKit', '~> 1.2.0'    
end

Any idea? Thanks.

**Comment by shogo4405** [comment]
GPUImage is unmaintained. Also I can't maintenance GPUHaishinKit.

> Pods/HaishinKit/Sources/RTMP/RTMPMessage.swift:672:9: Overlapping accesses to 'data', but modification requires exclusive access; consider copying to a local variable

Framework has fixed this issue. 0.9.4. But GPUHaishinKit requires 'HaishinKit' '~> 0.8.0'.

Thanks.
