### ISSUE TITLE
appendSampleBuffer missing from RTMPStream

### ISSUE THREAD

**Issue by sstasinos** [shogo4405/HaishinKit.swift#491]
Hi,

I moved from using the library to using cocoapods and HaishinKit 0.10.3 as I'm migrating a working app to Xcode 10. The issue I'm seeing is that appendSampleBuffer is no longer a method on RTMPStream, which is critical for the app.

I tried looking around for possibly a different way of doing it, but not seeing it. And the sample code still shows using appendSampleBuffer.

Thanks for any insight you can provide.

Steve

**Comment by shogo4405** [comment]
RTMPStream class inherits NetStream class.
https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/Net/NetStream.swift#L163

NetStream has appendSampleBuffer. Please try this.
