### ISSUE TITLE
Should write comment for every open func

### ISSUE THREAD

**Issue by wolfcon** [shogo4405/HaishinKit.swift#493]
```swift
rtmpConnection.connect(StreamingServer.urlString)
rtmpStream.publish(StreamingServer.name)
```

`StreamingServer.urlString + StreamingServer.name` is actually the steam server URL. I'm searching for solution in issues. There is no comment / Doc in Xcode at all. Thats not convenient. 😄

**Comment by psegalen** [comment]
Hi, an example for Twitch: the URL you pass to `rtmpConnection.connect()` is the ingest (ex: `rtmp://live-hkg.twitch.tv/app` from https://stream.twitch.tv/ingests/) and the "name" you pass to `rtmpStream.publish()` is actually your stream key.

Basically, you need to cut your stream URL in half: the service URL // the stream key

**Comment by psegalen** [comment]
Oh! You mean the SDK doc is lacking explanation about this? Yes, it could be a useful PR!
