### ISSUE TITLE
Broadcast iPhone Camera feed Over Network

### ISSUE THREAD

**Issue by user-iOS** [shogo4405/HaishinKit.swift#494]
I want to broadcast my iPhone camera on local network so, it should be accessible on every other system over the same Wifi. 

So for achieving this I implemented this code:

var httpStream = HTTPStream()
httpStream.attachCamera(DeviceUtil.device(withPosition: .back))
httpStream.attachAudio(AVCaptureDevice.defaultDevice(withMediaType: AVMediaTypeAudio))
httpStream.publish("hello")

var hkView = HKView(frame: view.bounds)
hkView.attachStream(httpStream)

// domain: will be iphone ip address.
var httpService = HLSService(domain: "", type: "_http._tcp", name: "HaishinKit", port: 8080)
httpService.startRunning()
httpService.addHTTPStream(httpStream)

// add ViewController#view
view.addSubview(hkView)

But, above code not working perfectly. On my Mac browser nothing has been displayed.

**Comment by shogo4405** [comment]
Plase use "Bug report" template.
