### ISSUE TITLE
Syncorientation doesn't handle "X..." iPhones

### ISSUE THREAD

**Issue by psegalen** [shogo4405/HaishinKit.swift#496]
**Describe the bug**
My app supports all orientations and I activated `syncOrientation`, it works perfectly on all the regular iPhones (rectangle screens) but on my iPhone XR (and on a coworker's iPhone XS), HaishinKit rotates the capture for all the 4 orientations but iPhones with a notch don't support the upside down orientation.

**To Reproduce**
1. Deploy the "Example iOS" app on an iPhone X, XR or XS
2. Change the device orientation to upside down
3. Bug: the capture rotates but the UI doesn't (see screenshot)

**Expected behavior**
On iPhones with a notch it seems that upside down orientation is fully disabled so the only functional behavior would be that the SDK detects the phone has a notch and handle orientation only if it's not upside down.

**Screenshots**
![Screenshot](https://cdn.pbrd.co/images/HY5VpN4.png)

**Smartphone**
 - Device: iPhone XR (doesn't happen on my iPhone 8)
 - OS: iOS 12.1.2

**Comment by joshuadiezmo** [comment]
any update on this? I also have problem on orientation.
