### ISSUE TITLE
streaming from BroadcastUploadExtension is slow and suddenly stops sometimes

### ISSUE THREAD

**Issue by corazn** [shogo4405/HaishinKit.swift#502]
I stream to twitch.tv from broadcast upload extension and when to twitch.tv to watch my stream. The livestream is slow and become offline after just a few minutes. But when I stream with camera from containing app, the livestream is fast. 

Can you help me?
Thank you.

I test on iphone 6s (iOS 12.0.1).

**Comment by shogo4405** [comment]
> Can you help me?

 I could not help you out. I have same troubles.
Please report a bug report Apple Developer Center.
