### ISSUE TITLE
How to display 2 HKViews (from one camera) on screen for one RTMPStream?

### ISSUE THREAD

**Issue by johnathan-terralogic** [shogo4405/HaishinKit.swift#503]
Dear @shogo4405, I would say this sdk is awesome and really appreciate your contribution so far. So I'm using this for my project and I need to display 2 HKViews (from front camera)  on screen for one RTMPStream but I can't do it, although I tried by initializing 2 HKViews then attachStream but it doesn't work. Can you help me with some suggestions? It would be great if there is some sample code. Thank you in advance.

**Comment by johnathan-terralogic** [comment]
I've tried by adding code to HKView but don't think it's the best solution. 

```
public protocol HKViewDelegate {
    func drawImageFromInputSource(image: UIImage)
}
.....

extension HKView: NetStreamDrawable {
    // MARK: NetStreamDrawable
    func draw(image: CIImage) {
        if let delegate = delegate {
            delegate.drawImageFromInputSource(image: UIImage.init(ciImage: image))
        }
    }
}
```
Then implement the protocol as:
```
    func drawImageFromInputSource(image: UIImage) {
        DispatchQueue.main.async { [unowned self] in
            if self.videoPlayer != nil && self.activeTabIndex != self.originVideoPageIndex() {
                self.videoPlayer.cameraView.image = image
            }
        }
    }
```

**Comment by shogo4405** [comment]
I'm not design 2 HKViews.
I can't even venture a guess.
