### ISSUE TITLE
Support higher video resolution

### ISSUE THREAD

**Issue by rahulimedia** [shogo4405/HaishinKit.swift#504]
I am using a higher video resolution in my video frame, but that is not pushing the live stream on the my server. I tried that, but doesn't seem to work.

```
rtmpStream.videoSettings = [
            "width": 1920,
            "height": 1080,
        ]
```

**Comment by psegalen** [comment]
You also have to set the sessionPreset I think, see: https://github.com/shogo4405/HaishinKit.swift/blob/master/Examples/iOS/LiveViewController.swift#L50

**Comment by rahulimedia** [comment]
Already I have set it, but it's not working...

**Comment by psegalen** [comment]
Many i-devices don't support 1080p for Front camera, are you using the Front cam and if so on which type of device?

**Comment by rahulimedia** [comment]
I'm using iPhone 6s plus with back camera. Its supported higher resolution.

**Comment by shogo4405** [comment]
Please use bug report template.

**Comment by DaniArnaout** [comment]
Solution: You have to set your profile level to "High" for it to work.

rtmpStream.videoSettings = [
"width": 1920,
"height": 1080,
"profileLevel": kVTProfileLevel_H264_High_AutoLevel
]

**Comment by rahulimedia** [comment]
Its working now.. thanks!
