### ISSUE TITLE
Metal is supported?

### ISSUE THREAD

**Issue by horita-yuya** [shogo4405/HaishinKit.swift#507]
I tried using `MTHKView` and `VisualEffect` with CIKernel. But nothing is displayed.
Some simple examples would help me.

Thank you 🙏 🙏

**Comment by shogo4405** [comment]
MTHKView can support VisualEffect.
Please see also. https://github.com/shogo4405/HaishinKit.swift/issues/505

**Comment by shogo4405** [comment]
@horita-yuya 
Please try master branch.
https://github.com/shogo4405/HaishinKit.swift/pull/498

**Comment by horita-yuya** [comment]
I could. Thanks.
