### ISSUE TITLE
RTMP stream playback with MTHKView on iOS?

### ISSUE THREAD

**Issue by kenosan** [shogo4405/HaishinKit.swift#509]
I'm trying to playback a RTMP stream using MTHKView but nothing shows. 

```
// MTHKView placed in storyboard 
@IBOutlet weak var playerView: MTHKView!

let rtmpConnection = RTMPConnection()
rtmpConnection.connect(mediaUrl.absoluteString)
// mediaUrl = rtmp://host/live/stream-name

let rtmpStream = RTMPStream(connection: rtmpConnection)
rtmpStream.play(mediaUrl.lastPathComponent)
playerView.attachStream(rtmpStream)
```

In my XCode console I see the following but nothing is displayed in UI:
```
MyApp[6370:954840] Metal GPU Frame Capture Enabled
MyApp[6370:954840] Metal API Validation Enabled
[Warn] [com.haishinkit.HaishinKit] [RTMPConnection.swift:372] on(status:) > 
```
On further investigation, the RTMPConnection seems to be be getting closed. Any thoughts or pointers to help debug why the connection is being closed even though I can view the same stream in VLC Player?
```
RTMP Event: [
"code": Optional("NetConnection.Connect.Closed"),
"level": Optional("status"), 
"description": Optional("")
]
```

I'm using HaishinKit v0.10.5 on iOS 12

**Comment by shogo4405** [comment]
* rtmp://host/live/stream-name
  - live means applicationName
  - stream-name means streamName

Please try 
```
// MTHKView placed in storyboard 
@IBOutlet weak var playerView: MTHKView!

let rtmpConnection = RTMPConnection()
rtmpConnection.connect("rtmp://host/live")

let rtmpStream = RTMPStream(connection: rtmpConnection)
rtmpStream.play("stream-name")
playerView.attachStream(rtmpStream)
```

**Comment by kenosan** [comment]
That worked. The RTMPConnection now works but I get a crash in `MTHKView`

MTHKView.swift:93
```
context.render(scaledImage, to: drawable.texture, commandBuffer: commandBuffer, bounds: bounds, colorSpace: colorSpace)
```
Xcode console outputs shows
```
-[MTLDebugComputeCommandEncoder setTexture:atIndex:]:401: failed assertion `frameBufferOnly texture not supported for compute.'
```

**Comment by bijanmmarkes** [comment]
Does Audio work for MTHKView? @shogo4405 I don't hear anything on playback

**Comment by bijanmmarkes** [comment]
@kenosan Does audio work for you when playing back using MTHKView?

**Comment by kenosan** [comment]
Hi, 

Revisiting this issue. I'm trying again with v1.0.0 running on iOS 12.4.2 and iOS 13.1.3. 

Now I'm getting crashes with message: 
`Message from debugger: Terminated due to memory issue`

While investigating, it looks like there is a memory leak in the `draw(in view:)` of `MTHKView`. As draw is invoked, at no point is the `displayImage` being released and there are several strong references to it. 

Also, the `draw(image:)` in the `NetStreamDrawable` extension might need some investigating. 

While my app is running and I'm using `MTHKView` to view an RTMP stream, the app's memory shoots up from 51MB to >1GB and gets terminated by the OS. I traced it to the above draw calls where on every frame received from the stream, the `CIImage` use seems to be growing and growing and never gets released while the stream is being viewed.

**Comment by mooncatventures-group** [comment]
Hey I know you said you have no plans to fix this but RTMP playback is crucial to our project and I am determined to make this player stable, my clients are really impressed with the latency .
Playback is ok for awhile but occasionally we get a crash, there is always a degrading of latency before the crash. 
I suspect its a memory leak in Metal as others noted , instruments shows total memory ramps up quickly but it does get released. 

Anyone have any hints were this defect is, we will of course share the fix when we have one and we will have one .

**Comment by saifDbm** [comment]
self.rtmpStream.attachCamera(self.getBackCamera())
         
         self.rtmpStream.attachAudio(AVCaptureDevice.default(.builtInMicrophone, for: .audio, position: .unspecified) )
