### ISSUE TITLE
Streaming a WKWebview leads to high CPU usage (only iPhone, iPad no problem)

### ISSUE THREAD

**Issue by themkn** [shogo4405/HaishinKit.swift#510]
**Describe the bug**
As soon as I start to publish the content of a WKWebview the CPU usage is very high and thus the webview is constantly lagging and not useable anymore.

**To Reproduce**

```
func setupRtmpStream(screen: UIView){
...
      rtmpStream.attachScreen(ScreenCaptureSession(viewToCapture: screen), useScreenSize: false)
      rtmpStream.publish("stream1")
}

```

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: 12
 - Swift: 4

**Comment by mocman** [comment]
I am having the same issue. Attaching screen makes app very slow and unusable.

**Comment by tatuanfpt** [comment]
Any ideal for this issues ? 
Im facing the same problem with WKWebView + Screen capture.
