### ISSUE TITLE
Multi streaming is not working

### ISSUE THREAD

**Issue by aarti1khajuria** [shogo4405/HaishinKit.swift#511]
**Describe the bug**
I am trying to stream on facebook and youtube simultaneously. But, it is going live on only one social media.

     var rtmpConnection = RTMPConnection()
     var rtmpStream: RTMPStream!
     var rtmpConnection1 = RTMPConnection()
     var rtmpStream1: RTMPStream!

     rtmpStream = RTMPStream(connection: rtmpConnection)
     rtmpStream1 = RTMPStream(connection: rtmpConnection1)

     rtmpStream = RTMPStream(connection: rtmpConnection)
     rtmpStream1 = RTMPStream(connection: rtmpConnection1)

     rtmpStream.attachAudio(AVCaptureDevice.default(for: .audio)) { error in
            logger.warn(error.description)
        }
        rtmpStream.attachCamera(DeviceUtil.device(withPosition: currentPosition)) { error in
            logger.warn(error.description)
        }
      
        rtmpStream1.attachAudio(AVCaptureDevice.default(for: .audio)) { error in
            logger.warn(error.description)
        }
        rtmpStream1.attachCamera(DeviceUtil.device(withPosition: currentPosition)) { error in
            logger.warn(error.description)
        }
       
         lfView?.attachStream(rtmpStream)
         lfView?.attachStream(rtmpStream1)

     @IBAction func on(publish: UIButton)
      {
        if publish.isSelected
        {
            UIApplication.shared.isIdleTimerDisabled = false
            rtmpConnection.close()
            rtmpConnection1.close()
            rtmpConnection.removeEventListener(Event.RTMP_STATUS, selector: #selector(rtmpStatusHandler), observer: self)
            publish.setTitle("●", for: [])
            
        //            rtmpConnection1.close()
      //            rtmpConnection1.removeEventListener(Event.RTMP_STATUS, selector: #selector(rtmpStatusHandler), observer: self)
       //            publish.setTitle("●", for: [])
        }
        else
        {
            UIApplication.shared.isIdleTimerDisabled = true
            rtmpConnection.addEventListener(Event.RTMP_STATUS, selector: #selector(rtmpStatusHandler), observer: self)
            rtmpConnection.connect("FBRTMPURL")
            rtmpConnection1.connect("YOUTUBERTMPURL")
            publish.setTitle("■", for: [])
        }
        publish.isSelected = !publish.isSelected
    }

    @objc
    func rtmpStatusHandler(_ notification: Notification) {
        let e = Event.from(notification)
        if let data: ASObject = e.data as? ASObject, let code: String = data["code"] as? String {
            switch code {
            case RTMPConnection.Code.connectSuccess.rawValue:
                rtmpStream!.publish("xxxxxxxxxxxxx")
                rtmpStream1!.publish("xxxxxxxxxxxx")
                // sharedObject!.connect(rtmpConnection)
            default:
                break
            }
        }
    }

After doing this it is going live on only one social media.

**Comment by RomanIvaniv** [comment]
Did you try to add event listener for  rtmpConnection1?
rtmpConnection1.addEventListener(Event.RTMP_STATUS, selector: #selector(rtmpStatusHandler), observer: self)
