### ISSUE TITLE
Broadcasting with RTMP is not happening

### ISSUE THREAD

**Issue by ankitthakur** [shogo4405/HaishinKit.swift#522]
There is method in **AVRecorder.swift**, `appendPixelBuffer(_ pixelBuffer: CVPixelBuffer...`

In that method, `self.delegate` is always nil. Also using debugger I have seen that, we are setting delegate during initialization but later it got nil.
```
guard let delegate: AVRecorderDelegate = self.delegate, self.isRunning else {
                return
            }
```

Due to this, it always get return, and is not transmitting buffer to the server.

**Comment by shogo4405** [comment]
see also #366
