### ISSUE TITLE
Switch Between Camera and Local File during Stream

### ISSUE THREAD

**Issue by mocman** [shogo4405/HaishinKit.swift#524]
**Is your feature request related to a problem? Please describe.**
I'd like to be start my stream using the camera, show a video I have in local documents, then go back to camera.

**Describe the solution you'd like**
To be able to appendfile during a livestream, then able to go back to camera after

**Comment by Sachinyadav6500** [comment]
@mocman  Did you find a way to do it?.   I am kind of stuck in similar scenarios

**Comment by Goule** [comment]
@mocman I'm also interested if you find a way :)

**Comment by mocman** [comment]
It wasn’t a perfect solution, but I found if you disconnect the camera stream then quickly reconnect a file stream, which worked fine on most streaming services.

Facebook didn’t seem to like it though and would end the stream immediately.

Other than that I had no luck.

**Comment by abubaqr70** [comment]
@mocman  @Sachinyadav6500 @Goule  do you guys know is there a way to append the file from the documents directory or by the gallery of the user phone i'm stuck over here and no support so far..!
