### ISSUE TITLE
Notifications / Multi-tasking break stream.

### ISSUE THREAD

**Issue by bijanmmarkes** [shogo4405/HaishinKit.swift#525]
**Describe the bug**
I created an RTMP stream, but if I get a notification from an app like Snapchat the stream breaks and network outgoing goes to 0KB/s. Any fixes for this? is this a known bug? or am I just forgetting something? It seems if anything interrupts the app at all the stream breaks and doesn't recover. are there any event handlers or callbacks built into this API that I could use?

**To Reproduce**
1. Start an RTMP stream
2. Notification from other app or message comes in
3. Stream breaks and no longer streams or recovers

**Expected behavior**
Notifications, and other phone behaviors shouldn't kill the video stream although it does.

**Comment by BenKatanHighLander** [comment]
still happens to you?

**Comment by mkrn** [comment]
@bijanmmarkes  So If you're leaving the app (switching to another app) then the streaming and recording will not work during that time. 

Here's how we handle the app moving to background:
```
func setupBackgroundHandler() {
    NotificationCenter.default.addObserver(self,
                                           selector: #selector(appMovingToBackground),
                                           name: UIApplication.didEnterBackgroundNotification,
                                           object: nil)
    NotificationCenter.default.addObserver(self,
                                           selector: #selector(appMovingToForeground),
                                           name: UIApplication.willEnterForegroundNotification,
                                           object: nil)
  }

@objc func appMovingToBackground() {
  rtmpStream.pause()
  rtmpStream.mixer.recorder.stopRunning()
}

func resumeStreaming() { 
    rtmpStream.resume()
    rtmpStream.mixer.recorder.startRunning()
}
```
