### ISSUE TITLE
about videoSettings

### ISSUE THREAD

**Issue by Hytper** [shogo4405/HaishinKit.swift#530]
I ran the example but I changed the settings as follows:
rtmpStream.captureSettings = [
            "sessionPreset": AVCaptureSession.Preset.hd1920x1080.rawValue,
            "continuousAutofocus": true,
            "continuousExposure": true
        ]
        rtmpStream.videoSettings = [
            "width": 1920,
            "height": 1080
        ]
FPS is always 0 during the push process.

**Comment by DaniArnaout** [comment]
@Hytper 
You have to set your profile level to "High" for it to work.

rtmpStream.videoSettings = [
"width": 1920,
"height": 1080,
"profileLevel": kVTProfileLevel_H264_High_AutoLevel
]
