### ISSUE TITLE
'withUnsafeBytes' is deprecated: use `withUnsafeBytes<R>(_: (UnsafeRawBufferPointer) throws -> R) rethrows -> R` instead

### ISSUE THREAD

**Issue by shogo4405** [shogo4405/HaishinKit.swift#531]
**Describe the bug**
Swift 5.0 deprecated: 'withUnsafeBytes' is deprecated: use `withUnsafeBytes<R>(_: (UnsafeRawBufferPointer) throws -> R) rethrows -> R` instead

**Screenshots**

<img width="330" alt="スクリーンショット 2019-05-01 4 19 15" src="https://user-images.githubusercontent.com/810189/56987427-5417fc00-6bc8-11e9-80bd-4c3b0250eed8.png">

**Comment by valvoline** [comment]
Depending on what you're doing, you could easily convert your code in something like that:
```
_ = d.withUnsafeBytes({ (ptr: UnsafeRawBufferPointer) -> Void in
	print(ptr.baseAddress) 
})
```

*ptr.baseAddress* is probably what you want as it should be the corresponding value for old ```UnsafePointer<UInt8>```
