### ISSUE TITLE
AttachStream to multiple instance of GLHKView 

### ISSUE THREAD

**Issue by Goule** [shogo4405/HaishinKit.swift#534]
Hello,

I'm trying to attach a stream's preview to 2 différents GLHKView, but I can't find how to do it.
It is possible ? 

Use case : the root screen which contains the mini preview, and a second detail screen with a full screen preview (displayed on tap on the first mini preview).

Thanks for your work

**Comment by floriangbh** [comment]
I have the same issue here. Seems to be a duplicate of https://github.com/shogo4405/HaishinKit.swift/issues/503
