### ISSUE TITLE
Back camera making lag, where as front camera is ok.

### ISSUE THREAD

**Issue by uttam-iu** [shogo4405/HaishinKit.swift#536]

**Comment by MikeDonahue** [comment]
It seems to have something to do with the video stabilization, possibly after the latest iOS update. Try setting your `preferredVideoStabilizationMode` to either `.off`, `.standard`.

`
rtmpStream.captureSettings["preferredVideoStabilizationMode"] = AVCaptureVideoStabilizationMode.off.rawValue
`

 or

`
rtmpStream.captureSettings["preferredVideoStabilizationMode"] = AVCaptureVideoStabilizationMode.standard.rawValue
`

**Comment by uttam-iu** [comment]
@MikeDonahue 
thanks, now it works fine..

**Comment by MikeDonahue** [comment]
I'm not sure if there is something that can be done besides this. It seems odd that the video stabilization causes such a large delay in the camera feed all of a sudden.

**Comment by about-prog** [comment]
I have the same problem.
Here it is how it looks with example app: https://vimeo.com/338505111
But I did use version 0.8.6 before and it was perfect: the video was stabilized and there wasn't delay. Also, the iphone camera app doesn't have a delay and have stabilization.

**Comment by KingJammin** [comment]
We just started seeing this problem with version 0.11.1 as well.
