### ISSUE TITLE
Visual effect and front camera mirror

### ISSUE THREAD

**Issue by Goule** [shogo4405/HaishinKit.swift#538]
**Describe the bug**
The front camera visual effect are reversed. I don't know if it's a bug or voluntary. If it's not how to delete this behavior ?

**To Reproduce**
1. Add visual effect on when you are on the back camera 
2. Switch from the back camera to the front camera 
3. See the visual effect which are reversed 

**Expected behavior**
Do not reverse the visual effect. 

**Screenshot**
![IMG_0732](https://user-images.githubusercontent.com/21126201/57930254-c3bf0400-78b5-11e9-9568-d57684932dbd.PNG)
![IMG_0733](https://user-images.githubusercontent.com/21126201/57930255-c3bf0400-78b5-11e9-9f34-58d741df6346.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: 12.3

**Comment by floriangbh** [comment]
You can use https://developer.apple.com/documentation/uikit/uiimage/2113668-withhorizontallyflippedorientati to reverse yourself the image (before convert to CIImage)

**Comment by Goule** [comment]
In fact, the problem is only on the preview (in the GLHKView), but not on the stream. So, if i flip myself the image, it will be flipped on the stream. I think it's a bug, the preview doesn't reflect what is send on the stream :-)

**Comment by ivai96** [comment]
Why is this closed? What is the solution?
