### ISSUE TITLE
MacOS screen capture is awful quality

### ISSUE THREAD

**Issue by drag0s** [shogo4405/HaishinKit.swift#541]
**Describe the bug**
I tried the [MacOS example](https://github.com/shogo4405/HaishinKit.swift/tree/master/Examples/macOS) but changing the camera by the the screen capture.

I replaced this line:

`rtmpStream.attachCamera(DeviceUtil.device(withLocalizedName: cameraPopUpButton.titleOfSelectedItem!, mediaType: .video))`

by this line:

`rtmpStream.attachScreen(AVCaptureScreenInput(displayID: CGMainDisplayID()))`

But the results are super pixelated and low quality. I tried with different captureSettings, videoSettings or recorderSettings including but didn't looked like was impacting at all.

Example of captured video:

![image](https://user-images.githubusercontent.com/16242963/58337213-95a56b00-7e45-11e9-9d4d-d641eb0eb15f.png)

**To Reproduce**
Go to `Examples/macOS/MainViewController.swift`

Replace the line 
`rtmpStream.attachCamera(DeviceUtil.device(withLocalizedName: cameraPopUpButton.titleOfSelectedItem!, mediaType: .video))`

by 

`rtmpStream.attachScreen(AVCaptureScreenInput(displayID: CGMainDisplayID()))`

Execute and try the results

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.4

Is this a bug or am I doing something wrong? If so, could someone provide a working example with screen capture?

Thanks!

**Comment by drag0s** [comment]
up

**Comment by quasivivo** [comment]
> But the results are super pixelated and low quality. I tried with different captureSettings, videoSettings or recorderSettings including but didn't looked like was impacting at all.

@drag0s Did you manage to resolve this issue?  I just ran into the same thing.

**Comment by dungkv-1044** [comment]
@drag0s i try to replace attachCamera to attachScreen but it's not working, black screen is displayed. Can u show me how to use attachScreen? 
many thanks.
