### ISSUE TITLE
Will you accept a PR decoupling NetStream & RTMPStream?

### ISSUE THREAD

**Issue by surajbarkale** [shogo4405/HaishinKit.swift#544]
We are trying to use HaishinKit in a project that already has a complex capture pipeline. We would like to use HaishinKit only for RTMP transport. However, since `RTMPStream` derives from `NetStream`, it is closed coupled with the capture pipeline.

**Describe the solution you'd like**
We would like to refactor `RTMPStream` and move all network activity in a new class `RTMPNetStream`. So the existing library API is unaffected and we can directly use `RTMPNetStream` in our code.

**Describe alternatives you've considered**
We do not want to maintain a fork with this refactoring in place. So I am asking if this kind of contribution is acceptable.

**Comment by shogo4405** [comment]
@surajbarkale 
Maybe No...
