### ISSUE TITLE
ReplayKitで端末スクリーン録画の時の縦横確認

### ISSUE THREAD

**Issue by likitabeena** [shogo4405/HaishinKit.swift#546]
こんにちは

BroadcastUploadExtensionで端末の画面を録画してライブ配信する時、縦形式の画面を録画してます。
Orientationを変えて横形式の画面を録画したいなら可能なのでしょうか？

ご教授いただければ幸いです！！

よろしくお願い致します！

**Comment by shogo4405** [comment]
こんにちは。はい、#481 にあるカスタムエフェクトを作成することで可能ですよ。
