### ISSUE TITLE
'shared' is unavailable: Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by springware** [shogo4405/HaishinKit.swift#548]
I am now trying to build version 0.11.1.
But I have faced some erros in Examples/iOS/LiveViewController.swift.
They are 

'shared' is unavailable: Use view controller based solutions where appropriate instead.  
Use of unresolved identifier 'Preference'
Use of unresolved identifier 'MonochromeEffect'
Use of unresolved identifier 'PronamaEffect'

That's all.
App Extension "Allow app extension API only" is already checked.
Can you help me?

**Comment by springware** [comment]
I am using Macos10.14/ Xcode10.2

**Comment by shogo4405** [comment]
> App Extension "Allow app extension API only" is already checked.

App Extension project can't use UIApplication.shared in the first place.
