### ISSUE TITLE
Multistreaming on all facebook pages together.

### ISSUE THREAD

**Issue by aarti1khajuria** [shogo4405/HaishinKit.swift#549]
Hi, what is a good way to implement multistreaming with Haishinkit. Created RTMP connection and stream but RTMP settings only 1 time for 5 facebook pages. it's only going live in 3 pages, not another one. What is the error?

  ["code": Optional("NetStream.Unpublish.InternalKill"), "description": Optional("Stop publishing stream.")]
NetStream.Unpublish.InternalKill
  ["description": Optional("Stream is now unpublished"), "level": Optional("status"), "code": Optional("NetStream.Unpublish.InternalKill"), "clientid": Optional("ASAICiss")]
NetStream.Unpublish.InternalKill
  ["code": Optional("NetConnection.Connect.Closed"), "description": Optional(""), "level": Optional("status")]
NetConnection.Connect.Closed

I am getting this for remaining 2 streams. Its publishing then it status coming like that.

**Comment by shogo4405** [comment]
I'm not sure. Please ask Facebook for Developers.
