### ISSUE TITLE
Please make NetStreamDrawable public

### ISSUE THREAD

**Issue by espresso3389** [shogo4405/HaishinKit.swift#551]
**Is your feature request related to a problem? Please describe.**

I'm now planning to implement Flutter plugin that uses HaishinKit.
The problem there is that HaishinKit only support direct rendering to UIView or such.

Flutter requires the image should be passed via it's own [FlutterTexture protocol](https://api.flutter.dev/objcdoc/Protocols/FlutterTexture.html); so I want to implement a class that implements both of NetStreamDrawable and FlutterTexture.

How do you think about making NetStreamDrawable public?
Or are there any other way to accomplish it?

**Comment by shogo4405** [comment]
> How do you think about making NetStreamDrawable public?

No problem. Please send this projects, Pull Request :)
