### ISSUE TITLE
Streamed live by front camera is mirrored on iOS

### ISSUE THREAD

**Issue by chengsam** [shogo4405/HaishinKit.swift#553]
**Describe the bug**
I use an iPhone to start streaming by front camera through RTMP, and watch it in browser, the video is mirrored/flipped.

**To Reproduce**
1. Start a stream on iOS
2. Watch it in browser

**Expected behavior**
The watched stream is exactly the same as the preview, do not mirror/flip the video, or provide an option to set mirror or not

**Smartphone (please complete the following information):**
 - Device: iPhone 6 Plus
 - OS: iOS 12.3.1
 - Browser: Safari
 - Version: 12.1

**Comment by chengsam** [comment]
No one is facing this issue?

**Comment by khawar-usman** [comment]
I'm facing it.

**Comment by floriangbh** [comment]
Same issue here !

**Comment by muaku** [comment]
I am facing this issue, any solution to fix it?
