### ISSUE TITLE
Hardware Encoding for iOS (H.264)

### ISSUE THREAD

**Issue by nwparker** [shogo4405/HaishinKit.swift#554]
According to [this](https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/Codec/H264Encoder.swift#L19) comment in code, hardware encoding is only supported in macOS. Are there plans to enable hardware encoding for iOS? Looking at a different library ([LFLiveKit](https://github.com/LaiFengiOS/LFLiveKit)), they claim to do iOS hardware encoding, so it should be feasible to do it here as well.

As a side-comment, do you think it's reasonable to change the README for the repository to be more explicit when it states:
> " Hardware acceleration for H264 video encoding, AAC audio encoding"

Instead it would be more accurate to state:
> " Hardware acceleration for H264 video encoding (macOS only), AAC audio encoding"

**Comment by shogo4405** [comment]
This means you can select Software Encoding or Hardware Encoding for macOS 
https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/Codec/H264Encoder.swift#L19

Don’t worry.  HaishinKit supports hardware encoding for iOS.  But can’t support software encoding.
