### ISSUE TITLE
Reconnection after temporary network loss not fast enough

### ISSUE THREAD

**Issue by mkrn** [shogo4405/HaishinKit.swift#555]
**Describe the bug**

We live stream weddings and it happened a few times that if the network would temporarily go down and the program could not re-establish the connection. This is the code of how we're approaching reconnection:

1) Periodical check to see if FPS = 0 initiate reconnection:

```
@objc func periodicalTasksLaunch() {
   curFps = Int(rtmpStream.currentFPS)
   if (curFps == 0) {
      fpsZeroDuration += 1
    } else {
      fpsZeroDuration = 0
    }
    if (fpsZeroDuration > 5) {
      rtmpConnection.close()
      rtmpConnection.connect(Constants.broadcastingUrl)
      self.reconnecting = "Connecting..."
      fpsZeroDuration = 0
    }
```

2) Reachability after the network was unreachable:
```
  lazy var reachability: Reachability? = {
    let reach = Reachability()
    
    reach?.whenReachable = { reachability in
      DispatchQueue.main.async {
        if self.wasUnreachable {
          self.rtmpConnection.close()
          self.rtmpConnection.connect(Constants.broadcastingUrl)
          self.wasUnreachable = false
        }
      }
    }
    
    reach?.whenUnreachable = {
      reachability in
      self.wasUnreachable = true
    }
    return reach
  }()
  ```

3) Automatic reconnection handler:
```
  @objc func rtmpStatusHandler(_ notification: Notification) {
    let e = Event.from(notification)
    guard
      let data: ASObject = e.data as? ASObject,
      let code: String = data["code"] as? String
      else { return }
    
    switch code {
    case RTMPConnection.Code.connectClosed.rawValue,
         RTMPConnection.Code.connectFailed.rawValue:
      
      //  rtmpStream.pause() ?
      rtmpConnection.close()
      rtmpConnection.connect(Constants.broadcastingUrl)
      self.reconnecting = "Connecting..."
      break
    
    case RTMPConnection.Code.connectSuccess.rawValue:
      rtmpStream.publish(streamAll.streamKey, type: .localRecord)
      self.reconnecting = "Starting Stream..."
      break
      
    case "NetStream.Publish.Start":
      self.reconnecting = "LIVE NOW"
      break;
      
    default:
      
      break
    }
  }
```

**To Reproduce**
1. After network 4g/wifi goes down temporarily it may be impossible to re-establish the connection. Hard to reproduce 

**Expected behavior**
Expected to be able to reconnect ASAP.

**Screenshots**

**Desktop (please complete the following information):**
- MacOS
- Xcode 10.2.1

**Smartphone (please complete the following information):**
- iPhone 8 plus
- iOS 12.3

**Additional context**

**Comment by mkrn** [comment]
So I've been debugging and now I believe that this happens because socket fails to connect when inputQueue is busy?
https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/RTMP/RTMPSocket.swift#L90-L91

And then it fails to close when outputQueue is busy 
https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/Net/NetSocket.swift#L101-L102

As in the execution never steps into the async block at times after the network disappears. 

@shogo4405  Any suggestions? I would really appreciate a hint. Learning swift on the go)

**Comment by mkrn** [comment]
For anyone interested I've also implemented a listener for IO_ERROR event (this happens when socket doesn't connect on timeout) 

```
rtmpConnection.addEventListener(Event.IO_ERROR, selector: #selector(ioErrorHandler), observer: self)

@objc func ioErrorHandler(_ notification: Notification) {
    rtmpConnection.connect(Constants.broadcastingUrl)
 }
```

**Comment by dawidvdh** [comment]
@mkrn super useful information, Experiencing the same issue just haven't had a chance to attempt to debug it myself. will post findings here when I get around to it.

**Comment by mkrn** [comment]
@dawidvdh my idea is to investigate how to stop output process so the socket could close (to be able to reconnect) 
It may have to do with the algorithm that is dropping frames, but I'm not quite sure which one it is yet.

**Comment by mkrn** [comment]
So to reproduce I'm starting streaming on wifi and it starts instantly, then turning off wifi in iPhone's settings bar and then turning it on again and a stream takes about a minute to restart.

Reachability is calling rtmpConnection.connect as soon as it reconnects but socket has a hard time reconnecting.

**Comment by mkrn** [comment]
I think I figured it out mostly...
I've added qos to both of those async calls:
```
func close(isDisconnected: Bool) {
   outputQueue.async(qos: .userInitiated) { 
```

and I've added a check to avoid connecting multiple times (RTMPSocket.swift): 
```
 override func connect(withName: String, port: Int) {
        guard !connecting else { return }
        connecting = true
        inputQueue.async(qos: .userInitiated) {
```

This seemed to help to reconnect much faster.

Now there is still a situation when FPS go down to 0 and it's not detecting the disconnect for many seconds... 

I will open a PR with my changes soon

**Comment by dawidvdh** [comment]
@mkrn have you managed to make any more progress in this?

**Comment by mkrn** [comment]
Thanks @dawidvdh

**Comment by leo150** [comment]
Hey @mkrn. Do you experience fps drop after reconnection?
