### ISSUE TITLE
720p+ resolutions do not publish

### ISSUE THREAD

**Issue by nwparker** [shogo4405/HaishinKit.swift#557]
**Describe the bug**
Any resolution higher than 720x1280 does not publish correctly. I'm not sure what data is being sent, but the streaming service I am pushing to detects it as invalid. I tested a 1080p through other software to ensure my streaming service supports it and that had no issues.
Also, the reported FPS is 0.

**To Reproduce**
1. Start the Example IOS Project
2. Set the resolution in LiveViewController.swift to anything greater than 720x1080
ex:
```
        rtmpStream.videoSettings = [
            "width": 1920,
            "height": 1080,
        ]
```
3. Start the app and attempt to publish

**Expected behavior**
The FPS should be non-zero and the stream should publish

**Smartphone (please complete the following information):**
I tested two devices
 - Device: iPhone 6s
 - OS: 12.3.1

 - Device: iPhone Xs Max
 - OS: 12.2

**Additional Information**
I enabled `.localRecord` mode and file does get written locally when using 1080x1920 resolution. Strangely the resolution of this local file appears to only be 568x320.

I also tried setting `"sessionPreset": AVCaptureSession.Preset.hd1920x1080.rawValue,` but it doesn't appear to have an effect

----

Please let me know and I can also push a branch up for testing purposes.

**Comment by nwparker** [comment]
Also see #504 where a similar issues was mentioned. It seems no further investigation was done by the reporter at that time and it was closed.

**Comment by nwparker** [comment]
@shogo4405 -- do you have any insight here?

Please let me know if I can help in any way!

**Comment by DaniArnaout** [comment]
Solution: You have to set your profile level to "High" for it to work.

rtmpStream.videoSettings = [
"width": 1920,
"height": 1080,
"profileLevel": kVTProfileLevel_H264_High_AutoLevel
]

**Comment by nwparker** [comment]
> Solution: You have to set your profile level to "High" for it to work.
> 
> rtmpStream.videoSettings = [
> "width": 1920,
> "height": 1080,
> "profileLevel": kVTProfileLevel_H264_High_AutoLevel
> ]

Thanks! That worked!!
