### ISSUE TITLE
Is it possible to implement stereo channel for audio? If possible how i can implement this?

### ISSUE THREAD

**Issue by uttam-iu** [shogo4405/HaishinKit.swift#558]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shogo4405** [comment]
> Is it possible to implement stereo channel for audio?
Yes.

**Comment by shogo4405** [comment]
> Is it possible to implement stereo channel for audio?
Yes. But iPhone's Built-In microphone is mono.

**Comment by uttam-iu** [comment]
how can i implement this? any demo code?

**Comment by shogo4405** [comment]
Already support stereo channel for audio. No need to implement.
Please buy external microphone. Ex. https://www.zoom.co.jp/ja/products/handy-recorder/iq6-xy-stereo-microphone-ios

**Comment by uttam-iu** [comment]
Thank you @shogo4405 , I already bought an external microphone. but i need how i use that part
Like this,
rtmpStream.audioSettings["sampleRate"] = 44100
rtmpStream.audioSettings["muted"] = false.

and whats for stereo or mono?

**Comment by shogo4405** [comment]
Well. No needs settings. Can you give me more details?

**Comment by uttam-iu** [comment]
yes. i can.

i need menu ui for live stream app through your  rtmp library. and update it when headphone connect or not. if not connect headphone then in ui shows only mono channel. but when headphone connects then shows mono and stereo channel with radio button and user can select mono r stereo and audio channel sets by selection. thats why i need the use case of stereo and mono channel. Thanks @shogo4405

**Comment by leo150** [comment]
@uttam-iu you can check [this](https://stackoverflow.com/a/44204378/1136218) answer to implement switching between the microphones. `HaishinKit` will handle changes in `AVAudioSession` automatically.
