### ISSUE TITLE
Video is no longer being recorded locally

### ISSUE THREAD

**Issue by khawar-usman** [shogo4405/HaishinKit.swift#559]
**Describe the bug**
If I choose .localRecord type while publishing, its no longer saving it locally in document directory, it was previously working before iOS update.

**To Reproduce**
1. Choose .localRecord publish type
2. Writer doesn't save video in local directory

**Expected behavior**
It should save video in document directory

**Smartphone:**
 - Device: iPhone X
 - OS: iOS 12.3.1

**Comment by khawar-usman** [comment]
I figured out the reason behind is that the very long token/streamName string I used to publish my stream, the code is setup like to use streamName/token as video filename while saving. iOS doesn't support much longer string name for saving video file.

**Comment by shogo4405** [comment]
@khawar-usman Thanks. PR. I accepted your PR. And will close this issue.
