### ISSUE TITLE
Adaptive bitrate streaming issue

### ISSUE THREAD

**Issue by raychongtk** [shogo4405/HaishinKit.swift#562]
I have implemented the RTMPStreamDelegate in my project but I cannot see the adaptive bitrate working well in my project. I just saw the FPS is changed but the bitrate does not change. 

Remark: My server is hosted in my own desktop and I accessed my server via the internal network.

I have written the delegate methods in the project:

> didPublishInsufficientBW
> didPublishSufficientBW 

https://github.com/shogo4405/HaishinKit.swift/pull/556

Also, passed my delegate class to RtmpStream:
```
rtmpStream = RTMPStream(connection: rtmpConnection)
rtmpStream.delegate = MyRTMPStreamDelegate()
```

Am I doing wrong?

**Comment by about-prog** [comment]
Same problem.
Implemented adaptive bitrate, but only FPS is changed. Wowza server

**Comment by raychongtk** [comment]
My project is running on Nginx with RTMP module
Is this feature only work on internet environment?
Could I simulate this feature in intranet environment? if so, how can I simulate it?

**Comment by raychongtk** [comment]
> Same problem.
> Implemented adaptive bitrate, but only FPS is changed. Wowza server

I found `rtmpStream.delegate = MyRTMPStreamDelegate()` shows this warning:
> Instance will be immediately deallocated because property 'delegate' is 'weak'

Are you get the same warning?

**Comment by about-prog** [comment]
raychongtk, yes.
Solved this with declaring a global variable to store MyRTMPStreamDelegate and later assigned it to rtmpStream.delegate. But still, there is a problem.

**Comment by raychongtk** [comment]
I solved it with implementing the delegate class into viewcontroller class

And calling rtmpStream.delegate = self
