### ISSUE TITLE
HLS stream always  disconnect after 30s

### ISSUE THREAD

**Issue by hieulike** [shogo4405/HaishinKit.swift#567]
**Describe the bug**
HLS stream always disconnect after 30s

**To Reproduce**
1. I using ReplayKit + HLS to live broadcast screen 
2. After 30s, the streaming has interrupt about 3-4s and its live comeback.

**Desktop (please complete the following information):**
 - OS: iOS 12

**Smartphone (please complete the following information):**
 - Device: [iPhone6]
 - OS: [12]

**Comment by leo150** [comment]
Do you reproduce the issue in the sample project?

**Comment by hieulike** [comment]
` var httpStream: HTTPStream = HTTPStream()
    var httpService: HLSService = HLSService(domain: "",
                                             type: "_http._tcp",
                                             name: "HaishinKit",
                                             port: HTTPService.defaultPort)
    
    var videoPlayer: VideoPlayer?
    var playTimer: Timer?
    
    override func broadcastStarted(withSetupInfo setupInfo: [String: NSObject]?) {
        isRecording = false
        httpStream.publish("hello", isRecording: true)
        httpStream.videoSettings = [
            "width": 1920,
            "height": 1080,
            "bitrate": 4e6,
            "profileLevel": kVTProfileLevel_H264_Baseline_AutoLevel,
            "maxKeyFrameIntervalDuration": 2,
            "scalingMode": kVTScalingMode_Letterbox
        ]

        httpService.startRunning()
        httpService.addHTTPStream(httpStream)
        
        let notificationName = CFNotificationName("com.notification.broadcast.started" as CFString)
        let notificationCenter = CFNotificationCenterGetDarwinNotifyCenter()
        CFNotificationCenterPostNotification(notificationCenter, notificationName, nil, nil, false)
        
        guard let id = UserDefaults.init(suiteName: appGroupID)?.string(forKey: selectedServiceID) else {
            return
        }

        Service.getById(id, completionHandler: { (service, _) in
            if let service = service {
                self.videoPlayer = service.createVideoPlayer(self.appName)
                if let videoPlayer = self.videoPlayer, let url = URL(string: "http://\(self.getWiFiAddress() ?? "0.0.0.0"):\(HTTPService.defaultPort)/hello/playlist.m3u8") {
                    self.playTimer = Timer.scheduledTimer(withTimeInterval: 5, repeats: false, block: { (_ ) in
                        videoPlayer.playContent(url)
                    })
                }
            }
        })
    }

 override func processSampleBuffer(_ sampleBuffer: CMSampleBuffer, with sampleBufferType: RPSampleBufferType) {
        switch sampleBufferType {
        case RPSampleBufferType.video:
            self.httpStream.appendSampleBuffer(sampleBuffer, withType: .video)
            
            break
        case RPSampleBufferType.audioApp:
            self.httpStream.appendSampleBuffer(sampleBuffer, withType: .audio)
            break
        case RPSampleBufferType.audioMic:
   
            break
        @unknown default:
            break
        }
        
    }
    `

I implelment as README.MD but HLS not working with broadcast upload extension.
I need add short code as below 
` self.tsWriter.expectedMedias.insert(.video)
                self.tsWriter.expectedMedias.insert(.audio)`
  the HLS streaming become work, but affter 30s, HLS streaming has offline about 10s and active again. Please check it for me. Thanks.
`
open func publish(_ name: String?,isRecording: Bool = true) {
        lockQueue.async {
            if name == nil {
                self.name = name
                #if os(iOS)
                self.mixer.videoIO.screen?.stopRunning()
                #endif
                self.mixer.stopEncoding()
                self.tsWriter.stopRunning()
                if isRecording {
                    self.tsWriter.expectedMedias.remove(.video)
                    self.tsWriter.expectedMedias.remove(.audio)
                }
                return
            }
            self.name = name
            #if os(iOS)
            self.mixer.videoIO.screen?.startRunning()
            #endif
            self.mixer.startEncoding(delegate: self.tsWriter)
            self.mixer.startRunning()
            self.tsWriter.startRunning()
            if isRecording {
                self.tsWriter.expectedMedias.insert(.video)
                self.tsWriter.expectedMedias.insert(.audio)
            }
        }
    }

`

**Comment by leo150** [comment]
Could you please format the code properly?

**Comment by c0r73x** [comment]
I have the same problem, but with 1080p streams using rtmp. 720p and lower works fine but 1080p disconnects. I've tried a lot of different profiles, bitrates etc. but nothing helps.

**Comment by dvt282** [comment]
I also had the same problem with the HLS stream, it was paused after 25s since it started needing to reload the browser to continue watching. Has anyone encountered this problem. Please help me.
