### ISSUE TITLE
Video stuttering on Wowza passthrough

### ISSUE THREAD

**Issue by pmagnussen** [shogo4405/HaishinKit.swift#570]
I'm trying to use HaishinKit to stream audio/video to Wowza but there's a lot of stuttering on the video - however, only on the passthrough. As long as I use Wowza's transcoder there's no stuttering.

Any idea on why this might be?

**Comment by nwparker** [comment]
See #536 incase that helps

**Comment by pmagnussen** [comment]
Thanks. However, the compiler can't seem to find any `AVCaptureVideoStabilizationMode` on macOS - is there an equivalent?

**Comment by nwparker** [comment]
> Thanks. However, the compiler can't seem to find any `AVCaptureVideoStabilizationMode` on macOS - is there an equivalent?

Sorry, not that I'm aware of. Perhaps just keep trying tweaking things

**Comment by shogo4405** [comment]
@pmagnussen Can I see your rtmpStream.videoSettings. 
```rtmpStream.videoSettings = [
    "width": 640, // video output width
    "height": 360, // video output height
    "bitrate": 160 * 1024, // video output bitrate
    // "dataRateLimits": [160 * 1024 / 8, 1], optional kVTCompressionPropertyKey_DataRateLimits property
    "profileLevel": kVTProfileLevel_H264_Baseline_3_1, // H264 Profile require "import VideoToolbox"
    "maxKeyFrameIntervalDuration": 2, // key frame / sec
]
```

**Comment by pmagnussen** [comment]
Sure

`
rtmpStream.videoSettings = [
            "width": res.width, // video output width
            "height": res.height, // video output height
            "bitrate":  bitRate, // video output bitrate
            // "dataRateLimits": [160 * 1024 / 8, 1], optional kVTCompressionPropertyKey_DataRateLimits property
            "profileLevel": kVTProfileLevel_H264_High_AutoLevel, // H264 Profile require "import VideoToolbox"
            "maxKeyFrameIntervalDuration": frameRate * 2, // key frame / sec
        ]
        rtmpStream.captureSettings = [
            "fps": frameRate, // FPS
            "sessionPreset": AVCaptureSession.Preset.high.rawValue, // input video width/height
            "continuousAutofocus": true, // use camera autofocus mode
            "continuousExposure": true //  use camera exposure mode
        ]
`

`bitRate = Int(Double(res.width*res.height) * 4)  + 128000 // 128 for audio`

`var frameRate = 30`

**Comment by pmagnussen** [comment]
Sure. Just cleaned up the code a bit to make it more readable.

```
rtmpStream.videoSettings = [
            "width": res.width,
            "height": res.height,
            "bitrate":  bitRate,
            "profileLevel": kVTProfileLevel_H264_High_AutoLevel,
            "maxKeyFrameIntervalDuration": frameRate * 2,
        ]
```

`var frameRate = 30`
`var bitRate = Int(Double(res.width*res.height) * 4)  + 128000 // 128 for audio`

`res` is a `CMVideoDimensions` object.

**Comment by shogo4405** [comment]
1 . Maybe fix it this commit. https://github.com/shogo4405/HaishinKit.swift/pull/580/files
2. Please update 0.11.8 or profileLevel: kVTProfileLevel_H264_Baseline_AutoLevel

**Comment by pmagnussen** [comment]
It seems to have been fixed now. Thanks.
