### ISSUE TITLE
Is it possible to get outputVideo(_ buffer: CMSampleBuffer) while publishing?

### ISSUE THREAD

**Issue by RollingGoron** [shogo4405/HaishinKit.swift#575]
I want to be able to grab a frame while the video is actively publishing to the server. I see there is a delegate method but it doesn't seem to fire while I'm pushing the stream to the server.

**Comment by shogo4405** [comment]
You can use https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/Media/VideoEffect.swift
