### ISSUE TITLE
videodatarate and audiodatarate sent in @setDataFrame message is in bps, but should be in kbps

### ISSUE THREAD

**Issue by arazuvaev** [shogo4405/HaishinKit.swift#577]
**Describe the bug**
videodatarate and audiodatarate sent in @setDataFrame message is in bps, but should be in kbps

**To Reproduce**
1. Set bitrate to any value
2. Inspect the metadata when @setDataFrame message is sent to see what video data rate is being sent

**Expected behavior**
Video data rate should be set in kbps

http://download.macromedia.com/f4v/video_file_format_spec_v10_1.pdf
audiodatarate Number Audio bit rate in kilobits per second
videodatarate Number Video bit rate in kilobits per second

**Screenshots**
n/a

**Desktop (please complete the following information):**
iOS, but should be applicable to all platforms

**Smartphone (please complete the following information):**
Not device specific

**Additional context**
I'm open to creating a PR to fix this.
The reason this was found was that Microsoft Stream drops the connection if data rate is specified with a large value. It appears that other providers seem to ignore the value or handle it more gracefully.

**Comment by shogo4405** [comment]
@arazuvaev 
OK. I will accept your PR.

> I'm open to creating a PR to fix this.

I'm waiting your PR.

**Comment by leo150** [comment]
I can confirm this, Twitch and YouTube don't care about metadata. Mixer works only with corrected metadata:
```
if let videodatarate = meta["videodatarate"] as? UInt32 {
	meta["videodatarate"] = videodatarate / 1024
}

if let audiodatarate = meta["audiodatarate"] as? UInt32 {
	meta["audiodatarate"] = audiodatarate / 1024
}
```

**Comment by arazuvaev** [comment]
I'll prep one up, standby 🙂

**Comment by ArtiomShapovalov** [comment]
@leo150 Hi, I'm also interested in streaming to Mixer, but can't really find their rtmp url. Where can I get it?

And also what bugs me, should I divide kbps by 1024 (as you suggested) or by 1000?

**Comment by ArtiomShapovalov** [comment]
@leo150 I suspect it's an error. [Wiki stated it's 1000](https://en.wikipedia.org/wiki/Data-rate_units#Kilobit_per_second)

**Comment by allenlinli** [comment]
Opened a PR to solve this already https://github.com/shogo4405/HaishinKit.swift/pull/698
