### ISSUE TITLE
Variable maxKeyFrameIntervalDuration? Does it make sense?

### ISSUE THREAD

**Issue by mkrn** [shogo4405/HaishinKit.swift#579]
**Is your feature request related to a problem? Please describe.**
On slow connections using short maxKeyFrameIntervalDuration (like 2) means that sometimes the streaming fails to start (fps goes between 0 and 1 and then timeout with server). Is it possible that it's overwhelmed with keyframes and fails to send any?

**Describe the solution you'd like**
Any way to automate maxKeyFrameIntervalDuration based on connection speed? 

**Describe alternatives you've considered**
Long maxKeyFrameIntervalDuration (15) works better on slow connections but results in server waiting too long for a keyframe = longer delay before stream start.

Does it make sense to increase `maxKeyFrameIntervalDuration` in `didPublishInsufficientBW` ?   

**Additional context**
Starting bitrate is 3000, fps is 30, size is 720p.

**Comment by shogo4405** [comment]
> fps goes between 0 and 1 and then timeout with server

It seems that vtcompressionsession is down. 
Maybe fix it this commit. https://github.com/shogo4405/HaishinKit.swift/commit/df85999eb16c535fbc0bbc1e7c21b8bb9ba951b6
