### ISSUE TITLE
orientation mode problem

### ISSUE THREAD

**Issue by adamasantares** [shogo4405/HaishinKit.swift#588]
Sorry but I have no choice, I need to reopen this one https://github.com/shogo4405/HaishinKit.swift/issues/406

When we start streaming in portrait mode and then rotate an iPhone the video is freezing on the clients side. We have read a lot of closed issues but no one of them helped us.

We tested another stream app (we have no idea which encoder it uses) and we streamed to our server, it worked well.

Any idea? We looking for solution 4th day. Really need your help.

**Comment by leo150** [comment]
What device, OS version, streaming platform and rendering view type are you using?

I can reproduce an issue in the sample app when video size doesn't change on rotation. However, it doesn't freeze the video and changing `videoSettings` on `orientationDidChangeNotification` notification updates video size correctly. 

Did you reproduce the issue in the sample app?

**Comment by adamasantares** [comment]
@leo150 

I'm sorry, I got some pause with that problem and worked with another tasks some time...so

> What device, OS version, streaming platform and rendering view type are you using?

I use xCode 10.2 and Swift 5, iPhone SE, iOS 12, streaming platform is nginx-rtmp, rendering view type ... (not sure what do you mean about that).

When I stream to nginx-rtmp by Larix encoder (demo app) it works well on client side. But when I stream by HaishinKit and during the streaming I rotate a phone, all clients get freezing of video.

There is a video: https://drive.google.com/file/d/1Fbr42h0nXScnGTPzOIdgbm0qh6Obw3ZP/view?usp=sharing
