### ISSUE TITLE
Exception on AudioConverterNewSpecific

### ISSUE THREAD

**Issue by leo150** [shogo4405/HaishinKit.swift#589]
**Description**

This is a report about #296 which can be reproduced in the sample iOS app. Exception raises on following line in `AudioConverter.swift:235`. However, it doesn't crash the app. Moreover, sound works as well. 
```swift
status = AudioConverterNewSpecific(
     &inSourceFormat!,
     &inDestinationFormat,
     UInt32(inClassDescriptions.count),
     &inClassDescriptions,
     &_converter
)
```

My setup is iPhone 7+ with iOS 12.4. I only changed stream url and key to Twitch. This is a C++ exception and I receive it every time I start a stream in the app. Here is a C++ breakpoint that catches the exception:

<img width="608" alt="Screen Shot 2019-09-03 at 3 43 11 PM" src="https://user-images.githubusercontent.com/3484524/64213405-b8dab000-ce61-11e9-85ea-ca1e99efafea.png">

Stacktrace of the exception:

<img width="494" alt="Screen Shot 2019-09-03 at 3 42 21 PM" src="https://user-images.githubusercontent.com/3484524/64213428-d0199d80-ce61-11e9-99b2-fd88f6f33851.png">

**To Reproduce**
1. Setup C++ exception breakpoint
2. Click on publics
3. `AudioConverterNewSpecific` raises the exception

**Smartphone (please complete the following information):**
 - Device: iPhone 7+
 - OS: iOS 12.4
 - Version 0.11.8

**Comment by leo150** [comment]
Close, as it's not related to the crash itself

**Comment by floriangbh** [comment]
Hello @leo150 , 
I have the same crash when I setup a C++ exception breakpoint ! Did you find the root cause ? 
Thanks

**Comment by leo150** [comment]
Is rather an exception than a crash. It looks like this is a normal behavior, as `status` is checked later. You can auto-enable C++ breakpoint after some other breakpoint is triggered when `return _converter!` is passed.
