### ISSUE TITLE
Crash after updating to 0.11.6

### ISSUE THREAD

**Issue by MrDongjuKim** [shogo4405/HaishinKit.swift#591]
**Describe the bug**

it crashed after I updated to 0.11.6, on 'rtmpConnection.connect(url)'
After a couple of tries, I found it happened after commit 'fb26b0191aa83bab65ac1d06d85eb3be7caab087'

I didn't have enough time to find the exact reason why it happens.

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS 12.4.1

**Comment by floriangbh** [comment]
I had the same issue, but this is fixed with the v0.11.8. 
Did you try the v0.11.8 ?

**Comment by MrDongjuKim** [comment]
> I had the same issue, but this is fixed with the v0.11.8.
> Did you try the v0.11.8 ?

Yes, I did. And It still happens.

**Comment by shogo4405** [comment]
I think  fixed 1.0.0.
