### ISSUE TITLE
[Error] [com.haishinkit.HaishinKit] [RTMPMessage.swift:319] payload > AMF0Serializer{data: 14 bytes,position: 14,reference: HaishinKit.AMFReference}

### ISSUE THREAD

**Issue by krantonio** [shogo4405/HaishinKit.swift#593]
I'm having this error on using this API,

I've created a test server that works with OBS:

when i used it on my app i got the error log.

        let rtmpConnection = RTMPConnection()
        let rtmpStream = RTMPStream(connection: rtmpConnection)
        rtmpStream.attachScreen(ScreenCaptureSession(shared: UIApplication.shared))

        let lfView = HKView(frame: view.bounds )
        lfView.videoGravity = AVLayerVideoGravity.resizeAspectFill
        lfView.attachStream(rtmpStream)
        view.addSubview(lfView)

        rtmpConnection.connect("rtmp://192.168.1.2:1935/live")
        rtmpStream.publish("hello")

any idea what the error message means? I encounter same error on the example ios app

[Error] [com.haishinkit.HaishinKit] [RTMPMessage.swift:319] payload > AMF0Serializer{data: 14 bytes,position: 14,reference: HaishinKit.AMFReference}

**Comment by leo150** [comment]
You need to publish only after successful connection event. As in the sample project.
