### ISSUE TITLE
Apple Low-Latency HLS support

### ISSUE THREAD

**Issue by thachonline** [shogo4405/HaishinKit.swift#602]
Currently with HLS server, there is always a delay of 10-15 seconds on iOS.
Support LHLS (Low-latency HLS) can be applied to
  HTTPService
  HLS Publish
Is there any solution?
[Apple LHLS](https://developer.apple.com/documentation/http_live_streaming/protocol_extension_for_low-latency_hls_preliminary_specification)

**Comment by thachonline** [comment]
Is this tool helpful?
[HLS Low Latency Beta Tool](https://developer.apple.com/download/more/?=hls)

**Comment by shogo4405** [comment]
I have no plans to change HLS server for low latency.
