### ISSUE TITLE
stream name change to "videoName" if the stream name is too long.

### ISSUE THREAD

**Issue by AugustAtSeattle** [shogo4405/HaishinKit.swift#603]
This is a bug in https://github.com/shogo4405/HaishinKit.swift/pull/560 .
I need a long stream name with a lot of parameters and I don't save filename on device.

**Comment by AugustAtSeattle** [comment]
It works well before this #560 commit. After this commit I always receive a fixed stream name "videoName".

**Comment by leo150** [comment]
Feel free to open a PR to expose `fileNameValid` property.

**Comment by Anveena** [comment]
it's ez to take md5 value of stream name to save videos.

**Comment by shogo4405** [comment]
https://github.com/shogo4405/HaishinKit.swift/pull/691
