### ISSUE TITLE
v1.0.0 broke HD stream 

### ISSUE THREAD

**Issue by floriangbh** [shogo4405/HaishinKit.swift#605]
Hello, 

**Describe the bug**
Since the v1.0.0 and the type-safed settings I'm not unable to stream in HD on Facebook. 

From the 0.11.9 to the v.1.0 I'v just updated settings (https://github.com/shogo4405/HaishinKit.swift/wiki/Moving-from-0.11.x-APIs-to-1.0.0#type-safed-settings) and events (https://github.com/shogo4405/HaishinKit.swift/wiki/Moving-from-0.11.x-APIs-to-1.0.0#type-safed-event).

**To Reproduce**

Maybe the type-safed settings broke the width and height settings ? 

Thanks

**Comment by shogo4405** [comment]
@floriangbh Thank u. Bug report. Can I see your code?

**Comment by floriangbh** [comment]
Hello @shogo4405, 

I just tried with your exemple (from the v1.0.0 source and from the 0.11.9) and there is the same problem. You can reproduce it with your project's exemple and a Facebook's rtmp/key [from facebook](https://easylive.io/en/support/knowledge-base/outputbroadcasters/publish-custom-rtmp-facebook-live/). 

This is weird because with the v1.0.0 the Facebook's monitoring is displaying 720*1280 for the resolution (but the stream look like 360p) but the replay is in 360p. Whereas with the v0.11.9 everything is ok...

**Comment by shogo4405** [comment]
I can't reproduce. Please more information.

**https://www.facebook.com/live/create**
<img width="913" alt="スクリーンショット 2019-10-14 19 14 16" src="https://user-images.githubusercontent.com/810189/66744485-7cb25a80-eeb7-11e9-8d0e-268e7f78cde0.png">

**Live Preview**
It seemes that work *自動 720p(Auto 720p)*.
<img width="492" alt="スクリーンショット 2019-10-14 19 16 39" src="https://user-images.githubusercontent.com/810189/66744559-c3a05000-eeb7-11e9-87ae-751fb279baff.png">

**Comment by floriangbh** [comment]
It's a screenshot from the replay or from the Facebook live monitoring ? 
Because in my case Facebook's monitoring is displaying 720*1280 but the replay isn't in true HD. With 720p the logo should be : 
<img width="52" alt="Screenshot 2019-10-14 at 12 28 41" src="https://user-images.githubusercontent.com/14054997/66745135-8370ab80-ee7e-11e9-97cb-caff37ec9453.png">

**Comment by floriangbh** [comment]
Hello @shogo4405,

I found the problem. In my app `captureSettings` height and width was initialyzed with CGSize, which have CGFloat type.

In the previous version there were no force cast, but since the 1.0.0 the width and height are casted into Int32 : https://github.com/shogo4405/HaishinKit.swift/blob/412e48c31428d150c00245ef09758f91a4b57e05/Platforms/iOS/VideoIOComponent%2BExtension.swift#L37
That's why all my stream was in 360p. 

So there is no issue ! 

Thanks for your help
