### ISSUE TITLE
Invalid timestamp warnings when playing video via ffplay/ ffmpeg

### ISSUE THREAD

**Issue by spllr** [shogo4405/HaishinKit.swift#607]
**Describe the bug**

Since version 1.0 I am experiencing issues with the video produced by the framework when playing the video back with ffplay/ ffmpeg.

Although the video still appears to play fine, closes inspection reveals `Invalid timestamp` warnings.

**To Reproduce**
1. Stream to a RTMP or SRT server where you have access to the produced video files.
2. Either play the video via ffplay (`ffplay path/to/my/video.flv`) or convert to a ts stream with ffmpeg (`ffmpeg -i path/to/my/video.flv -codec copy ./out.ts`)
3. Either one of the process should produce warnings along the lines of `Invalid timestamps stream=1, pts=75077, dts=78080, size=12704` (see screenshot)

**Expected behavior**
The video should be playable and/ or convertable without issues.

**Screenshots**

<img width="1092" alt="Invalid Timestamps" src="https://user-images.githubusercontent.com/131222/67215470-cfdd5d80-f421-11e9-987f-8ac115a8b0a3.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6, ffplay version 4.1.4

**Smartphone (please complete the following information):**
 - Device: iPhone 6+, iPhone 7
 - OS: iOS 12, iOS 13

**Additional context**
I am experiencing similar behaviour when streaming via SRT.

**Comment by animaonline** [comment]
Any updates?

**Comment by animaonline** [comment]
Adjusting the audio sample rate helped me solve this problem.

**Comment by spllr** [comment]
I will try adjusting the audio to see if this solves the issue. Did you make any specific changes or used specific settings?

**Comment by animaonline** [comment]
I'm using these settings

`self.rtmpStream.audioSettings[.muted] = false
            self.rtmpStream.audioSettings[.bitrate] = 32 * 1000
            self.rtmpStream.audioSettings[.sampleRate] = 44_000`

**Comment by Anveena** [comment]
i got sth of this trouble.
maybe the 'profileLevel' of videoSettings takes this error
kVTProfileLevel_H264_Main_xxx or
kVTProfileLevel_H264_High_xxx
is not working well

**Comment by spllr** [comment]
I changed the `profileLevel` to `kVTProfileLevel_H264_Baseline_5_2` which resolved the issue.

Thanks you @Anveena, @animaonline for the input.

FYI: I found [this page](http://blog.mediacoderhq.com/h264-profiles-and-levels/ "H.264 profiles and levels") by Stanley Huang helpful in understanding the different profiles.
