### ISSUE TITLE
Youtube live streaming doesn't work using HaishinKit in iOS 13

### ISSUE THREAD

**Issue by PavitramAppsmartz** [shogo4405/HaishinKit.swift#609]
I am facing issue while going live on youtube using HaishinKit in iOS 13 .But my code is working fine in iOS 12. I don't know what is wrong with it. I am using sample code provided in example project source code of HaishinKit.

Link for library is here :- https://github.com/shogo4405/HaishinKit.swift

**logs :-** 
[Warn] [com.haishinkit.HaishinKit] [SoundSpliter.swift:16] status > -12731

**CMSample Buffer in iOS 12**
CMSampleBuffer 0x101529fb0 retainCount: 8 allocator: 0x1fbf89430
	invalid = NO
	dataReady = NO
	makeDataReadyCallback = 0x0
	makeDataReadyRefcon = 0x0
	formatDescription = <CMAudioFormatDescription 0x282311d40 [0x1fbf89430]> {
	mediaType:'soun' 
	mediaSubType:'lpcm' 
	mediaSpecific: {
		ASBD: {
			mSampleRate: 44100.000000 
			mFormatID: 'lpcm' 
			mFormatFlags: 0xe 
			mBytesPerPacket: 2 
			mFramesPerPacket: 1 
			mBytesPerFrame: 2 
			mChannelsPerFrame: 1 
			mBitsPerChannel: 16 	} 
		cookie: {(null)} 
		ACL: {(null)}
		FormatList Array: {(null)} 
	} 
	extensions: {(null)}
}
	sbufToTrackReadiness = 0x0
	numSamples = 1024
	sampleTimingArray[1] = {
		{PTS = {3252839839028/1000000000 = 3252.840, rounded}, DTS = {INVALID}, duration = {1/44100 = 0.000}},
	}
	dataBuffer = 0x0

**CMSampleBuffer in iOS 13**

CMSampleBuffer 0x104e8a600 retainCount: 8 allocator: 0x1f54375e0
	invalid = NO
	dataReady = NO
	makeDataReadyCallback = 0x0
	makeDataReadyRefcon = 0x0
	formatDescription = <CMAudioFormatDescription 0x280d91540 [0x1f54375e0]> {
	mediaType:'soun' 
	mediaSubType:'lpcm' 
	mediaSpecific: {
		ASBD: {
			mSampleRate: 44100.000000 
			mFormatID: 'lpcm' 
			mFormatFlags: 0xe 
			mBytesPerPacket: 4 
			mFramesPerPacket: 1 
			mBytesPerFrame: 4 
			mChannelsPerFrame: 2 
			mBitsPerChannel: 16 	} 
		cookie: {(null)} 
		ACL: {(null)}
		FormatList Array: {
			Index: 0 
			ChannelLayoutTag: 0x650002 
			ASBD: {
			mSampleRate: 44100.000000 
			mFormatID: 'lpcm' 
			mFormatFlags: 0xe 
			mBytesPerPacket: 4 
			mFramesPerPacket: 1 
			mBytesPerFrame: 4 
			mChannelsPerFrame: 2 
			mBitsPerChannel: 16 	}} 
	} 
	extensions: {(null)}
}
	sbufToTrackReadiness = 0x0
	numSamples = 1024
	outputPTS = {66465077710011/1000000000 = 66465.078, rounded}(based on cachedOutputPresentationTimeStamp)
	sampleTimingArray[1] = {
		{PTS = {66465077710011/1000000000 = 66465.078, rounded}, DTS = {INVALID}, duration = {1/44100 = 0.000}},
	}
	dataBuffer = 0x0
**_Note_** Using default sound spliter settings

**Comment by shogo4405** [comment]
I know. I remove SoundSpliter. Because I can't support ReplayKit :(

**Comment by arslanilyas** [comment]
@PavitramAppsmartz, did you find a fix for this?

**Comment by arslanilyas** [comment]
@shogo4405 I am working on an upnp app and I have to mirror my screen on TV. I am having the same issue. Is there any chance if you can help me out?
