### ISSUE TITLE
HLS example not working

### ISSUE THREAD

**Issue by dvt282** [shogo4405/HaishinKit.swift#611]
**Describe the bug**
When I run example on macOS with HLS. Stream not display with version 1.0.0

**To Reproduce**
1. Start macOS demo
2. Select HLS
3. Start publishing
4. Open url on safari/vlc

**Expected behavior**
Display stream from camera

**Screenshots**
https://gyazo.com/46b142bbe9aef2ea0aa4b43c331a7de9

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser safari
 - Version 1.0.0

**Comment by thachonline** [comment]
I have encountered the same situation here. HLS is stopped after 20-25 second

**Comment by quangphap208** [comment]
I have encountered the same situation here. HLS sample is not working.

**Comment by halil** [comment]
We have encountered the same situation here. HLS example is not working.

**Comment by quangphap208** [comment]
I run HLS sample with error: SocketStream write error [0x0]: 1 60. There is a solution
any?

**Comment by c-Punk** [comment]
Hello
Have implemented the HLS Code in my own app.
Same problem as described above.
SocketStream write error [0x0]: 1 60

Info via curl :
$ curl http://172.16.17.11:8080/test/playlist.m3u8
curl: (52) Empty reply from server
$ curl http://172.16.17.11:8080/test/playlist.m3u8
curl: (52) Empty reply from server
$ curl http://172.16.17.11:8080/test/playlist.m3u8
curl: (52) Empty reply from server
$ curl http://172.16.17.11:8080/test/playlist.m3u8
#EXTM3U
#EXT-X-VERSION: 3
#EXT-X-MEDIA-SEQUENCE: 0
#EXT-X-TARGETDURATION: 3
#EXTINF: 2.00533333333442,
44847.ts
#EXTINF: 2.00533333333442,
44849.ts
#EXTINF: 2.005333333327144,
44851.ts
#EXTINF: 2.00533333333442,
44853.ts
#EXTINF: 2.00533333333442,
44855.ts
#EXTINF: 2.00533333333442,
44857.ts
#EXTINF: 2.00533333333442,
44859.ts
$ curl http://172.16.17.11:8080/test/playlist.m3u8
curl: (52) Empty reply from server
$ curl http://172.16.17.11:8080/test/playlist.m3u8
curl: (52) Empty reply from server
$ curl http://172.16.17.11:8080/test/playlist.m3u8
curl: (52) Empty reply from server
