### ISSUE TITLE
Local recording and background 

### ISSUE THREAD

**Issue by Goule** [shogo4405/HaishinKit.swift#612]
Hello ,

**Describe the bug**
When the stream is ON with local recording if the application pass in background the recording is broke without any error and the stream will never pass in any `DefaultAVRecorderDelegate` handler. 

**To Reproduce**
1. Start the steam
2. Go in background for 3 secondes 
3. Go back to the app
4. See the local recording which isn't present 

**Expected behavior**
Have an error callback or maintain the local recording. 

Thanks for your help !

**Comment by mkrn** [comment]
I believe this line is the issue https://github.com/mkrn/HaishinKit.swift/commit/b45f8e38d5ed403e2e71a85b5a2577d83a023394#diff-0d4d75ecbced79f01c21e954840e396bL270

**Comment by yuya-h-29** [comment]
@Goule @mkrn 
Sorry to interrupt the conversation...

I'm working on exactly the same thing now. I manually close the stream to trigger didFinishWriting, but it sometimes fails the local record...
How did you guys handle in `didEnterBackground` and `didBecomeActive` to maintain the local recording?

    @objc func didEnterBackground(_ notification: Notification) {
        rtmpStream.close()
    }
    
    @objc func didBecomeActive(_ notification: Notification) {
        rtmpStream.publish(streamKey, type: .localRecord)
    }


    override func didFinishWriting(_ recorder: AVRecorder) {
        guard let writer: AVAssetWriter = recorder.writer else { return }
        PHPhotoLibrary.shared().performChanges({() -> Void in
            PHAssetChangeRequest.creationRequestForAssetFromVideo(atFileURL: writer.outputURL)
        }, completionHandler: {saved, error -> Void in
            // do something
            do {
                try FileManager.default.removeItem(at: writer.outputURL)
            } catch {
                print("error in recorder delegate: \(error.localizedDescription)")
            }
        })
    }
