### ISSUE TITLE
Stream Not Sent

### ISSUE THREAD

**Issue by Ankush-Redapple** [shogo4405/HaishinKit.swift#615]
**Describe the bug**
I am trying to screen cast from broadcast extension to Twitch tv, installed the HaishinKit through cocapod. I have set endpoint URL as twitch provide rtmp://live.twitch.tv/app/{stream_key}. While run the code did not get any warning/ error, but steam not deliver to the twitch server. Could you please help?

> iOS 12.2

**Comment by Sayanta-Redapple** [comment]
I am also stuck in the same.

**Comment by Ankush-Redapple** [comment]
Stream name was wrong. Now works fine.

**Comment by iamvijay** [comment]
I am also facing the same issue, I am using twitch but stream is not delivered to twitch server. Could you help?
