### ISSUE TITLE
fps could not be changed even set 60

### ISSUE THREAD

**Issue by wolfcon** [shogo4405/HaishinKit.swift#629]
**To Reproduce**
```swift
rtmpStream?.captureSettings = [
            .fps: 60, // FPS
            ]
rtmpStream?.attachCamera(DeviceUtil.device(withPosition: position))
rtmpStream?.orientation = .landscapeRight
hkView?.attachStream(rtmpStream)
```

**Expected behavior**
It should be 60 instead of always 30 fps.

**Smartphone (please complete the following information):**
 - Device: iPhoneXs Max
 - OS: iOS 13.3
**HaishinKit Version**
1.0.3

**Additional context**
I watched fps would be changed by `rtmpStream?.attachCamera`. fps in`rtmpStream?.captureSettings` would not be set.

**Comment by leo150** [comment]
HK will stream with 60 fps only if the current device's `activeFormat` supports 60 fps. If you want to control this, change `.sessionPreset` of your `captureSettings` to `AVCaptureSession.Preset.inputPriority` and then you need manually iterate through all available formats of the current device and find one that support 60 fps.

**Comment by wolfcon** [comment]
### Solution
#### Do not use these code `DeviceUtil.device(withPosition: position)`
Put your  customized camara to `This kit` instead.

1. Do not set `.sessionPreset` of your `captureSettings`.
2. Get device what you like `AVCaptureDevice.default(for:)` or `AVCaptureDevice.default(_:for:position:)`
3. Choose (or create) a `format` from `device.formats`
4. Set this format to `device.activeFormat`

#### Done
