### ISSUE TITLE
HLS for 4k resolution in iPhone

### ISSUE THREAD

**Issue by Lyovvvv** [shogo4405/HaishinKit.swift#633]
Dear HaishinKit Team
  I want to use your framework to convert the iPhone camera output in real time to .ts video files and save it in a local directory, but it only works with AVCaptureSession.Preset.medium.
  Is there any way to change the preset to 4k and have the correct .ts files without losing frames when switching from one segment of a video file to another?
Thanks in advance

**Comment by shogo4405** [comment]
Please use Issue templates.
