### ISSUE TITLE
How to add multiple audio input (CMSampleBuffer) to haishinkit using swift?

### ISSUE THREAD

**Issue by PavitramAppsmartz** [shogo4405/HaishinKit.swift#634]
I want to add internal and mic audio at same time while streaming to youtube using haishinkit. I am getting noisy beeps sound only while streaming.

**Code Used**

In case of `RPSampleBufferType.audioMic:` and `RPSampleBufferType.audioApp`, I am doing following code to append the sampleBuffer to RTMPBroadcaster class object.

```
if CMSampleBufferDataIsReady(sampleBuffer) 
{
   broadcaster.appendSampleBuffer(sampleBuffer, withType: .audio)
}
```

**Comment by shogo4405** [comment]
No way. Please mix .audioMix and .audioApp your self.
