### ISSUE TITLE
screen broadcast orientation

### ISSUE THREAD

**Issue by joshuadiezmo** [shogo4405/HaishinKit.swift#639]
**Describe the bug**
I try to create a screen broadcast like OBS, and when I go to other apps, the app is landscape but the video is still portrait.

**Expected behavior**
it will automatically rotate to landscape

**Screenshots**
![Screen Shot 2020-02-10 at 12 05 13 PM](https://user-images.githubusercontent.com/8644115/74120259-9e211a00-4bfd-11ea-9c61-1882d7f52f07.png)

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: 13
 - Version 'HaishinKit', '~> 0.11.9'

**Comment by leo150** [comment]
Can you provide a landscape screenshot of the app you are trying to stream?

**Comment by shogo4405** [comment]
Duplicate as close, #481.
