### ISSUE TITLE
Failed Running the Example iOS app on Screencast

### ISSUE THREAD

**Issue by nkllkc** [shogo4405/HaishinKit.swift#641]
**Describe the bug**

When I'm trying to run the Example iOS app, I get:

failed to demangle superclass of RTMPBroadcaster from mangled name '10HaishinKit14RTMPConnectionC'
2020-02-17 16:16:35.357011-0800 Screencast[404:17877] failed to demangle superclass of RTMPBroadcaster from mangled name '10HaishinKit14RTMPConnectionC'.

**Expected behavior**
The application should start running.

**Screenshots**
Not applicable.

**Smartphone (please complete the following information):**
 - Device: iPhone 
 - OS: iOS13.3.1
![Screen Shot 2020-02-17 at 4 28 07 PM](https://user-images.githubusercontent.com/43245821/74693855-83711700-51a2-11ea-830d-f7e984109867.png)

**Comment by AlexanderKozhevin** [comment]
@nkllkc Sorry for stupid question. How did you start the project at all?
I mean did you select "single view app" and then copied screencast file inside of it?
I'm just lost a bit, can you give some guidance?

**Comment by shogo4405** [comment]
I can't reproduce.
Please do something.
