### ISSUE TITLE
Running constantly failing. dyld: Library not loaded.

### ISSUE THREAD

**Issue by nkllkc** [shogo4405/HaishinKit.swift#642]
**Describe the bug**
When I want to run the app (any app that uses HaishinKit) I can't due to following:

dyld: Library not loaded: @rpath/HaishinKit.framework/HaishinKit
  Referenced from: /private/var/containers/Bundle/Application/73DB8265-3988-4287-B0C8-D1B5FC87E706/ScreenShare.app/ScreenShare
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/73DB8265-3988-4287-B0C8-D1B5FC87E706/ScreenShare.app/Frameworks/HaishinKit.framework/HaishinKit: code signature invalid for '/private/var/containers/Bundle/Application/73DB8265-3988-4287-B0C8-D1B5FC87E706/ScreenShare.app/Frameworks/HaishinKit.framework/HaishinKit'

	/private/var/containers/Bundle/Application/73DB8265-3988-4287-B0C8-D1B5FC87E706/ScreenShare.app/Frameworks/HaishinKit.framework/HaishinKit: stat() failed with errno=25
	/private/var/containers/Bundle/Application/73DB8265-3988-4287-B0C8-D1B5FC87E706/ScreenShare.app/Frameworks/HaishinKit.framework/HaishinKit: code signature invalid for '/private/var/containers/Bundle/Application/73DB8265-3988-4287-B0C8-D1B5FC87E706/ScreenShare.app/Frameworks/HaishinKit.framework/HaishinKit'

	/private/var/containers/Bundle/Application/73DB8265-3988-4287-B0C8-D1B5FC87E706/ScreenShare.app/Frameworks/HaishinKit.framework/HaishinKit: stat() failed with errno=1
	/private/var/containers/Bundle/Application/73DB8265-3988-4287-B0C8-D1B5FC87E706/ScreenShare.app/Frameworks/HaishinKit.framework/HaishinKit: code signature invalid for '/private/var/containers/Bundle/Application/73DB8265-3988-4287-B0C8-D1B5FC87E706/ScreenShare.app/Frameworks/HaishinKit.framework/HaishinKit'

	/private/var/containers/Bundle/Application/73DB8265-3988-4287-B0C8-D1B5FC87E706/ScreenShare.app/Frameworks/HaishinKit.framework/HaishinKit: stat() failed with errno=1
(lldb) 

Running:
iOS 13.3.1 on iPhone XS Max

**Comment by shogo4405** [comment]
> code signature invalid

Please ask to the Stackoverflow.

**Comment by nkllkc** [comment]
Why you close the issue though? It's not solved yet?
