### ISSUE TITLE
Swift5 compilation error.

### ISSUE THREAD

**Issue by AlexanderKozhevin** [shogo4405/HaishinKit.swift#644]
**Describe the bug**
I just created a blank single view app and install HaishinKit via cocoaPods.
Everything is good. 

But when I try compile blank app without even importing HaisinKit, I'm getting the following error.
Like dozens of complications errors

```
Missing return in a function expected to return 'Bool'
Missing return in a function expected to return 'AVCaptureDevice?'
```
Which version of swift should I use?

![Screenshot 2020-02-24 at 01 27 43](https://user-images.githubusercontent.com/4464561/75121442-0a435980-56a5-11ea-924f-4f399ec56399.png)

![Screenshot 2020-02-24 at 01 27 19](https://user-images.githubusercontent.com/4464561/75121440-09aac300-56a5-11ea-96ad-e41e2fb92bf6.png)

**Comment by shogo4405** [comment]
> Which version of swift should I use?

Requirements is here. If you want to use Swift 5. pod 'HaishinKit', '~> 1.0.4'
https://github.com/shogo4405/HaishinKit.swift#requirements

I tested a blank app. It works fine.
https://github.com/shogo4405/HaishinKit-CocoaPods-Test
