### ISSUE TITLE
Visual effect (image as watermark) is flipped on front camera

### ISSUE THREAD

**Issue by ivai96** [shogo4405/HaishinKit.swift#648]
**Describe the bug**
I am trying to add watermark image using the PronamaEffect as example. When I switch to front camera the image is mirrored and its position is changed. I don't want this behavior, I need the image to stay in the original place. 
IMPORTANT: The filter(image) is OK on the stream. The problem is only on the front camera preview, so I tried to transform the image to look ok on front camera, but then it is flipped on the stream..

**To Reproduce**
1. Add pronama visual effect on when you are on the back camera
2. Switch from the back camera to the front camera
3. See that the image is reversed

**Expected behavior**
Image to stay in the same place and do not flip when displayed on both front and back camera

**Screenshots**
![57930255-c3bf0400-78b5-11e9-9f34-58d741df6346](https://user-images.githubusercontent.com/28016601/75892416-8ec67280-5e31-11ea-8f3e-f2a3dad2a8b2.png)
![57930254-c3bf0400-78b5-11e9-9568-d57684932dbd](https://user-images.githubusercontent.com/28016601/75892421-90903600-5e31-11ea-9746-618519d8a09d.png)

iOS 12.4.5

**Additional context**
I found this issue https://github.com/shogo4405/HaishinKit.swift/issues/538
but there isn't any solution.

@shogo4405  Please help! :)

**Comment by shogo4405** [comment]
This PR is helpful to you. https://github.com/shogo4405/HaishinKit.swift/pull/650
Please try master branch.

**Comment by ivai96** [comment]
It works as expected now, thank you very much! :)
