### ISSUE TITLE
Connection to RTMP service is unstable (v 1.0.7)

### ISSUE THREAD

**Issue by deniszhukov** [shogo4405/HaishinKit.swift#654]
During streaming we're getting RTMPConnection.Code.connectClosed at random time.
I saw that 1.0.7 was supposed to fix that, but it's still happening for us.

**Comment by shogo4405** [comment]
I will be investigating this issue.
For a while, please use 1.0.5.

**Comment by MikeDonahue** [comment]
I also have seen this, even back as far as 1.0.3. Reverted to 1.0.0 and it seems more stable. Hopefully this will help identify anything that might have started causing these issues.

**Comment by deniszhukov** [comment]
Hi @shogo4405 , any luck resolving this?

**Comment by jmsiox** [comment]
Facing same issue. Cant reliably stream for long duration using rtmp. Connection gets disconnected on its own in middle of stream

**Comment by deniszhukov** [comment]
Hi @shogo4405 , I know it's crazy times. We've sent you $50 as an appreciation for working on this issue.

**Comment by shogo4405** [comment]
I think might be fixed this issue 6a33884, 569723a.

**Comment by MikeDonahue** [comment]
@shogo4405 @deniszhukov, I tested this a few times with the latest commit you mentioned 569723a34e18a4b0a862c662f3e7560291cc6920 and it appears to be fixed. 👍

**Comment by shogo4405** [comment]
Thank u for testing. Released 1.0.8 https://github.com/shogo4405/HaishinKit.swift/releases/tag/1.0.8.

**Comment by wolfcon** [comment]
#611
Got this error when reconnect
`SocketStream write error [0x0]: 1 57`

[6a3388](https://github.com/shogo4405/HaishinKit.swift/commit/6a338844339ad0c37ee0050c1a654e85c02dc2d7) This commit revert changes.
