### ISSUE TITLE
How do I modify the bitrate using HaishinGPUImage?

### ISSUE THREAD

**Issue by giotto2012** [shogo4405/HaishinKit.swift#655]
I modified the width and height by modifying the rawDataOutput in NetStream
But you cannot modify the version used by bitrate is 1.0.5

         rtmpStream.videoSettings = [
             .width: 480,
             .height: 854
             .bitrate: 2000000
         ]

**Comment by shogo4405** [comment]
GPUHaishinKit.swift requires "github "shogo4405/HaishinKit.swift" ~> 0.8.0."

```
rtmpStream.videoSettings = [
  "width": 480,
  "height": 854,
  "bitrate": 2000000
]
```

**Comment by shogo4405** [comment]
I stopped to support GPUHaishinKit.
I will close this PR.
