### ISSUE TITLE
Swift 5.2 support

### ISSUE THREAD

**Issue by about-prog** [shogo4405/HaishinKit.swift#656]
With the latest XCode update I get "Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2 Compiler" for Haishinkit during compiling.

**Comment by floriangbh** [comment]
@about-prog what is your dependencies manager ? 

If you are using Carthage you need to recompile your dependencies.

**Comment by about-prog** [comment]
@floriangbh thank you! That helped
