### ISSUE TITLE
Change the scale aspect ratio

### ISSUE THREAD

**Issue by ioanalexme** [shogo4405/HaishinKit.swift#657]
Hello guys,

When broadcasting a computer screen with the ScalingMode.letterbox option, the broadcasted image has a 4:3 aspect ratio, as you can see in the print-screen preview. The preview image from Facebook Live looks kinda "squared" or squeezed. Is there a way to change this and make it 16:9 (keep the true aspect ratio of the screen)?

rtmpStream.videoSettings = [
   .scalingMode: ScalingMode.letterbox
]

 - OS: macOS, any version
 - Browser: any browser
 - Version: used 1.0.5 (but the same on any version)

![1](https://user-images.githubusercontent.com/28654763/77852754-ff6e6e00-71e8-11ea-879e-b7171ae2c88c.jpg)

**Comment by shogo4405** [comment]
> The preview image from Facebook Live looks kinda "squared" or squeezed. Is there a way to change this and make it 16:9 (keep the true aspect ratio of the screen)?

Please ask Facebook developer community.

**Comment by ioanalexme** [comment]
It's the same on Youtube... Any hints?

![YT](https://user-images.githubusercontent.com/28654763/78420366-154fb900-7657-11ea-876a-c870e10bf32f.png)

**Comment by ioanalexme** [comment]
> > The preview image from Facebook Live looks kinda "squared" or squeezed. Is there a way to change this and make it 16:9 (keep the true aspect ratio of the screen)?
> 
> Please ask Facebook developer community.

It's the same on Youtube... Any hints? Maybe I can have a look in the code and make a pool request, but where can I have a look?

![YT](https://user-images.githubusercontent.com/28654763/78420366-154fb900-7657-11ea-876a-c870e10bf32f.png)
