### ISSUE TITLE
Switching the contents of stream

### ISSUE THREAD

**Issue by Sachinyadav6500** [shogo4405/HaishinKit.swift#659]
Hi All

I was trying to build something like streaming from the front camera then the user switches to stream a local video for 10 sec then again switch back to the camera stream.

Individual camera stream and append file are working fine

But if I'm trying the above stream getting distorted.

can we build this feature using this library?

**Comment by Sachinyadav6500** [comment]
When we restart the app it keeps playing the the appendwithfile not sure why

**Comment by shogo4405** [comment]
> can we build this feature using this library?

No way.
