### ISSUE TITLE
Streaming device is connected to server, but no client can subscribe to this stream

### ISSUE THREAD

**Issue by lukkas** [shogo4405/HaishinKit.swift#660]
**Describe the bug**
I'm trying to use HaishinKit to publish RTMP stream. It seems to be connecting fine, however no client is able to receive this stream. I've subscribed to `.rtmpStatus` and I'm getting these two events:
```
NetConnection.Connect.Success
NetStream.Publish.Start
```

I'm currently using this little app to test my RTMP setup https://github.com/sallar/mac-local-rtmp-server. My setup is basically the same as in README. In fact I've also created new sample project to make sure, that nothing from my project is affecting how stream is functioning. 

When I connect, status bar icon of my server app turns red, which means that connection has been made. Besides icon turning red, this little window should also change and start displaying some information about stream audio and video codecs, amount of data sent and stream name, however it stays as it was before. I also can't connect to this stream using VLC as a client.
<img width="403" alt="Zrzut ekranu 2020-04-2 o 21 48 05" src="https://user-images.githubusercontent.com/3305872/78296221-9f9bfe00-752d-11ea-8c54-ac72cd09bb7e.png">

**To Reproduce**
1. Create new project and copy setup from README.
2. Run `Local RTMP Server`.
3. Use your local network IP to start local RTMP server.
4. Run example Xcode project create in point 1 and try connecting to local server.
5. Observe `Local RTMP Server` turning red.
6. Try connecting to this stream using VLC - it fails.

Besides my `Local RTMP Server` + `VLC` setup I've been also using streams from youtube and livestream.com with similar effect.

**Expected behavior**
I should be able to connect to this stream.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 13.4
 - SDK: 13.4 / Xcode 11.4

**Comment by shogo4405** [comment]
I'm not sure. It works for me. 


<img width="388" alt="スクリーンショット 2020-04-04 16 20 13" src="https://user-images.githubusercontent.com/810189/78421106-32ed4480-7690-11ea-8494-72c441e82653.png">

HaishinKit preferences is here:
```
rtmpConnection.connect("rtmp://127.0.0.1/live")
rtmpStream.publish("BJRmijHvU")
```

VLC playback path is here:
- rtmp://127.0.0.1/live/BJRmijHvU

* macOS + HaishinKit
  - <img width="972" alt="スクリーンショット 2020-04-04 15 51 14" src="https://user-images.githubusercontent.com/810189/78420991-2d432f00-768f-11ea-9604-981f88d0339a.png">
* iOS + HaishinKit
  - ![Image from iOS](https://user-images.githubusercontent.com/810189/78421018-67accc00-768f-11ea-8e4e-00485a86c71c.png)

**Comment by lukkas** [comment]
I was constructing the entire address by appending stream key to the base url. Thanks for the answer. Closing.
