### ISSUE TITLE
RTMP Stream not starting

### ISSUE THREAD

**Issue by PhilipDukhov** [shogo4405/HaishinKit.swift#661]
I'm trying your examples and wanna stream on local network. I had tried these URIs: "rtmp://localhost/live", "rtmp://127.0.0.1/live", "rtmp://192.168.1.12/live" (device local ip address) and "rtmp://169.254.224.93/live" (en2 interface ip of the device, http server works fine with this one), on both Mac and iOS - the result is the same in all cases: the first event I get in `public func stream(_ aStream: Stream, handle eventCode: Stream.Event)` of `NetSocket`(in this case it's subclass `RTMPSocket`) is `.errorOccurred` with the following error:
`Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}`
Am I doing something wrong?

**Comment by shogo4405** [comment]
I'm not sure. This issue contains so little information.
Please use issue templates.
