### ISSUE TITLE
cordova plugin for ios streaming

### ISSUE THREAD

**Issue by Fayozjon** [shogo4405/HaishinKit.swift#662]
Hello!
Need plugin for cordova for streaming via iOS platform. On Android there is plugin 
https://github.com/disono/cordova-rtmp-rtsp-stream/
Can you wrap it as cordova plugin?

**Comment by shogo4405** [comment]
> Can you wrap it as cordova plugin?

No. I will not support the Cordova.
Please fork and customize HaishinKit.
