### ISSUE TITLE
The M3U8 file don't contain informations of *.ts files (TSWriter)

### ISSUE THREAD

**Issue by phinguyenmaplelabs** [shogo4405/HaishinKit.swift#664]
**Describe the bug**
The M3U8 file don't contain informations of *.ts files (TSWriter)

` guard expectedMedias.isEmpty else { return true }`

This condition is wrong, it should be vice versa

<img width="665" alt="Screen Shot 2020-04-13 at 11 42 31" src="https://user-images.githubusercontent.com/62593343/79092834-5b55fc80-7d7c-11ea-8e4e-8f247fbca173.png">

**Expected: 
"guard !expectedMedias.isEmpty else { return true }"

**Comment by shogo4405** [comment]
Currently, It's in the specifications.
