### ISSUE TITLE
Is it possible to have rtsp stream as inout source instead of camera?

### ISSUE THREAD

**Issue by hubus** [shogo4405/HaishinKit.swift#667]
I would like to redirect rtsp stream from one device to FB/Youtube or any other rtmps. And I would like to do it on iOS. I tried playing it and than doing ScreenCaptureSession(view) but I was only able to get 3-8 fps on FB. 

I have preview of the rtsp stream on iOS (VLCKit). I can stream camera to rtmps (HaisihinKit). But I can't connect those strings. Do You have an idea how to achieve that?

**Comment by shogo4405** [comment]
No.

**Comment by hubus** [comment]
And is there a chance to increase fps for ScreenCaptureSession to 25/30?
