### ISSUE TITLE
Xcode 11.4+ SPM install fails due to mixed language source

### ISSUE THREAD

**Issue by bhlvoong** [shogo4405/HaishinKit.swift#669]
First off, great library and thanks for open sourcing this. Now to the issue:

When installing with Xcode 11.3 SPM, everything seems fine.  However when using latest Xcode 11.4 and 11.4.1, you'll hit an error complaining about mixed source files:

/Users/.../Developer/Xcode/DerivedData/sample_haishin-gotjctuildylrfampxnpzgpiqysw/SourcePackages/checkouts/HaishinKit.swift/Sources' contains mixed language source files; feature not supported

**Comment by shogo4405** [comment]
It works Xcode Version 11.7 and master branch.
I will close this issue. Please update Xcode. Thank u.
