### ISSUE TITLE
The app crashes when the Current time watermark video effect filter is used

### ISSUE THREAD

**Issue by rizwan95** [shogo4405/HaishinKit.swift#670]
**Describe the bug**
The app crashes when the Current time watermark video effect filter is used. 

**To Reproduce**
1. Create a current time watermark effect using the sample code. 
2. Register the effect.
3. Start broadcasting. The broadcast will crash as, ```UIGraphicsGetImageFromCurrentImageContext()!``` is nil. 

**Expected behavior**
The current time should be shown in the broadcast video.

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: 13.4.5

@shogo4405

**Comment by shogo4405** [comment]
I'm not provide `Current time watermark video effect filter`
If you want to get support, please should write that code.
I'm not sure.

**Comment by rizwan95** [comment]
Please check this link https://github.com/shogo4405/HaishinKit.swift/blob/master/Examples/iOS/VisualEffect.swift

This is included in your sample. The method name is `CurrentTimeEffect`

@shogo4405

**Comment by shogo4405** [comment]
Oh, yes. It is dead code. I will remove. Thank u.

**Comment by rizwan95** [comment]
Can you please provide a working example?

**Comment by shogo4405** [comment]
No.
