### ISSUE TITLE
RTMP Status Listener not receiving `RTMPConnection.Code.connectClosed` Event when `rtmpConnection.close()`

### ISSUE THREAD

**Issue by allenlinli** [shogo4405/HaishinKit.swift#671]
**Describe the bug**
Our RTMP status listening function is not getting a notification when we close the connection by `rtmpConnection.close()`. After reviewing #653 and #489, we do not know why our listener is not receiving the .connectClosed event. 

Should the `RTMPConnection.Code.connectClosed` be called in such situation? If not, how can get the event when unpublish (close) the connection?

**To Reproduce**
1. Comment (remove) the two lines in `LiveViewController.swift`
```
//rtmpConnection.removeEventListener(.rtmpStatus, selector: #selector(rtmpStatusHandler), observer: self)
//rtmpConnection.removeEventListener(.ioError, selector: #selector(rtmpErrorHandler), observer: self)
```
2. Start the streaming by clicking the publish button (with preferred `streamName` and `uri` set up.)
3. Stop the streaming by clicking the publish button again, which triggers `rtmpConnection.close()`.
4. Add a log in the function `private func rtmpStatusHandler(_ notification: Notification)`.
5. Notice no logs from rtmpStatusHandler

**Expected behavior**
rtmpStatusHandler is called with .connectClosed event; in this case, printing logs with event info.

Smartphone (please complete the following information):

Device: Real device iPhone X
OS: iOS 13.3
Version: HaishinKit (1.0.8) via CocoaPods

**Comment by allenlinli** [comment]
I found the true reason should be our server does not send "NetStream.Connect.Closed" at all.
When I tried Facebook and Twitch, their server does not send it also, I wonder if sending "NetStream.Connect.Closed" is the standard procol?

**Comment by shogo4405** [comment]
> Should the RTMPConnection.Code.connectClosed be called in such situation?

* This status code raises disconnected by the server or turn off to WiFi.
  - https://github.com/shogo4405/HaishinKit.swift/blob/48e122bad5c6f62919bff1a59b99bf1ee5987755/Sources/RTMP/RTMPSocket.swift#L93-L94
* `rtmpConnect.close()` will not raise RTMPConnection.Code.connectClosed.

**Comment by allenlinli** [comment]
Thank you so much. I understood.

**Comment by allenlinli** [comment]
Just a follow-up question. Then what's the proper way to get the callback for `rtmpConnect.close()`？ Or we do not need the callback here at all?
