### ISSUE TITLE
How to properly close a live video

### ISSUE THREAD

**Issue by ioanalexme** [shogo4405/HaishinKit.swift#672]
**Describe the bug**
When a user wants to close a connection, what sequence of operations one must make? I'm trying like this, but I'm not sure if this is the correct order:

rtmpConnection.close()
rtmpStream.close()
rtmpStream.dispose()

Is this the right order?

Or there is another recommended order (to prevent race conditions or random crashes)?

 - OS: any (iOS and macOS)
 - Browser: any
 - Version: 1.0.8 (or any other older version)

**Comment by shogo4405** [comment]
In the regular case, Please call only `rtmpConneciton.close()`.

`rtmpConneciton.close()` calls `rtmpStream.close` internally. 
https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/RTMP/RTMPConnection.swift#L303-L317

RTMPConnection can contains any RTMPStreams. If you want to close indivisual a RTMPStream.
1. One RTMPStream.close()
2. Other RTMPStream.close()
3. RTMPConnection.close()

**Comment by ioanalexme** [comment]
I see.. but the problem is that not calling rtmpStream.close() and rtmpStream.dispose() will keep the web cam on.
On a Mac computer not calling close() and dispose() on rtmpStream will keep the camera light on.

Is this a bug?

**Comment by ioanalexme** [comment]
I guess a order can be:

rtmpConnection.close() // this will also call rtmpStream.close()
rtmpStream.dispose()

**Comment by shogo4405** [comment]
> rtmpStream will keep the camera light on.

Please call `RTMPStream.attachCamera(nil)`

**Comment by ioanalexme** [comment]
Great, thank you. It is clear now.
Closing the issue.
