### ISSUE TITLE
WebRTCでの会議の様子をattachScreenでRTMP配信したい

### ISSUE THREAD

**Issue by Zakimiii** [shogo4405/HaishinKit.swift#673]
はじめまして。
現在、こちらの記事を参考にWebRTCを使った会議を作ることができています。
https://qiita.com/tnoho/items/f5afa3ba749eed9b9716

こちらの記事ではWebRTCによりcameraPreview と remoteView の2つで会話の様子をビデオチャットで配信しています。
今回はこのcameraPreview単体, remoteView単体,  cameraPreview + remoteViewを含むview それぞれをrtmpStreamにattachScreenしても配信は真っ暗なままで配信ができませんでした。

attachScreenによって普通のUIViewをrtmp配信することはできるのですが、cameraPreviewとremoteViewをrtmp配信するのは不可能でしょうか？

配信をrenderingしているViewをattachScreenするのは原理的に可能かと思っていたのですが、できないケースもあるのでしょうか？
ご確認宜しくお願いします！

**Comment by shogo4405** [comment]
おそらくcameraPreview内部の処理にAVSampleBufferLayer や GPUを使ったレンダリングをしている可能性があります。この場合、attachScreenの内部的に利用しているUIView#drawHierarchy をつかったキャプチャーはできません。

**Comment by Zakimiii** [comment]
わかりました！
丁寧な回答ありがとうございます！
別の方法を考えてみます。
