### ISSUE TITLE
MTHKView does not mirror front facing camera

### ISSUE THREAD

**Issue by hambly** [shogo4405/HaishinKit.swift#674]
**Describe the bug**
MTHKView does not mirror the preview when using the front facing camera.  GLHKView does this (line 66) by calling `.oriented(forExifOrientation:2)` when the front camera is used.

MTHKView does not do this mirroring, and produces an unmirrored preview. Similar code from GLHKView should be added around line 95 of MTHKView (right before generating `scaled image`)

The following adjustment to that line of code is likely a sufficient fix for this.

```       
let adjustedImage = position == .front ? image.oriented(forExifOrientation: 2) : image
let scaledImage: CIImage = adjustedImage
  .transformed(by: CGAffineTransform(translationX: translationX, y: translationY))
  .transformed(by: CGAffineTransform(scaleX: scaleX, y: scaleY))
```

**To Reproduce**
1. Using MTHKView, load the front facing camera. Move left -> the preview of yourself will move right.

**Expected behavior**
The front facing camera should be mirrored -> If you move left, the preview of yourself will move left.

**Smartphone (please complete the following information):**
All iOS devices, tested locally on:
iPhone 11 Pro - iOS 13.3.1
iPad Pro 10.5 - iOS 13.4

**Additional context**
This could be a setting, as the non-mirrored output might be desirable in some cases. However, I consider this a bug as the default behavior is not consistent between GLHKView and MTHKView.

**Comment by shogo4405** [comment]
https://github.com/shogo4405/HaishinKit.swift/pull/704
