### ISSUE TITLE
[Need Help] Does this kit support insert a timecode  SEI message to H.264 video

### ISSUE THREAD

**Issue by dungpa-tmm** [shogo4405/HaishinKit.swift#683]
We're developing a live stream app to work with Aws Medialive
to sync time between multiple channel outputs, we need to set up a timecode source follow by
_https://docs.aws.amazon.com/medialive/latest/ug/timecode.html_

We need to insert a timecode that's in an SEI message of type pic_timing to H.264 video
Does your kit support that?

**Comment by shogo4405** [comment]
No.

**Comment by helgehoi** [comment]
Hi! 

First of all - thank you for providing this great repo.

I see that this discussion is 3 years old.
Is there any news on the timecode question? It would be great to have some sort of timecode in the rtmp-stream.

Many thanks
