### ISSUE TITLE
Record without remote server 

### ISSUE THREAD

**Issue by Goule** [shogo4405/HaishinKit.swift#687]
Hello,

I'm looking for a way to record the video without remote server. 

I found this PR which has been closed : https://github.com/shogo4405/HaishinKit.swift/pull/402
This PR is really old, maybe there is an other way since 2018 ? 

Thanks for you help

**Comment by shogo4405** [comment]
This method can publish to remote server and record the video local (iOS).
```rtmpStream.publish("streamName", type: .localRecord)```

**Comment by Goule** [comment]
Hello thanks for the answer @shogo4405 

This method can publish to remote server and record but it cannot ONLY record the video local if I understand. 
I'm looking for a way only record in local (for offline use case and publish later for exemple).
It is possible ? 

Thanks !

**Comment by shogo4405** [comment]
> I'm looking for a way only record in local (for offline use case and publish later for exemple).
It is possible ?

No. I have no plans to implement it.

**Comment by Goule** [comment]
Ok thanks for your feedback
