### ISSUE TITLE
Broadcast extension exceeds 50MB limit

### ISSUE THREAD

**Issue by Moonko** [shogo4405/HaishinKit.swift#689]
**Describe the bug**
Hi! Thanks for the framework! I'm facing the issue with app broadcast extension. I'm listening to app audio and mic. When I try to send both CMSampleBuffers with audio app extension exceeds 50MB limit.

**To Reproduce**
1. Call rtmpStream.appendSampleBuffer(...) on line 52 instead of ignoring it.
2. Start screen broadcast from control centre.
3. Don't forget to enable microphone.
4. Watch memory growth until it reaches 50MB.
<img width="911" alt="Screenshot 2020-05-20 at 02 02 28" src="https://user-images.githubusercontent.com/5665912/82386793-fc9c3680-9a3d-11ea-8580-1d855092abf5.png">

**Expected behavior**
I can send both audio samples.

**Additional context**
Appreciate your help! Just pointing to the place in code where the issue might be will be helpful. Thanks in advance.

**Comment by shogo4405** [comment]
Did you changed this? 

        case .audioApp:
            rtmpStream.appendSampleBuffer(sampleBuffer, withType: .audio)
        case .audioMic:
            rtmpStream.appendSampleBuffer(sampleBuffer, withType: .audio)

In the first place, HaishinKit can't send to `appAudio` and `micAudio` both sampleBuffer.

**Comment by rizwan95** [comment]
@shogo4405  It would be better if HaishinKit could merge audios and send them. Else, a pointer on how to do it could also be helpful for users.

**Comment by Moonko** [comment]
@shogo4405 Yes, I added this line. It works if I send only app or mic audio, but overflows while sending both. What's the difference? They are still separate buffers with different presentation time.

**Comment by rizwan95** [comment]
@shogo4405 has already said that the framework will not combine both audio buffers and we have to do it on our own. So, if you try to use the method for both the sources, it is meant to crash.

**Comment by darnfish** [comment]
Are there any docs on combining two CMSampleBuffers?
