### ISSUE TITLE
Too low FPS for screencast

### ISSUE THREAD

**Issue by razalur** [shogo4405/HaishinKit.swift#694]
Hello!

When I use rtmpStream.attachScreen I have too low FPS = 4 or even 2. May be someone have any idea how to fix it?

P.S.: I tested it with app from examples. Just replaced attachCamera to attachScreen as described in docs.

 - Device: iPhoneX
 - OS: iOS 13.3

**Comment by shogo4405** [comment]
> May be someone have any idea how to fix it?

No way. UIView.drawHierarchy method is too heavy.
https://github.com/shogo4405/HaishinKit.swift/blob/master/Platforms/iOS/ScreenCaptureSession.swift#L137

Please consider to use ReplayKit https://developer.apple.com/documentation/replaykit.
