### ISSUE TITLE
Screencasting of video from camera.

### ISSUE THREAD

**Issue by razalur** [shogo4405/HaishinKit.swift#695]
Hello!
I'm trying to screencast from my iPhone. And all elements I can see in my stream video: buttons, labels, images - all I added to my UIViewController. Except the view with the video from camera. I see the video from camera on the screen of my phone. But it disappears on the video from screencast.

May be someone knows solution to stream video from camera via screencast?

I add video from camera in such way:
`    func addCameraInView() {
        
        imagePickers = UIImagePickerController()
        if UIImagePickerController.isCameraDeviceAvailable( UIImagePickerController.CameraDevice.rear) {
            imagePickers?.delegate = self
            imagePickers?.sourceType = UIImagePickerController.SourceType.camera
            
            //add as a childviewcontroller
            addChild(imagePickers!)
            
            // Add the child's View as a subview
            
            lfView?.addSubview((imagePickers?.view)!)
            imagePickers?.view.frame = lfView!.bounds
            imagePickers?.allowsEditing = false
            imagePickers?.showsCameraControls = false
            imagePickers?.view.autoresizingMask = [.flexibleWidth,  .flexibleHeight]
        }
    }`

 - Device: iPhoneX
 - OS: iOS 13.3

**Comment by shogo4405** [comment]
Maybe `imagePickers?.view` can't capture by UIView.drawHierarchy method.

**Comment by THEMaxNorman** [comment]
Did you ever figure this out? I'm having similar issues
