### ISSUE TITLE
Library streams static video frame while audio streams, in bad internet connection

### ISSUE THREAD

**Issue by mkrn** [shogo4405/HaishinKit.swift#696]
**Describe the bug**
In a few rare cases when internet is unstable and / or after reconnect, especially if streaming away from router, the video encoder can stop and only audio keeps streaming. 

RTMP streams a static frame for video or in some rare cases black screen. Audio keeps streaming.

Lib keeps streaming static frame even after reconnection. 

**To Reproduce**
It is hard to reproduce. Using very bad network or walking away and towards the router. This happens in rare cases. Logic of locking needs to be reviewed.

**Expected behavior**
Video should always keep streaming with the audio.

**Screenshots**
example: https://eventlivehls.sfo2.digitaloceanspaces.com/streams/YXJLHWZH_3.mp4

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser N/A
 - Version any

**Smartphone (please complete the following information):**
 - Device: iphone
 - OS: any
 - Browser n/a
 - Version n/a

**Additional context**
Bad connection.

**Comment by mkrn** [comment]
Curious could it be related to 

RTMPStream.swift sampleOutput
OSAtomicOr32Barrier(1, &mixer.videoIO.encoder.locked)

And NetSocket.swift
if locked != nil {
                    OSAtomicAnd32Barrier(0, locked!)
                }


?

**Comment by shogo4405** [comment]
Yeah, that's very likely. But HaishinKit will set locked = 0 when reconnection.
https://github.com/shogo4405/HaishinKit.swift/blob/3e5555014b3aaa9ca5c786c83353ebbaddb77621/Sources/RTMP/RTMPStream.swift#L268

Can I see your the reconnect code?

**Comment by mkrn** [comment]
For reconnection I use a timer that tries to connect every 3s, 
It's triggered by any error, reachability, etc.

reconnect function does:
rtmpConnection.close()
rtmpConnection.connect(url)

What's strange is video running, audio not running. That's why I think it's because of the lock

Should we set `OSAtomicAnd32Barrier(0, &self.locked)`  in H264Encoder startRunning too?

**Comment by mkrn** [comment]
Thanks @shogo4405 will be testing it extensively this weekend

**Comment by mkrn** [comment]
Unfortunately the issue is still happening for some users, although I'm not 100% sure if it's using RTMPSocket or RTMPNWSocket 

Is it possible that encoding gets stuck on Reconnect if it closes here before unlocking? https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/RTMP/RTMPNWSocket.swift#L114

**Comment by shogo4405** [comment]
> Is it possible that encoding gets stuck on Reconnect if it closes here before unlocking? > https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/RTMP/RTMPNWSocket.swift#L114

Yes. How about this? https://github.com/shogo4405/HaishinKit.swift/commit/9c452849eee5e1e553c960c93129d70789fbdf8e

**Comment by mkrn** [comment]
Looks good, I've also integrated it with NetSocket for iOS 11 support 
https://github.com/mkrn/HaishinKit.swift/commit/32f65f3726649c827d69ffe5a1e9f7a69277ce2f#diff-400b474c45f91dd9cfa65fa1ed828b7aR47

**Comment by mkrn** [comment]
@shogo4405 With those 2 changes the problem is not happening anymore! Thank you for the support!
