### ISSUE TITLE
Streaming ARKit

### ISSUE THREAD

**Issue by razalur** [shogo4405/HaishinKit.swift#697]
Hello! Is it possible to stream video getting from ARKit?

May be there is some ability for streaming my own frames buffer?

Best regards,
Aleksey Razzhivaykin

**Comment by shogo4405** [comment]
Have a try! I'm not sure ARKIt.

**Comment by razalur** [comment]
Ok, but what about streaming of my buffer of frames?

**Comment by ntqp97** [comment]
> Ok, but what about streaming of my buffer of frames?

Have you found a solution to this problem yet?

**Comment by patthehuman** [comment]
Any solution to this?
