### ISSUE TITLE
How can I get the actual bitrate of a streaming video?

### ISSUE THREAD

**Issue by allenlinli** [shogo4405/HaishinKit.swift#700]
**Is your feature request related to a problem? Please describe.**
No.
I wonder if the actual video bitrate is different from the bitrate we are setting in `RTMPStream` (with `rtmpStream.videoSettings[H264Encoder.Option.bitrate]`)? Because the bitrate our server receive (700 Kbps) is different from the bitrate I set (1000 Kbps) in RTMPStream. 

**Describe the solution you'd like**
A `actualBitrate` property to provide the real bitrate, if there is such a thing.

**Describe alternatives you've considered**

**Additional context**
AudioConverter has a property `actualBitrate`, it could be the reference.

**Comment by shogo4405** [comment]
rtmpStream.videoSettings[.bitrate] means a average bitrate
  - see also https://developer.apple.com/documentation/videotoolbox/kvtcompressionpropertykey_averagebitrate

> A actualBitrate property to provide the real bitrate, if there is such a thing.

rtmpStream.info.currentBytesPerSecond
https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/RTMP/RTMPStreamInfo.swift#L9

**Comment by allenlinli** [comment]
Great! I understood. Thank you for the explanation.
