### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by gofey** [shogo4405/HaishinKit.swift#705]
**Describe the bug**
Demo does not work on macOS. I use rtmp url from YouTube to publish video, but "rtmpStatusHandler" will return close after returning success soon. 

**To Reproduce**
1. edit YouTube rtmp url
2. Click on 'publish'
3. rtmpStatusHandler return "connection close" message

**Expected behavior**
I can see the live streaming in YouTube 
**Screenshots**
![image](https://user-images.githubusercontent.com/24378831/84991789-952af100-b179-11ea-8cfa-de4733cde947.png)

**Desktop (please complete the following information):**
 - OS: 10.15.5

**Comment by shogo4405** [comment]
It works for me. Please modify https://github.com/shogo4405/HaishinKit.swift/blob/master/Examples/iOS/Preference.swift

**Comment by gofey** [comment]
I tried,but the connect will close in seconds in MasOS or iOS .I don't know where the problem is. this is my trmp url "rtmp://a.rtmp.youtube.com/live2/htk4-xgpj-j2zj-jy50-60yh". could  you try again? you can see the log.

**Comment by shogo4405** [comment]
@gofey 
It's wrong. Please try.

```
struct Preference {
    static var defaultInstance = Preference()

    var uri: String? = "rtmp://a.rtmp.youtube.com/live2"
    var streamName: String? = "htk4-xgpj-j2zj-jy50-60yh"
}
```

**Comment by gofey** [comment]
I got it ,and resolved the question. thanks a lot.But run the demo on Mac OS.it will crash.
![image](https://user-images.githubusercontent.com/24378831/85195299-d0592b80-b303-11ea-9e64-1d3ee6302bf2.png)
the _converter is nil and the inClassDescriptions is empty array.what is the reason?

**Comment by gofey** [comment]
when I lower the SampleRate, it will not crash, I just want to know the reason
