### ISSUE TITLE
[HLSService] attach CMSampleBuffer seem not work

### ISSUE THREAD

**Issue by dangquochoi2007** [shogo4405/HaishinKit.swift#706]
I using HLSService from iPhone cast video to Safari

here my code:
`    
private func setupStream() {
        
        let httpStream = HTTPStream()
        ///httpStream.attachScreen(ScreenCaptureSession(shared: UIApplication.shared))
        ///httpStream.attachAudio(AVCaptureDevice.default(for: .audio))
        httpStream.publish("hello")
        
        
        let httpService = HLSService(domain: "", type: "_http._tcp", name: "HaishinKit", port: 8080)
        httpService.startRunning()
        httpService.addHTTPStream(httpStream)
        
        RPScreenRecorder.shared().startCapture(handler: { (sampleBuffer, type, error) in
            switch type {
            case .video:
                if let description:CMVideoFormatDescription = CMSampleBufferGetFormatDescription(sampleBuffer) {
                    let dimensions:CMVideoDimensions = CMVideoFormatDescriptionGetDimensions(description)
                    httpStream.videoSettings = [
                        .width: dimensions.width,
                        .height: dimensions.height ,
                        .profileLevel: kVTProfileLevel_H264_Baseline_AutoLevel,
                    ]
                }
                httpStream.appendSampleBuffer(sampleBuffer, withType: .video)
            default:
                break
            }
        }) { (error) in

        }
    }`

I expect safari appear my mobile screen.

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser  safari
 - Version 22

**Smartphone **
 - Device: iPhone6
 - OS: iOS 13.2
 - Browser safari
 - Version HaishinKit (1.0.10)

I check from file playlist.m3u8

`
#EXTM3U
#EXT-X-VERSION: 3
#EXT-X-MEDIA-SEQUENCE: 0
#EXT-X-TARGETDURATION: 2
`

**Comment by dindin44** [comment]
What was the solution to this?

**Comment by dangquochoi2007** [comment]
> What was the solution to this?

I update publish function

```    
    open func publish(_ name: String?) {
        lockQueue.async {
            if name == nil {
                self.name = name
                #if os(iOS)
                self.mixer.videoIO.screen?.stopRunning()
                #endif
                self.mixer.stopEncoding()
                self.tsWriter.stopRunning()
                return
            }
            self.name = name
            #if os(iOS)
            self.mixer.videoIO.screen?.startRunning()
            #endif
            self.tsWriter.expectedMedias.remove(.video)
            self.tsWriter.expectedMedias.remove(.audio)
            self.mixer.startEncoding(delegate: self.tsWriter)
            self.mixer.startRunning()
            self.tsWriter.startRunning()
        }
    }
```
