### ISSUE TITLE
how can i get the network stats 

### ISSUE THREAD

**Issue by talaltariq3299** [shogo4405/HaishinKit.swift#707]
**how can I calculate the network stats like data loses, actually I want to show the network strength signal like good medium poor based upon how much bytes need to upload and how much data actually we are uploading based upon our network speed (**latency**), like if I have a bad connection or Good how can I calculate through HaishinKit** like in nanostream we can get the packet loose percentage and network connection strength and show red green yellow icon based upon network connection

**Comment by pinkfish** [comment]
Was not sure on this too. I cannot see a status callback, although it does look like a lot of this info is collected in the various classes, just not exposed.

**Comment by shogo4405** [comment]
HaishinKit has no feature.
