### ISSUE TITLE
[Update for Readme] How can I connect to rtmp server with VLC 

### ISSUE THREAD

**Issue by aelam** [shogo4405/HaishinKit.swift#711]
**Is your feature request related to a problem? Please describe.**
 When I run the project, I don't know how to connect to this rtmp server via VLC app or ffmpeg, after I've read the readme and some code of the project. I still get nothing. There is no description in README 

**Describe the solution you'd like**
Description about how to connect with a client to test if it works

**Describe alternatives you've considered**

**Additional context**

**Comment by shogo4405** [comment]
> this rtmp server via 

I think you've got it wrong. HaishinKit has no feature rtmp service.

**Comment by aelam** [comment]
I got it today.
And i tried to publish the stream to a nginx-rtmp server with this app, it
doesn't work, i dont know why.

Another question, is it possible just post audio stream via rtmp?

shogo4405 <notifications@github.com> 于 2020年7月7日周二 16:10写道：
