### ISSUE TITLE
Orientation always portrait when streaming

### ISSUE THREAD

**Issue by pinkfish** [shogo4405/HaishinKit.swift#715]
Using the orientation as described in the issues ie:
```
DispatchQueue.main.async {
            if let orientation = DeviceUtil.videoOrientation(by:  UIApplication.shared.statusBarOrientation) {
                self.rtmpStream.orientation = orientation
                print(String(format:"Orient %d", orientation.rawValue))
            }
            self.rtmpConnection.connect(self.url ?? "frog")
        }
```
However I am still seeing it output always in portrait mode on the streaming side. Is there something else I need to do here?

RUnning this on ios using 1.0.10 version of hashinkit

Expected behavior, when looking at the feed in the streaming playback it is rotated to match the orientation on the screen.  It always stays as portrait.  From what I can tell you just need to put some metadata into the feed, looking in the code I couldn't figure out if this is happening or not? vs doing a physical rotation of the bits.

**Comment by shogo4405** [comment]
Close issue as duplicate https://github.com/shogo4405/HaishinKit.swift/issues/147.
