### ISSUE TITLE
how can we add custom sticker , overlay images and text  on the live streaming (included in live video)

### ISSUE THREAD

**Issue by talaltariq3299** [shogo4405/HaishinKit.swift#722]
I want to add custom sticker its more like images over live video and text overlay, please help me how can I add them 
one of my ideas is I tried it capture device camera preview on uiview and attach that screen to the RTMP server but somehow its show capture video on broadcaster screen but blank screen on viewer screen you can suggest me how can I achieve this feature please let me know as soon as you can 

please give me your suggestion how can I add overlay text and image on the live stream

**Comment by floriangbh** [comment]
Hello, 

You can check the project exemple. There is effect demonstration : https://github.com/shogo4405/HaishinKit.swift/blob/a5eebba3d1378bf8e774a0d850eec1cc997d594e/Examples/iOS/LiveViewController.swift#L199

**Comment by talaltariq3299** [comment]
how can i preview camera on uiview and attach that view to rtmp server ? can you explain me how i can do this ?

**Comment by shogo4405** [comment]
Please check exemple. You can get answer.

**Comment by talaltariq3299** [comment]
i understand about the effect but my question is how can we add sticker's and text overlay over the live stream video???
