### ISSUE TITLE
Stream unable to start after reconnect [iOS]

### ISSUE THREAD

**Issue by CubitSpeed** [shogo4405/HaishinKit.swift#724]
**Describe the bug**
In certain conditions after reconnecting, the stream will be unable to start.

**To Reproduce**
**NOTE: Bug doesn't always happen. In my tests is happens 33% of the time**
1. Load iOS example project
2. Start streaming to RTMP
3. Swipe up to manually disconnect phone from internet
4. Press button to "STOP" stream
5. Swipe up to manually reconnect phone to internet
6. Press button to "START" stream

**Expected behavior**
The stream, after pressing start in the last step above, should start streaming again. Instead, it will never start.

**Smartphone (please complete the following information):**
 - Device: iPhone6s
 - OS: 12.3.1

**Comment by CubitSpeed** [comment]
@shogo4405 

It looks like the code [rtmpConnection.close()](https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/RTMP/RTMPConnection.swift#L300) always calls the underlying `close` method with the value of `isDisconnected: false`.

Do you think this may be a possible cause for the above behavior I am experiencing?

**Comment by shogo4405** [comment]
This issue might be fixed https://github.com/shogo4405/HaishinKit.swift/pull/733
