### ISSUE TITLE
attach screen with rtmpstram stuck the application 

### ISSUE THREAD

**Issue by talaltariq3299** [shogo4405/HaishinKit.swift#726]
rtmpStream.attachScreen(ScreenCaptureSession(shared: .shared)).   wokring fine but when i attach some view like
 rtmpStream.attachScreen(ScreenCaptureSession(viewToCapture: self.lfview!))  it slow down the application even the keyboard popup animation become very slow can you suggest me why this happened and how to prevent from it

**Comment by shogo4405** [comment]
* ScreenCaptureSession is heavy. I can't resolve it.
* Please try to consider to use https://developer.apple.com/documentation/replaykit

**Comment by dindin44** [comment]
How do you suggest linking Replaykit with the rtmpStream?
