### ISSUE TITLE
Attach Screen using UIApplication.shared causes app to crash

### ISSUE THREAD

**Issue by dindin44** [shogo4405/HaishinKit.swift#728]
I am trying to screen capture my app using the following:
`rtmpStream.attachScreen(ScreenCaptureSession(shared: UIApplication.shared))`
 
The app seems to crash because it's trying to force unwrap a nil window object on the AppDelegate. 

I am using iOS 13 so the window should be inside the scene delegate object, but I can't see a way of accessing this through the library. Are there any solutions to get around this? 

Is there any difference by using `rtmpStream.attachScreen(ScreenCaptureSession(viewToCapture: self.view))`? I just want to share the screen of my app

**Comment by shogo4405** [comment]
I needs steps to reproduce the behavior, additional context.
Please use the bug report template.
