### ISSUE TITLE
Streaming via RTMP results in a reasonable amount of lag

### ISSUE THREAD

**Issue by dindin44** [shogo4405/HaishinKit.swift#729]
I am trying to share my screen capture via RTMP to another device, but am experiencing quite a reasonable amount of lag on the other device. It is currently about 10 seconds before the stream updates.

I am a complete beginner with regards to video, so I apologise if I am missing something simple. I'm not sure if this is related to the settings I am using, but any help would be great thanks.

My current settings are

```
rtmpStream.captureSettings = [
            .sessionPreset: AVCaptureSession.Preset.low, 
             .preferredVideoStabilizationMode: AVCaptureVideoStabilizationMode.off
]
rtmpStream.videoSettings = [
            .width: 320,
            .height: 480,
            .bitrate: 160 * 1000, // video output bitrate
            .profileLevel: kVTProfileLevel_H264_Baseline_5_2, 
            .maxKeyFrameIntervalDuration: 2,
]
```

I have tried streaming from both an iPhone 7 and 10.5 inch iPad, and noticed the large lag from both.

**Comment by dindin44** [comment]
Also worth noting I mean using `ScreenCaptureSession` rather than the camera

**Comment by shogo4405** [comment]
> It is currently about 10 seconds before the stream updates.

RTMP has latency 2sec 〜 30sec. 
It's depends on server side settings.

Please use the bug report template.
