### ISSUE TITLE
Getting random video sizes while always streaming with the same settings. ( seen as black bars on the sides of some of the videos )

### ISSUE THREAD

**Issue by alongenosar** [shogo4405/HaishinKit.swift#730]
**Describe the bug**
Getting random video sizes while always streaming with the same settings.
Black bars appears on **some** of the recorded  videos

**Expected behaviour**
I Expect all videos streamed with the same settings to have the same size, without the black bars on the sides

**Screenshots**
<img width="912" alt="Screen Shot 2020-08-12 at 7 56 25" src="https://user-images.githubusercontent.com/10558287/89979080-8d6a6300-dc77-11ea-8a14-7f77f35ec242.png">

**Additional context**
Code snippets for creating the stream
```
    func createStream(bitrate: UInt, _ callback: (() -> Void)? = nil) {
        // RtmpStream
        rtmpStream = RTMPStream(connection: rtmpConnection)
        rtmpStream.attachAudio(AVCaptureDevice.default(for: AVMediaType.audio))
        rtmpStream.attachCamera(DeviceUtil.device(withPosition: .back))

        // RtmpStream Config
        rtmpStream.captureSettings = [
            .fps: 30,
            .sessionPreset: AVCaptureSession.Preset.hd1280x720, // input video width/height
            .isVideoMirrored: false,
            //.continuousAutofocus: true, // use camera autofocus mode
            // .continuousExposure: true, //  use camera exposure mode
            // .preferredVideoStabilizationMode: AVCaptureVideoStabilizationMode.auto
        ]

        rtmpStream.audioSettings = [
            .muted: false, // mute audio
            .bitrate: 32 * 1024,
        ]

        rtmpStream.videoSettings = [
            .scalingMode: ScalingMode.letterbox,
            .width: 1280, // video output width
            .height: 720, // video output height
            .bitrate: bitrate, // video output bitrate
            .profileLevel: kVTProfileLevel_H264_Baseline_3_1, // H264 Profile require "import VideoToolbox"
            .maxKeyFrameIntervalDuration: 2, // key frame / sec
        ]

        rtmpStream.orientation = .landscapeLeft

        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5, execute: {
            self.hkView.attachStream(self.rtmpStream)
            callback?()
        })
    }

   func start(streamName: String, videoBitrate: UInt = 2 * 1024 * 1024) {
        guard state == .stopped else { return }
        state = .starting
        createStream(bitrate: videoBitrate) {
            self.rtmpConnection.connect(self.serverAddress)
            self.rtmpStream.publish(streamName)
        }
    }
```

**Comment by shogo4405** [comment]
> Getting random video sizes while always streaming with the same settings.

- Is this same devices? If device can't support `AVCaptureSession.Preset.hd1280x720`, then cause this issue.
- It seemes that a webpage, how about playback  recorded videos with VLCPlayer?

## Please try setup orders
  1. rtmpStream.orientation = .landscapeLeft // with main thread
  1. rtmpStream.attachCamera(DeviceUtil.device(withPosition: .back))

**Comment by alongenosar** [comment]
Hi, Thanks you for the fast response
All videos are captured with the same device, a brand new iPhone se 2 (2020), but I also get the same problems with other devices.
Captured videos looks the same when played on VLC Player, or Safari.
I tried the setup order you suggested, but still get the same result 

Thanks
Alon

**Comment by shogo4405** [comment]
I can reproduce this issue. I will close this issue.

**Comment by alongenosar** [comment]
you wrote that you **can** reproduce it?

**Comment by shogo4405** [comment]
I'm wrong. I **can't** reproduce it.
