### ISSUE TITLE
Streaming app screen via RTMP to Twitch results in 10 second lag

### ISSUE THREAD

**Issue by dindin44** [shogo4405/HaishinKit.swift#732]
**Describe the bug**
I am trying to share my screen capture using `ScreenCaptureSession` via RTMP to Twitch, but am experiencing around a ten second lag before the stream updates on their side. I tried using the camera feed instead, and the lag is much less.

**To Reproduce**
1. Set up an account on Twitch.
2. Set up new project in Xcode 11.6 with a slider, and import HaishinKit.
3. Set up RTMP connection and stream with the following settings:
```
rtmpStream.captureSettings = [
            .sessionPreset: AVCaptureSession.Preset.low
             .preferredVideoStabilizationMode: AVCaptureVideoStabilizationMode.off
]
        
rtmpStream.videoSettings = [
            .width: 400,
            .height: 200,
            .profileLevel: kVTProfileLevel_H264_Baseline_AutoLevel
]

rtmpStream.attachScreen(ScreenCaptureSession(viewToCapture: self.view))
```
4. Connect to Twitch RTMP URL and publish to Twitch Stream Key
5. Once live, move the slider up and down and notice the lag in which the Twitch stream updates.

**Expected behavior**
I expect that the lag for screen capturing should be similar to the one streaming the camera feed. At the moment, there is a 5 second discrepancy between the two. 

**Screenshots**
![Screenshot 2020-08-12 at 09 51 37](https://user-images.githubusercontent.com/64090963/89995493-716bbf00-dc81-11ea-91f9-ede2573487fd.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.6
 - Browser: Chrome
 - Version: 84.0.4147.105

**Smartphone (please complete the following information):**
 - Device: iPhone 7, iPad 10.5 inch
 - OS: iOS 13.3.1

**Comment by shogo4405** [comment]
The `ScreenCaptureSession` has  performance issues.
HaishinKit call the UIView#drawHierarchy method internally. Unfortunately, this method is too heavy.
So I can't resolve this issue.
