### ISSUE TITLE
What does RTMPStream.receiveAudio do?

### ISSUE THREAD

**Issue by ArchForge** [shogo4405/HaishinKit.swift#735]
Hello!
I'm examining a sound issue I'm having, and I came across this property (RTMPStream.receiveAudio).
I don't really understand what it does, so could anyone be kind enough to enlighten me?

**Comment by shogo4405** [comment]
This property determine to receive RTMPAudioMessages from server when playback mode.

- It’s not stabled.
- Also have to implements the server side. It works OK the Wowza. Not works for me the nginx + rtmp module
