### ISSUE TITLE
iPadOS 14 compatibility

### ISSUE THREAD

**Issue by alexpli** [shogo4405/HaishinKit.swift#747]
**Describe the bug**
HaishinKit doesn't seem to be working on iOS 14.

**To Reproduce**
Just copy the sample source code https://github.com/shogo4405/HaishinKit.swift#rtmp-usage in your project (and change the connection URI and stream name).

**Screenshots**
HKView seems to start rendering : 
![IMG_B9BD8BD9919B-1](https://user-images.githubusercontent.com/12477869/92360566-4e4ff600-f0ed-11ea-80bb-2d1335ff56e7.jpeg)

**Device**
 - iPad mini 4 - iOS 14 beta 7

**Additional context**
- There is no crash or force-close
- There is only one message log in console : `[com.haishinkit.HaishinKit] [VideoIOComponent.swift:96] fps > (fps: 30.0, duration: __C.CMTime(value: 100, timescale: 3000, flags: __C.CMTimeFlags(rawValue: 1), epoch: 0))`
- There is no error detected during compilation
- I tried with the [feature/xcode12](https://github.com/shogo4405/HaishinKit.swift/tree/feature/xcode12) branch. Same results.

**Comment by mkrn** [comment]
FYI Just tried our app in iOS14 beta 7, iPhone 11 and streaming worked as expected.
Curious what this issue might be.

**Comment by alexpli** [comment]
Yes, I've just tried with iPhone 11 iOS14 beta 7 and It works.
So, the issue come from iPadOS 14.

**Comment by shogo4405** [comment]
Thank you for your feedback.
I tested iPadOS14 beta 7 build with Xcode12.0. It works for me :(

Can I see trace log?
`Logboard.with(HaishinKitIdentifier).level = .trace`

**Comment by alexpli** [comment]
Log : [log.txt](https://github.com/shogo4405/HaishinKit.swift/files/5200737/log.txt)

**Comment by shogo4405** [comment]
How about iPasOS14.0 official version with Xcode12.0? Still can't work? It works OK for me.
I saw this log. It seems that disconnect by a server side. I need a server log.  
https://github.com/shogo4405/HaishinKit.swift/issues/747#issuecomment-690126385

**Comment by alexpli** [comment]
Yes, it works with final version. 
Sorry for the inconvenience.
