### ISSUE TITLE
Audio disappearing

### ISSUE THREAD

**Issue by ArchForge** [shogo4405/HaishinKit.swift#749]
**Describe the bug**
After streaming RTMP for 5-25 seconds, audio is lost following a tiny chop in the video, and audio is gone for the rest of the stream. It's rare but still a significant issue.

In the beginning of the stream, the audio bitrate is steady at about 48k (or whatever level is set). After the audio cuts off, the audio bitrate is constant at about 5k, as if it's only sending metadata or something. Incidentally, this audio bitrate is the same as the audio bitrate when audio is muted. 

Muting and Unmuting does not turn it back on. I know from logging that the user hasn't accidentally muted the stream.

**To Reproduce**
I can't reliably reproduce it. I've seen it happen (rarely) among end users.

**Smartphone (please complete the following information):**
 - iOS (no specific device or iOS version)
- HaishinKit v. 1.0.11
- We're streaming passthough rtmp to wowza streaming cloud (if that matters)

**Additional context**
I'm currently attempting a workaround to reconnect when this happens, to see if that can make the sound return. Will take a while to get results.

**Comment by mkrn** [comment]
I had a few streams with no sound at all 
As if Audio stream is missing. 
Is that the same issue? 
Otherwise I can open a new issue and try to look into why it can happen

Data from ffprobe:
```
  Duration: 00:21:54.03, start: 1.999000, bitrate: 2047 kb/s
    Stream #0:0: Data: none
    Stream #0:1: Video: h264 (High), yuv420p(progressive), 1280x720, 30 fps, 30 tbr, 1k tbn
Unsupported codec with id 0 for input stream 0
```

**Comment by CubitSpeed** [comment]
Possibly related, audio appears to be lost sometimes when receiving a phone call:
Also see #755

Possibly also same issue?

**Comment by ArchForge** [comment]
@mkrn I've had some where the audio has been missing for the entire stream, but most often it disappears after streaming for 10-20 seconds. Not sure if those are separate issues or if the audio simply disappears before stream is live. I've also tested now to reconnect after audio disappears, but it does not return the audio.

@CubitSpeed Phone calls, messages and notifications can all cause audio interruptions when streaming, and can be handled with AVAudioSessionInterruptionNotification and CallKit. I'm not sure if HaishinKit handles it, but when I've tested, these rarely cause sound issues when livestreaming. But I'm certain it's not the same issue as the one I'm describing.

**Comment by mkrn** [comment]
@ArchForge Does it happen to you lately? I've had another instance where the audio track was missing entirely. Cannot reproduce. I'm handling audio interruptions properly.
How do you detect if the audio is missing in the code?

Thanks

**Comment by ArchForge** [comment]
@mkrn We've now replaced HaishinKit for streaming. However, I figured out that the issue we had was that rare circumstances in our app, caused by a SignalR message related to our streaming, in turn caused the AVAudioSessionCategory to change, which interfered with the audio in the livestream. Not sure if that helps you.
