### ISSUE TITLE
Xcode12 + CocoaPods: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by chrisid** [shogo4405/HaishinKit.swift#753]
**Describe the bug**
Build error on Xcode 12

**To Reproduce**
1. Install the pod
2. Try to build the project on XCode (Swift 5)

**Expected behavior**
Build

`Undefined symbols for architecture x86_64:
  "__swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers", referenced from:
      __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_HaishinKit in libHaishinKit.a(ASClass.o)
      __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_HaishinKit in libHaishinKit.a(AVRecorder.o)
      __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_HaishinKit in libHaishinKit.a(GLHKView.o)
      __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_HaishinKit in libHaishinKit.a(HTTPService.o)
      __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_HaishinKit in libHaishinKit.a(IOComponent.o)
      __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_HaishinKit in libHaishinKit.a(AudioIOComponent.o)
      __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_HaishinKit in libHaishinKit.a(MTHKView.o)
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_HaishinKit)
  "__swift_FORCE_LOAD_$_swiftCoreMIDI", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreMIDI_$_HaishinKit in libHaishinKit.a(ASClass.o)
      __swift_FORCE_LOAD_$_swiftCoreMIDI_$_HaishinKit in libHaishinKit.a(AVRecorder.o)
      __swift_FORCE_LOAD_$_swiftCoreMIDI_$_HaishinKit in libHaishinKit.a(GLHKView.o)
      __swift_FORCE_LOAD_$_swiftCoreMIDI_$_HaishinKit in libHaishinKit.a(HTTPService.o)
      __swift_FORCE_LOAD_$_swiftCoreMIDI_$_HaishinKit in libHaishinKit.a(IOComponent.o)
      __swift_FORCE_LOAD_$_swiftCoreMIDI_$_HaishinKit in libHaishinKit.a(AudioIOComponent.o)
      __swift_FORCE_LOAD_$_swiftCoreMIDI_$_HaishinKit in libHaishinKit.a(MTHKView.o)
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreMIDI_$_HaishinKit)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by shogo4405** [comment]
It works for me. I can build on xcode12 + cocoapods.
https://github.com/shogo4405/HaishinKit-CocoaPods-Test

**Comment by chrisid** [comment]
The issue seems to be with cocoapods if you have more Dynamic and Static. I'm using this with React Native.
I'm guessing (and hoping) is related to this:
https://github.com/CocoaPods/CocoaPods/issues/9525

**Comment by shogo4405** [comment]
I heard fixd it. Please try.
gem 'cocoapods', ">= 1.10.0.rc.1"

I will close this issue.

**Comment by crpr** [comment]
I'm having the exact same problem. Already have that version of cocoapods.
