### ISSUE TITLE
Playback becomes choppy or freezes when connecting headphones

### ISSUE THREAD

**Issue by calinbodnar** [shogo4405/HaishinKit.swift#754]
**Describe the bug**
I'm using the library in a video conferencing app; that is, I'm using both streaming and playback (at the same time). All works fine until I connect the headphones when I've noticed that the playback becomes really choppy and sometimes freezes.

The logs get flooded by this warning message (full logs attached):
`[AudioIOComponent.swift:233] sampleOutput(audio:presentationTimeStamp:) > required condition is false: _engine->IsRunning()`

Any input on how to solve this would be highly appreciated.

**To Reproduce**
1. Publish stream and start playback
2. Connect headphones
3. Check video playback quality

**Expected behavior**
The stream plays normally (as it did before connecting the headphones)

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 13.1.3

**Additional context**
AVSession setup:

```
let session = AVAudioSession.sharedInstance()
do {
    try session.setCategory(.playAndRecord,
                            mode: .videoChat,
                            options: [.defaultToSpeaker,
                                      .allowBluetooth])
    } catch {
          print(error.localizedDescription)
    }
```

Playback setup:

```
self.rtmpConnection = RTMPConnection()
self.rtmpConnection.requireNetworkFramework = true
self.rtmpStream = RTMPStream(connection: rtmpConnection)

self.rtmpConnection.connect(STREAM_URL)
self.rtmpStream.play(STREAM_NAME)
```

Stream configuration:

```
self.rtmpStream.captureSettings = [
            .fps: 30,
            .sessionPreset: .medium,
            .preferredVideoStabilizationMode: AVCaptureVideoStabilizationMode.off.rawValue,
            .continuousAutofocus: false,
            .continuousExposure: false
        ]

self.rtmpStream.videoSettings = [
            .width: 960,
            .height: 540,
            .bitrate: 300_000,
            .profileLevel: kVTProfileLevel_H264_Main_AutoLevel
        ]

self.rtmpStream.audioSettings = [
            .muted: false,
            .bitrate: 32_768
        ]
```

[logs_debug.txt](https://github.com/shogo4405/HaishinKit.swift/files/5244834/logs_debug.txt)

**Comment by calinbodnar** [comment]
@shogo4405 Hi, just wondering if you managed to have a look at this issue? I can provide more logs if necessary.
Any suggestions of how to overcome it would be appreciated. Thanks.

**Comment by shogo4405** [comment]
Thank you feedback.
