### ISSUE TITLE
Audio Interruption causes AVSync disparity

### ISSUE THREAD

**Issue by ryango** [shogo4405/HaishinKit.swift#755]
[Audio interruptions](https://developer.apple.com/documentation/avfoundation/avaudiosession/responding_to_audio_session_interruptions) cause AV sync issues. Because video frames continue to be sent while audio frames are not sent, remote playback now has disparity between audio and video.

**To Reproduce**
Launch sample app, call phone and let it ring, observer broadcast AV sync issues after it recovers.

**Expected behavior**
Timestamps provided in the samplebuffers inform the encoder of how to synchronize buffers

**Comment by CubitSpeed** [comment]
Wanted to chime in:
I was streaming, received a phone call, and afterwards audio was not present in the stream. Interestingly, audio came back after I received a second phone call (during the same stream).

I am not able to reliably recreate the above scenario.

**Comment by tatuanfpt** [comment]
Any update for this ? I am facing the same issue.
