### ISSUE TITLE
Please tell how to add server_url, stream_key and stream_name 

### ISSUE THREAD

**Issue by tejaskdubal** [shogo4405/HaishinKit.swift#756]
How I tried - 
struct Preference {
    static var defaultInstance = Preference()

    var uri: String? = "rtmp://fso34-1.streamhoster.com/{Stream_Key}"
    var streamName: String? = "stream_name"
}

I tried all the ways from other issues but not able to stream at all.

I think this should be added in Readme too that how to pass these three parameters.

Please help.

**Comment by shogo4405** [comment]
I update README.md
 - https://github.com/shogo4405/HaishinKit.swift/blob/master/README.md#rtml-url-format

**Comment by tejaskdubal** [comment]
> I update README.md
> 
> * https://github.com/shogo4405/HaishinKit.swift/blob/master/README.md#rtml-url-format

Thanks!
