### ISSUE TITLE
Beauty Face Filter

### ISSUE THREAD

**Issue by duyhct** [shogo4405/HaishinKit.swift#757]
Will you update Beauty Face Filter Feature on this project? Or can you suggest for me to add some beauty function into your code?
Thank you and waiting for your reply!

**Comment by shogo4405** [comment]
> Will you update Beauty Face Filter Feature on this project?

No.

> Or can you suggest for me to add some beauty function into your code?

HaishinKit has feature that a custom filter for a visualization.
 - https://github.com/shogo4405/HaishinKit.swift/blob/master/Examples/iOS/VisualEffect.swift#L37-L49
 - rtmpStream.registerVideoEffect(currentEffect)

Please create your own a beauty filter.

**Comment by duyhct** [comment]
Thank you for your reply
