### ISSUE TITLE
Continue local recording even if something went wrong in live streaming 

### ISSUE THREAD

**Issue by tejaskdubal** [shogo4405/HaishinKit.swift#760]
1. Users start live streaming.
2. Streaming works well for 30min.
3. Streaming got into some problems because of network issues or RTMP server issues.

I think this could be the usual situation.

Current Problem  - 
Users will not able to record/save the remaining part of streaming.

The solution could be - 
Allow users to continue local recording even after live streaming got into a problem.

Current alternatives I considered -
When live streaming went into problem show alert for offline record and navigate them to another screen (which is not that much feasible solution).

Please think about this.
Thanks for this awesome library.

**Comment by shogo4405** [comment]
Thank you feedback. Currently, priority is low. I will close.
If I feel like it, reopen then implement.

**Comment by floriangbh** [comment]
I'm very interested to record even if an issue appear with the stream. 
Did you find any solution @tejaskdubal ? 
Thanks

**Comment by mkrn** [comment]
@floriangbh  Yes, very easy fix: https://github.com/mkrn/HaishinKit.swift/commit/b45f8e38d5ed403e2e71a85b5a2577d83a023394#diff-7a25799241cc9c1986657e30d9359979568f52c00dc5825355d91540e5c693a5L270

**Comment by floriangbh** [comment]
Thanks @mkrn :)
