### ISSUE TITLE
Screen casting process stops after 30 minutes

### ISSUE THREAD

**Issue by aliuzunoglu** [shogo4405/HaishinKit.swift#762]
I am trying to implement your example broadcast upload extension file with 1280x720 resolution and after 30 min screen casting stops.

I am testing on iphone 11, ios 14.0.1.

my sampleHandler code is 
`
   
      override open func broadcastStarted(withSetupInfo setupInfo: [String: NSObject]?) {
        
        rtmpStream.captureSettings = [
            .fps: 24,
            .sessionPreset: AVCaptureSession.Preset.hd1280x720, // input video width/height
        ]
        
        rtmpStream.audioSettings = [
            .muted: false, // mute audio
            .bitrate: 128000,
        ]
        
        rtmpStream.videoSettings = [
            .width: 1280, // video output width
            .height: 720, // video output height
            .bitrate: 2 * 1280 * 720, // video output bitrate
        ]
        
        logger.level = .debug
        Logboard.with(HaishinKitIdentifier).level = .trace
        rtmpConnection.connect(Preference.defaultInstance.uri!, arguments: nil)
    }

    override open func processSampleBuffer(_ sampleBuffer: CMSampleBuffer, with sampleBufferType: RPSampleBufferType) {
        switch sampleBufferType {
        case .video:
            
            rtmpStream.appendSampleBuffer(sampleBuffer, withType: .video)
        case .audioApp:
            break
        case .audioMic:
            rtmpStream.appendSampleBuffer(sampleBuffer, withType: .audio)
        @unknown default:
            break
        }
    }`

**Comment by shogo4405** [comment]
ReplayKit is buggy. I can't help you.
