### ISSUE TITLE
Is there a way to be notified when and how much bytes sent sent through the socket?

### ISSUE THREAD

**Issue by alongenosar** [shogo4405/HaishinKit.swift#763]
Is there a way to be notified when and how much bytes sent through the socket?

**Comment by shogo4405** [comment]
Yes. You can get these properties.
- rtmpConneciton.totalBytesOut
- rtmpConnection.currentBytesOutPerSecond

**Comment by alongenosar** [comment]
Is there a way to observe this values for changes?

**Comment by shogo4405** [comment]
Realtime observe no way.
But you can get observe per seconds. 
https://shogo4405.github.io/HaishinKit.swift/Protocols/RTMPStreamDelegate.html#/s:10HaishinKit18RTMPStreamDelegateP10rtmpStream_10didStaticsyAA0C0C_AA14RTMPConnectionCtF
