### ISSUE TITLE
Index out of range error in H264+AVC.swift

### ISSUE THREAD

**Issue by iAmcR** [shogo4405/HaishinKit.swift#764]
During RTMP Playback in the Example iOS app, there is an Index out of range error in AVCConfigurationRecord.createFormatDescription(_:) at Sources/ISO/H264+AVC.swift:87

1. Configure uri and streamName in Preference.swift
2. Run target: Example iOS on device (iPhone X, iOS 14.0.1)
3. Tap "Playback" on Tab bar. Then tap play button. 
4. See error in logs and debugger: 

`020-08-10 10:46:56.133 [Info] [com.haishinkit.Exsample.iOS] [PlaybackViewController.swift:55] rtmpStatusHandler(_:) > NetConnection.Connect.Success`
`2020-08-10 10:46:56.200 [Info] [com.haishinkit.Exsample.iOS] [PlaybackViewController.swift:55] rtmpStatusHandler(_:) > NetStream.Play.Start`
`2020-08-10 10:46:56.888 [Error] [com.haishinkit.HaishinKit] [H264+AVC.swift:148] data > ByteArray{data: 179642 bytes,position: 166127}`
`Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift, line 444
2020-10-08 10:46:56.889105-0500 Example iOS[11337:3543438] Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift, line 444`

The error is caused by the following in AVCConfigurationRecord.createFormatDescription(_:) at Sources/ISO/H264+AVC.swift:87: 

`UnsafePointer<UInt8>(pictureParameterSets[0])`

**Expected behavior**
Playback occurs with video displayed in the PlaybackViewController.

**Smartphone:**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 14.0.1]

**Additional Context:**
This occurs whether the view of the PlaybackViewController is of type GLHKView or MTHKView. 
Playback of the RTMP source was verified with VLC. 

I hope you get a chance to look into this. Thank you for the great library!

**Comment by shogo4405** [comment]
Thank you your feedback.
I can't reproduce. Do you know publish source settings?

**Comment by iAmcR** [comment]
I just did a screen recording and send to a docker nginx-rtmp as follows: 
 
ffmpeg -f avfoundation -framerate 30  -i "1:0" -f flv rtmp://localhost:1935/video/me
