### ISSUE TITLE
Presentation timestamp custom value

### ISSUE THREAD

**Issue by MarcFerry** [shogo4405/HaishinKit.swift#768]
Hello,

I am currently using this library to livestream multiple feeds. 
In order to synchronise the feeds server-side I'd like to be able to set the presentation timestamp as a live timestamp.
Currently it uses the iPhone mach time (time since last reboot) and I have not found how to change it.
Could you add a way to set a custom initial value ?

Thanks,

**Comment by shogo4405** [comment]
> Could you add a way to set a custom initial value ?

I have no plan. Thank u.
