### ISSUE TITLE
Single RTMP URL for streaming

### ISSUE THREAD

**Issue by iantimmis** [shogo4405/HaishinKit.swift#773]
**Is your feature request related to a problem? Please describe.**

Most applications which allow you to stream video over RTMP only require a single URL to the RTMP destination. This library requires a server URI and StreamName. There have been several issues similar to https://github.com/shogo4405/HaishinKit.swift/issues/336 where developers are unaware of how to split the URL up properly.

**Describe the solution you'd like**

It would be very helpful if one could use a single URL as input to HaishinKit, and the library would work out the details on its own.

**Comment by shogo4405** [comment]
RTMP protocol can publish and playback multi RTMPStream with one RTMPConnection
I designed this.

Please see README and this line.
- https://github.com/shogo4405/HaishinKit.swift#rtml-url-format

Best regards.
