### ISSUE TITLE
Feature request: Stream duration

### ISSUE THREAD

**Issue by iantimmis** [shogo4405/HaishinKit.swift#774]
**Is your feature request related to a problem? Please describe.**
Neither of the rtmpConnection/rtmpStream objects provide the duration of the stream.  

**Describe the solution you'd like**
In the same way that we monitor rtmpStatus and ioError, it would be very useful to have a stream duration event listener.

```swift
// Already exists
rtmpConnection.addEventListener(.rtmpStatus, selector: #selector(rtmpStatusHandler), observer: self)
rtmpConnection.addEventListener(.ioError, selector: #selector(rtmpErrorHandler), observer: self)

// Desired. updated once per second with the duration of the current stream
rtmpConnection.addEventListener(.streamDuration, selector: #selector(streamDurationHandler), observer: self)
```

**Comment by shogo4405** [comment]
Please use RTMPStreamDelegate#rtmpStream(_ stream: RTMPStream, didStatics connection: RTMPConnection) 
https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/RTMP/RTMPStreamDelegate.swift#L14
