### ISSUE TITLE
Akamai RTMP not working, Wowza RTMP is working

### ISSUE THREAD

**Issue by d3vilmayc4y** [shogo4405/HaishinKit.swift#780]
I am using Dacast(Akamai) credentials for streaming, which throws below error 

> rtmpStatusHandler
> Event{type: Name(rawValue: "rtmpStatus"),bubbles: false,data: Optional(Optional(["level": Optional("error"), "code": Optional("NetConnection.Connect.Rejected"), "description": Optional("[ AccessManager.Reject ] : [ code=403 need auth; authmod=adobe ]")])),target: Optional(HaishinKit.RTMPConnection)}
> ["level": Optional("error"), "code": Optional("NetConnection.Connect.Rejected"), "description": Optional("[ AccessManager.Reject ] : [ code=403 need auth; authmod=adobe ]")]
> NetConnection.Connect.Rejected
> 

I tested with Wowza credentials, its working.

This is how i pass credentials,

**Akamai**

> var streamUrl = "rtmp://1049604:773016@p.epXXXXXX.i.akamaientrypoint.net/EntryPoint"
> var streamName = "dclive_1_150@XXXXXX"

**Wowza**

> var streamUrl = "rtmp://test:test123@XXX.XXX.XXX.XXX:1935/live"
> var streamName = "iostest@123"

**Comment by floriangbh** [comment]
Hello @d3vilmayc4y,

When you say Wowza is working, does it work at the first connect attemp ? 
In my case, when there is credentials it's working only at the 3th attempt (like in this issue https://github.com/shogo4405/HaishinKit.swift/issues/682).

Thanks

**Comment by shogo4405** [comment]
I can't debug the Akamai.
I'm individual developer.  I can't contract the Akamai.

Please resolve yourself!
