### ISSUE TITLE
APPEND SAMPLE VIDEO IN LIVE STREAM OF MUX WITH HAISHINKIT

### ISSUE THREAD

**Issue by ArungokulPersonal** [shogo4405/HaishinKit.swift#781]
Hi Everyone, 

Does anyone have any idea to append a static video in the RTMP stream using haishinkit in the MUX stream? If I use the below code 

/********* CODE ***********/
rtmpStream.appendFile(URL.init(string: "")) {
            
            }
/********* CODE ***********/
the app is crashing in the MP4Sample in line no 72 of cocoa Pods with version 1.1.0(latest). 

                self.lockQueue.sync {

In the above line.

Kindly give some suggestions on how to append a static video at the end of a live stream.

Thanks!

**Comment by abubaqr70** [comment]
@ArungokulPersonal have you find the way to append the static video in the rtmp stream
