### ISSUE TITLE
Сrash when user swipes up-down "Notifications Center" view while streaming

### ISSUE THREAD

**Issue by rybachenko2206** [shogo4405/HaishinKit.swift#784]
**Describe the bug**

**To Reproduce**
1. Start Streaming
2. Put finger on top of the screen and swipe down and then swipe up to open-close  "Notificaions Center" Screen
3. Repeat p.2 two or a few more times
4. Crash received In the class RTMPConnection line 434
"Thread 1 "-[NSTaggedPointerString countByEnumeratingWithState: object: count:]: unrecognised selector sent to instance ....

**Expected behavior**

**Screenshots**
video: https://drive.google.com/file/d/1zu019FUr9KoFDOlwI7sx2anqzCPaHSn0/view
screenshot:
 https://drive.google.com/file/d/1zu019FUr9KoFDOlwI7sx2anqzCPaHSn0/view
 

**Smartphone (please complete the following information):**
 - Device: iPhone SE, iPhone 7+
 - OS: iOS 13.6.1, 
 - Browser  - 
 - Version -

**Additional context**

**Comment by shogo4405** [comment]
I can't reporoduce it. I tested iOS14.2.
If it can reproduce my exsamples. I'm able to rearch.
