### ISSUE TITLE
RTMPConnection objects do not appear to be re-usable after they enter the NetConnection.Connect.Closed state

### ISSUE THREAD

**Issue by GeneticGenesis** [shogo4405/HaishinKit.swift#785]
HaishinKit Version: 1.1.1 (latest)
iOS Version 14.1 / 14.2

Thanks for all the hard work, I'm running into a problem re-using RTMPConnections after they enter the NetConnection.Connect.Closed state.

I'm using latest HaishinKit. My example flow here is simple - I'm attempting to re-use a RTMPConnection after it's entered the `NetConnection.Connect.Closed` state.

Is this intentional? If not, is there some flow that I'm missing around making the RTMPConnection reusable?

I did check other examples on issues including #456 and #555 and they seem to imply that this should be possible. 

**Expected Behaviour:**
Calling `connect` on an `RTMPConnection` in the `NetConnection.Connect.Closed` state, should attempt to re-connect to the RTMP server.

**Observed Behaviour:**
The `RTMPConnection` immediately enters the `NetConnection.Connect.Failed` state.

**Steps to reproduce:**

First, create and RTMPConnection, and start streaming to it:
```
// Initial configuration not shown

 if !rtmpConnection.connected {
    rtmpConnection.connect("rtmp://server:port/app/")
}

rtmpStream.publish("STREAM-KEY")
```

The stream connects successfully and starts streaming.
```
name = rtmpStatus/false, object = Optional(HaishinKit.RTMPConnection), userInfo = Optional([AnyHashable("event"): Event{type: Name(rawValue: "rtmpStatus"),bubbles: false,data: Optional(Optional(["description": Optional("Start publishing"), "code": Optional("NetStream.Publish.Start"), "level": Optional("status")])),target: Optional(HaishinKit.RTMPConnection)}])
```

Later, disconnect from that stream:

```
rtmpStream.close()
```

The unpublish happens fine:
```
name = rtmpStatus/false, object = Optional(HaishinKit.RTMPConnection), userInfo = Optional([AnyHashable("event"): Event{type: Name(rawValue: "rtmpStatus"),bubbles: false,data: Optional(Optional(["code": Optional("NetStream.Unpublish.Success"), "level": Optional("status"), "description": Optional("Stop publishing")])),target: Optional(HaishinKit.RTMPConnection)}])
```

After while, the connection will transition to `NetConnection.Connect.Closed`:
```
name = rtmpStatus/false, object = Optional(HaishinKit.RTMPConnection), userInfo = Optional([AnyHashable("event"): Event{type: Name(rawValue: "rtmpStatus"),bubbles: false,data: Optional(["level": Optional("status"), "description": Optional(""), "code": Optional("NetConnection.Connect.Closed")]),target: Optional(HaishinKit.RTMPConnection)}])
```

Once this has happened, attempting to call `connect` on the RTMPConnection will produce a `NetConnection.Connect.Failed`:

```
 if !rtmpConnection.connected {
    rtmpConnection.connect("rtmp://server:port/app/")
}
```

Results in:
```
name = rtmpStatus/false, object = Optional(HaishinKit.RTMPConnection), userInfo = Optional([AnyHashable("event"): Event{type: Name(rawValue: "rtmpStatus"),bubbles: false,data: Optional(["code": Optional("NetConnection.Connect.Failed"), "level": Optional("error"), "description": Optional("")]),target: Optional(HaishinKit.RTMPConnection)}])
```

Thanks!

**Comment by GeneticGenesis** [comment]
So after a little more digging, this happens when you don't wait for the callback saying that the `RTMPConnection` is connected before calling `publish()`.

It appears to be safe to call `connect()` followed by `publish()` immediately after provided that the `RTMPConnection` hasn't been used yet, _but_ if the `RTMPConnection` has been used previously, you _must_ wait for the `RTMPConnection` to transition back to `RTMPConnection.Code.connectSuccess` before you call `publish()`.

I'm not 100% sure if this is expected behaviour, but that's what's going on here for sure.

**Comment by shogo4405** [comment]
> It appears to be safe to call connect() followed by publish() immediately after provided that the

https://github.com/shogo4405/HaishinKit.swift/blob/master/Examples/iOS/LiveViewController.swift#L149-L171

I designed Notification callback base. Please try this one.
