### ISSUE TITLE
Logboard was compiled with optimization 

### ISSUE THREAD

**Issue by KAZUMA87** [shogo4405/HaishinKit.swift#786]
**Describe the bug**
When you start streaming, the LogBoard crashes giving an error.
In Xcode, Logboard was compiled with optimization - stepping may behave oddly; variables may not be available.
I get the following message.

Logboard was introduced using carthage and is written using v2.2, HaishinKit is written using v1.1.1, Xcode is written using 12.1 and Swift is written using 5.3. I turned off all the optimization options, but there was no change.

Is there any way to resolve this?

**Smartphone (please complete the following information):**
 - Device: iPodTouch 7th
 - OS: iOS13.7

----Japanese----
ストリーミングを開始しようとすると、クラッシュする。Xcode上では、Logboard was compiled with optimization - stepping may behave oddly; variables may not be available.と表示される。
Xcodeでのコンパイル最適化オプションをすべてオフにするなどしたが、変化は無かった。
Logboard、HaishinKitはCarthage経由で導入し、それぞれv2.2およびv1.1.1を利用している。
何からの解決策があれば、ご教授頂きたい。

**Comment by DmitriiChikovinskii** [comment]
Hi! Try to change Carthage to Pods, it should help you.

**Comment by KAZUMA87** [comment]
Thanks to @DmitriiChikovinskii , changed from carthage to cocoaPod and the problem no longer arises.

**Comment by shogo4405** [comment]
Might be fixed it 263c6a3.
