### ISSUE TITLE
Clarification on Adaptive bitrate functionality

### ISSUE THREAD

**Issue by GeneticGenesis** [shogo4405/HaishinKit.swift#787]
Hey @shogo4405, thanks again for the hard work. 

Can I get some clarification on if and how ABR functionality for RTMP is expected to work right now. 

In the initial implementation issue (https://github.com/shogo4405/HaishinKit.swift/issues/126) a couple of features were added:

1) Added automatic frame dropping
2) Added a QoS delegate to RTMPStream

It appears that at this time both of those pieces of code have now been removed from the implementation. 

Is it likely that this will be re-added, or is there a replacement way implementing ABR in Haishinkit right now?

Thanks.

**Comment by shogo4405** [comment]
> code have now been removed from the implementation.

 Not removed.
- Added automatic frame dropping
  -  https://github.com/shogo4405/HaishinKit.swift/blob/192493c5fa470e45740fab90f4a3610d85736510/Sources/Codec/H264Encoder.swift#L248-L250
  - If locked = true, HaishinKit will drop a frame.
- I renamed from RTMPStreamQoSDelagate to RTMPStreamDelegate.
  - https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/RTMP/RTMPStreamDelegate.swift

Thank you.

**Comment by GeneticGenesis** [comment]
Thanks @shogo4405, let me implement these and see how it goes!
