### ISSUE TITLE
HLStream crashes after a while

### ISSUE THREAD

**Issue by sokold** [shogo4405/HaishinKit.swift#788]
**Describe the bug**
streaming with HLSService and HTTPStream, it works and after a while the app frequently crashes at
```
 private mutating func extend(_ data: Data) {
            if 0 < top {
                let subdata = self.data.subdata(in: 0..<bottom)
                self.data.replaceSubrange(0..<capacity - top, with: self.data.advanced(by: top))
                self.data.replaceSubrange(capacity - top..<capacity - top + subdata.count, with: subdata) // <--- crashed here
                bottom = capacity - top + subdata.count
            }
            self.data.append(.init(count: capacity))
            top = 0
            capacity = self.data.count
            append(data)
        }
```

Log
'''
NSFilePath=/private/var/mobile/Containers/Data/PluginKitPlugin/2C889BF0-9B52-484D-B532-3F263E97F466/tmp/259.ts, NSUnderlyingError=0x280701bf0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2020-02-12 10:48:16.306 [Info] [com.haishinkit.HaishinKit] [NetSocket.swift:24] capacity > extends a buffer size from 65535 to 134416
2020-02-12 10:48:16.838 [Info] [com.haishinkit.HaishinKit] [NetSocket.swift:24] capacity > extends a buffer size from 65535 to 131543
2020-02-12 10:48:16.839 [Info] [com.haishinkit.HaishinKit] [NetSocket.swift:24] capacity > extends a buffer size from 131543 to 263086
```

**To Reproduce**
Steps to reproduce the behavior:
 start a hls stream:
var httpStream = HTTPStream()
var httpService = HLSService(domain: "", type: "_http._tcp", name: "HaishinKit", port: 8080)

 httpService.addHTTPStream(httpStream)

 httpStream.publish("hello")

 httpService.startRunning()

**Smartphone (please complete the following information):**
 - Device: iPhone6 Plus
 - OS: iOS 14.2

**Comment by shogo4405** [comment]
I can't reproduce it. Please use issue templates and more info. videoSetting, audioSetting etc...

> PluginKitPlugin

It seems you are using ReplayKit?

**Comment by sokold** [comment]
yes, I am using ReplayKit, what I did is passing the buffers to captureOutput method of VideoIOComponent and AudioIOComponent, other than iOS 14.2, it doesn't seems to crash as much, but the stream dropped at the time it crashes on iOS 14.2. I also saw a couple of extend buffer info in console.
