### ISSUE TITLE
HDクオリティの配信にならない

### ISSUE THREAD

**Issue by jumperson** [shogo4405/HaishinKit.swift#789]
ライブラリを使用させて頂いております。ありがとうございます

一部きたいした動きにならなかったため問題がないかご確認頂けると幸いです。

**Describe the bug**
```
        rtmpStream.captureSettings = [
            .fps: 30,
            .sessionPreset: AVCaptureSession.Preset.hd1280x720
        ]

        rtmpStream.videoSettings = [
            .width: 1280, // video output width
            .height: 720, // video output height
            .bitrate: 2000 * 1000 // video output bitrate
        ]
```

上記設定を行いストリーミング配信を行ったのですが、HDクオリティの配信になりませんでした。

**Smartphone (please complete the following information):**
 - Device: iPhone11 
 - OS: iOS12

**Additional context**
上り回線も60Mほどだったので回線の問題ではないと思います。

**Comment by shogo4405** [comment]
> HDクオリティの配信

HDクオリティというのを具体的にどのようなことを期待したのでしょうか？
定義でいえば、解像度が width: 720 pxの解像度が出てればHDクオリティになります。

width: 1280, .height: 720 に設定したにも関わらず、 640px, 360px になってしまったということですか？

**Comment by jumperson** [comment]
ご回答ありがとうございます。

ストリーミング配信及び動画撮影の知識が足りず至らない質問になってしまい申し訳ございません。

> width: 1280, .height: 720 に設定したにも関わらず、 640px, 360px になってしまったということですか？

サーバのファイルを確認することができず明確な回答ができないのですが、記載の設定でストリーミング配信を行ったところ、キャプチャーに表示されたものには及ばない品質でした。

動くものがポリゴンのようにカクついてしまいました。

この状態を見て、品質が及ばないと判断しました。

**Comment by jumperson** [comment]
ちなみに

`AVCaptureSession.Preset.medium` を設定すると良くなり
`AVCaptureSession.Preset.high` を設定すると更に良くなりました。

端末はiPhone 11及びiPad（第6世代）で検証しました。

**Comment by shogo4405** [comment]
Profileのレベルが間違えすぎると、おっしゃるような結果になる場合があります。一旦、AutoLevelにしてください。
```
rtmpStream.videoSettings = [
    .profileLevel: kVTProfileLevel_H264_Baseline_AutoLevel,
]
```

あとは、ビットレートを理想とする品質にあげてください。
YouTubeだと推奨する値が、となっています。
720p
* 解像度: 1280x720
* 動画ビットレート範囲: 1,500～4,000 Kbps

```
rtmpStream.videoSettings = [
    .bitrate: 2000 * 1000 // video output bitrate
]
```

画質設定で変更できるパラメータは上記です。

**Comment by jumperson** [comment]
ご回答ありがとうございます！
頂いた内容で検証してみます！
