### ISSUE TITLE
Adding documentation regarding appdelegate

### ISSUE THREAD

**Issue by al3x88** [shogo4405/HaishinKit.swift#792]
Hi!!!
I was struggling to import this project because I didn't notice the importance of app delegate instructions under didFinishLaunchingWithOptions.

I would suggest you to make it more clear in the readme, to add the app delegate configuration. If you miss this step then u get a black screen, like no camera is attached to it.

Thank you so much for this amazing project, really really useful!!!

**Comment by shogo4405** [comment]
> I was struggling to import this project because I didn't notice the importance of app delegate instructions under didFinishLaunchingWithOptions.

What did you mean? No needs set up didFinishLaunchingWithOptions.

README.md. Make sure you setup and activate your AVAudioSession.
https://github.com/shogo4405/HaishinKit.swift#prerequisites

Thank you.
