### ISSUE TITLE
HLS ts segment duration changes when using a high bitrate setting

### ISSUE THREAD

**Issue by sokold** [shogo4405/HaishinKit.swift#794]
**Describe the bug**
ts segment duration changes when using a high bitrate setting

**To Reproduce**
 use a setting with big bitrate like
 httpStream.videoSettings = [
                            .width: UIScreen.main.bounds.width,
                           .height: UIScreen.main.bounds.height, 
                           .bitrate: 2000 * 1000, 
                           .profileLevel: kVTProfileLevel_H264_Baseline_3_1
}

 download a ts file in the m3u8. the ts file's duration should be 1 second. it is 1 second if the bitrate is set as 500*1000.but now the ts segment duration becomes 0.3 second

**Expected behavior**
the ts segment duration is still 1 second

**Smartphone (please complete the following information):**
 - Device: iPhone 6 Plud
 - OS: iOS 14.2

**Comment by shogo4405** [comment]
> now the ts segment duration becomes 0.3 second

How did you think it. Can I see .ts and m3u8 file?

**Comment by sokold** [comment]
yes, uploaded the files with bitrates of 500k, 1M, 2M, the durations are about 1m,0,8m, 0.5m. if I check ts file with ffmpeg 
```ffmpeg -i 2M.ts -f null -```  I can see errors like  "corrupted macroblock 38 29 (total_coeff=-1)"
``` 
httpStream.videoSettings = [
                        .width:720,
                        .height:1280,
                        .bitrate: 1000 * 1000, 
                        .profileLevel: kVTProfileLevel_H264_Baseline_3_1,
]
```
