### ISSUE TITLE
Slow FPS when Streaming ReplayKit video through HttpStream

### ISSUE THREAD

**Issue by jsheely** [shogo4405/HaishinKit.swift#795]
I'm having trouble getting the ReplayKit video stream to come through at a "normal" 30 or 60 FPS when streaming through HttpStream. Currently any UI interaction takes around 10+ seconds until I see it on stream.

I am using VideoLAN(VLC) player to play the stream

I am able to get a stream by doing the following

```swift
override func broadcastStarted(withSetupInfo setupInfo: [String : NSObject]?) {
        httpStream.publish("hello")
        httpStream.expectedMedias.insert(.video)
        httpService.startRunning()
        httpService.addHTTPStream(httpStream)
    }

override func processSampleBuffer(_ sampleBuffer: CMSampleBuffer, with sampleBufferType: RPSampleBufferType) {
        switch sampleBufferType {
        case RPSampleBufferType.video:
            // Handle video sample buffer
            if let description = CMSampleBufferGetFormatDescription(sampleBuffer) {
                            let dimensions = CMVideoFormatDescriptionGetDimensions(description)
                            httpStream.videoSettings = [
                                .width: dimensions.width,
                                .height: dimensions.height,
                                //.bitrate: 5000,
                                .profileLevel: kVTProfileLevel_H264_Baseline_AutoLevel
                            ]
                        }
            
            httpStream.appendSampleBuffer(sampleBuffer, withType: .video)
            break
        case RPSampleBufferType.audioApp:
            // Handle audio sample buffer for app audio
//            httpStream.appendSampleBuffer(sampleBuffer, withType: .audio)

            break
        case RPSampleBufferType.audioMic:
            // Handle audio sample buffer for mic audio
//            httpStream.appendeSampleBuffer(sampleBuffer, withType: .audio)
            break
        @unknown default:
            // Handle other sample buffer types
            fatalError("Unknown type of sample buffer")
        }
    }

```

I'm not exactly certain what is causing the delay and how I can tweak it. I've tried setting the bitrate and changing the profileLevel to: ```kVTProfileLevel_H264_Main_AutoLevel``` but no luck.

*My Goal*
- Get stream
- Add configuration for FPS and Bitrate
- Stream to Chromecast (Will work on this next after getting reliable feed from previous steps)

Any advice?

Thank you kindly

**Comment by jsheely** [comment]
So I think my issue is actually related to: https://github.com/shogo4405/HaishinKit.swift/issues/602

If this is still true this is sad news. Makes it hard to live stream the screen in a presentation as the viewers will always be 10 seconds before

**Comment by shogo4405** [comment]
> Currently any UI interaction takes around 10+ seconds until I see it on stream.

This is normal behavior on HLS(without Apple Low-latency HLS).
I can't fixed it.
