### ISSUE TITLE
RTMPs Playback of Facebook live

### ISSUE THREAD

**Issue by Hesham-Salama** [shogo4405/HaishinKit.swift#796]
**Describe the bug**
RTMPs playback of Facebook is not working

**To Reproduce**
1. Go to live producer
2. copy stream link and key and paste it in Preferences class 
```
var uri: String? = "rtmps://live-api-s.facebook.com:443/rtmp/"
var streamName: String? = "234234......"

```
3. click camera option & start live stream (for example from PC's camera )
4. No stream to be played in playback tab

Also this error appear
`2020-12-16 16:02:00.571831+0200 rtmp[4494:890492] [connection] nw_resolver_start_query_timer_block_invoke [C2] Query fired: did not receive all answers in time for live-api-s.facebook.com:443`

I also made sure I copied this code
```
if #available(iOS 12.0, *) {
            let params = NWParameters.tls
            rtmpConnection.parameters = params
 }

```
Test device : iPhone 8 - iOS 14.3

**Comment by onebuckgames** [comment]
Same behaviour with playback on live producer page opened in Safari. Try open it in the Chrome or Firefox browser.

**Comment by shogo4405** [comment]
It works ok.
 - macOS with HaishiKit 1.1.1.
 - iPhone12 Pro max with HaishinKit 1.1.1

I will close this issue.
