### ISSUE TITLE
Green background while broadcast screen to TV with iOS broadcast extension

### ISSUE THREAD

**Issue by petrutms** [shogo4405/HaishinKit.swift#799]
Hi, I am working on a screen mirroring app, and it works fine except that the video background is green when playing on TV. Less green when phone is in landscape but still green... I played with settings but couldn't find a way to fix this. Any ideas? Thanks
![IMG_0406](https://user-images.githubusercontent.com/35230476/102805950-aec92180-43c4-11eb-8cc3-2e744c856493.jpg)

**Comment by shogo4405** [comment]
I thought that playbackside issue.
 I can't resolve it.

**Comment by bemisal01** [comment]
@petrutms  hi can u please guide me how you have pass CMSampleBuffer frames to smart tv ? are you using RTMP server to HLS stream?
