### ISSUE TITLE
HLS doesn't work

### ISSUE THREAD

**Issue by ragian** [shogo4405/HaishinKit.swift#803]
**Describe the bug**
I'm facing some problems in the use of the HLS stream with the iPhone: the connections of the clients to the "playlist.m3u8" remain in pending.

To allow you to reproduce the issue I have edited your demo Screencast Extension to stream via HLS the screen.

https://gist.github.com/ragian/ecfb5aee8d105d2dad95a46ded57289d

Running the extension and beginning to capture the screen do not generate messages or alerts but when I try to connect to 

http://10.11.12.93:8080/hello/playlist.m3u8

(where 10.11.12.93 is the ip address of the device where the ext is running) using Safari or VLC the stream is not available.
The connection stays "pending" until I swith off the extension (after that the connection closes).

**To Reproduce**
- Replace the SampleHandler of the demo app with this one https://gist.github.com/ragian/ecfb5aee8d105d2dad95a46ded57289d

**Expected behavior**
- Watch the stream video to the client

**Smartphone (please complete the following information):**
 - Device: iPhone SE (edition 1)
 - OS: 14.0

 - Device: iPad Pro
 - OS: 14.2

**Comment by vr-wonny** [comment]
change domain -> 10.11.12.83 here:

let httpService = HLSService(domain: "10.11.12.83", type: "_http._tcp", name: "HaishinKit", port: 8080)

**Comment by ragian** [comment]
Thanks
