### ISSUE TITLE
Broadcasting video content

### ISSUE THREAD

**Issue by staticdreams** [shogo4405/HaishinKit.swift#810]
I'm trying to broadcast a webpage from an iPad (using webkit) and while it mostly ok, I'm unable to see the videos, just black screen.

This is what I'm broadcasting:
![ipad](https://user-images.githubusercontent.com/988705/104436315-bd52c500-558d-11eb-9c9b-d7294336c486.jpeg)

And this is what users see:
![broadcast](https://user-images.githubusercontent.com/988705/104436376-d196c200-558d-11eb-8570-4bfdce282d5f.jpg)

I'm guessing this has something to do with encoding or broadcasting a video of a video.. 
Has anyone had such experience? Or perhaps this is only a matter of tweaking some settings?

Any help is much appreciated.

Thank you!

**Comment by shogo4405** [comment]
Please use an issue template. I will close this issue. Thank you.
