### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by mazharhameed25** [shogo4405/HaishinKit.swift#811]
i am not able to connect with  rtmp url. getting error "an ssl error has occured and secure connection to the server can not be made". tried by adding different keys in info.plist but can't find the solution. any help would be appreciated. thanks

**Comment by shogo4405** [comment]
Please use an issue template. I will close this issue. Thank you.

**Comment by mazharhameed25** [comment]
how to use template?
Can you reply my question please
