### ISSUE TITLE
Broadcasting video content results in black screen

### ISSUE THREAD

**Issue by staticdreams** [shogo4405/HaishinKit.swift#812]
**Describe the bug**
When broadcasting a screen (webpage), the videos are black. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Start broadcasting of any webpage containing a video using ``rtmpStream?.attachScreen(ScreenCaptureSession(shared: UIApplication.shared), useScreenSize: true)``
2. Click Play video
3. Broadcaster see the video as expected
4. Broadcast viewer see the video progress bar is moving (video is playing)
5. Video screen is black

**Expected behaviour**
Videos play as expected and are visible on the final viewer screen

**Screenshots**
What broadcaster sees: 
![104436315-bd52c500-558d-11eb-9c9b-d7294336c486](https://user-images.githubusercontent.com/988705/104599660-5cec8200-5678-11eb-9681-69b737c1c0b5.jpg)
What final user sees:
![104436376-d196c200-558d-11eb-8570-4bfdce282d5f](https://user-images.githubusercontent.com/988705/104599718-6c6bcb00-5678-11eb-9580-d3b8ce690336.jpg)

**Desktop (please complete the following information):**
 - OS: macOS, Windows
 - Browser Chrome, Safari, Firefox
 - Version any

**Smartphone (please complete the following information):**
 - Device: iPad Pro 11" (2018)
 - OS: iOS 14.3
 - Browser Safari (webkit)
 - Version any

**Additional context**
I'm guessing this has something to do with encoding or broadcasting a video of a video..
Any help is appreciated

**Comment by shogo4405** [comment]
1. ScreenCaptureSession uses the https://developer.apple.com/documentation/uikit/uiview/1622589-drawhierarchy method internally.
2. This method can't capture a gpu-based content such as AVSampleBufferLayer or Safari's video content.

This is specification. I can't fix it.

**Comment by staticdreams** [comment]
FYI: when using ReplayKit the video is visible and playing, but the whole ReplayKit experience is really bad comparing to what you have achieved and the delay is so long.. 
Is there any other way to be able to broadcast screen with video playing to make it work or this is not possible at all?

**Comment by shogo4405** [comment]
well... I'm not sure.
