### ISSUE TITLE
Is there a way to see if an incoming stream is audio-only?

### ISSUE THREAD

**Issue by pardeike** [shogo4405/HaishinKit.swift#815]
I am using the concepts of "rooms" and the rtmp server I have does not allow for meta data queries. All I want is to determine if I should attach a video player of a more slim audio player to an incoming rtmp connection.

After searching the documentation and source code for a while, I cannot see how I can examine the RTMPStream to see if its audio only.

Is this possible or can I send meta data with the rtmp stream (also done with HaishinKit)?

**Comment by pardeike** [comment]
Ok, you should document that adding a RTMPStreamDelegate will allow you to observe audio/video receiving. I delayed attaching my window until I get the first call to `func rtmpStream(_ stream: HaishinKit.RTMPStream, didOutput video: CMSampleBuffer)`

Should be documented.

**Comment by shogo4405** [comment]
OK. I'm waiting your PullRequest! Thank you.
