### ISSUE TITLE
iOS: MTHKView/HKView ignore safe ares is not working

### ISSUE THREAD

**Issue by tarassh** [shogo4405/HaishinKit.swift#816]
**Describe the bug**
I want the feed from camera to be render to the entire screen.
It is rendered inside safe area rectangle no matter what I am trying to do.
I tried to disable safe areas guidelines
<img width="268" alt="image" src="https://user-images.githubusercontent.com/5903550/105476224-0bac4600-5ca9-11eb-9b18-060f4275cd0f.png">

Also tried using SwiftUI  .ignoreSafeArea() function.

Screenshot just showing the areas I am trying to remove.
![IMG_3629](https://user-images.githubusercontent.com/5903550/105572539-63f24f00-5d60-11eb-8412-63827db87def.jpg)

**Comment by tarassh** [comment]
@shogo4405 do you have any suggestions?

**Comment by shogo4405** [comment]
I'm not sure. You don't write expected value. So I can't answer your issue.

Maybe this HKView.videoGravity property. Document is here https://developer.apple.com/documentation/avfoundation/avcapturevideopreviewlayer/1386708-videogravity.
