### ISSUE TITLE
Make frame dropping observable

### ISSUE THREAD

**Issue by pardeike** [shogo4405/HaishinKit.swift#820]
**Is your feature request related to a problem? Please describe.**
The sender currently cannot observe if any frames are dropped. The implementation here https://github.com/shogo4405/HaishinKit.swift/blob/9fda58ac1e1b9d7587ea4200066b76f3aede4562/Sources/Codec/H264Encoder.swift#L248 is silent.

**Describe the solution you'd like**
In the sending delegate, I would like to have a method that is called whenever a frame is dropped so I can add a dropped frames counter.

**Comment by pardeike** [comment]
Is this implemented or are you closing this because it’s a wontfix?

**Comment by shogo4405** [comment]
Priority is very low. I decided wontfix.
