### ISSUE TITLE
Connection always NetConnection.Connect.Closed

### ISSUE THREAD

**Issue by gajddo00** [shogo4405/HaishinKit.swift#821]
**Describe the bug**
When I try to connect to rmtp server, the notification event always reports NetConnection.Connect.Closed. 

**To Reproduce**
The RTMP server url I'm using looks something like this, it is an AWS server, there is no authentication

rtmp://3.127.38.148/5WF7f3WEo8few5f4Pf9e84/ZQZQsmgDPxpCcrnbxaEhIEtJwKhMfj?psk=161037020796912143250530521225

This url is generated before the stream starts, I receive this url from API and then in the callback I call the connect function.

**Smartphone (please complete the following information):**
 - Device: iPhone 11, iPhone 8
 - OS:  iOS 14.3

I'm building and compiling on Mac M1

**Additional context**
I thought it might be the url address that's wrong, but later I tried another streaming library LFLiveKit and it worked immediately, and the Android version of the app I'm working on also works without problems, so I've been wondering what's wrong here.

I did the setup same way it is showed in the example, only it will never connect and it gets closed immediately.

Thanks you for help! I really like this library and would be sad to not be able to use it :)

**Comment by shogo4405** [comment]
Please try these cases.

Case 1:
~~~
rtmpConneciton.connect("rtmp://3.127.38.148/5WF7f3WEo8few5f4Pf9e84")
rtmpStream.publish("ZQZQsmgDPxpCcrnbxaEhIEtJwKhMfj?psk=161037020796912143250530521225")
~~~

Case 2:
~~~
rtmpConneciton.connect(“rtmp://3.127.38.148/5WF7f3WEo8few5f4Pf9e84j?psk=161037020796912143250530521225”)
rtmpStream.publish(“ZQZQsmgDPxpCcrnbxaEhIEtJwKhMfj”)
~~~

**Comment by gajddo00** [comment]
Case 1 works, thank you!
