### ISSUE TITLE
Clarification: how to solve that rtmp reader over time lags behind more and more 

### ISSUE THREAD

**Issue by pardeike** [shogo4405/HaishinKit.swift#822]
Can you elaborate how an rtmp reader can over time shows older and older frames. I am aware that this can depend a lot on the server and the infrastructure in between. I am using srs in a container and with different configurations including real-time and more. I always end up with the reader being behind 10-12 seconds after a while even though it starts very quickly and at start only is behind 0.5 seconds. This is not really related to the bitrate and I only use video only grabbed from the screen in the writer (also HaishinKit). 

**To Reproduce**
At this point I don’t have a public project but if necessary I can create a minimal case. Before I do that I would like to hear some advice on how to fix this. The use case is pure screen sharing and skipping frames is preferred to maintain low delay. 

**Expected behavior**
A way to understand where the problem is so I can reduce the problem area. 

**Desktop (please complete the following information):**
 - BigSur (reader + writer)
 - master on HaishinKit

**Additional context**
I am fully aware that this isn’t a bug report because the problem can clearly be on my side. Just a request for clarification since I could not find anything on the wiki or the source code and no issues except for skipping frames on the writer side which I think works and is not the problem. 

Thanks for making an excellent library!

**Comment by shogo4405** [comment]
In my case,  1-2 seconds lag. 
- HaishinKit(as rtmp writer) - nginx with rtmp(localhost) - HaishinKit(as rtmp reader)

I thought your side.
