### ISSUE TITLE
Crash in RTMPConnection on(timer)

### ISSUE THREAD

**Issue by mrhydeee** [shogo4405/HaishinKit.swift#824]
**Describe the bug**
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
Crash in RTMPConnection on(timer: Timer) line 434. 

**To Reproduce**
Hard to reproduce unfortunately, could be a locking / concurrency issue. 

1. have shared RTMPConnection instance 
2. create RTMPStream for connection
3. stream.attachAudio(...)
4. connection.connect(...)
5. stream.publish(...)
 ... wait a little ...
6. stream.close()
(7. repeat from 2, reuse connection)

Happens more often when only stream is closed. Happens less often when connection.close() is called after stream.close(). But still happens. 

**Smartphone (please complete the following information):**
iOS 12 and up (could affect earlier iOS as well)

**Additional context**
The problem does not exist in Haishinkit 0.10.5

**Comment by mrhydeee** [comment]
So connection.close(isDisconnected:) removes objects from the streams array (RTMPConnection line 313) while timer is still running. That causes the crash in iterator.next on RTMPConnection line 434.

I removed the timer since I don't need the statistics, but you may look into fixing that sync issue.

**Comment by dfvalue** [comment]
Does not fix. You need to timer?.invalidate before setting timer = nil. Setting a NSTimer to nil won't remove the timer from the run loop, so it will fire one more time.

**Comment by leo150** [comment]
`invalidate` is called in timer's `didSet`
