### ISSUE TITLE
Example Screencast crashes when attempting to mix audioApp and audioMic

### ISSUE THREAD

**Issue by richard-ash** [shogo4405/HaishinKit.swift#829]
**Describe the bug**

When I attempt to mix the audio of the broadcast extension, the extension crashes because it hits the 50 MB memory limit. My guess is there is something wrong with the audio mixing in the framework (or maybe there isn't audio mixing supported), as streaming either `audioMic` or `audioApp` works fine and profiles to under 10 MB.

Does HaishinKit support audio mixing?

My edits in `Examples/iOS/Screencast/SampleHandler.swift` are below:
```swift
override open func processSampleBuffer(_ sampleBuffer: CMSampleBuffer, with sampleBufferType: RPSampleBufferType) {
    switch sampleBufferType {
    case .video:
        if let description = CMSampleBufferGetFormatDescription(sampleBuffer) {
            let dimensions = CMVideoFormatDescriptionGetDimensions(description)
            rtmpStream.videoSettings = [
                .width: dimensions.width,
                .height: dimensions.height ,
                .profileLevel: kVTProfileLevel_H264_Baseline_AutoLevel
            ]
        }
        rtmpStream.appendSampleBuffer(sampleBuffer, withType: .video)
    case .audioApp:
        rtmpStream.appendSampleBuffer(sampleBuffer, withType: .audio)
    case .audioMic:
        rtmpStream.appendSampleBuffer(sampleBuffer, withType: .audio)
    @unknown default:
        break
    }
}
```

**To Reproduce**
1. Start streaming from the iOS control center
2. Crash

**Expected behavior**
I expect both audio streams to be mixed together.

**Screenshots**
<img width="1792" alt="Screen Shot 2021-02-24 at 4 44 21 PM" src="https://user-images.githubusercontent.com/12877678/109086646-d7b9ab80-76c0-11eb-9569-97e3beb4711a.png">

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS 14.4

**Additional context**
I captured the logs with `.trace` enabled. This may help debug what's going on.

[Logs.txt](https://github.com/shogo4405/HaishinKit.swift/files/6039824/Logs.txt)

**Comment by shogo4405** [comment]
Thanks. Feedback.
Unfortunately HaishinKit has no mix audioApp and audioMic feature.

**Comment by richard-ash** [comment]
Thanks for the heads up!
