### ISSUE TITLE
Terminated due to memory issue

### ISSUE THREAD

**Issue by jxxnnee** [shogo4405/HaishinKit.swift#833]
Hi @shogo4405 , 

Revisiting this issue. I'm trying again with v1.0.0 running on iOS 12.4.2 and iOS 13.1.3. 

Now I'm getting crashes with message: 
> Message from debugger: Terminated due to memory issue

While investigating, it looks like there is a memory leak in the `draw(in view:)` of `MTHKView`. As draw is invoked, at no point is the `displayImage` being released and there are several strong references to it. 

Also, the `draw(image:)` in the `NetStreamDrawable` extension might need some investigating. 

While my app is running and I'm using `MTHKView` to view an RTMP stream, the app's memory shoots up from 51MB to >1GB and gets terminated by the OS. I traced it to the above draw calls where on every frame received from the stream, the `CIImage` use seems to be growing and growing and never gets released while the stream is being viewed.

_Originally posted by @kenosan in https://github.com/shogo4405/HaishinKit.swift/issues/509#issuecomment-544375003_

**Comment by jxxnnee** [comment]
I also ended up with a memory problem, and when I played Stream, the memory went up to 1GB.

**Comment by shogo4405** [comment]
Yes, I know. Playback feature is beta version.
Contains too much memory use bug.
