### ISSUE TITLE
Logboard issue (Carthage and Cocoapods)

### ISSUE THREAD

**Issue by lucasrama** [shogo4405/HaishinKit.swift#834]
**Describe the bug**

When it comes to install logboard with carthage, the installation fail with this error: "The file "logboard.xcframework" counldn't be opened because there is no such file." 

When it comes to install logboard with Cocoapods, there is the famous and unsolved error "no logboard module error". Shogo4405 have you an idea? cordially.

**Comment by shogo4405** [comment]
- You have to use carthage ver 0.37.0
  - Then exec `carthage bootstrap --use-xcframeworks`.

Also please update master branch.

**Comment by lucasrama** [comment]
ok thanks.
