### ISSUE TITLE
RTMPConnectionをcloseした後のイベントが来なくなった

### ISSUE THREAD

**Issue by dazy1030** [shogo4405/HaishinKit.swift#836]
## 概要
* `RTMPConnection.close()` を呼び出しRTMP接続を切断した後に、`Event.Name.rtmpStatus` を通知で受信できなくなった（code: NetStream.Unpublish.Success が受信されるはず）
* 1.0.11 までは `addEventListener(_, selector:, observer:)` で設定したハンドラで受信できていた（1.0.12 で来なくなったことを確認）
* 接続時の通知は受信できている

## 環境
 - OS: iOS14.3
 - Device: iPhone8
 - Version: 1.0.12以降

**Comment by shogo4405** [comment]
* RTMPSocket を中途半端な非同期処理から非同期処理に変更したことから`NetStream.Unpublish.Success` を受け取る前に `NSOutputStream/NSInputStream`を破棄をしていることをが原因です。
* flash側の挙動を確認したときには、NetConnection#close では、`NetStream.Unpublish.Success` を受け取れませんでした。

意図した変更ではないですが、仕様として扱い `wontfix` でクローズします。

**Comment by donuts-odajima** [comment]
flashの挙動まで確認していただき…ありがとうございました！

**Comment by dazy1030** [comment]
flashの挙動まで確認していただき…ありがとうございました！
