### ISSUE TITLE
Memory leak when Mic is on

### ISSUE THREAD

**Issue by Gorg5** [shogo4405/HaishinKit.swift#842]
Hi there,
I'm using your framework in our app for quite sometime now and wanted to thank you for the great job. Since I first tested your framework (about three years ago) I noticed the app and mic sounds are not working well together. I recently started testing your last version (1.1.2 at this time) and noticed there was improvement there and Mic starts working while the app sound is still being heard in the background. The problem is that the app crashes after working for 15-20 seconds due to maximum 50MB memory limit reached. I decided to take a look at memory footprint. I ran my app with Mic off first. It could stream the screen and game sound successfully and very stable. Then I turned on the Mic and I could hear the app and mic sounds fine but as you can see in the Figure 1 below, the memory consumption started increasing till it crashed. Before I turn the mic on the memory print is pretty stable and around 10MB. I also started getting the following in the log files right after starting the mic as shown in Figure 2. I copied my code in SampleHandler.swift in Figure 3, which is pretty much what you have in your example. 

I tried to chase and find the leak but no luck so I thought it might be much easier for you to take a look at it. It seems it might be a simple issue with reclaiming the Mic memory buffer between the intervals when processSampleBuffer method is being called by ReplayKit.

This is a very important feature for us and I really appreciate it if you can take a look and let us know.
Thanks

**To Reproduce**
Explained above

**Expected behavior**
No memory leak. When turning Mic on, the memory line should go a bit higher, but still stable.

**OS:**
 iOS

**Smartphone :**
 - Device: Tested on iPhone 6 with iOS 12.4.7 
 - Device: Tested oniPhone 12 with iOS 14.4
![Figure_1](https://user-images.githubusercontent.com/37096310/111941820-26bfea00-8a8f-11eb-8f98-bcbf9e046cfc.png)
<img width="1153" alt="Figure_2" src="https://user-images.githubusercontent.com/37096310/111941831-2b849e00-8a8f-11eb-89b3-c5b681ed41de.png">
<img width="759" alt="Figure_3" src="https://user-images.githubusercontent.com/37096310/111941838-2e7f8e80-8a8f-11eb-9ac2-c0441b2e22dc.png">

**Comment by Gorg5** [comment]
Hi there,
Any update on this issue? It's been a while!

Thanks.

**Comment by AnkitaPundir** [comment]
Hello, Any findings?

**Comment by Gorg5** [comment]
Hi there,
Any update on this issue? I reported this like seven months ago, but haven't seen any response! This is a very important feature for us. Please let me know if there's a solution for this or where I should look in code to solve this. We need this soon or we have to switch to another library.

**Comment by shogo4405** [comment]
It seemes that it works ok for me with HaishinKit 1.2.1 
- Tested on iPhone 7 Plus with iOS 14.8, HaishinKit 1.2.1
- Tested on iPhone 12 Pro Max with iOS15.1, HaishinKit 1.2.1
- Tested on iPhone XR with iOS14.4, HaishinKit 1.2.

<img width="786" alt="スクリーンショット 2021-11-07 16 02 11" src="https://user-images.githubusercontent.com/810189/140635728-3714b385-12e7-4a36-b5e6-5daaa2c971d7.png">
1

**Comment by Gorg5** [comment]
Ok, great! Let me do some testing and get back to you. Thank.
