### ISSUE TITLE
Continue screencast after leaving the app

### ISSUE THREAD

**Issue by svprdga** [shogo4405/HaishinKit.swift#847]
**Describe the bug**
I am trying to create an app capable of broadcasting everything that happens on the device. For that, the user starts the screencast within the app and then leaves to other app. It is expected that the screencast continues after leaving the app, but right now the screencast is only capturing the host app and stops when the user goes away.

**To Reproduce**
1. Create an app that can do screencast
2. Start the screencast
3. Press home button and go to another app

**Expected behavior**
The screencast continues and the broadcast shows the new app that the user has opened.

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 14.3

**Additional context**
Start capture session with:

```
rtmpStream = RTMPStream(connection: rtmpConnection)

rtmpStream.captureSettings = [
    .fps: 30, // FPS
    .sessionPreset: AVCaptureSession.Preset.medium,
]
rtmpStream.audioSettings = [
    .muted: false, // mute audio
    .bitrate: 32 * 1000,
]
rtmpStream.videoSettings = [
    .width: 640, // video output width
    .height: 360, // video output height
    .bitrate: 160 * 1000, // video output bitrate
    .profileLevel: kVTProfileLevel_H264_Baseline_3_1, // H264 Profile require "import VideoToolbox"
    .maxKeyFrameIntervalDuration: 2, // key frame / sec
]
// "0" means the same of input
rtmpStream.recorderSettings = [
    AVMediaType.audio: [
        AVFormatIDKey: Int(kAudioFormatMPEG4AAC),
        AVSampleRateKey: 0,
        AVNumberOfChannelsKey: 0,
        // AVEncoderBitRateKey: 128000,
    ],
    AVMediaType.video: [
        AVVideoCodecKey: AVVideoCodecH264,
        AVVideoHeightKey: 0,
        AVVideoWidthKey: 0,
    ],
]

rtmpStream.attachScreen(ScreenCaptureSession(shared: UIApplication.shared))

rtmpConnection.connect("rtmp://192.168.1.128:1935/free")
rtmpStream.publish("stream")
```

**Comment by dazy1030** [comment]
Hi @svprdga ,

If you want to create such an app, you cannot complete it with HaishinKit alone; you need to use HaishinKit only to encode the delivery data and send it in RTMP, and use ReplayKit to collect the delivery data.
Please refer to this link: https://developer.apple.com/videos/play/wwdc2018/601/

**Comment by svprdga** [comment]
I see, thanks @dazy1030 
I am trying to configure it but I am seeing that there is very little documentation regarding it...I found [this](https://github.com/StraaS/StraaS-iOS-sdk/wiki/Live-Streaming-with-Apple%27s-ReplayKit) and I managed to configure the Broadcast Upload Extension but my app is not being listed as a recorder app when I long press in the recorder button in Control Center. By any chance do you know how to do it?

**Comment by dazy1030** [comment]
@svprdga 
One possibility is that the Deployment target of Broadcast Upload Extension is higher than your iPhone.

**Comment by svprdga** [comment]
You were right @dazy1030 , thanks.
