### ISSUE TITLE
配信を続けていると瞬間的なメモリ使用量が徐々に増加していく

### ISSUE THREAD

**Issue by dazy1030** [shogo4405/HaishinKit.swift#851]
**Describe the bug**
* RTMP接続で配信を続けていると、瞬間的なメモリ使用量が徐々に増加していく。
* iOS14.2の端末1台では発生せず。iOS14.3の端末2台で発生。iOS14.4の端末1台で発生（SSなし）。
* このリポジトリのサンプルでも再現。カメラからの配信と画面キャプチャでの配信の両方で発生。

**To Reproduce**
1. iOS14.3の端末にサンプルをビルドしインストール。
2. PCのローカルホストなどにRTMPを受信できるサーバーをたてて配信開始。
3. 徐々にメモリ使用量のピークが増加していく。30分を超えたあたりから顕著になっていく。

**Expected behavior**
* メモリ使用量のピークが安定し、数時間後でも配信開始時とほぼ変わらないこと。

**Screenshots**
||配信開始時|配信から一定時間たった後|
|:-:|-|-|
|iPhone7Plus<br>iOS14.3|![iPhone7p_14 3_0h](https://user-images.githubusercontent.com/21330273/113838390-afe25b00-97c9-11eb-9dbb-cabceafa8779.jpg)|![iPhone7p_14 3_1 5h](https://user-images.githubusercontent.com/21330273/113838401-b2dd4b80-97c9-11eb-80e1-ed0fc7cb2950.jpg)|
|iPhone8<br>iOS14.3|![iPhone8_14 3_0h](https://user-images.githubusercontent.com/21330273/113838691-f89a1400-97c9-11eb-854f-637d91ba2d32.jpg)|![iPhone8_14 3_2h](https://user-images.githubusercontent.com/21330273/113838701-fc2d9b00-97c9-11eb-9459-5546871f634b.jpg)|
|iPhoneSE2<br>iOS14.2|![iPhoneSE2_14 2_0h](https://user-images.githubusercontent.com/21330273/113838744-094a8a00-97ca-11eb-82f2-7b8bf83ff826.jpg)|![iPhoneSE2_14 2_2h](https://user-images.githubusercontent.com/21330273/113838754-0cde1100-97ca-11eb-98ac-3e231bb754cb.jpg)|

**Smartphone:**
再現端末1
 - Device: iPhone7Plus
 - OS: iOS14.3
 - Version: 1.1.4（現在のmasterブランチ）

再現端末2
 - Device: iPhone8
 - OS: iOS14.3
 - Version: 1.1.4

再現端末3
 - Device: iPhone11 Pro Max
 - OS: iOS14.4
 - Version: 1.1.4

再現しない端末
 - Device: iPhoneSE2
 - OS: iOS14.2
 - Version: 1.1.4

**Comment by shogo4405** [comment]
@dazy1030 バグレポートありがとうございます。確認してみます。
