### ISSUE TITLE
Multiple Streams

### ISSUE THREAD

**Issue by ethaneast** [shogo4405/HaishinKit.swift#852]
I know this has been asked on here before but I have been searching for a correct answer and trying out solutions mentioned for days and I can't seem to figure out how to get this to work. I'm trying to have two RTMPStreams() and RTMPConnections() and then simultaneously stream to both of them with the same camera and audio. This issue is that when I do this it only streams to the one that I last attached the camera and audio to. I know in one of the previous issues you mentioned that if you want to multistream you can't use .attachCamera/Audio and instead you have to use .appendSampleBuffer. I saw the code that you gave and it didn't really make sense. It seems that I have to use .attachCamera in order for LFView.attachStream to work. Also when using the .appendSampleBuffer and the code you included in the other post [https://github.com/shogo4405/HaishinKit.swift/issues/253](url), I don't understand how that is supposed to work. When I try to publish and connect, neither stream starts and I can't see anything on LFView because I can't use .attachCamera. The streams are obviously not getting video from the .appendSampleBuffer() and I don't even know if that is what it is intended to do but there just isn't a lot of documentation on this and I'd really appreciate if you could clarify if this is possible.

**Comment by shogo4405** [comment]
First, I designd one RTMPConnection with multi RTMPStreams. But I don’t test well.

**Comment by ethaneast** [comment]
I’ve tried using these things, but I’m still missing something and I don’t know what. 

I used exactly what you had given in the previous posts with .appendSampleBuffer and the entire multiStream class you made but there is still no video/audio on the streams. 

I’m not an expert on Swift or coding in general and I think I just need someone to show me what something that is working would look like because I’m out of ideas.

Thanks for taking the time to reply to me though.
