### ISSUE TITLE
AVAudioPCMBuffer Support

### ISSUE THREAD

**Issue by k2sebeom** [shogo4405/HaishinKit.swift#857]
**Is your feature request related to a problem? Please describe.**
I am trying to integrate AVAudioEngine to do a preprocessing of audio signal before publishing it to the stream. However, the tapNode of the AudioEngine is in the format of AVAudioPCMBuffer, while the appendBuffer method of RTMPStream takes in an input of CMSampleBuffer, which is a typical buffer used in AVCaptureSession. Since AVCaptureSession does not allow much room for audio mixing and processing, I wonder if there is a way to integrate AVAudioEngine with HaishinKit.

**Describe the solution you'd like**
If there is a way to publish AVAudioPCMBuffer or if there exists a recommended method to integrate AVAudioEngine output.

**Describe alternatives you've considered**

**Additional context**

**Comment by abubaqr70** [comment]
> **Is your feature request related to a problem? Please describe.**
> I am trying to integrate AVAudioEngine to do a preprocessing of audio signal before publishing it to the stream. However, the tapNode of the AudioEngine is in the format of AVAudioPCMBuffer, while the appendBuffer method of RTMPStream takes in an input of CMSampleBuffer, which is a typical buffer used in AVCaptureSession. Since AVCaptureSession does not allow much room for audio mixing and processing, I wonder if there is a way to integrate AVAudioEngine with HaishinKit.
> 
> **Describe the solution you'd like**
> If there is a way to publish AVAudioPCMBuffer or if there exists a recommended method to integrate AVAudioEngine output.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

I would appreciate if you could help me while streaming a video from the gallery i'm unable to do that while the video from the bundle is been streamed i'm new to this library and stuck over here

**Comment by shogo4405** [comment]
Please convert AVAudioPCMBuffer -> CMSampleBuffer yourself.
Close as `wontfix`
