### ISSUE TITLE
How to pick the video from gallery to stream

### ISSUE THREAD

**Issue by abubaqr70** [shogo4405/HaishinKit.swift#858]
**Describe the bug**
When i append the file from the bundle it works fine but while picking the video from gallery it doesn't stream

**To Reproduce**
1. Go to [MP4Sampler.swift:35]
4. See error (execute > url)

**Expected behavior**
I want to append the file from the gallery picked by the user 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iphone X and iphone 12promax, iphone 8
 - OS: ios 12.0 >

**Additional context**
I just need to add the video from the gallery to stream how can I achieve it whether by append file method or append buffer method and kindly tell me with example..!

**Comment by shogo4405** [comment]
@abubaqr70 Stop multi post. This is not Q and A forum.  I have no code `the video from the gallery to stream`.
RTMPStream.appendFile can support mp4 file with audio codec is AAC and video codec is H264. Unfortunately, It is an  experimatal implementation.

**Comment by abubaqr70** [comment]
@shogo4405  the codecs you suggested which are supported by rtmpstream.append file an mp4 file with audio codec AAC and video codec H264 i have converted  the video with same codecs but still not working.

**Comment by abubaqr70** [comment]
![Screenshot 2021-04-19 at 11 00 37 AM](https://user-images.githubusercontent.com/59121649/115188563-85b06780-a0fe-11eb-9415-f2107cad5f4a.png)
You can see the converted file settings what else am i missing could you kindly please guide me...!
