### ISSUE TITLE
The problem of getting the captured image cut off??

### ISSUE THREAD

**Issue by mud0107** [shogo4405/HaishinKit.swift#863]
hi. ??

If you send it out in "portrait mode" with this library, the top/bottom part is cut and played.
However, if you set the "landscape mode" on the contrary, it is normal when playing the normally transmitted screen.

So I have the rtmpStream.videoSettion
I tried modifying .width = 1080 ,.height = 1920 but

The top/bottom is cut, so it is played.

I ask a question.
1. How can I display the camera image captured by the transmission side as it is?
2. Any other questions? --> Would you like to know what settings you need to set to increase the video quality??

   sessionPress:? in captureSettings
  In the video Settings .profileLevel:?

Thank you.

**Comment by mud0107** [comment]
attach image ... file
![cap_0423](https://user-images.githubusercontent.com/5044450/115847559-0e603800-a45e-11eb-9310-842755bba180.jpeg)

**Comment by shogo4405** [comment]
> How can I display the camera image captured by the transmission side as it is?

I'm not sure. I can't reproduce it. Please more information.
- Please provide reproduce code.

> Would you like to know what settings you need to set to increase the video quality??

It is .bitrate propery.

**Comment by mud0107** [comment]
The current code is the setting for sending rtmp.

The attached image is the result through my streaming server.
The codec information of vlc is displayed as 480 * 272.

The code was set to 1920 * 1080.
What is the solution?
thank.
===============================================
![cap1](https://user-images.githubusercontent.com/5044450/116019410-1cd96a00-a67f-11eb-903b-444635458816.jpeg)
![cap2](https://user-images.githubusercontent.com/5044450/116019434-282c9580-a67f-11eb-8cad-c9c905f2a4af.jpeg)


    func rtmpInfoSetting() {
        let bitRate = OptionsModel.shared.bitrate
        let audioBitRate = 192 * 1000
        let videoBitRate = bitRate - audioBitRate
        let videoSize = OptionsModel.shared.videoSize
        
        rtmpStream = RTMPStream(connection: rtmpConnection)
        
        
        if let orientation = DeviceUtil.videoOrientation(by: ifOrientation()) {
            rtmpStream.orientation = orientation
        }
        rtmpStream.captureSettings = [
            .fps: 30,
//            .sessionPreset: AVCaptureSession.Preset.hd1280x720,
            .sessionPreset: AVCaptureSession.Preset.inputPriority,
            .continuousAutofocus: true,
            .continuousExposure: true,
            .preferredVideoStabilizationMode: AVCaptureVideoStabilizationMode.auto
        ]

        rtmpStream.audioSettings = [
            .muted: false, // mute audio
            .bitrate: audioBitRate,
        ]
        rtmpStream.videoSettings = [
            .width: 1080, // video output width
            .height: 1920, // video output height
            .bitrate: videoBitRate, // video output bitrate
            .profileLevel: kVTProfileLevel_H264_Baseline_1_3, // H264 Profile require "import VideoToolbox"
            .maxKeyFrameIntervalDuration: 2, // key frame / sec
        ]
        
        
        rtmpStream.mixer.recorder.delegate = ExampleRecorderDelegate.shared

        //        rtmpStream.videoSettings = [
        //            .width: 720,
        //            .height: 1280
        //        ]

        rtmpStream.audioSettings[.bitrate] = 192 * 1000
        rtmpStream.videoSettings[.bitrate] = 2400 * 1000

        rtmpStream.captureSettings[.fps] = 30.0

        
        NotificationCenter.default.addObserver(self, selector: #selector(on(_:)), name: UIDevice.orientationDidChangeNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(didEnterBackground(_:)), name: UIApplication.didEnterBackgroundNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(didBecomeActive(_:)), name: UIApplication.didBecomeActiveNotification, object: nil)

        
        
//        rtmpStream.audioSettings = [
//            .muted: false, // mute audio
//            .bitrate: 32 * 1000,
//        ]

            // 일단.....
        // "0" means the same of input
        rtmpStream.recorderSettings = [
            AVMediaType.audio: [
                AVFormatIDKey: Int(kAudioFormatMPEG4AAC),
                AVSampleRateKey: 0,
                AVNumberOfChannelsKey: 0,
                // AVEncoderBitRateKey: 128000,
            ],
            AVMediaType.video: [
                AVVideoCodecKey: AVVideoCodecType.h264,
                AVVideoHeightKey: 0,
                AVVideoWidthKey: 0,
            ],
        ]
        
    }

**Comment by shogo4405** [comment]
The `480 * 272` value is default. It seemes that can't set property. 
I'm recommend `.propertyLevel = kVTProfileLevel_H264_Main_AutoLevel`
```
rtmpStream.videoSettings = [
            .width: 1080, // video output width
            .height: 1920, // video output height
            .bitrate: videoBitRate, // video output bitrate
            .profileLevel:kVTProfileLevel_H264_Main_AutoLevel, // H264 Profile require "import VideoToolbox"
            .maxKeyFrameIntervalDuration: 2, // key frame / sec
        ]
```

**Comment by mud0107** [comment]
Hi. !
.profileLevel:kVTProfileLevel_H264_Main_AutoLevel,
Even if the setting is made, playback will be performed at the resolution of "480*272" in the playback information.
The same applies to other setting information ":kVTProfileLevel_H264_High_AutoLevel".
<img width="427" alt="cap_2021-04-28" src="https://user-images.githubusercontent.com/5044450/116355265-91a1d500-a834-11eb-9e3c-ff2d04da8014.png">

**Comment by shogo4405** [comment]
I can't reproduce it. Please resolve yourself.
