### ISSUE TITLE
Question: Is there a way to disable frame dropping?

### ISSUE THREAD

**Issue by EitanGoldfrad** [shogo4405/HaishinKit.swift#864]
Hi @shogo4405 ,

Is there a way to disable frame dropping entirely?

For example by increasing the queue buffer size and letting the latency grow until the network speed goes up?

Thanks!

**Comment by shogo4405** [comment]
Please comment out this line. https://github.com/shogo4405/HaishinKit.swift/blob/e773532b57bbfaec603bd7d7ba809810d6d06af2/Sources/RTMP/RTMPStream.swift#L621
