### ISSUE TITLE
Screen capture broadcast doesn't show the video output in the RTMP server when Streamed from macOS. 

### ISSUE THREAD

**Issue by rizwan95** [shogo4405/HaishinKit.swift#865]
**Describe the bug**
Screen capture broadcast doesn't show the video output in the RTMP server when Streamed from macOS. 

**To Reproduce**
1. Download the sample project included in the repository.
2. Install dependencies. 
3. Select the macOS target and run.
4. The video will be rendered in the app's preview but not in the RTMP server. It will be distorted. 

**Expected behavior**
The video output should be seen in the RTMP server. 

**Screenshots**
Video output in the app preview
<img width="650" alt="Video output in the app preview" src="https://user-images.githubusercontent.com/10910174/115959571-7419f600-a52a-11eb-9689-f40d43cd52d2.png">

Video output in the RTMP server

<img width="1200" alt="Screenshot 2021-04-24 at 7 11 09 PM" src="https://user-images.githubusercontent.com/10910174/115960880-7895dd00-a531-11eb-86cf-15cead545003.png">

**Desktop:**
 - OS: macOS (M1 Chip)
 - Version - 11.2.3 (20D91)

LogBoard log
[Logboardlog.txt](https://github.com/shogo4405/HaishinKit.swift/files/6369731/Logboardlog.txt)

**Comment by shogo4405** [comment]
It seemes might be fixed it https://github.com/shogo4405/HaishinKit.swift/pull/850

**Comment by rizwan95** [comment]
Oh wow! I will give it a try! Thank you so much!

**Comment by shogo4405** [comment]
Please try master branch. I'm not released yet.

**Comment by rizwan95** [comment]
It Works!
