### ISSUE TITLE
Connection always NetConnection.Connect.Closed

### ISSUE THREAD

**Issue by sergykapitan** [shogo4405/HaishinKit.swift#866]
Describe the bug
When I try to connect to rmtp server, the notification event always reports NetConnection.Connect.Closed.

To Reproduce
The RTMP server url I'm using looks something like this, it is an AWS server, there is no authentication

rtmp://vp-push-ix1.gvideo.co/in/67674?10e42ad17cff46bfa0118f5043180884

This url is generated before the stream starts, I receive this url from API and then in the callback I call the connect function.

Smartphone (please complete the following information):

Device: iPhone 11, iPhone 8
OS: iOS 14.3

Additional context
I thought it might be the url address that's wrong, but later I tried another streaming library LFLiveKit and it worked immediately, and the Android version of the app I'm working on also works without problems, so I've been wondering what's wrong here.

I did the setup same way it is showed in the example, only it will never connect and it gets closed immediately.

Thanks you for help! I really like this library and would be sad to not be able to use it :)

**Comment by shogo4405** [comment]
Can I see these settings?
- rtmpConnection.connect("$connectURL")
- rtmpStream.publish("$streamName")

**Comment by sergykapitan** [comment]
`struct Preference {
    static var defaultInstance = Preference()

    var uri: String? = "rtmp://vp-push-ix1.gvideo.co/in"
    var streamName: String? = "67674?10e42ad17cff46bfa0118f5043180884"
}
`

**Comment by shogo4405** [comment]
Please try

### No.1
```
struct Preference {
    static var defaultInstance = Preference()

    var uri: String? = "rtmp://vp-push-ix1.gvideo.co/in?10e42ad17cff46bfa0118f5043180884"
    var streamName: String? = "67674"
}
```


### No.2
```
struct Preference {
    static var defaultInstance = Preference()

    var uri: String? = "rtmp://vp-push-ix1.gvideo.co/in/" // require last "/" 
    var streamName: String? = "67674?10e42ad17cff46bfa0118f5043180884"
}
```

**Comment by sergykapitan** [comment]
No2 Work , Thank you!
