### ISSUE TITLE
What is the difference in resolution between mOS and iOS when transmitting?

### ISSUE THREAD

**Issue by mud0107** [shogo4405/HaishinKit.swift#867]
Hi..!
The resolution for publishing to the iPhone was 480 * 272 by default.
So, I modified the code as follows and executed it.
Log in window
"logger.error("encoding failed with kVTParameterErr. Perhaps the width x height is too big for the encoder setup?") "
Comes out as.

The fix code is
public static let defaultWidth: Int32 = 1080
     public static let defaultHeight: Int32 = 1920
     public static let defaultBitrate: UInt32 = 1200 * 1000
     public static let defaultScalingMode: ScalingMode = .normal

And handled it.

But why on macOS? Doesn't the same ligament error come out?
What is different?

![cap0429_2](https://user-images.githubusercontent.com/5044450/116514575-2e807300-a906-11eb-89b6-9b4a8a511295.jpeg)
![cap0429_01](https://user-images.githubusercontent.com/5044450/116514703-57a10380-a906-11eb-9a19-69d48be4af26.jpg)

**Comment by shogo4405** [comment]
I don't know.
