### ISSUE TITLE
broadcast front and back camera's simultaneously?

### ISSUE THREAD

**Issue by usman179821** [shogo4405/HaishinKit.swift#868]
Hi, 
I want to broadcast front and back camera at the same time.  Right now my idea is to use back camera default which is right now used in library. For the front camera i want to use Effects but unfortunately i am unable to achieve this. I have read some issues as well but those issues are from 2016. I am getting error while applying this solution "https://github.com/shogo4405/HaishinKit.swift/issues/28#issuecomment-213821706". Because this ans is too old. 
Can you please help me how to achieve this thing. I am pretty sure i will achieve this thing by only using HaishinKit library.

Regards,
Usman

**Comment by Arslanmajeed270** [comment]
Hi, Have you find any solution?
