### ISSUE TITLE
Recording HLS stream

### ISSUE THREAD

**Issue by iosdeveloper** [shogo4405/HaishinKit.swift#872]
Can I use HaishinKit to play/record a HLS stream from a m3u8 URL? I couldn't find the HLS equivalent to `RTMPConnection.connect()`. I would appreciate any pointers. If this is not supported yet I'm interested in sponsoring the development if anyone is available for it.

**Comment by shogo4405** [comment]
No. I recommended, to play for AVPlayer and to record for ffmpeg.
I will not implement this feature.
