### ISSUE TITLE
Can't broadcast my application screen.

### ISSUE THREAD

**Issue by Bhaswati-Redapple** [shogo4405/HaishinKit.swift#873]
I have written following code to see my application screen broadcasting in youtube Golive but it does not work.
import UIKit
import HaishinKit
import AVFoundation
import Logboard
import VideoToolbox
let logger = Logboard.with("com.haishinkit.Exsample.iOS")

class ViewController: UIViewController {
    private var rtmpConnection = RTMPConnection()
    private var rtmpStream: RTMPStream!
    override func viewDidLoad() {
        super.viewDidLoad()
        rtmpStream = RTMPStream(connection: rtmpConnection)
        rtmpStream.captureSettings = [
            .fps: 30, // FPS
            .sessionPreset: AVCaptureSession.Preset.medium, // input video width/height
            // .isVideoMirrored: false,
            // .continuousAutofocus: false, // use camera autofocus mode
            // .continuousExposure: false, //  use camera exposure mode
            // .preferredVideoStabilizationMode: AVCaptureVideoStabilizationMode.auto
        ]
        rtmpStream.audioSettings = [
            .muted: false, // mute audio
            .bitrate: 32 * 1000,
        ]
        rtmpStream.videoSettings = [
            .width: 640, // video output width
            .height: 360, // video output height
            .bitrate: 160 * 1000, // video output bitrate
            .profileLevel: kVTProfileLevel_H264_Baseline_3_1, // H264 Profile require "import VideoToolbox"
            .maxKeyFrameIntervalDuration: 2, // key frame / sec
        ]
    }
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
       
    }
    @IBAction func on(publish: UIButton) {
        UIApplication.shared.isIdleTimerDisabled = true
        rtmpConnection.addEventListener(.rtmpStatus, selector: #selector(rtmpStatusHandler), observer: self)
        rtmpConnection.addEventListener(.ioError, selector: #selector(rtmpErrorHandler), observer: self)
        rtmpConnection.connect("rtmp://a.rtmp.youtube.com/live2/pa0x-y94j-md79-bb69-fx7z")
        rtmpStream!.publish("hello")
        rtmpStream.attachScreen(ScreenCaptureSession(shared: UIApplication.shared))
    }
    
  
    @objc
    private func rtmpStatusHandler(_ notification: Notification) {
        let e = Event.from(notification)
        guard let data: ASObject = e.data as? ASObject, let code: String = data["code"] as? String else {
            return
        }
        logger.info(code)
        switch code {
        case RTMPConnection.Code.connectSuccess.rawValue:
            rtmpStream!.publish("hello")
            rtmpStream.attachScreen(ScreenCaptureSession(shared: UIApplication.shared))
        case RTMPConnection.Code.connectFailed.rawValue, RTMPConnection.Code.connectClosed.rawValue:
            rtmpConnection.connect("rtmp://a.rtmp.youtube.com/live2/pa0x-y94j-md79-bb69-fx7z")

        default:
            break
        }
    }

    @objc
    private func rtmpErrorHandler(_ notification: Notification) {
        logger.error(notification)
        rtmpConnection.connect("rtmp://a.rtmp.youtube.com/live2/pa0x-y94j-md79-bb69-fx7z")
        rtmpStream.attachScreen(ScreenCaptureSession(shared: UIApplication.shared))
    }
}

**Comment by Piyushhhhh** [comment]
@Bhaswati-Redapple  you need to call    rtmpStream.attachScreen(ScreenCaptureSession(shared: UIApplication.shared)) before stream publish
