### ISSUE TITLE
Displaying Raw H264 Data With Video Toolbox

### ISSUE THREAD

**Issue by jerrypainter** [shogo4405/HaishinKit.swift#874]
Hey there,

Does HaishinKit support raw h264 data? For example, I put a data object in a function and then the decoder gives back a CMSampleBufferRef. I did't see this in the guide. Thanks in advance.

Best,
Jerry

**Comment by shogo4405** [comment]
HaishinKit has no feature. But You can see the H264 decoding program. https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/Codec/H264Decoder.swift#L101

Please reference it.
