### ISSUE TITLE
VideoIOComponent orientation manual override

### ISSUE THREAD

**Issue by relatedcode** [shogo4405/HaishinKit.swift#879]
Please make it possible to override the default VideoIOComponent orientation.

It would be nice to have the following option to be available, whenever it's necessary:

`rtmpStream.mixer.videoIO.orientation = .landscapeRight`

At the moment it's not possible. It says:

> 'videoIO' is inaccessible due to 'internal' protection level

Thank you! :)

**Comment by shogo4405** [comment]
Thank you. Feedback.
I'm waiting your PR. 

Regards.

**Comment by relatedcode** [comment]
@shogo4405 FYI https://github.com/shogo4405/HaishinKit.swift/pull/886 Thanks!
