### ISSUE TITLE
Haishinkit Play Library crashed on the H264Decoder module

### ISSUE THREAD

**Issue by dovelive** [shogo4405/HaishinKit.swift#881]
Thank you for checking my error.

**Describe the bug**
I created the rtmp publishing and playing app using the Haishinkit.
I embedded the Hashinkit using Carthage.

But my app crashed while while playing the rtmp streams.

Below is the crash screenshot.
I think error is related with the H264Decoder.
![1](https://user-images.githubusercontent.com/19376598/123820755-666b5d00-d92d-11eb-80a4-7160121e50a8.PNG)

And my code for player is same with the sample playback source code.
https://github.com/shogo4405/HaishinKit.swift/blob/master/Examples/iOS/PlaybackViewController.swift

Please check this issue and fix the error.

**Comment by dovelive** [comment]
I added the new screenshot for describing more detail about the error.
![image](https://user-images.githubusercontent.com/19376598/123834856-7473aa80-d93a-11eb-9856-8c3d4bd5ea5a.png)

**Comment by shogo4405** [comment]
I can't reproduce it.
