### ISSUE TITLE
[Question] Can I preview at high FPS, and stream at low FPS?

### ISSUE THREAD

**Issue by gfpacheco** [shogo4405/HaishinKit.swift#882]
I'm sorry, I couldn't find the answer to my question anywhere, and I don't know a better place to ask either, let me know if there is.

I want to preview the camera at high fps, but stream at low fps, is that possible using Haishinkit and HKView in iOS?

I tried creating my own AVCaptureSession, Input and Preview Layer using the same Device, but when I publish the stream my preview stops.

**Comment by shogo4405** [comment]
HaishinKit has no feature.
