### ISSUE TITLE
Unable to start camera rendering once app will go into background and then open the app again

### ISSUE THREAD

**Issue by ShahRiddhiGirishkumar** [shogo4405/HaishinKit.swift#883]
Hello,

I am using MTHKView in storyboard which is used to render camera. but when I go into background and open app again, camera is freezes. I tried multiple ways, but not working. Can you please check?

**Comment by shogo4405** [comment]
I can't reproduce it. Please use issue template and write reproduce steps.
Regards.

**Comment by ShahRiddhiGirishkumar** [comment]
HI

I am streaming using rtmp stream


> I can't reproduce it. Please use issue template and write reproduce steps.
> Regards.

I have just simply integrated view in a storyboard and taken its outlet, when I open the controller then its working fine, but going in background and coming in foreground is not working. I mean camera freezes @shogo4405
