### ISSUE TITLE
Appending audio sample buffer crashes when unwrapping _converter variable

### ISSUE THREAD

**Issue by alexisPonce98** [shogo4405/HaishinKit.swift#889]
**Describe the bug**
When i am appending audio sample buffers from a RPScreenRecorder, the app is crashing with HaishinKit/AudioCodec.swift:164: Fatal error: Unexpectedly found nil while unwrapping an Optional value. It seems to be when the _converter variable from the AudioCodec class. If i attach the app audio it doesnt seem to crash but there is also no audio being passed to the stream, it only happens with mic audio. 
**To Reproduce**
1. append an audio sampleBuffer to the stream

**Expected behavior**
Not to crash and append the audio to the stream.
<img width="1440" alt="Screen Shot 2021-07-18 at 3 20 01 PM" src="https://user-images.githubusercontent.com/79240148/126083820-6f7e9231-2b7b-44b9-84af-029e0dd0fe8e.png">

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.6

**Additional context**

**Comment by shogo4405** [comment]
It caused to crash with an unsupported input format for CMSampleBuffer.
I see `mChanneIsPerFrame: 3`. It value is mChanneIsPerFrame: 2(stereo) or 1(mono) normal.

Please provide more info  `print(RPScreenRecorder.CMSampleBuffer)`.

**Comment by alexisPonce98** [comment]
Thank you for your reply!, yea i thought that was weird that i am getting mChannelsIsPerFram: 3. Here is a screenshot of the sample all the info from the sample buffer that is being captured by rpScreenRecorder.
![Screen Shot 2021-07-30 at 12 34 57 PM](https://user-images.githubusercontent.com/79240148/127703666-45b80cfd-4a4d-4c09-9fcb-8f2b3157ca38.png)

**Comment by SergiyZhyrov** [comment]
Hello. Just update one `enum`
```
    enum ChannelConfiguration: UInt8 {
        case definedInAOTSpecificConfig = 0
        case frontCenter = 1
        case frontLeftAndFrontRight = 2
        case frontCenterAndFrontLeftAndFrontRight = 3
        case frontCenterAndFrontLeftAndFrontRightAndBackCenter = 4
        case frontCenterAndFrontLeftAndFrontRightAndBackLeftAndBackRight = 5
        case frontCenterAndFrontLeftAndFrontRightAndBackLeftAndBackRightLFE = 6
        case frontCenterAndFrontLeftAndFrontRightAndSideLeftAndSideRightAndBackLeftAndBackRightLFE = 7
        
        case ch8 = 8
        case ch9  = 9
        case ch10 = 10
        case ch11 = 11
        case ch12 = 12
        case ch13 = 13
        case ch14 = 14
        case ch15 = 15
        case ch16 = 16
    }
```

and also change `defaultChannels` in `public class AudioCodec`. Converter can't convert to 16 output channels
    /// 0 means according to a input source
    public static let defaultChannels: UInt32 = 2
    
 To reproduce bug, just try `BlackHole` with 16 channels  https://github.com/ExistentialAudio/BlackHole

**Comment by shogo4405** [comment]
HaishinKit can support 1 or 2 channels input audio.
I thought iOS can't support 3 channels an AudioConverter.
I will not fix it.
