### ISSUE TITLE
Metadata don't send if you append  as CMSampleBuffer 

### ISSUE THREAD

**Issue by andrew3213221** [shogo4405/HaishinKit.swift#892]
**Describe the bug**
RTMP stream
Metadata don't send if you append  as CMSampleBuffer 

**To Reproduce**
Steps to reproduce the behaviour:
connect to RTMP server and use input as sample buffer 
`RTMPStream.appendSampleBuffer(CMSampleBuffer, AVMediaType)`
the problem is when message with data send 
use function createMetaData which check if input device was used 
but appendSampleBuffer doesn't set input device as function attachCamera

**Expected behavior**
When you use own capture session with output metadata must be included also

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 1.1.6

**Comment by shogo4405** [comment]
I have no good idea.  Please override `RTMPStream`.
```
class YourRTMPStream: RTMPStream {
    override func createMetadata() -> ASObject  {
           ...
    }
}
```
https://github.com/shogo4405/HaishinKit.swift/pull/1074

Close as won't fix.
