### ISSUE TITLE
`RTMPConnection.Code.connectAppshutdown` level is "status" ? (and more)

### ISSUE THREAD

**Issue by SergiyZhyrov** [shogo4405/HaishinKit.swift#893]
Is this typo in code?
1) `RTMPConnection.Code.connectAppshutdown` level is `"status"` but on site
https://help.adobe.com/en_US/air/reference/html/flash/events/NetStatusEvent.html#NET_STATUS
level property is `error`
"NetConnection.Connect.AppShutdown" | "error" | The server-side application is shutting down.

https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/RTMP/RTMPConnection.swift#L62-L63

2) same with `case .connectRejected:  return "status"` but on site `"NetConnection.Connect.Rejected" | "error"`

3)  same with `RTMPStream-> case .playStreamNotFound:  return "status"` but on site `"NetStream.Play.StreamNotFound" | "error"`

**Comment by shogo4405** [comment]
Thank you feedback. I fixed it.
