### ISSUE TITLE
How to use HLS with Broadcast Extension UI

### ISSUE THREAD

**Issue by dongnv1991** [shogo4405/HaishinKit.swift#900]
I'm trying to show the phone screen to the browser with Broadcast Extension UI using HLS, but when accessing the addresses on safari, there is no content displayed, only a blank page.

The contents of the SampleHandler file are as follows:

```
class SampleHandler: RPBroadcastSampleHandler {
    
    var httpStream : HTTPStream!
    var httpService: HLSService!
    
    override func broadcastStarted(withSetupInfo setupInfo: [String : NSObject]?) {
        // User has requested to start the broadcast. Setup info from the UI extension can be supplied but optional.
        httpStream = HTTPStream()
        httpStream.publish("hello")
        httpService = HLSService(domain: "", type: "_http._tcp", name: "Cast", port: 8080)
        httpService.startRunning()
        httpService.addHTTPStream(httpStream)
    }
    
    override func broadcastPaused() {
        // User has requested to pause the broadcast. Samples will stop being delivered.
    }
    
    override func broadcastResumed() {
        // User has requested to resume the broadcast. Samples delivery will resume.
    }
    
    override func broadcastFinished() {
        // User has requested to finish the broadcast.
    }
    
    override func processSampleBuffer(_ sampleBuffer: CMSampleBuffer, with sampleBufferType: RPSampleBufferType) {
        switch sampleBufferType {
        case RPSampleBufferType.video:
            self.httpStream.appendSampleBuffer(sampleBuffer, withType: .video)
            break
        case RPSampleBufferType.audioApp:
            // Handle audio sample buffer for app audio
            httpStream.appendSampleBuffer(sampleBuffer, withType: .audio)
            break
        case RPSampleBufferType.audioMic:
            // Handle audio sample buffer for mic audio
            httpStream.appendSampleBuffer(sampleBuffer, withType: .audio)
            break
        @unknown default:
            // Handle other sample buffer types
            fatalError("Unknown type of sample buffer")
        }
    }
}

```

What link do I have to go to to be able to see the mirrored content on the screen. 
I have tried the links:
http://localhost:8080
http://ip.address:8080
http://ip.address:8080/hello/playlist.m3u8 >> no items.
If my above code is wrong, please guide how to fix it.

**Smartphone **
 - Device: iPhone 7 Plus, XR
 - OS: iOS 14, iOS 15
 - Browser : Safari

**Comment by shogo4405** [comment]
1st, please call `startRunning` in this order.
```
    override func broadcastStarted(withSetupInfo setupInfo: [String : NSObject]?) {
        httpStream = HTTPStream()
        httpService = HLSService(domain: "", type: "_http._tcp", name: "Cast", port: 8080)
        httpService.addHTTPStream(httpStream)
        httpService.startRunning()
        httpStream.publish("hello")
   }
```

2nd, HTTPStream can't append `.audioApp` and `.audioMic`.
Please select an .audioApp or .audioMic one option.

```
        case RPSampleBufferType.audioApp:
            // Handle audio sample buffer for app audio
            // Please comment out this line.
            // httpStream.appendSampleBuffer(sampleBuffer, withType: .audio)
            break
        case RPSampleBufferType.audioMic:
            // Handle audio sample buffer for mic audio
           httpStream.appendSampleBuffer(sampleBuffer, withType: .audio)
           break
```

Best regards.

**Comment by dongnv1991** [comment]
Thanks

> 1st, please call `startRunning` in this order.
> 
> ```
>     override func broadcastStarted(withSetupInfo setupInfo: [String : NSObject]?) {
>         httpStream = HTTPStream()
>         httpService = HLSService(domain: "", type: "_http._tcp", name: "Cast", port: 8080)
>         httpService.addHTTPStream(httpStream)
>         httpService.startRunning()
>         httpStream.publish("hello")
>    }
> ```
> 
> 2nd, HTTPStream can't append `.audioApp` and `.audioMic`.
> Please select an .audioApp or .audioMic one option.
> 
> ```
>         case RPSampleBufferType.audioApp:
>             // Handle audio sample buffer for app audio
>             // Please comment out this line.
>             // httpStream.appendSampleBuffer(sampleBuffer, withType: .audio)
>             break
>         case RPSampleBufferType.audioMic:
>             // Handle audio sample buffer for mic audio
>            httpStream.appendSampleBuffer(sampleBuffer, withType: .audio)
>            break
> ```
> 
> Best regards.

**Comment by dongnv1991** [comment]
Thanks, 
I appreciate your reply,

I have modified the code,

> override func broadcastStarted(withSetupInfo setupInfo: [String : NSObject]?) {
>         // User has requested to start the broadcast. Setup info from the UI extension can be supplied but optional.
>         httpStream = HTTPStream()
>         httpService = HLSService(domain: "", type: "_http._tcp", name: "Cast", port: 8080)
>         httpService.addHTTPStream(httpStream)
>         httpService.startRunning()
>         httpStream.publish("hello")
>     }


However when accessing the link,
http://ip.address:8080/hello/playlist.m3u8 (http://192.168.1.13:8080/hello/playlist.m3u8)
I still can't see the mirror screen.

What is the correct link?

**Comment by dongnv1991** [comment]
I still can't connect. Please help.

**Comment by dongnv1991** [comment]
I added more pictures, tested with safari on mac. Same thing on my iPhone.

![image](https://user-images.githubusercontent.com/17741140/130257596-287b5301-54d8-498d-9780-f7ffc14dfe72.png)

Hope to hear from you soon.

**Comment by dongnv1991** [comment]
Everything worked after I added the following code:

httpStream.expectedMedias.insert(.video)
Thanks.
