### ISSUE TITLE
Carthage を走らせたにも関わらず、Logboard.xcframework が見つからずに build が失敗します

### ISSUE THREAD

**Issue by snakajima** [shogo4405/HaishinKit.swift#901]
**Describe the bug**
はじめまして。はじめて試みたのですが、xcode でビルドしたところ、
/Users/satoshi/git/open/HaishinKit.swift/Carthage/Build/Logboard.xcframework:1:1: While building for iOS, no library for this platform was found in '/Users/satoshi/git/open/HaishinKit.swift/Carthage/Build/Logboard.xcframework'.
というエラーで失敗します。carthage も走らせています。

**To Reproduce**
1. HaishinKit.swift をクローン
2. carthage bootstrap --use-xcframeworks を実行
*** No Cartfile.resolved found, updating dependencies
*** Cloning Logboard
*** Checking out Logboard at "2.2.2"
*** xcodebuild output can be found in /var/folders/hp/_fhb12m95z370782s4_6d1jh0000gn/T/carthage-xcodebuild.n14Yhn.log
*** Building scheme "Logboard watchOS" in Logboard.xcodeproj
*** Building scheme "Logboard tvOS" in Logboard.xcodeproj
*** Building scheme "Logboard macOS" in Logboard.xcodeproj
*** Building scheme "Logboard iOS" in Logboard.xcodeproj*** No Cartfile.resolved found, updating dependencies
*** Cloning Logboard
*** Checking out Logboard at "2.2.2"
*** xcodebuild output can be found in /var/folders/hp/_fhb12m95z370782s4_6d1jh0000gn/T/carthage-xcodebuild.n14Yhn.log
*** Building scheme "Logboard watchOS" in Logboard.xcodeproj
*** Building scheme "Logboard tvOS" in Logboard.xcodeproj
*** Building scheme "Logboard macOS" in Logboard.xcodeproj
*** Building scheme "Logboard iOS" in Logboard.xcodeproj
3. Xcode （Version 12.5.1 (12E507)）でHaishinKit.xcodeprojを開く
4. Example iOS->iPhone を選んで build

**Desktop (please complete the following information):**
 - OS: macOS Big Sur Version 11.4 
 - Hardware: M1 MacBook Air

**Comment by shogo4405** [comment]
ご連絡ありがとうございます。申し訳ないです。私の手元で再現しないため、わからないです。

1. わたしの手元の環境が、M1ではなくIntel Mac なのでもしかするとその違いの可能性
2. 利用しているiPhoneのアーキテクチャのビルドが対応していない可能性
    1. iPhone 11 Pro max + iOS14.5 で検証しました。

の仮説がありますが、真偽を確かめるのが難しいです。

手元で実行したコマンド
```
git clone git@github.com:shogo4405/HaishinKit.swift.git
cd HaishinKit.swift 
carthage bootstrap --use-xcframeworks
> Please update to the latest Carthage version: 0.38.0. You currently are on 0.37.0
```

直接の解決には至らないのですが、評価という点であれば CocoaPods を利用いただき、
自身でサンプルコードをコピペしていただけば動作確認いただけると思います。
