### ISSUE TITLE
Can't add HaishinKit with SPM

### ISSUE THREAD

**Issue by Goule** [shogo4405/HaishinKit.swift#917]
Hello 

**Describe the bug**
Can't install HaishinKit with SPM. 

**To Reproduce**
1. Create project
2. Add HaishinKit with SPM 
3. Compile

**Screenshots**
<img width="1627" alt="Capture d’écran 2021-10-05 à 16 44 15" src="https://user-images.githubusercontent.com/21126201/136046137-e5b01614-46f2-4b5f-95c9-12ad266019ae.png">

**Additional context**
XCode 13

Thanks

**Comment by tsahi-deri** [comment]
+1

**Comment by tsahi-deri** [comment]
@shogo4405 Can you please estimate when is the next release with that fix ?
