### ISSUE TITLE
Stream Starting Overlay

### ISSUE THREAD

**Issue by AnkitaPundir** [shogo4405/HaishinKit.swift#920]
**Describe the bug**
I was trying to add Stream Start Overlay for the first 15 sec of the stream. After 15 seconds Video frames are getting distorted.

<img width="744" alt="Screenshot 2021-10-11 at 10 39 37 AM" src="https://user-images.githubusercontent.com/62744295/136736421-f2e1e01b-de99-4d3a-ab71-cee8d2c44ad7.png">

<img width="720" alt="Screenshot 2021-10-11 at 10 39 30 AM" src="https://user-images.githubusercontent.com/62744295/136736430-4aa5fdf3-034e-4fe3-bc27-7da408581c76.png">

**Expected behavior**
Video Frames should not discort after we remove the start Overlay Image.

Note:- Issue is only for iPhone, On iPad this is not happning. Video frame are fine even after the start stream overlay.

To Add Stream Start Overly I am Passing only Stream Overlay image for fist 15 second. after that only video frames.
Becuse if i add stream overlay over video frame ...than Overlay Image will be streached according to video frames size.

Any Help?

**Comment by shogo4405** [comment]
What’s the meaning of 'Stream Starting Overlay'?
How can I reproduce it?
