### ISSUE TITLE
バックグランド時に音声のみを配信する方法について

### ISSUE THREAD

**Issue by Rikukuku** [shogo4405/HaishinKit.swift#926]
## 概要
配信中のアプリをバックグランドにしたときに音声のみを配信することは可能でしょうか？

過去のIssuueを拝見させてもらったところ、映像はバックグランドでは配信不可能ということがわかりましたが、
[音声であれば配信可能](https://github.com/shogo4405/HaishinKit.swift/issues/124#issuecomment-253911285)であるという旨のコメントを確認したので、お伺いしました。

もし可能であれば、実装方法などをご教授いただけますと幸いです。

## 確認したIssue
https://github.com/shogo4405/HaishinKit.swift/issues/124
https://github.com/shogo4405/HaishinKit.swift/issues/525
https://github.com/shogo4405/HaishinKit.swift/issues/626
https://github.com/shogo4405/HaishinKit.swift/issues/847

**Comment by shogo4405** [comment]
- iOS12 の時代だと既存のコードでできた記憶があります。
- iOS15 の時代だと、カメラを利用している場合にバックグラウンドにうつると`AVCaptureSession`が停止させられているようでした
   - 回避方法として、バックグラウンドとフォアグランド時にカメラのデタッチとアタッチを行えば動きました
``` 
        NotificationCenter.default.addObserver(self, selector: #selector(didEnterBackground(_:)), name: UIApplication.didEnterBackgroundNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(didBecomeActive(_:)), name: UIApplication.didBecomeActiveNotification, object: nil)

   @objc
    private func didEnterBackground(_ notification: Notification) {
        rtmpStream.attachCamera(nil)
    }

    @objc
    private func didBecomeActive(_ notification: Notification) {
        rtmpStream.attachCamera(DeviceUtil.device(withPosition: currentPosition)) { error in
            logger.warn(error.description)
        }
    }
```

**Comment by Rikukuku** [comment]
iOSのバージョンの問題だったのですね...
ご教授頂いたコードを追加すると、正常に動作するようになりました！

お忙しい中ご返信ありがとうございました。
