### ISSUE TITLE
Any way to know if LTE or WiFi currently being used?

### ISSUE THREAD

**Issue by mkrn** [shogo4405/HaishinKit.swift#931]
**Is your feature request related to a problem? Please describe.**
Since only LTE or WiFi can be used at a time it is good to know which one is being used. That way users could tell to switch to a stronger connection if it is available to save data. 

**Describe the solution you'd like**
A way to access the variable to know the details about the connection socket was open.

**Describe alternatives you've considered**
The status bar indicator doesn't show which connection is being used.

**Additional context**

**Comment by shogo4405** [comment]
HaishinKit has no feature. I also want to know that.
It seemes can't detect WiFi/LTE the NSStream https://developer.apple.com/documentation/foundation/nsinputstream.

iOS12 has network monitoring feature. https://developer.apple.com/documentation/network/nwpath.
I think can detect LTE/WiFi this monitor.
