### ISSUE TITLE
Stream stop when push new ViewController

### ISSUE THREAD

**Issue by namnvsskpi** [shogo4405/HaishinKit.swift#933]
**Describe the bug**
i'm doing a normal live broadcast, when i push a new ViewController by pushViewController then user can't watch livestream any more, It's freezing. And i got log info: 
```bash
2021-11-11 11:27:40.209 [Info] [com.haishinkit.HaishinKit] [AudioCodec.swift:81] formatDescription > nil
```
 
How can I still go live while on another screen?

**Smartphone (please complete the following information):**
 - Device: [iPhone7]
 - OS: [e.g. iOS14.4.2] 
 - Version [1.2.2]

**Comment by shogo4405** [comment]
Could you please provide us reproduce code?

**Comment by namnvsskpi** [comment]
Sorry my fault.
in my viewDidDisappear closed my collection.
