### ISSUE TITLE
Add example for SwiftUI

### ISSUE THREAD

**Issue by mildis** [shogo4405/HaishinKit.swift#934]
Hi,

Could you point to a working example of integrating HaishinKit with SwiftUI ?

Thanks

**Comment by shogo4405** [comment]
I'm not familiar with SwiftUI. I can't explain it.

**Comment by y2kpaulh** [comment]
I have tested in SwiftUI target. but, any code is not exist in ContentView.swift. Not porting swift feature yet ?
