### ISSUE TITLE
Missing video on sublayer when streaming to Facebook, NDI Server...

### ISSUE THREAD

**Issue by seanmars** [shogo4405/HaishinKit.swift#943]
**Describe the bug**
I have a video with alpha(hevc), and I add this video to sublayer. It's shown on screen but when I streaming to Facebook and NDI Server, that video is missing on Fb and NDI Server.

**To Reproduce**
1. Load the video and create AVPlayer
2. Create AVPlayerLayer
3. Add the AVPlayerLayer to the main view's sublayer

**Smartphone (please complete the following information):**
 - Device: Any iPhone
 - OS: iOS 13, 14, 15

**Comment by shogo4405** [comment]
Unfortunately, iOS not allowed to capture the AVPlayerLayer. 
It's in the specifications.
