### ISSUE TITLE
Sending two CMSampleBuffers

### ISSUE THREAD

**Issue by darnfish** [shogo4405/HaishinKit.swift#946]
I'd love to be able to send two different CMSampleBuffer streams for audioApp and audioMic in RPBroadcastSampleHandler. Currently when trying to do this the memory maxes out at 50MB and crashes the target.

I'm not sure how these two buffers could be merged (I've looked around for solutions), I've found [this](https://github.com/AgoraIO/Agora-Extensions/blob/6ac3172b91b1e95496dbba2739f2807970e336ce/RtmpStreaming/ios/LiveStreaming-iOS-Objective-C/ScreenShare/Utils/AgoraAudioTube.mm) but I'm not sure how to implement it in Swift, let alone trying to send through an RTMPConnection. 

What would it take to be able to send these two CMSampleBuffers so streams could have the users mic alongside the in-app audio?

**Comment by shogo4405** [comment]
Unfortunately HaishinKit has no mix audioApp and audioMic feature.
https://github.com/shogo4405/HaishinKit.swift/issues/689

Regards.

**Comment by darnfish** [comment]
@shogo4405 does this mean it's not planned for the future? I know it doesn't currently have one but it'd be cool to see it down the line.

**Comment by shogo4405** [comment]
Yes, I have **no** plan for the future.
