### ISSUE TITLE
encoder height and width issue

### ISSUE THREAD

**Issue by HamzaKiyani43** [shogo4405/HaishinKit.swift#947]
brother i have changed encoder width and height in AVVideoIOUnit class for attachscreen method, code is below:

func session(_ session: CaptureSessionConvertible, didSet size: CGSize) {
        lockQueue.async {
            self.encoder.width = Int32(1280)
            self.encoder.height = Int32(720)
        }
        if i increase the value from of width from 1280 to 1920 it give error that encoder height and width is too big. can we resolve this issue for handling high resolutions?
        
        [Error] [com.haishinkit.HaishinKit] [VideoCodec.swift:196] VideoCodec > encoding failed with kVTParameterErr. Perhaps the width x height is too big for the encoder setup?

**Comment by shogo4405** [comment]
Please use issue template.

**Comment by HamzaKiyani43** [comment]
@shogo4405 dear brother, i don't get that what are you pointing at. what do you mean by use issue template?

**Comment by augustl** [comment]
@HamzaKiyani43 when you create a new issue, there's a form you can fill out. The form has fields for all the details the developers needs in order to be able to investigate the issue you're having.

**Comment by HamzaKiyani43** [comment]
> @HamzaKiyani43 when you create a new issue, there's a form you can fill out - i.e. the issue template. The form has fields for all the details the developers needs in order to be able to investigate the issue you're having.

Thanks
