### ISSUE TITLE
Can't setup video setting 1920x1080 for iPhone 7

### ISSUE THREAD

**Issue by namnvsskpi** [shogo4405/HaishinKit.swift#950]
**Describe the bug**
I prepare for RTMP live with my iPhone 7 and video setting is 1920x1080, all other settings are default.
I can't update video setting to 1920x1080.
I got error: 
```bash
[Error] [com.haishinkit.HaishinKit] [VideoCodec.swift:196] VideoCodec > encoding failed with kVTParameterErr. Perhaps the width x height is too big for the encoder setup?
```

**To Reproduce**
1. Setup rtmpStream.videoSettings = [ .width: 1920,   .height: 1080 ] and rtmpStream.captureSettings[.sessionPreset] = AVCaptureSession.Preset.hd1920x1080
2. On Live
3. See error

**Expected behavior**
Live stream normal with RTMP

**Smartphone (please complete the following information):**
 - Device: [iPhone 7]
 - OS: [iOS 14.4.2]
 - Version [1.2.2]

**Comment by y2kpaulh** [comment]
I have same issue in iPhone Xs Max.

**Comment by y2kpaulh** [comment]
@shogo4405 I have same issue in any iPhone device. Could you check this issue?

**Comment by y2kpaulh** [comment]
@shogo4405 The same issue above continues to reproduce on all the phones I have. Is there something to check when setting the resolution to 1080p?

**Comment by namnvsskpi** [comment]
Add  profileLevel: kVTProfileLevel_H264_High_AutoLevel to resolve this problem in videoSettings
It took me 10 days
