### ISSUE TITLE
Application sends invalid dts and pts on the server

### ISSUE THREAD

**Issue by EvgenPol** [shogo4405/HaishinKit.swift#958]
**Describe the bug**
When sending a stream, server-side errors occur, such as:

```
[flv @ 000002648f7e2680] Invalid timestamps stream=2, pts=616, dts=654, size=549
[flv @ 0x561a2e220c80] invalid dts/pts combination 7304
[libx264 @ 0x55da206c9800] non-strictly-monotonic PTS
[null @ 0x55da206ad440] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 75 >= 75
```

What can sometimes delay the start of the broadcast for a long time (more than 22 seconds)
There are no errors on the application side.

**To Reproduce**
N/A

**Expected behavior**
The server stably receives the stream without errors, the broadcast starts stably with a delay of no more than 15 seconds.

**Screenshots**
Logboard trace screenshot: 
![logboard](https://user-images.githubusercontent.com/78258561/151132575-18e78de0-0ac1-4c3c-b85a-5b231eabb157.png)

**Desktop:**
 - Server: SRS

**Smartphone:**
 - Device: iPhone6
 - OS: iOS 12.5.5
 

**Additional context**
I tried changing the video profile to H264_Main_Auto Level, then to H264_Baseline_5_2.
I also changed the audio settings, or rather sampleRate to 44100, and the audio bitrate to 32000.
Made ABR, the initial bitrate of the video is 200_000.

Please tell me any tips that I can still try

**Comment by shogo4405** [comment]
Related issue is here:
- https://github.com/shogo4405/HaishinKit.swift/issues/607#issuecomment-590704786

Please use the baseline profile. I'm not familiar to the main profile.
But It's works ok Wowza server.

**Comment by EvgenPol** [comment]
I read this thread, but nothing helped, now I use Baseline_5_2, and the problem does not go away.

**Comment by shogo4405** [comment]
>  I use Baseline_5_2

Oh. I see. But I'm not sure. I can't resolve it.
