### ISSUE TITLE
Flutter: Access to CMSampleBuffer of captureOutput

### ISSUE THREAD

**Issue by ThibaultBee** [shogo4405/HaishinKit.swift#961]
**Is your feature request related to a problem? Please describe.**
I am trying to develop a RTMP publisher for Flutter based on your great framework.
Everything is perfect unless for the camera preview. If you look on github already existing flutter library based on HaishinKit reimplements an AVCaptureSession just for the camera preview. It is far from being the most efficient and it is a boilerplate solution.
We need to have access to the CVPixelBuffer that comes from the camera.

**Describe the solution you'd like**
In your HKView, I added a 
```
public var onPixelBufferAvailable: ((CVPixelBuffer) -> Void)?
```
And call the `onPixelBufferAvailable` in `enqueue`. It works but I have the feeling that it is not the best approach.

**Describe alternatives you've considered**
I guess the best solution would be to:
- either have a light implementation of `NetStreamRenderer` (without UIView or an MTKView) 
- to make `NetStreamRenderer` public as you did in https://github.com/shogo4405/HaishinKit.swift/issues/551. In this case, I would need an access to `stream.mixer.session`, `stream.mixer.videoIO`,... as well.

 They are multiple solutions, I just don't know which one to pick. Could you help me? Thank you :)

**Additional context**
For flutter, we have to implement a [FlutterTexture](https://api.flutter.dev/objcdoc/Protocols/FlutterTexture.html) protocol for the camera preview. It will look like something like this:
```
class PreviewTexture: HKView, FlutterTexture {
 ...
    func copyPixelBuffer() -> Unmanaged<CVPixelBuffer>? {
        if let latestPixelBuffer = latestPixelBuffer {
            return Unmanaged<CVPixelBuffer>.passRetained(latestPixelBuffer)
        }
        return nil
    }
...
}
```
where `latestPixelBuffer` contains the `CVPixelBuffer` that comes from the `captureOutput`.
For your information, an example of camera implementation within Flutter is available here: https://github.com/flutter/plugins/blob/72dff1b4342676f3b4b6fc9a7fb810140dcf7477/packages/camera/camera/ios/Classes/FLTCam.m#L615

**Comment by ThibaultBee** [comment]
Do you mean by the `currentSampleBuffer` variable?
Is there a way to know when a new currentSampleBuffer is available (like a callback)?

**Comment by shogo4405** [comment]
Yes. Unfortunately I have no plan. Please fork it.

**Comment by ThibaultBee** [comment]
Ok! Thank you :)
According to you, what is the best way to implement this callback?
Would you like a PR after the implementation?

**Comment by shogo4405** [comment]
Something like this.
```
var currentSampleBuffer: CMSampleBuffer? {
   didSet {
       delegate?.hkView(didCurrentSampleBuffer: CMSamplBuffer?)
   }
}
 ```
No. I am not very familiar with the Flutter. So I can't maintenance it.

**Comment by ThibaultBee** [comment]
Thank you! That's perfect! I will implement it in a fork then :)

**Comment by ThibaultBee** [comment]
Hi,

I did notice that in release note of version [1.2.5](https://github.com/shogo4405/HaishinKit.swift/releases/tag/1.2.5), you made changes for Flutter: 
> Change declaration for Flutter friendly :D

I notice that `NetStreamDrawable` is now public but as the VideoIO is private, we can not `attachStream`.

- Is there any documentation about the flutter friendly changes?
- Are we supposed to use `NetStreamDrawable` and how?

**Comment by shogo4405** [comment]
Please see this file. https://github.com/shogo4405/HaishinKit.dart/blob/main/ios/Classes/NetStreamDrawableTexture.swift
