### ISSUE TITLE
videoSettings.bitrate - is this in bits or bytes?

### ISSUE THREAD

**Issue by msimonetta1** [shogo4405/HaishinKit.swift#962]
When setting the bitrate of a videoSettings is the value passed in meant to be bits, bytes, kilobytes?

**Comment by shogo4405** [comment]
VideoSettings.bitrate is wrapper for kVTCompressionPropertyKey_AverageBitRate.
https://developer.apple.com/documentation/videotoolbox/kvtcompressionpropertykey_averagebitrate?language=objc

So in **bits**.
