### ISSUE TITLE
Streaming stops when I switch the cameras (from front to back camera) - iOS

### ISSUE THREAD

**Issue by Jsmorales1415** [shogo4405/HaishinKit.swift#964]
The stream seems to work properly only if I use 1 camera, if I try to switch the streaming it stops but I get no feedback, the UI shows that I am still streaming.

**To Reproduce**
1. Press the 'start streaming' button 
2. Click on switch camera icon (top right corner)
4. See error in logs

**Expected behavior**
The app should continue to stream what the camera shows.

**Smartphone**
 - Device: iPhone SE 2nd generation.

**Comment by yorudotlife** [comment]
I think, if my memory is good, that old iphone do not have a 1080p on the front camera: maybe your problem is that you are asking the second camera to have a resolution that is higher than it can provide.

**Comment by Nodalailama** [comment]
I think, if my memory is good, that old iphone do not have a 1080p on the front camera: maybe your problem is that you are asking the second camera to have a resolution that is higher than it can provide.
