### ISSUE TITLE
Mobile heats up and restarts (iphone 12 pro max)

### ISSUE THREAD

**Issue by HamzaKiyani43** [shogo4405/HaishinKit.swift#972]
i use this library in my project and made 2 rtmpstreams one to attachCamera and other to attachScreen because i want to stream my full screen with camera feed and some other views on camera view(MTHKView). code is below.but after this i got a problem my mobile heats up restarts saying that you need to cool down you mobile to use again.

rtmpStream.attachAudio(AVCaptureDevice.default(for: .audio)) { error in
        }
        rtmpStreamLayer.attachCamera(DeviceUtil.device(withPosition: cameraPosition)) { error in
        }
        rtmpStream.attachScreen(ScreenCaptureSession(viewToCapture: view))
        
        self.videoView.attachStream(self.rtmpStreamLayer)
            self.videoView.videoGravity = .resizeAspectFill

**To Reproduce**
use 2 stream objects 
use one to show camera stream on MTHKView 
other to attachscreen screen.
i have a webview on top of MTHKView.
then i publish stream with videosettings = [
.width: 1080,
.height: 720,
.profileLevel: kVTProfileLevel_H264_High_AutoLevel]
in first 3,4 mins everythings goes good but after that i feel my mobile is heating up. and after 10 mins of going live on RTMPS server.my mobile got restarted saying you need to cool down your mobile to use before. 

Screenshot:
![WhatsApp Image 2022-03-18 at 6 53 49 PM](https://user-images.githubusercontent.com/32823530/159015623-2f09141b-7023-4158-8c0c-cfef2d8723d9.jpeg)

**Expected behavior**
is to go live with my screen recording at normal temperature.

**Smartphone:**
 - Device: iphone 12 pro max
 - OS: 15.3
 - network connection: cellular
 - battery 58%
 - Architecture: arm64e

**Additional context**

**Comment by shogo4405** [comment]
Duplicate as closed. https://github.com/shogo4405/HaishinKit.swift/issues/989#issuecomment-1124850720
