### ISSUE TITLE
RTMPStreamDelegate didOutput not called.

### ISSUE THREAD

**Issue by DylanVann** [shogo4405/HaishinKit.swift#977]
**Describe the bug**

When an `RTMPStream` is created and the `delegate` property is set the delegate methods `didOutput video` and `didOutput audio` are not called.

**To Reproduce**

Follow one of the examples from the README, use the `delegate`, see methods are not called.

**Expected behavior**

For the methods to be called when video and audio is streamed.

**Screenshots**

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/1537615/160653462-884431e8-1b52-4fb1-869e-2fd14c586ae9.png">

Logs from a video and audio RTMP stream. There are logging statements in the `didOutput` methods but they are not called.

<img width="848" alt="image" src="https://user-images.githubusercontent.com/1537615/160653592-69efbcea-ba93-40eb-bdd0-9d1f48d0992a.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: `12.3`
 - HaishinKit Version: `1.2.3`

**Additional context**

This isn't directly documented, maybe I'm not using it how it's intended.
 
Part of my goal here is syncing audio and video between an RTMP stream and another audio platform. 

One option for me is getting the audio in the `didOutput` method and sending the same data so it matches exactly.

The other option is knowing the timestamp the first video sample is taken at.

**Comment by shogo4405** [comment]
Yes. You can get RTMPStream#play method. 
But you can't get  RTMPStream#publish method.

**Comment by DylanVann** [comment]
I've thought of one workaround. I can maybe get the same data by creating an `AudioEffect` and getting the raw audio.

Turns out the provider wants audio in a significantly different format though, different sample rate, then how we'd want it in the RTMP stream. So it might be easier to keep the two processes separate. I can use the `AudioEffect` to find when the first sample is taken at though I think, that should be relatively accurate.
