### ISSUE TITLE
RTMPStream resolution locked at 480x272

### ISSUE THREAD

**Issue by kenle** [shogo4405/HaishinKit.swift#981]
**Describe the bug**
High, I'm following the examples on homepage and in iOS directory, but cannot get the `rtmpStream.videoSettings` to listen to the `.width` and `.height` parameters, it always outputs 480x272.  I saw previous bugs (#360) reported on this but you said it was a `framework bug`.  How comes the examples shows setting resolution, but it may not have any affect?

**To Reproduce**
For example, I tried the homepage example:
```
rtmpStream.videoSettings = [
    .width: 640, // video output width
    .height: 360, // video output height
    .bitrate: 160 * 1000, // video output bitrate
    .profileLevel: kVTProfileLevel_H264_Baseline_3_1, // H264 Profile require "import VideoToolbox"
    .maxKeyFrameIntervalDuration: 2, // key frame / sec
]
```

I am also using ReplayKit to stream to youtube with the following line:
```
    RPScreenRecorder.shared().startCapture(
        handler: { (cmSampleBuffer, rpSampleType, error) in
          guard error == nil else {
            return;
          }
      switch rpSampleType {
        case RPSampleBufferType.video:
...
        rtmpStream.appendSampleBuffer(cmSampleBuffer, withType: .video);
```

**Expected behavior**
I expect it to stream the desired resolution, for example 640x360, or whatever I set the resolution to.

**Screenshots**
Screenshot from youtube rtmp stream:
<img width="1364" alt="Screen Shot 2022-04-06 at 4 45 38 PM" src="https://user-images.githubusercontent.com/47367/162094054-1297a5da-3d15-409b-a89a-097e203cfe20.png">

**Smartphone (please complete the following information):**
 - Device: [iPhone 12 Max]
 - OS: [iOS15.3]

**Comment by shogo4405** [comment]
I fixed this issue https://github.com/shogo4405/HaishinKit.swift/issues/360 4years ago. Currentry, It works for me [Examples](https://github.com/shogo4405/HaishinKit.swift/tree/main/Examples/iOS). I can publish 720x1280.

    Duration: 00:00:00.00, start: 10.240000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 48000 Hz, mono, fltp, 32 kb/s
    Stream #0:1: Video: h264 (Baseline), yuv420p(tv, progressive), 720x1280, 422 kb/s, 30 fps, 30 tbr, 1k tbn

**Comment by kenle** [comment]
@shogo4405 I resolved it :)

I have to call this every time before appending to the rtmpStream, and I get the resolution I desire!  Thank you for your great library.

```
                if let description = CMSampleBufferGetFormatDescription(cmSampleBuffer) {
                    let dimensions = CMVideoFormatDescriptionGetDimensions(description)
                    self.rtmpStream?.videoSettings = [
                        .width: dimensions.width,
                        .height: dimensions.height,
                        .profileLevel: kVTProfileLevel_H264_Baseline_AutoLevel,
                        .maxKeyFrameIntervalDuration: 2,
                        .bitrate: 1200 * 1024
                    ]
                    self.rtmpStream?.captureSettings = [
                        .fps: 24
                    ]
                }
                
                self.rtmpStream?.appendSampleBuffer(cmSampleBuffer, withType: .video);
```

**Comment by Andriiklymiuk** [comment]
On what version changing videoSettings works? cause it still seems in 1.4.3 it randomly stops working
