### ISSUE TITLE
Continous AutoFocus

### ISSUE THREAD

**Issue by ThibaultBee** [shogo4405/HaishinKit.swift#983]
**Describe the bug**

The continous auto focus does not run if sessionPreset is not set.
In the trace we got the warn messages:
```
2022-12-04 10:55:26.931 [Warn] [com.haishinkit.HaishinKit] [AVVideoIOUnit.swift:158] continuousAutofocus > focusMode(2) is not supported
2022-12-04 10:55:26.933 [Warn] [com.haishinkit.HaishinKit] [AVVideoIOUnit.swift:217] continuousExposure > exposureMode(2) is not supported
```

**To Reproduce**
1. Edit Example iOS LiveViewController
2. Replace `rtmpStream.captureSettings` by
```
rtmpStream.captureSettings = [
   // .sessionPreset: AVCaptureSession.Preset.hd1280x720,
    .fps: 30,
    .continuousAutofocus: true,
    .continuousExposure: true
    // .preferredVideoStabilizationMode: AVCaptureVideoStabilizationMode.auto
]
```
3. Launch Example iOS
4. Focus to infinity

**Expected behavior**
I expect the focus to go to infinity when it tries to focus to infinity.
Is it a requirement to set `sessionPreset`? Why do I need to set it althought `AVCaptureSessionPresetHigh` is the default sessionPreset value.

**Smartphone (please complete the following information):**
- iPhone XR
- iOS 15.2
- 
**Additional context**
If `sessionPreset` is set, the focus goes to infinity and there are no warn messages.
Possibly the same issue for `continuousExposure`.

**Comment by shogo4405** [comment]
> Is it a requirement to set sessionPreset? Why do I need to set it althought AVCaptureSessionPresetHigh is the default sessionPreset value.

The framework's default value is `AVCaptureSessionPresetMiddle`. Please set `sessionPreset`.
