### ISSUE TITLE
Can't set orientation when start streaming any video

### ISSUE THREAD

**Issue by PriyankaNovo** [shogo4405/HaishinKit.swift#984]
while streaming server video doesn't appear in desired orientation.
Orientation was applied before start streaming.

     `          var orientationLast: UIInterfaceOrientation?
                let deviceOrientation = self.orientationLast ?? .portrait
                let captureOrientation:AVCaptureVideoOrientation = deviceOrientation.isLandscape ? rtmpStream.orientation == .portrait ? .landscapeLeft : .landscapeRight : .portrait
                rtmpStream.orientation = captureOrientation
`

Any suggestions?

**Comment by shogo4405** [comment]
Please try this property.
- rtmpStream.syncOrientation = true
