### ISSUE TITLE
NetStream.lock crash

### ISSUE THREAD

**Issue by Goule** [shogo4405/HaishinKit.swift#986]
**Describe the bug**
I have some new crash in my Crashytics dashboard 

> Crashed: com.haishinkit.HaishinKit.NetStream.lock
0  MyApp                     0x73abac closure # 1 in MTHKView.currentStream.didset + 23 (AVVideoIOUnit.swift:23)
1  MyApp                     0x6fafb0 thunk for @ escaping @callee_guaranteed () -> () + 4221632 (<compiler-generated>:4221632)
2  libdispatch.dylib              0x63094 _dispatch_call_block_and_release + 24
3  libdispatch.dylib              0x64094 _dispatch_client_callout + 16
4  libdispatch.dylib              0x3f4a4 _dispatch_lane_serial_drain$VARIANT$armv81 + 600
5  libdispatch.dylib              0x3ff44 _dispatch_lane_invoke$VARIANT$armv81 + 388
6  libdispatch.dylib              0x498e0 _dispatch_workloop_worker_thread + 608
7  libsystem_pthread.dylib        0x1e10 _pthread_wqthread + 284
8  libsystem_pthread.dylib        0x193c start_wqthread + 8
`

**To Reproduce**
I can reproduce the error, I only see it in my crashlytics logs.

It appear on various OS and Device (iOS 14 >). 

Running on HaishinKit.swift 1.2.1.

Have you any idea how to fix it ? :) 

Thanks !

**Comment by shogo4405** [comment]
I'm not sure. I can't reproduce it. 
Could you provide me of reproducible short sample code?

**Comment by Goule** [comment]
Hello @shogo4405 

Unfortunately, I can't reproduce it... It happened at 2% of our users since we've compiled the app with the latest Xcode (13.3). 
It looks like the latest SDK has broke something, we didn't touch the streaming part of the app.

**Comment by nonocast** [comment]
+1, same problem.

**Comment by floriangbh** [comment]
Hello, 

Same issue on my side : 

<img width="995" alt="Screenshot 2022-07-05 at 13 32 35" src="https://user-images.githubusercontent.com/14054997/177318419-7493cf82-f0ac-423b-a53f-5951f5fa3391.png">

Always with iOS 15. 
Can reproduce with my app, seems to be random crash

**Comment by floriangbh** [comment]
Hello, 

Same issue : 
<img width="995" alt="Screenshot 2022-07-05 at 13 32 35" src="https://user-images.githubusercontent.com/14054997/177318806-eca8a150-e556-4016-9c17-bc5d2f16424e.png">

I can't reproduce it, seems to be a random crash.

**Comment by floriangbh** [comment]
Sorry for the late reply, I can try but this is a complex application which can't work with sample project

**Comment by Goule** [comment]
Hello, 

Look like there was an extra DispatchQueue in my code : 
<img width="401" alt="Screenshot 2022-09-21 at 16 58 24" src="https://user-images.githubusercontent.com/21126201/191539488-9cc59a89-6c12-4f22-82ac-b27dc61b7e65.png">

After removing, no more crash at this time !
