### ISSUE TITLE
VIdeoEffect doesn't work with camera streaming.

### ISSUE THREAD

**Issue by nadein** [shogo4405/HaishinKit.swift#988]
**Describe the bug**
I use VIdeoEffect subclass like in [Example](https://github.com/shogo4405/HaishinKit.swift/blob/main/Examples/iOS/VisualEffect.swift) (PronamaEffect) to place image over the stream video.
If I use screen capturing - it works.
`rtmpStream.attachScreen(ScreenCaptureSession(viewToCapture: captureView))`
When I use camera capturing - it doesn't show image.
`rtmpStream.attachCamera(DeviceUtil.device(withPosition: defaultCamera))`

**To Reproduce**
1. Setup RTMP stream.
2. Attach device camera to stream.
3. Register video effect (VIdeoEffect subclass).
4. Start streaming.

**Expected behavior**
The image is placed over the stream video.

**Screenshots**
Screen streaming - VideoEffect image is present:
[![Screen streaming - VideoEffect image is present.](https://i.postimg.cc/2SQbhdF8/Screenshot-2022-05-03-at-14-36-41.png)](https://postimg.cc/18z3ZqjL)
Camera streaming - VideoEffect image is missing:
[![Camera streaming - VideoEffect image is missing.](https://i.postimg.cc/CKMGK6TV/Screenshot-2022-05-03-at-14-40-47.png)](https://postimg.cc/G4N87KmM)

**Smartphone:**
 - Device: iPhone 8, iPhone 13, iPad Air
 - OS: iOS 15.4.1
 - IDE: Xcode 13.3.1
 - HaishinKit 1.2.3

**Additional context**
Code for applying video effect:
```
let overlay = OverlayVideoEffect(image)
overlayEffect = overlay
 _ = rtmpStream.registerVideoEffect(overlay)
```
VideoEffect subclass implementation:
```
final class OverlayVideoEffect: VideoEffect {
    let filter: CIFilter? = CIFilter(name: "CISourceOverCompositing")
    
    var extent = CGRect.zero {
        didSet {
            if extent == oldValue {
                return
            }
            UIGraphicsBeginImageContext(extent.size)
            image.draw(at: CGPoint(x: 50, y: 50))
            self.overlay = CIImage(image: UIGraphicsGetImageFromCurrentImageContext()!, options: nil)
            UIGraphicsEndImageContext()
        }
    }
    var overlay: CIImage?
    var image: UIImage
    
    init(_ image: UIImage) {
        self.image = image
        super.init()
    }
    
    override func execute(_ image: CIImage, info: CMSampleBuffer?) -> CIImage {
        guard let filter: CIFilter = filter else {
            return image
        }
        extent = image.extent
        filter.setValue(overlay!, forKey: "inputImage")
        filter.setValue(image, forKey: "inputBackgroundImage")
        return filter.outputImage!
    }
}
```

**Comment by nadein** [comment]
[Logboard log during reproduction of this issue](https://gist.github.com/nadein/3fcbe365fff1640d4b150fe0b2ba7492)

**Comment by shogo4405** [comment]
How about Example. Does that work properly?
If it works ok.. I can't resolve this issue.

**Comment by flashin** [comment]
@nadein 
I have the same issue. Did you manage to solve it?

**Comment by nadein** [comment]
Yes. It works properly. Thank you.
