### ISSUE TITLE
(A serious concern) IPhone gets heats up within 5 minute of screen sharing.

### ISSUE THREAD

**Issue by wajeeh-hassan** [shogo4405/HaishinKit.swift#989]
I use example project for screen sharing on RTMP server.
I am using one object of RTMPStream for camera preview and second object of RTMPStream for screen sharing because i need camera input along with my stickers that are presented over the screen. 

Following is the code which i am using.

`rtmpStreamCamera.attachCamera(DeviceUtil.device(withPosition: currentPosition)) { error in
      logger.warn(error.description)
    }
`
`rtmpStreamScreen.attachScreen(ScreenCaptureSession(viewToCapture: myView))`

Run the example project to create 

- Add two images on the main view
- And go live. for the initial few minutes, stream goes smoothly but after 7 to 8 minutes mobile gets heated and a warning popup is displayed saying that iPhone needs to cool down before you can use.

**Expected behavior**
Stream should go live smoothly without swear heating up the device.

Here are the attached screenshots 
**Screenshots**
<img width="507" alt="Screen Shot 2022-05-11 at 10 10 15 PM" src="https://user-images.githubusercontent.com/20623183/167911804-6dba0c81-34db-4e39-9c6e-daee675b40c7.png">

![Image from iOS](https://user-images.githubusercontent.com/20623183/167911781-52d675c5-a850-4192-818f-63d488f16ac7.png)

**Smartphone (please complete the following information):**
 - Device: [iPhone6]
 - OS: [iOS12.4]

**Comment by shogo4405** [comment]
I'm not designed to use `attachCamera` and `attachScreen`. Both are heavy processing.

On a whim
- Disconnect lightning cable.
- Change the `Optimization level -none` to ` -Fast `
