### ISSUE TITLE
iPhone 12 encoding failed with kVTParameterErr. Perhaps the width x height is too big for the encoder setup?

### ISSUE THREAD

**Issue by ldhios** [shogo4405/HaishinKit.swift#990]
**Describe the bug**
 encoding failed with kVTParameterErr. Perhaps the width x height is too big for the encoder setup?

**To Reproduce**
1. Change HaishinKit  iOS Example  LiveViewController.swift code

`      rtmpStream.captureSettings = [
            .sessionPreset: AVCaptureSession.Preset.hd1280x720,
            .continuousAutofocus: true,
            .continuousExposure: true
            // .preferredVideoStabilizationMode: AVCaptureVideoStabilizationMode.auto
        ]
        rtmpStream.videoSettings = [
            .width: 1280,
            .height: 720,
            .scalingMode: ScalingMode.letterbox
        ]
`
The rest of the code is unchanged

2. See error
log encoding failed with kVTParameterErr. Perhaps the width x height is too big for the encoder setup?

But the same project run iPhone 6   iOS version 12.5.5 ，no problem。

**Expected behavior**
RTMP live normal。
I need a 16:9 video stream to upload to a live site ,where the user always uses portrait orientation. So I need to set letterBox mode.
The following picture，iPhone 6   iOS version 12.5.5  is good 。

VLC Screenshots
![截屏2022-05-12 14 55 35](https://user-images.githubusercontent.com/9722423/168014263-9ec8f5a3-d575-4443-b104-f9ef16db80c6.png)

iPhone 6 Screenshots
![IMG_0092](https://user-images.githubusercontent.com/9722423/168014720-45e357a0-d06a-4940-bdb7-88e2aa3312f9.PNG)

**Screenshots**
Run iPhone 12 report issue
![image](https://user-images.githubusercontent.com/9722423/168015177-e1f8f8fc-a40b-4921-9251-69b3c88e6f67.png)

**Desktop (please complete the following information):**
 - OS: Mac os Monterey 12.3.1
 - Xcode Version 13.3

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.4.1
 - HaishinKit: 1.2.3

**Additional context**

**Comment by ldhios** [comment]
I'm sorry that I have only these two iphones, so I can't test whether other iphones have this problem

**Comment by ldhios** [comment]
I also  see [https://github.com/shogo4405/HaishinKit.swift/issues/950](url) , add profileLevel: kVTProfileLevel_H264_High_AutoLevel.  But it doesn't work for me or I get an error。“kVTParameterErr. Perhaps the width x height is too big for the encoder setup?”

**Comment by shogo4405** [comment]
If set to `VideoCodec.defaultAttributes = nil`, works fine.
