### ISSUE TITLE
The streaming stops when play audio at same time OR connect iPhone with AirPods

### ISSUE THREAD

**Issue by islamnabil** [shogo4405/HaishinKit.swift#991]
**Describe the bug**
The streaming freezing or to be a black screen if I play a sound in iPhone with the streaming OR start the streaming while I'm using AirPods.

**To Reproduce**
1. Start the Stream.
2. Play a sound file from the app.
3. The streams freeze & the screen becomes black.

OR
1. Connect the iPhone with AirPods. 
2. Start the Stream.
3. The streams freeze & the screen becomes black.3.The streams freeze & the screen becomes black.

**Smartphone (please complete the following information):**
 - Device: iPhone 8 & above
 - OS: **iOS 13** & above
 - Version **1.2.2**

**Comment by shogo4405** [comment]
Are you talking about publishing feature or playback feature?

**Comment by islamnabil** [comment]
Publishing feature
