### ISSUE TITLE
Is there way to set  "scenecut=0" like x264 Options in OBS?

### ISSUE THREAD

**Issue by HiroshiOshiro** [shogo4405/HaishinKit.swift#993]
Hi, 
Thank you for this HaishinKit.

I usually use OBS(https://obsproject.com/) from PC to broadcast and set `scenecut=0` to"x 264 Options" like below.

<img width="600" alt="スクリーンショット 2022-05-23 10 09 47" src="https://user-images.githubusercontent.com/4166369/169725514-3e60f34f-f5c0-4242-8c2f-18abe71230d9.png">

Is there any way to set the option?
I checked [VideoCodec](https://github.com/shogo4405/HaishinKit.swift/blob/main/Sources/Codec/VideoCodec.swift) but could not find the way to set it.

If it is impossible now, do you have any plan to implement like that?

**Comment by shogo4405** [comment]
No. I have no plan. VideoCodec is the Video Toolbox 's wrapper.
https://developer.apple.com/documentation/videotoolbox

It seems that VideoToolbox has no feature.

**Comment by HiroshiOshiro** [comment]
I see, Thank you.
