### ISSUE TITLE
Please change Set<VideoEffect> to array. Because i sequential sort VideoEffect

### ISSUE THREAD

**Issue by Chiennv1130810** [shogo4405/HaishinKit.swift#994]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shogo4405** [comment]
OK. I'm waiting your PR.

**Comment by eerimoq** [comment]
I'm interested in this as well. Will create a PR.

**Comment by eerimoq** [comment]
https://github.com/shogo4405/HaishinKit.swift/pull/1281
